### ISSUE TITLE
hhvm crashed with xdebug enabled

### ISSUE THREAD

**Issue by netroby** [facebook/hhvm#6896] opened 2016-03-09 02:47 UTC
This is the error log

```
Assertion failure: /tmp/tmp.sbwY0BY757/hphp/runtime/base/program-functions.cpp:2197: void HPHP::hphp_memory_cleanup(): assertion `g_context.isNull() || !g_context->hasRequestEventHandlers()' failed.


Core dumped: Aborted
Stack trace in /tmp/stacktrace.1.log
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.1.log
Now starting hhvm

Assertion failure: /tmp/tmp.sbwY0BY757/hphp/runtime/base/program-functions.cpp:2197: void HPHP::hphp_memory_cleanup(): assertion `g_context.isNull() || !g_context->hasRequestEventHandlers()' failed.


Core dumped: Aborted
Stack trace in /tmp/stacktrace.1.log
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.1.log
Now starting hhvm

Assertion failure: /tmp/tmp.sbwY0BY757/hphp/runtime/base/program-functions.cpp:2197: void HPHP::hphp_memory_cleanup(): assertion `g_context.isNull() || !g_context->hasRequestEventHandlers()' failed.


Core dumped: Aborted
Stack trace in /tmp/stacktrace.1.log

Assertion failure: /tmp/tmp.sbwY0BY757/hphp/runtime/base/program-functions.cpp:2197: void HPHP::hphp_memory_cleanup(): assertion `g_context.isNull() || !g_context->hasRequestEventHandlers()' failed.


Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.1.log
Now starting hhvm

Assertion failure: /tmp/tmp.sbwY0BY757/hphp/runtime/base/program-functions.cpp:2197: void HPHP::hphp_memory_cleanup(): assertion `g_context.isNull() || !g_context->hasRequestEventHandlers()' failed.


Core dumped: Aborted
Stack trace in /tmp/stacktrace.1.log
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.1.log

```

and this is my /etc/hhvm/php.ini configure

```
; php options
session.save_handler = files
session.save_path = /var/lib/hhvm/sessions
session.gc_maxlifetime = 1440

; hhvm specific 
hhvm.log.level = Warning
hhvm.log.always_escape_log = false
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
; custom
date.timezone="Asia/Shanghai"
upload_max_filesize = 64M
post_max_size = 64M

xdebug.enable=1
xdebug.max_nesting_level = 65536
xdebug.profiler_enable=1
xdebug.profiler_append=1
xdebug.profiler_output_dir=/www/deyihome-phpsource/vendor/logs
xdebug.remote_enable=1
xdebug.remote_host="0.0.0.0"
xdebug.remote_port=8787

```

**Comment by netroby** [comment] 2016-03-09 02:48
And the /tmp/stacktrace file seems empty

```
huzhifeng@w ~/workspace/hzfeng/demo (stable) $ docker exec docker-hhvm ls -l /tmp/       
total 4
-rw-r--r-- 1 root root  0 Mar  9 02:45 perf-1.map
-rw------- 1 root root 18 Mar  9 02:45 stacktrace.1.log
huzhifeng@w ~/workspace/hzfeng/demo (stable) $ docker exec docker-hhvm cat /tmp/stacktrace.1.log

PHP Stacktrace:

```

**Comment by Orvid** [comment] 2016-03-14 17:44
The stacktrace being empty is known. To get a proper stacktrace you have to attach to it with GDB.

**Comment by joelastpass** [comment] 2016-04-21 23:08
I haven't investigated but I'm seeing this too only with xdebug enabled with latest git tip.

#0  0x00007f8eb60eccc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f8eb60f00d8 in __GI_abort () at abort.c:89
#2  0x000000000276ab79 in HPHP::assert_fail(char const*, char const*, unsigned int, char const*, std::string const&) ()
#3  0x00000000010a59f2 in HPHP::hphp_session_exit() ()
#4  0x0000000003375265 in HPHP::HttpRequestHandler::teardownRequest(HPHP::Transport*) ()
#5  0x000000000129e276 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) ()
#6  0x000000000129e8ee in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) ()
#7  0x0000000001295de6 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
#8  0x0000000002784d87 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
#9  0x0000000000eb1667 in HPHP::start_routine_wrapper(void*) ()
#10 0x00007f8eb6ca3182 in start_thread (arg=0x7f8e9efff700) at pthread_create.c:312
#11 0x00007f8eb61b047d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
Comment here: 

 // We should never have any registered RequestEventHandlers. If we do
  // something after onRequestShutdown registered a RequestEventHandler.
  // Its now too late to run the requestShutdown functions, but if we carry
  // on, requestInit and requestShutdown will never be called again.
  // I considered just clearing the inited flags; which works for some
  // RequestEventHandlers - but its a disaster for others. So just fail hard
  // here.
  always_assert(g_context.isNull() || !g_context->hasRequestEventHandlers());

**Comment by aorenste** [comment] 2016-09-28 16:59
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Comment by bcopeland** [comment] 2017-12-18 18:29
This might also help:
```
(gdb) p g_context.isNull()
$10 = false
(gdb) p g_context->hasRequestEventHandlers()
$11 = true
(gdb) p *((*g_context).m_requestEventHandlers[0])
$12 = {_vptr.RequestEventHandler = 0x8531bf0 <vtable for HPHP::OptionData+16>, m_inited = true}
(gdb) p *((*g_context).m_requestEventHandlers[1])
$13 = {_vptr.RequestEventHandler = 0x8442eb0 <vtable for HPHP::ProfilerFactory+16>, m_inited = true}
```

**Comment by netroby** [comment] 2017-12-18 23:43
600 days goes. the bug still exists. no matter you see or not see it .
Thanks for your hard works. @bcopeland

**Closed** 2018-11-17 06:48 UTC
Labels: crash, needs more info, no isolated repro
