### ISSUE TITLE
cotire-enabled build fails - undefined sqlite3_api

### ISSUE THREAD

**Issue by Majkl578** [facebook/hhvm#4524] opened 2014-12-23 16:59 UTC
While building HHVM with cotire enabled, the build failed with:
```
Building CXX object hphp/util/CMakeFiles/hphp_util.dir/embedded-vfs.cpp.o
/build/hhvm/hhvm/hphp/util/embedded-vfs.cpp: In function ‘void HPHP::embeddedEnter()’:
/build/hhvm/hhvm/hphp/util/embedded-vfs.cpp:68:31: error: ‘sqlite3_api’ was not declared in this scope
 static void embeddedEnter() { sqlite3_mutex_enter(gEmbedded.pMutex); }
                               ^
/build/hhvm/hhvm/hphp/util/embedded-vfs.cpp: In function ‘void HPHP::embeddedLeave()’:
/build/hhvm/hhvm/hphp/util/embedded-vfs.cpp:69:31: error: ‘sqlite3_api’ was not declared in this scope
 static void embeddedLeave() { sqlite3_mutex_leave(gEmbedded.pMutex); }
                               ^
/build/hhvm/hhvm/hphp/util/embedded-vfs.cpp: In function ‘int HPHP::sqlite3_embedded_initialize(const char*, int)’:
/build/hhvm/hhvm/hphp/util/embedded-vfs.cpp:219:14: error: ‘sqlite3_api’ was not declared in this scope
   pOrigVfs = sqlite3_vfs_find(zOrigVfsName);
              ^
/build/hhvm/hhvm/hphp/util/embedded-vfs.cpp: In function ‘int HPHP::sqlite3_embedded_shutdown()’:
/build/hhvm/hhvm/hphp/util/embedded-vfs.cpp:269:3: error: ‘sqlite3_api’ was not declared in this scope
   sqlite3_mutex_free(gEmbedded.pMutex);
   ^
```

Using Debian experimental.

**Comment by jrobeson** [comment] 2015-01-07 09:06
which version is this? the LTS version? can you replicate it in 3.4.2?

**Comment by glensc** [comment] 2015-01-07 09:18
for me it failed on LTS build (3.3.2)

however the failure is not consistent, i.e on dev machine i was not able to reproduce, but on builders it always failed. can not tell what's the difference on the both setups. afaik, for 3.3.1 it did not fail on builder env too, however, again, not certain on this

**Comment by jrobeson** [comment] 2015-01-07 09:38
oh hi @glensc : you're a maintainer for PLD, right? do you think can can come by the #hhvm room on irc.freenode.net (i'm jrobeson there too) so i can ask you a few questions about some of the patches you're carrying around?

Maybe we can get some of them upstreamed.

**Comment by jrobeson** [comment] 2015-01-14 10:23
@glensc : did they have the same sqlite versions?

**Comment by glensc** [comment] 2015-01-14 11:30
@jrobeson you mean dev-env vs builder-env? or system-sqlite vs bundled-sqlite?

**Comment by jrobeson** [comment] 2015-01-14 11:32
if you're using the bundled version in both places, then that can't be the issue.

So system versions between the two.

**Comment by glensc** [comment] 2015-01-14 18:27
checked again today, and no, both have same version: sqlite3-3.8.7.2-2.x86_64

if you're interested of both build logs, i can provide them

**Comment by jrobeson** [comment] 2015-01-15 10:33
do you use ccache on both systems?

**Comment by glensc** [comment] 2015-01-15 10:37
nop. ccache only in dev-env

**Comment by glensc** [comment] 2015-01-15 10:49
indeed. i disabled ccache in my dev-env and got cotire errors as well. so why it worked in my dev-env was that ccache avoided doing full rebuild, i.e the files that get compile error were already compiled from ccache cache. i could probably end up with build failure if i keep ccache enabled but purge it's cache.

**Comment by jrobeson** [comment] 2015-01-15 11:43
well consistent failure is better than inconsistent failure!  What happens if you use the bundled version instead?

**Comment by glensc** [comment] 2015-01-15 12:13
seems to fail the same way:


```
[ 17%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/exception.cpp.o
cd /home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util && /usr/bin/x86_64-pld-linux-g++   -DENABLE_FASTCGI=1 -DENABLE_ZEND_COMPAT=1 -DFOLLY_HAVE_CLOCK_GETTIME
=1 -DFOLLY_HAVE_FEATURES_H=1 -DFOLLY_HAVE_WEAK_SYMBOLS=1 -DFOLLY_NO_CONFIG=1 -DHAVE_BOOST1_49 -DHAVE_CURL_MULTI_WAIT -DHAVE_ELF_GETSHDRSTRNDX -DHAVE_FEATURES_H=1 -DHAVE_LIBDL -DHHVM -DHHVM_DYNAMIC_EXTENSION_DIR=\"/usr/lib64/hhvm\" -DHPHP_OSS=1 -DLIBDWARF_CONST_NAME -DLIBDWARF_USE_INIT_C -DNDEBUG -DNO_JEMALLOC=1 -DNO_TCMALLOC=1 -DPACKAGE=hhvm -DPACKAGE_VERSION=Release -DRELEASE=1 -DUSE_CMAKE -DUSE_EDITLINE -DUSE_LLVM -D_GNU_SOURCE -D_PTHREADS=1 -D_REENTRANT=1 -D__STDC_FORMAT_MACROS -Wall -std=gnu++11 -fno-gcse -fno-omit-frame-pointer -ftemplate-depth-180 -Woverloaded-virtual -Wno-deprecated -Wno-strict-aliasing -Wno-write-strings -Wno-invalid-offsetof -fno-operator-names -Wno-error=array-bounds -Wno-error=switch -Werror=format-security -Wno-unused-result -Wno-sign-compare -Wno-attributes -Wno-maybe-uninitialized -Wno-unused-local-typedefs -fno-canonical-system-headers -Wno-deprecated-declarations -fno-delete-null-pointer-checks -mcrc32 -O2 -fwrapv -pipe -Wformat -Werror=format-security -gdwarf-4 -fno-debug-types-section -fvar-tracking-assignments -g2 -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fPIC -march=x86-64 -gdwarf-4 -fno-debug-types-section -fvar-tracking-assignments -g2  -DNDEBUG -DQT_NO_DEBUG -I/usr/include/mysql -I/usr/include/libxml2 -I/usr/include/double-conversion -I/usr/lib64/libzip/include -I/usr/include/security -I/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/LIBLLVM_INCLUDE_DIR -I/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp -I/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/third-party/fastlz -I/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/third-party/timelib -I/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/third-party/libafdt/src -I/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/third-party/libmbfl -I/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/third-party/libmbfl/mbfl -I/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/third-party/libmbfl/filter -I/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/third-party/folly -I/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/third-party -I/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2     -Winvalid-pch -include "/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/cotire/hphp_util_CXX_prefix.hxx"  -o CMakeFiles/hphp_util.dir/exception.cpp.o -c /home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/exception.cpp
In file included from /home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/cotire/hphp_util_CXX_prefix.cxx:73:0,
                 from /home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/cotire/hphp_util_CXX_prefix.hxx:4:
/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/embedded-vfs.cpp: In function 'void HPHP::embeddedEnter()':
/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/embedded-vfs.cpp:68:31: error: 'sqlite3_api' was not declared in this scope
 static void embeddedEnter() { sqlite3_mutex_enter(gEmbedded.pMutex); }
                               ^
/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/embedded-vfs.cpp: In function 'void HPHP::embeddedLeave()':
/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/embedded-vfs.cpp:69:31: error: 'sqlite3_api' was not declared in this scope
 static void embeddedLeave() { sqlite3_mutex_leave(gEmbedded.pMutex); }
                               ^
/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/embedded-vfs.cpp: In function 'int HPHP::sqlite3_embedded_initialize(const char*, int)':
/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/embedded-vfs.cpp:219:14: error: 'sqlite3_api' was not declared in this scope
   pOrigVfs = sqlite3_vfs_find(zOrigVfsName);
              ^
/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/embedded-vfs.cpp: In function 'int HPHP::sqlite3_embedded_shutdown()':
/home/users/glen/rpm/packages/BUILD.x86_64-linux/hhvm-HHVM-3.3.2/hphp/util/embedded-vfs.cpp:269:3: error: 'sqlite3_api' was not declared in this scope
   sqlite3_mutex_free(gEmbedded.pMutex);
   ^
```

**Comment by Orvid** [comment] 2016-03-21 23:30
This is against 3.3, so closing for now. If it's still an issue, feel free to re-open it.

**Closed by Orvid** 2016-03-21 23:30 UTC
