### ISSUE TITLE
PHP7 Arrays are not allowed in class constants

### ISSUE THREAD

**Issue by thebatundertaken** [facebook/hhvm#7214] opened 2016-07-08 21:34 UTC
### HHVM Version
HHVM-3.14.2-0

### Standalone code, or other way to reproduce the problem
class Foo {
    const BAR = array('apple', 'orange');
}

### Expected result
Code works in PHP7

### Actual result
Fatal error: Arrays are not allowed in class constants

**Comment by TysonAndre** [comment] 2016-07-23 05:13
Not a member of hhvm team, but this is a duplicate of https://github.com/facebook/hhvm/issues/4277

**Closed** 2016-09-29 16:58 UTC
Labels: duplicate, php7 incompatibility
