### ISSUE TITLE
Cannot build on Fedora 22

### ISSUE THREAD

**Issue by sebastianbergmann** [facebook/hhvm#5658] opened 2015-07-11 07:06 UTC
At first glance looks similar (though much earlier in the build process) to #5536 and #5606. However, it does not seem to memory related. Of the 8 GB of RAM installed never more than 1 GB is used (according to `top`) while the build is running.

## cmake

```
$ cmake  .
-- The C compiler identification is GNU 5.1.1
-- The CXX compiler identification is GNU 5.1.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test IS_X64
-- Performing Test IS_X64 - Success
-- Performing Test IS_AARCH64
-- Performing Test IS_AARCH64 - Failed
-- Performing Test IS_PPC64
-- Performing Test IS_PPC64 - Failed
-- Performing Test PTHREAD_TIMEDLOCK
-- Performing Test PTHREAD_TIMEDLOCK - Failed
-- Build type not specified: cmake build type Release.
-- Found LibDL: /usr/lib64/libdl.so  
-- Performing Test LIBDL_NEEDS_UNDERSCORE
-- Performing Test LIBDL_NEEDS_UNDERSCORE - Failed
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   system
--   program_options
--   filesystem
--   context
-- Found LIBGLOG: /usr/lib64/libglog.so  
-- Could NOT find LIBINOTIFY (missing:  LIBINOTIFY_LIBRARY) 
-- Could NOT find LIBICONV (missing:  LIBICONV_LIBRARY) 
-- Performing Test LIBICONV_CONST
-- Performing Test LIBICONV_CONST - Failed
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Found LIBMEMCACHED: /usr/lib64/libmemcached.so  
-- Found PCRE: /usr/lib64/libpcre.so  
-- Performing Test SYSTEM_PCRE_HAS_JIT
-- Performing Test SYSTEM_PCRE_HAS_JIT - Success
-- Found libevent: /usr/lib64/libevent.so
-- Looking for evhttp_bind_socket_with_fd
-- Looking for evhttp_bind_socket_with_fd - not found
-- Could NOT find LibUODBC (missing:  LIBODBC_LIBRARIES LIBODBC_INCLUDE_DIRS) 
-- Found CURL: /usr/lib64/libcurl.so (found version "7.40.0") 
-- Looking for curl_multi_select
-- Looking for curl_multi_select - not found
-- Looking for curl_multi_wait
-- Looking for curl_multi_wait - found
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.2") 
-- Found LibXslt: /usr/lib64/libxslt.so (found version "1.1.28") 
-- Found EXPAT: /usr/lib64/libexpat.so (found version "2.1.0") 
-- Found LIBSQLITE3: /usr/lib64/libsqlite3.so  
-- Found libsqlite3: /usr/lib64/libsqlite3.so
-- Could NOT find DOUBLE_CONVERSION (missing:  DOUBLE_CONVERSION_LIBRARY DOUBLE_CONVERSION_INCLUDE_DIR) 
-- Using third-party bundled double-conversion
-- Found LZ4: /usr/lib64/liblz4.so  
-- Found LZ4: /usr/lib64/liblz4.so
-- Could NOT find FastLZ (missing:  FASTLZ_LIBRARY FASTLZ_INCLUDE_DIR) 
-- Using third-party bundled fastlz
-- Found LIBZIP: /usr/lib64/libzip.so  
-- Found libzip: /usr/lib64/libzip.so 0.11.2
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib64/libicuuc.so
-- Performing Test JEMALLOC_VERSION_MINIMUM
-- Performing Test JEMALLOC_VERSION_MINIMUM - Success
-- Found jemalloc: /usr/lib64/libjemalloc.so
-- Found Intel TBB
-- Found mcrypt: /usr/lib64/libmcrypt.so
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1k") 
-- Performing Test OPENSSL_HAVE_RAND_EGD
-- Performing Test OPENSSL_HAVE_RAND_EGD - Success
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so - found
-- Found ONIGURUMA: /usr/lib64/libonig.so  
-- Found ldap: /usr/lib64/libldap.so;/usr/lib64/liblber.so
-- Found LIBPTHREAD: /usr/lib64/libpthread.so  
-- Found Readline: /usr/include  
-- Found Editline: /usr/lib64/libedit.so  
-- Found LibElf: /usr/lib64/libelf.so  
-- Performing Test ELF_GETSHDRSTRNDX
-- Performing Test ELF_GETSHDRSTRNDX - Success
-- Found LibDwarf: TRUE  
-- Looking for dwarf_producer_init
-- Looking for dwarf_producer_init - found
-- Performing Test DW_CONST
-- Performing Test DW_CONST - Success
-- Looking for dwarf_producer_init_c
-- Looking for dwarf_producer_init_c - not found
-- libdwarf uses const char* type
-- libdwarf does not have dwarf_producer_init_c, using dwarf_producer_init
-- Performing Test FOLLY_HAVE_WEAK_SYMBOLS
-- Performing Test FOLLY_HAVE_WEAK_SYMBOLS - Success
Generating Release build
-- Performing Test FOLLY_IFUNC
-- Performing Test FOLLY_IFUNC - Failed
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for pthread_atfork
-- Looking for pthread_atfork - found
-- Looking for pthread_spin_lock
-- Looking for pthread_spin_lock - found
-- Did not find system RE2
-- Building RE2 from third-party
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file locale.h
-- Looking for include file locale.h - found
-- Looking for include file limits.h
-- Looking for include file limits.h - found
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for atoll
-- Looking for atoll - found
-- Looking for strftime
-- Looking for strftime - found
-- Looking for setlocale
-- Looking for setlocale - found
-- Performing Test FOLLY_MALLOC
-- Performing Test FOLLY_MALLOC - Success
-- Performing Test FOLLY_FUNCTEXCEPT
-- Performing Test FOLLY_FUNCTEXCEPT - Success
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   system
--   program_options
--   filesystem
--   regex
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   thread
--   system
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   thread
--   system
-- Looking for arpa/inet.h
-- Looking for arpa/inet.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of ssize_t
-- Check size of ssize_t - done
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Looking for AF_LOCAL
-- Looking for AF_LOCAL - found
-- Looking for PF_LOCAL
-- Looking for PF_LOCAL - found
-- Looking for memset
-- Looking for memset - found
-- Looking for socket
-- Looking for socket - found
-- Looking for strerror
-- Looking for strerror - found
-- Found libevent: /usr/lib64/libevent.so
-- Looking for event_get_version_number
-- Looking for event_get_version_number - found
-- Performing Test HAVE_LIBEVENT_209
-- Performing Test HAVE_LIBEVENT_209 - Success
-- Found libevent 2.0.9+
-- Looking for include file stdio.h
-- Looking for include file stdio.h - found
-- Looking for include file assert.h
-- Looking for include file assert.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strchr
-- Looking for strchr - found
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   context
--   regex
--   system
--   filesystem
-- Build type not specified: cmake build type Release.
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   system
--   program_options
--   filesystem
--   context
-- Found libevent: /usr/lib64/libevent.so
-- Could NOT find LibUODBC (missing:  LIBODBC_LIBRARIES LIBODBC_INCLUDE_DIRS) 
-- Found libsqlite3: /usr/lib64/libsqlite3.so
-- Could NOT find DOUBLE_CONVERSION (missing:  DOUBLE_CONVERSION_LIBRARY DOUBLE_CONVERSION_INCLUDE_DIR) 
-- Using third-party bundled double-conversion
-- Found LZ4: /usr/lib64/liblz4.so
-- Could NOT find FastLZ (missing:  FASTLZ_LIBRARY FASTLZ_INCLUDE_DIR) 
-- Using third-party bundled fastlz
-- Found libzip: /usr/lib64/libzip.so 0.11.2
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib64/libicuuc.so
-- Found jemalloc: /usr/lib64/libjemalloc.so
-- Found Intel TBB
-- Found mcrypt: /usr/lib64/libmcrypt.so
-- Looking for dwarf_producer_init
-- Looking for dwarf_producer_init - found
-- Performing Test DW_CONST
-- Performing Test DW_CONST - Success
-- Looking for dwarf_producer_init_c
-- Looking for dwarf_producer_init_c - not found
-- libdwarf uses const char* type
-- libdwarf does not have dwarf_producer_init_c, using dwarf_producer_init
Generating Release build
-- Found ocamlc: /usr/bin/ocamlc
-- Found ocamlc.opt: /usr/bin/ocamlc.opt
-- Building async MySQL extension
-- Found LibJpeg: /usr/lib64/libjpeg.so  
-- Found LibPng: /usr/lib64/libpng.so  
-- Found LibVPX: /usr/lib64/libvpx.so  
-- Found Freetype: /usr/lib64/libfreetype.so  
-- Building mcrouter extension
-- Found GMP: /usr/lib64/libgmp.so  
-- GNU FriBidi not found
-- Found LibMagicWand: /usr/lib64/libMagickWand-6.Q16.so  
-- Using built-in JSON parser
-- Found LibYaml: /usr/lib64/libyaml.so  
-- Found gold: /usr/bin/ld.gold
-- Performing Test NOT_REQUIRE_ATOMIC_LINKER_FLAG
-- Performing Test NOT_REQUIRE_ATOMIC_LINKER_FLAG - Success
CMake Warning (dev) at CMake/HPHPFunctions.cmake:158 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "hhvm".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  hphp/hhvm/CMakeLists.txt:79 (HHVM_INSTALL)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/hhvm/src
```

## make

```
$ make -j1
Scanning dependencies of target timelib
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/astro.c.o
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/dow.c.o
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/interval.c.o
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/parse_date.c.o
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/parse_iso_intervals.c.o
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/parse_tz.c.o
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/timelib.c.o
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/tm2unixtime.c.o
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/unixtime2tm.c.o
Linking C static library libtimelib.a
[  0%] Built target timelib
Scanning dependencies of target double-conversion
[  0%] Building CXX object third-party/double-conversion/CMakeFiles/double-conversion.dir/src/bignum.cc.o
/usr/local/src/hhvm/src/third-party/double-conversion/src/bignum.cc: In member function ‘void double_conversion::Bignum::AssignDecimalString(double_conversion::Vector<const char>)’:
/usr/local/src/hhvm/src/third-party/double-conversion/src/bignum.cc:101:6: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]
 void Bignum::AssignDecimalString(Vector<const char> value) {
      ^
[  0%] Building CXX object third-party/double-conversion/CMakeFiles/double-conversion.dir/src/bignum-dtoa.cc.o
[  0%] Building CXX object third-party/double-conversion/CMakeFiles/double-conversion.dir/src/double-conversion.cc.o
[  0%] Building CXX object third-party/double-conversion/CMakeFiles/double-conversion.dir/src/cached-powers.cc.o
[  0%] Building CXX object third-party/double-conversion/CMakeFiles/double-conversion.dir/src/fixed-dtoa.cc.o
[  0%] Building CXX object third-party/double-conversion/CMakeFiles/double-conversion.dir/src/fast-dtoa.cc.o
[  0%] Building CXX object third-party/double-conversion/CMakeFiles/double-conversion.dir/src/strtod.cc.o
[  0%] Building CXX object third-party/double-conversion/CMakeFiles/double-conversion.dir/src/diy-fp.cc.o
Linking CXX static library libdouble-conversion.a
[  0%] Built target double-conversion
Scanning dependencies of target folly
[  0%] Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/IPAddressV6.cpp.o
[  1%] Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/FileUtil.cpp.o
[  1%] Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/Malloc.cpp.o
[  1%] Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/Uri.cpp.o
[  1%] Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/json.cpp.o
In file included from /usr/local/src/hhvm/src/third-party/folly/folly/FBString.h:59:0,
                 from /usr/local/src/hhvm/src/third-party/folly/folly/dynamic.h:78,
                 from /usr/local/src/hhvm/src/third-party/folly/folly/json.h:44,
                 from /usr/local/src/hhvm/src/third-party/folly/folly/json.cpp:17:
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h: In substitution of ‘template<class RHS, RHS rhs, class LHS> bool folly::detail::greater_than_impl(typename std::enable_if<(rhs < std::numeric_limits<_UIntType>::min()), LHS>::type) [with RHS = long int; RHS rhs = 9223372036854775807l; LHS = bool]’:
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:419:4:   required from ‘bool folly::greater_than(LHS) [with RHS = long int; RHS rhs = 9223372036854775807l; LHS = bool]’
/usr/local/src/hhvm/src/third-party/folly/folly/Conv.h:103:59:   required from ‘typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type folly::to(const Src&) [with Tgt = long int; Src = bool; typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:591:26:   required from ‘T folly::dynamic::asImpl() const [with T = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:384:64:   required from here
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:379:10: warning: comparison of constant ‘9223372036854775807l’ with boolean expression is always false [-Wbool-compare]
     (rhs < std::numeric_limits<LHS>::min()),
          ^
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h: In substitution of ‘template<class RHS, RHS rhs, class LHS> bool folly::detail::greater_than_impl(typename std::enable_if<(rhs > std::numeric_limits<_UIntType>::max()), LHS>::type) [with RHS = long int; RHS rhs = 9223372036854775807l; LHS = bool]’:
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:419:4:   required from ‘bool folly::greater_than(LHS) [with RHS = long int; RHS rhs = 9223372036854775807l; LHS = bool]’
/usr/local/src/hhvm/src/third-party/folly/folly/Conv.h:103:59:   required from ‘typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type folly::to(const Src&) [with Tgt = long int; Src = bool; typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:591:26:   required from ‘T folly::dynamic::asImpl() const [with T = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:384:64:   required from here
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:336:10: warning: comparison of constant ‘9223372036854775807l’ with boolean expression is always true [-Wbool-compare]
     (rhs > std::numeric_limits<LHS>::max()),
          ^
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h: In substitution of ‘template<class RHS, RHS rhs, class LHS> bool folly::detail::greater_than_impl(typename std::enable_if<(rhs > std::numeric_limits<_UIntType>::max()), LHS>::type) [with RHS = long int; RHS rhs = 9223372036854775807l; LHS = bool]’:
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:419:4:   required from ‘bool folly::greater_than(LHS) [with RHS = long int; RHS rhs = 9223372036854775807l; LHS = bool]’
/usr/local/src/hhvm/src/third-party/folly/folly/Conv.h:103:59:   required from ‘typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type folly::to(const Src&) [with Tgt = long int; Src = bool; typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:591:26:   required from ‘T folly::dynamic::asImpl() const [with T = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:384:64:   required from here
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:336:10: warning: comparison of constant ‘9223372036854775807l’ with boolean expression is always true [-Wbool-compare]
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:336:10: warning: comparison of constant ‘9223372036854775807l’ with boolean expression is always true [-Wbool-compare]
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h: In substitution of ‘template<class RHS, RHS rhs, class LHS> bool folly::detail::greater_than_impl(typename std::enable_if<((rhs <= std::numeric_limits<_UIntType>::max()) && (rhs >= std::numeric_limits<_UIntType>::min())), LHS>::type) [with RHS = long int; RHS rhs = 9223372036854775807l; LHS = bool]’:
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:419:4:   required from ‘bool folly::greater_than(LHS) [with RHS = long int; RHS rhs = 9223372036854775807l; LHS = bool]’
/usr/local/src/hhvm/src/third-party/folly/folly/Conv.h:103:59:   required from ‘typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type folly::to(const Src&) [with Tgt = long int; Src = bool; typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:591:26:   required from ‘T folly::dynamic::asImpl() const [with T = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:384:64:   required from here
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:358:10: warning: comparison of constant ‘9223372036854775807l’ with boolean expression is always false [-Wbool-compare]
     (rhs <= std::numeric_limits<LHS>::max()
          ^
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:359:14: warning: comparison of constant ‘9223372036854775807l’ with boolean expression is always true [-Wbool-compare]
       && rhs >= std::numeric_limits<LHS>::min()),
              ^
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h: In substitution of ‘template<class RHS, RHS rhs, class LHS> bool folly::detail::less_than_impl(typename std::enable_if<(rhs <= std::numeric_limits<_UIntType>::min()), LHS>::type) [with RHS = long int; RHS rhs = -9223372036854775808l; LHS = bool]’:
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:412:4:   required from ‘bool folly::less_than(LHS) [with RHS = long int; RHS rhs = -9223372036854775808l; LHS = bool]’
/usr/local/src/hhvm/src/third-party/folly/folly/Conv.h:110:56:   required from ‘typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type folly::to(const Src&) [with Tgt = long int; Src = bool; typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:591:26:   required from ‘T folly::dynamic::asImpl() const [with T = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:384:64:   required from here
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:346:10: warning: comparison of constant ‘-9223372036854775808l’ with boolean expression is always true [-Wbool-compare]
     (rhs <= std::numeric_limits<LHS>::min()),
          ^
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h: In substitution of ‘template<class RHS, RHS rhs, class LHS> bool folly::detail::less_than_impl(typename std::enable_if<(rhs <= std::numeric_limits<_UIntType>::min()), LHS>::type) [with RHS = long int; RHS rhs = -9223372036854775808l; LHS = bool]’:
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:412:4:   required from ‘bool folly::less_than(LHS) [with RHS = long int; RHS rhs = -9223372036854775808l; LHS = bool]’
/usr/local/src/hhvm/src/third-party/folly/folly/Conv.h:110:56:   required from ‘typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type folly::to(const Src&) [with Tgt = long int; Src = bool; typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:591:26:   required from ‘T folly::dynamic::asImpl() const [with T = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:384:64:   required from here
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:346:10: warning: comparison of constant ‘-9223372036854775808l’ with boolean expression is always true [-Wbool-compare]
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:346:10: warning: comparison of constant ‘-9223372036854775808l’ with boolean expression is always true [-Wbool-compare]
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h: In substitution of ‘template<class RHS, RHS rhs, class LHS> bool folly::detail::less_than_impl(typename std::enable_if<(rhs > std::numeric_limits<_UIntType>::max()), LHS>::type) [with RHS = long int; RHS rhs = -9223372036854775808l; LHS = bool]’:
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:412:4:   required from ‘bool folly::less_than(LHS) [with RHS = long int; RHS rhs = -9223372036854775808l; LHS = bool]’
/usr/local/src/hhvm/src/third-party/folly/folly/Conv.h:110:56:   required from ‘typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type folly::to(const Src&) [with Tgt = long int; Src = bool; typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:591:26:   required from ‘T folly::dynamic::asImpl() const [with T = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:384:64:   required from here
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:336:10: warning: comparison of constant ‘-9223372036854775808l’ with boolean expression is always false [-Wbool-compare]
     (rhs > std::numeric_limits<LHS>::max()),
          ^
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h: In substitution of ‘template<class RHS, RHS rhs, class LHS> bool folly::detail::less_than_impl(typename std::enable_if<((rhs <= std::numeric_limits<_UIntType>::max()) && (rhs > std::numeric_limits<_UIntType>::min())), LHS>::type) [with RHS = long int; RHS rhs = -9223372036854775808l; LHS = bool]’:
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:412:4:   required from ‘bool folly::less_than(LHS) [with RHS = long int; RHS rhs = -9223372036854775808l; LHS = bool]’
/usr/local/src/hhvm/src/third-party/folly/folly/Conv.h:110:56:   required from ‘typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type folly::to(const Src&) [with Tgt = long int; Src = bool; typename std::enable_if<((std::is_integral<_Tp2>::value && std::is_integral<_Tp>::value) && (! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value)), Tgt>::type = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:591:26:   required from ‘T folly::dynamic::asImpl() const [with T = long int]’
/usr/local/src/hhvm/src/third-party/folly/folly/dynamic-inl.h:384:64:   required from here
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:325:10: warning: comparison of constant ‘-9223372036854775808l’ with boolean expression is always true [-Wbool-compare]
     (rhs <= std::numeric_limits<LHS>::max()
          ^
/usr/local/src/hhvm/src/third-party/folly/folly/Traits.h:326:14: warning: comparison of constant ‘-9223372036854775808l’ with boolean expression is always false [-Wbool-compare]
       && rhs > std::numeric_limits<LHS>::min()),
              ^
‘
Internal compiler error: Error reporting routines re-entered.
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/ccAtXRLK.out file, please attach this to your bugreport.
third-party/folly/CMakeFiles/folly.dir/build.make:146: recipe for target 'third-party/folly/CMakeFiles/folly.dir/folly/json.cpp.o' failed
make[2]: *** [third-party/folly/CMakeFiles/folly.dir/folly/json.cpp.o] Error 1
CMakeFiles/Makefile2:173: recipe for target 'third-party/folly/CMakeFiles/folly.dir/all' failed
make[1]: *** [third-party/folly/CMakeFiles/folly.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jwatzman** [comment] 2015-07-11 20:37
This ICE is different than the others you linked, indeed -- it might actually be a bug in GCC? That's my best guess, and the usual cause of ICE errors other than the OOM "cc1plus killed".

I might follow the directions in the error message and submit a bug upstream to GCC with the preprocessed source? It's probably a *huge* test case for them, so I'm not sure how useful it will end up being for GCC devs.

That said, HHVM is known to not compile with GCC 5.x for other reasons.

**Comment by sebastianbergmann** [comment] 2015-07-12 05:09
Is this incompatibility with GCC 5.x documented somewhere? What is the latest version of GCC that is supported?

**Comment by jwatzman** [comment] 2015-07-13 16:42
GCC 4.8 and 4.9 both are regularly tested. https://github.com/facebook/hhvm/pull/5472 was an attempt to fix some of the GCC 5 issues, though both https://github.com/facebook/hhvm/issues/5343 and https://github.com/facebook/hhvm/issues/5184 remain open, and I think there's still an issue with `re2` in third-party.

Happy to take PRs to fix any of these issues -- I suspect most of them aren't that complicated -- but just not something we're focusing on ourselves right now.

**Comment by sebastianbergmann** [comment] 2015-07-19 16:39
It would be nice if `cmake` would bail out when an unsupported version of GCC is used. Nevertheless, I managed to build HHVM (current `master`) on Fedora with a self-built GCC 4.9.3.

**Comment by Orvid** [comment] 2016-09-30 19:32
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:32 UTC
Labels: build, external
