### ISSUE TITLE
PHP Upload size problem

### ISSUE THREAD

**Issue by Karabaja** [facebook/hhvm#7169] opened 2016-06-19 17:03 UTC
HipHop VM 3.13.2 (rel)

We are running vbulletin forum and have a problem with attaching files of certain size. 10MB file works fine, but 15MB for example fails. I get no errors logged so I am not sure what is wrong. I just get an error in vbulletin attachment window saying upload of filed failed. 
I imagine it could be related to vbulletin not being able to read php PHP Max Post Size and Max Upload Size. As it just reads N/A in VB admin panel. 
Opening a php file that should read those values in browser reads no values. And this is what it reads with hhvm 
hhvm -f test.php
Possible bad config node: Eval.JitAStubsSize
value: '60M'
value: '104857600'

In similar issue here I saw someone mention this as a solution:
hhvm.enable_zend_ini_compat=false

But seems to have made no change for me. Vbulletin still doesn't read any values. 
Is there a way for me to at least log the exact error? 
Nginx doesn't log anything for these events when upload fails, and hhvm doesn't log anything either, just some slow mysql queries.

**Comment by jjborie** [comment] 2016-07-15 13:47
Check on server.ini:
hhvm.server.max_post_size = 15MB
hhvm.server.upload.upload_max_file_size = 15MB

On php.ini:
upload_max_filesize = 15M

If you using API to upload files check also on nginx.conf these 2:
  client_body_buffer_size 15M;
  client_max_body_size 15M;

**Comment by Karabaja** [comment] 2016-07-18 23:46
Thx jjborie for suggestions but those values are all set high enough. Still vbulletin just seems to pull some limit from I don't know where. Here is what file upload diagnostics in vbulletin reads:
Pertinent PHP Settings
file_uploads: 	On
open_basedir: 	None
safe_mode: 	Off
upload_tmp_dir: 	/tmp
upload_max_filesize: 	10.00 MB

There is no php.ini file anywhere on the server that has the limit set to 10MB.

**Comment by aorenste** [comment] 2016-09-29 16:49
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by aorenste** 2016-09-29 16:49 UTC
Labels: needs more info, no isolated repro
