### ISSUE TITLE
DateTimeZone::listIdentifiers with PER_COUNTRY gives empty result for all countries but WF

### ISSUE THREAD

**Issue by doublecompile** [facebook/hhvm#5876] opened 2015-08-07 16:26 UTC
Using HHVM 3.8.1 on both Ubuntu Trusty and Debian Jessie, using the `DateTimeZone::listIdentifiers` method to filter time zones by country will return an empty array.

```php
var_dump(DateTimeZone::listIdentifiers(DateTimeZone::PER_COUNTRY, 'US'));
```
Outputs:
```
array(0) {
}
```
However, out of all of the ISO 3166 country codes, *only* `WF` returns any data.
```php
var_dump(DateTimeZone::listIdentifiers(DateTimeZone::PER_COUNTRY, 'WF'));
```
Outputs:
```
array(1) {
  [0] =>
  string(14) "Pacific/Wallis"
}
```
Calling `DateTimeZone::listIdentifiers` with no arguments produces the correct list of *all* timezones.

Calling `DateTimeZone::listIdentifiers` to filter for a *region* seems to work correctly.
```php
var_dump(DateTimeZone::listIdentifiers(DateTimeZone::AMERICA));
```
Outputs (truncated):
```
array(164) {
  [0] =>
  string(12) "America/Adak"
  [1] =>
  string(17) "America/Anchorage"
…
```
What gives? Is there some missing timezone database package on these platforms, or is there a bug in HHVM?

**Comment by jwatzman** [comment] 2015-08-10 18:15
This looks like an HHVM bug, and a regression in 3.8 to boot: http://3v4l.org/M9fmO

**Comment by wjywbs** [comment] 2015-08-10 20:21
By the way, this was fixed by https://github.com/facebook/hhvm/commit/1b89ce62d6cb9d9086f872bd4e7b92932485affd.

**Comment by jwatzman** [comment] 2015-08-10 20:22
Aha, that's why I couldn't repro in a recent internal build :)

**Comment by jwatzman** [comment] 2015-08-10 20:23
The rev @wjywbs indicates will be in 3.9, due out late this week / early next week.

**Closed by jwatzman** 2015-08-10 20:23 UTC
Labels: php5 incompatibility
