### ISSUE TITLE
HHVM fastcgi_params can only be set once

### ISSUE THREAD

**Issue by jg-development** [facebook/hhvm#5085] opened 2015-03-27 12:33 UTC
Hi,
I have the following nginx configuration (In php 5.5.22 it works fine).
```
    fastcgi_param SERVER_PORT 443;
    fastcgi_param HTTPS on;
```

A "var_dump($_SERVER);die();" in my index.php results in the following:
```
["SERVER_PORT"]=> string(4) "8080" 
["HTTPS"]=> string(0) "" 
["SCRIPT_URI"]=> string(56) "http://test.local/index.php" 
```
But it should be:
```
["SERVER_PORT"]=> string(4) "443" 
["HTTPS"]=> string(0) "on" 
["SCRIPT_URI"]=> string(56) "https://test.local/index.php" 
```

I am working with hhvm 3.6.1. I think this issue is new and wasnt there in 3.6.0

Greetings

Jan

**Comment by danslo** [comment] 2015-03-27 13:24
Works fine for me (``SERVER_PORT``) in both 3.6.1 and latest master.

```
$ cat /etc/nginx/sites-enabled/development | grep SERVER_PORT
fastcgi_param  SERVER_PORT     1337;
$ hhvm --version
HipHop VM 3.6.1 (rel)
Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3
$ hhvm -ms -vServer.Type=fastcgi -vServer.Port=9000
$ curl http://hhvm.dev/test.php 2>/dev/null | grep SERVER_PORT -A1
  ["SERVER_PORT"]=>
  string(4) "1337"
```

So I think you'll have to get a lot more specific about your nginx configuration.

**Comment by jg-development** [comment] 2015-03-27 13:50
Hi,

the configuration is generally like this:
Port 80/443 Nginx for SSL-Temrination ->
Port 6081 Varnish Reverse Proxy ->
Port 8080 Nginx with hhvm fastcgi.

The configuration for the public (80/443) is like this:

```
server {
  listen                *:80;
  server_name           test.local;
  if ($ssl_protocol = "") {
    return 301 https://$host$request_uri; 
  }


  access_log            /var/log/nginx/test.local.access.log combined;
  error_log             /var/log/nginx/test.local.error.log;

  location / {
    proxy_pass            http://varnish-upstream;
    proxy_read_timeout    900;
    proxy_connect_timeout 900;
    proxy_redirect        off;

    proxy_set_header      Host $host;
    proxy_set_header      X-Real-IP $remote_addr;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;

  }
}

```

The configuration for the internal (magento shop) ist like this:

```
server {
  listen                127.0.0.1:8080;
  server_name           test.local;

  root /var/www/test.local;

  access_log            /var/log/nginx/test.local.access.log combined;
  error_log             /var/log/nginx/test.local.error.log;

  location = / {
    return http://test.local/de;
  }

  location / {
    expires 30d;
    index index.php;
    try_files $uri $uri/ @handler;
  }

  location ^~ /report/config.xml {
    deny all;
    index index.php;
  }

  location ^~ /media/downloadable/ {
    deny all;
    index index.php;
  }

  location ^~ /var/ {
    deny all;
    index index.php;
  }

  location ^~ /lib/ {
    deny all;
    index index.php;
  }

  location ^~ /pkginfo/ {
    deny all;
    index index.php;
  }

  location ^~ /app/ {
    deny all;
    index index.php;
  }

  location ^~ /includes/ {
    deny all;
    index index.php;
  }

  location /var/export/ {
    autoindex on;
  }

  location ~ .php/ {
    rewrite ^(.*.php)/ $1 last;
  }

  location ~ \.php$ {
    include       /etc/nginx/fastcgi_params;

    fastcgi_pass  127.0.0.1:9000;
    fastcgi_connect_timeout 3m;
    fastcgi_param SERVER_PORT 443;
    fastcgi_param HTTPS on;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PHP_VALUE 'newrelic.appname=test.loal';
    fastcgi_read_timeout 3m;
    fastcgi_send_timeout 3m;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
  }

  location @handler {
    rewrite / /index.php;
  }
}

```

Hope that helps a bit. If I switch to "fastcgi_pass  unix:/var/run/php5-fpm.sock;" it is working without any problems.

Greetings Jan

**Comment by dannytrue** [comment] 2015-03-27 16:22
@jg-development any luck? got into the same problems

**Comment by jg-development** [comment] 2015-03-27 16:34
Ok, thats good to know. Now I am quite sure, that it is a hhvm problem. And I tested it on a seperate vagrant box. The only quickfix option was to switch back to php or at the top of the index.php set the settings manually.
Like:
```
$_SERVER['SERVER_PORT'] = "443";
$_SERVER['HTTPS'] = "on";
$_SERVER["SCRIPT_URI"] = "https://test.local/index.php";
```

**Comment by dannytrue** [comment] 2015-03-27 16:45
@jg-development yeah, it's definitely HHVM issue, because all works fine on PHP-FPM. Moreover it had worked correctly before I upgraded HHVM. Going to try downgrade HHVM.

**Comment by jg-development** [comment] 2015-03-27 17:37
@facebook: Could you plz look into this? This issue had come with 3.6.1.

**Comment by dannytrue** [comment] 2015-03-27 18:14
@jg-development I found very interesting issue, I'm not sure that the same makes sense for you, but I have fixed this issue on my server just by moving declaration of a fastcgi parameter above include of default fastcgi parameters. It seems fastcgi_params that were defined are not being redefined.

Anyway the following changes were helpful for me:

    include fastcgi_params;
    -fastcgi_param SERVER_PORT 443;
    ------------------------------------------------
    +fastcgi_param SERVER_PORT 443;
    include fastcgi_params;

**Comment by jg-development** [comment] 2015-03-27 19:35
Thanks @dannytrue. That was the hint I needed. I had rewrite the puppet module, but now all vhosts are working.
Still... this is a bug in hhvm. The correct subject must be now addressed as: "HHVM fastcig_params can only be set once"

**Comment by jrobeson** [comment] 2015-03-29 03:48
this happened in 3.6.0 because the fastcgi code in was massively refactored to be more maintainable. Looks like few cases got left out in the process though.

@jg-development : can you edit the title one more time? s/fastcig/fastcgi/

**Comment by frankh** [comment] 2015-05-01 14:39
This issue caused our wordpress site that mounts to a path on a site to fail. The cause seemed to be that REQUEST_URI was not being passed through with this config:

    include fastcgi_params;
    fastcgi_param REQUEST_URI /articles$request_uri;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_index index.php;
    fastcgi_pass php;

Moving include fastcgi_params to the end fixed it:

    fastcgi_param REQUEST_URI /articles$request_uri;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_pass php;

**Comment by paulbiss** [comment] 2015-06-18 23:54
So I can't seem to reproduce this. If I pass multiple parameters the value in $_SERVER is always the last one sent. The transport code is certainly written to take the last value seen before the end of the parameters :/

**Comment by Orvid** [comment] 2016-09-30 21:24
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:24 UTC
Labels: fastcgi
