### ISSUE TITLE
HHVM - Installation error on Centos 7

### ISSUE THREAD

**Issue by datomnurdin** [facebook/hhvm#5606] opened 2015-07-08 03:29 UTC
I need to install HHVM on my linux server to enable my hacklang working. But I got this error message during installation

```
    c++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <http://bugzilla.redhat.com/bugzilla> for instructions.
    make[2]: *** [third-party/proxygen/CMakeFiles/hphp_proxygen.dir/lib/services/RequestWorker.cpp.o] Error 4
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [third-party/proxygen/CMakeFiles/hphp_proxygen.dir/all] Error 2
    make: *** [all] Error 2
```

Please advice. Thank you.

**Comment by jazzdan** [comment] 2015-07-08 05:16
If you run make again does the error persist?

**Comment by datomnurdin** [comment] 2015-07-08 05:21
yes. But I already solve it using his method, it's because of memory issue. http://stackoverflow.com/questions/31283017/hhvm-installation-error-on-centos-7

**Comment by datomnurdin** [comment] 2015-07-08 07:17
I just got this new error message after 51% completed.

```
Linking CXX static library libhphp_hhbbc.a
[ 51%] Built target hphp_hhbbc
make: *** [all] Error 2
```

Please advice. Thank you.

**Comment by jwatzman** [comment] 2015-07-11 20:35
`c++: internal compiler error: Killed (program cc1plus)`

The cause of this is almost invariably running out of RAM. How much memory does your machine have? You'll need at least 4G or so, more if you're using `make -j`.

**Comment by Orvid** [comment] 2016-09-30 19:39
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Closed by Orvid** 2016-09-30 19:39 UTC
Labels: needs more info
