### ISSUE TITLE
Profiling requests do not obey memory_limit

### ISSUE THREAD

**Issue by dzuelke** [facebook/hhvm#4723] opened 2015-01-28 00:24 UTC
With HHVM/3.5.0 on Trusty.

Config (`128M`)

```
memory_limit=134217728
```

The following script:

```
<?php
var_dump(ini_get('memory_limit'));
$x = str_repeat('x', 1024*1024*128*2);
var_dump(strlen($x));
```

is terminated as expected on the CLI:

```
~ $ hhvm -c hhvm.ini index.php 
string(9) "134217728"

Fatal error: request has exceeded memory limit in /app/index.php on line 4
```

but exceeds the limit just fine without termination via `hhvm --mode server -dhhvm.server.type=fastcgi -dhhvm.server.fastcgi...=... -c hhvm.ini`:

```
string(9) "134217728"
int(268435456)
```

**Comment by jwatzman** [comment] 2015-01-28 00:27
Especially interesting since a similar program was getting properly killed for me yesterday. Worth digging into when someone gets some time.

**Comment by jwatzman** [comment] 2015-01-28 01:13
Hm, the *first* fastcgi request works, but the rest seem to hit the memory limit. If you refresh a few times, does it start hitting the limit?

My test case was very similar to yours, `memory_limit = 10000` with

```php
<?php
var_dump(ini_get("memory_limit"));
$byte = 'x';

$y = str_repeat('x', 10000000);
var_dump(strlen($y));
```

**Comment by jwatzman** [comment] 2015-01-28 01:14
(I just used your ini setting and code, and saw the same behavior: first run incorrectly runs to completion; refreshes after that are correctly killed by the mem limit.)

**Comment by jwatzman** [comment] 2015-01-28 01:16
And if one refresh doesn't cause it to hit the mem limit, try 11 more -- I'm using the debug version which invokes the JIT after a very small number of warmup requests, but the release version doesn't trigger it until the 11th or 12th request or so. It could be that the JIT'd code is obeying the limit, but the interpreter is not?

**Comment by dzuelke** [comment] 2015-01-28 01:18
Yes! Same behavior here. Eleven requests are fine, and on the 12th:

```
2015-01-28T01:17:08.459679+00:00 app[web.1]: \nFatal error: request has exceeded memory limit in /app/index.php on line 4
```

**Comment by dzuelke** [comment] 2015-01-28 01:22
That begs the question why it terminates as expected from the first request on in the CLI though...

**Comment by jwatzman** [comment] 2015-01-28 01:22
I *think* the CLI will just always JIT, since there is no notion of "requests" there?

**Comment by jwatzman** [comment] 2015-01-28 01:26
Hm yeah it might be more complicated than that. I just tried turning the JIT off explicitly in CLI mode, and it still got killed by mem limit. Totally possible I was turning off the JIT the wrong way though :)

**Comment by paulbiss** [comment] 2015-01-28 05:47
This might be by design. It looks as though we don't allow the allocator to set OOM surprise flags in profiling requests.

https://github.com/facebook/hhvm/blob/5a46b50d809590b8feeeb05ede056106bcfb12a6/hphp/runtime/base/program-functions.cpp#L1910

**Comment by jwatzman** [comment] 2015-01-28 18:16
@dzuelke how important is this working on the profiling requests to your customers? The profiling requests are going to be slower than the rest anyways due to the profiling and lack of JIT. Does opcache have a similar warmup time?

**Comment by dzuelke** [comment] 2015-01-28 21:21
I don't think it matters much, but there's of course always the chance of one of the first eleven requests hitting some kind of infinite loop and eating up all RAM.

**Comment by jwatzman** [comment] 2015-01-29 17:36
OK -- marking as low-pri to either figure out if we can lift the restriction (and perhaps to do), or find a workaround, or decide it isn't worth it.

**Comment by paulbiss** [comment] 2016-09-28 00:18
Just about the only thing the profile requests do is set AttrHot on functions, which only matters when Eval.JitPGOHotOnly is set (by default it's off). Now that instance-bits for interface checks are computed as part of JIT profiling it should be safe to just disable profile requests (Eval.JitProfileInterpRequests=0) if you're worried about this particular pathological situation.

**Closed by paulbiss** 2016-09-28 00:18 UTC
Labels: ini, low-pri, webserver
