### ISSUE TITLE
HHVM 3.6.1: PDO connections not closed after request ends

### ISSUE THREAD

**Issue by gmagana** [facebook/hhvm#5132] opened 2015-04-05 23:37 UTC
In my nginx-hosted web site, I am opening MySQL PDO connections like this:

        $this->conn = new \PDO("mysql:host=$host;port=$port;dbname=$dbName;charset=utf8", $username, $password, array(
            \PDO::ATTR_PERSISTENT => false,
            \PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
            \PDO::ATTR_EMULATE_PREPARES => false,
            \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION
        ));

In 3.3.5 (LTS stable release), after the request ends, the MySQL connection is closed and all is well. This same code after upgrading to 3.6.1 results in the connections NOT being closed, and unless I bounce the HHVM service, MySQL eventually runs out of connections.

I tried setting PDO::ATTR_PERSISTENT = true, but then I ran into #5016 :-(.

I tried installing the nightly build, but that did not help. All was solved in the meantime by downgrading to 3.3 LTS.

Is this a known issue (searched and could not find)?  If you need more details from me, what are those?

**Comment by clementhk** [comment] 2015-04-08 07:59
Does `$this->conn = null;` help?

**Comment by Thomas2500** [comment] 2015-04-09 14:04
I have the same problem.
Closing the connection with $sql = null; doesn't help.
I'm running HHVM 3.6.1 (tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e) on Ubuntu 14.04.2 with nginx 1.6.3.

**Comment by clementhk** [comment] 2015-04-09 14:15
@AlphaStream do you know anything about this?

**Comment by gmagana** [comment] 2015-04-09 14:25
Thanks for confirming, Thomas2500, I had not had time to upgrade again to test that.

**Comment by gmagana** [comment] 2015-04-09 14:55
I think I found the problem: There is no garbage collection done at the end of a request when using HHVM from (at least) nginx on Ubuntu 14.04.2.

I went ahead and upgraded again, added this to the end of my PHP code:

        $this->conn = null;
        gc_collect_cycles();

And that DID seem to fix everything.

I'm not sure, though, if this is indicative of a larger problem in HHVM than just PDO connections.

**Comment by paulbiss** [comment] 2015-04-09 15:39
Hmm, [gc_collect_cycles](https://github.com/facebook/hhvm/blob/134d41e20c87c7f81d3fca8f1ef564dbc84aa6f7/hphp/runtime/ext/std/ext_std_options.cpp#L1182) isn't implemented in hhvm. @mxw I think this may be another issue with that persistent PDO diff.

**Comment by clementhk** [comment] 2015-04-09 16:07
I personally think this deserve a hi-pri label base on the usage of mysql, would be better if we have a regression label.

**Comment by paulbiss** [comment] 2015-04-09 16:33
@clementhk: It's being looked at-- there is an ongoing effort to refactor some of our extensions and this one was broken in the process. The priority labels don't really mean much unfortunately (I thought I had removed them awhile back...), but this one is being worked on.

**Comment by simonmilz** [comment] 2015-04-15 09:31
I also can confirm this problem with nginx + hhvm:

HipHop VM 3.6.1 (rel)
Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3

**Comment by JohanTan** [comment] 2015-04-16 02:35
Confirmed on:

HipHop VM 3.6.1 (rel)
Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3

Enabled it on staging server caused mysql connection hogging. Had to shut it down.

**Comment by clementhk** [comment] 2015-04-16 02:39
Hi @mxw,

Any estimation on this?

Thanks!

**Comment by pkirk** [comment] 2015-05-06 20:51
Seems to be still here:

HipHop VM 3.7.0 (rel)
Compiler: tags/HHVM-3.7.0-0-gc8baf9cd3cb603e030969bfe24634d5e85549915
Repo schema: 1988ce75e6a571ce9c79c60fd7dc3ca8a5a5d403

While trying CakePHP3 on HHVM 3.7 from Debian repo.

**Comment by leearmstrong** [comment] 2015-05-07 03:49
Seeing this on 3.7.0 too

**Comment by paulbiss** [comment] 2015-05-07 04:48
There's a fix up for review internally, it hasn't landed yet. Sorry for the delay.

**Comment by leearmstrong** [comment] 2015-05-07 04:51
Thanks @paulbiss 

As it is quite a large bug in the LTS. Are we likely to see this in a 3.6.x point release?

**Comment by paulbiss** [comment] 2015-05-07 05:01
Assuming it applies cleanly (I have no reason to suspect that it won't), I will make sure it gets cherry-picked. I can't promise that we will cut the release just for this patch though, it may have to wait for the next CVE to get merged.

**Comment by leearmstrong** [comment] 2015-05-07 05:07
Thanks. We've had to roll back to 3.3 for the time being

**Comment by pkirk** [comment] 2015-05-07 05:34
Just noted that on my setup (Debian7+HHVM3.7.0 from repo+latest CakePHP3 from composer), HHVM crashes at the second request when activating "persistent" flag in the DB.
[Stacktrace.log](https://gist.github.com/pkirk/2403ad03c3276374be5f)

**Comment by paulbiss** [comment] 2015-05-07 06:07
@pkirk the fix hasn't even landed in master yet. I'll be sure to update here once it does.

**Comment by igorclark** [comment] 2015-05-11 14:59
Hi folks, just noting that we're experiencing this too, on nginx 1.6.2 + hhvm 3.7.0. We made some changes so we could work without persistent connections and #5016 wouldn't stop us moving to HHVM - and then we got hit by this. Would be great to get even a rough ETA for when this will land? Thanks!

**Comment by sgolemon** [comment] 2015-05-14 17:22
It looks liwk @mxw may have fixed this with a diff that's already been cherry-picked onto the HHVM-3.6 branch.   Would someone who's experiencing this issue mind compiling from there and letting us know if it solves the problem?

**Comment by leearmstrong** [comment] 2015-05-14 17:29
Sara,




What commit was this out of interest?

**Comment by paulbiss** [comment] 2015-05-14 17:36
cf68d8ad996fc44eaceb7a1b042ae9267957f3ff

**Comment by leearmstrong** [comment] 2015-05-14 19:03
See latest comment on https://github.com/facebook/hhvm/issues/5016. Appears connections still not closed. @igorclark

**Comment by sgolemon** [comment] 2015-05-14 22:11
Boo... More digging then...

**Comment by igorclark** [comment] 2015-05-15 11:12
Hey, I just tried this again in a different environment and first tests seem to indicate that actually it is working as expected, both with persistent and non-persistent connections.

As per my comment on #5016, it wan't doing that with non-persistent connections when I tested it before; that was running in a debian VM on Vagrant/Virtualbox, talking to a MySQL server on the same VM. Tried again this morning with the same results.

However I've just tried it on Compute Engine with two separate VMs, and it *seems* to be working as it should, for both types of connections. Which seems great.

I'm going to do a lot more testing particularly by putting some load on the instances and see how it works out. Worth testing in your setup (and your apps) too, as it might be different again. No idea why it would be different but there are quite a lot of variables there.

**Comment by leearmstrong** [comment] 2015-05-21 06:38
@igorclark How has testing been going for non persistent connections?  Are you happy it works?

**Comment by igorclark** [comment] 2015-05-26 08:31
Hello! Sorry for the delay and not replying sooner.

It turned out to be fine for us, both in Compute Engine and on Vagrant. I destroyed and re-built all our Vagrant VMs in dev from scratch, re-set everything to make sure I wasn't doing anything mad, and beat it up pretty hard using siege. It worked as expected, both with persistent and non-persistent connections. So there must have been something messed up in my config/setup, or I guess something in that specific nightly build that affected it, but honestly my money's on it being on our side ;-)

We moved it into a GCE dev environment and did the same, with the same results. It's looking good for us right now, so thanks very much to @paulbiss and the team for pushing this through!

**Comment by leearmstrong** [comment] 2015-05-26 08:43
Awesome thanks, hopefully it will make it to 3.6.3 and the packages for this!

**Comment by leearmstrong** [comment] 2015-05-30 07:39
I notice 3.6.3 is out, is this fix inside it?

**Comment by mwpastore** [comment] 2015-05-30 09:44
I've been running 3.6.3 in production for two or three days now. Persistent connections are definitely fixed. I haven't retested non-persistent connections to see if they're closing properly.

**Comment by clementhk** [comment] 2015-05-30 11:45
Awesome, guys!! Time to close this?

**Comment by gmagana** [comment] 2015-05-30 16:25
Hi everyone, took some time to do thorough testing. 3.6.3 (obtained with the LTS 3.6 repo) and 3.7.1 behave the same as of now:

* Persistent connections now work (as observed by the other folks)
* Non-persistent connections still stay open until HHVM process is bounced.

So probably #5016 can be closed, but not this issue :-(

**Comment by leearmstrong** [comment] 2015-06-01 13:22
I managed to try today and this is fixed for me now it appears.

**Comment by leearmstrong** [comment] 2015-06-02 07:44
Actually, rolled out to some live servers and the issue persists.

Version info...
``
HipHop VM 3.6.3 (rel)
Compiler: tags/HHVM-3.6.3-0-gbf944cda87d271894e1ce5de944f3864f4e81ab2
Repo schema: c263bc50883e99184ee57a28306a5c7568781d98
``

**Comment by BrunoCartier** [comment] 2015-06-10 10:02
Seems I have this problem too trying to use Prestashop with HHVM :/
```
HipHop VM 3.7.1 (rel)
Compiler: tags/HHVM-3.7.1-0-g111c76378ac29aa8f25e6bb3c5f15b628e6bbea1
Repo schema: be14a89778f35ca7f7dd4aca7fff0793e8ae3334
```
Any update?

**Comment by csvan** [comment] 2015-06-16 18:05
Just like @BrunoCartier , I have this exact same issue on a Prestashop installation. HHVM 3.7.1.

**Comment by mattab** [comment] 2015-06-16 22:46
Piwik, the leading free/libre and open analytics platform, also experiences the issue: https://github.com/piwik/piwik/issues/7555

**Comment by gmagana** [comment] 2015-06-16 23:06
Just checked with the newly-released 3.7.2, no luck, this bug is still there :-(

**Comment by paulbiss** [comment] 2015-06-18 19:17
Pretty sure I have a fix for this, but I don't have a good way to test it.

**Comment by paulbiss** [comment] 2015-06-18 19:19
Up for review, but if anyone wants to test it and let me know if it works, you can patch this on master: https://gist.github.com/paulbiss/fe46031d06d136df6043

**Comment by Loscillo** [comment] 2015-06-19 12:56
HHVM is currently being compiled in test server to test the fix. :)

**Comment by Loscillo** [comment] 2015-06-19 14:21
Tested in Debian Jessie (8) with nginx 1.6.2 and it seems to work :) @paulbiss

**Comment by paulbiss** [comment] 2015-06-19 19:48
@Loscillo thanks! I'll land it today, we're going to cherry-pick it back into the LTS.

**Closed** 2015-06-19 20:16 UTC

**Comment by gmagana** [comment] 2015-07-06 14:36
Just got HHVM 3.7.3 from apt repo, and can form this is fixed for me as well :-) Thanks!

**Comment by craigcarnell** [comment] 2015-07-06 15:17
Slightly off topic, but does anyone know if Magento uses persistent or non-persistent connections by default?
