### ISSUE TITLE
Support is_a for providing class checks to Hack

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#7272] opened 2016-08-08 01:23 UTC
### HHVM Version

3.14
### Standalone code, or other way to reproduce the problem

``` hack
<?hh // strict

interface A {
  require extends B;

  public static function foo(): int;
}

class B {
  public static function getClass(): classname<B> {
    return C::class;
  }

  public static function test(): int {
    $class = static::getClass();

    if (is_a($class, A::class, true)) {
      return $class::foo();
    }

    return 0;
  }
}

class C extends B implements A {
  public static function foo(): int {
    return 3;
  }
}
```
### Expected result

Hack reports no errors.
### Actual result

```
test.php:18:22,24: Could not find static method foo in type B (Typing[4090])
  test.php:9:7,7: Declaration of B is here
```

I can't use `instanceof` here as `$class` is a `classname` and `instanceof` always returns false if the object variable is a string.

**Comment by paulbiss** [comment] 2016-08-08 18:45
cc @andrewjkennedy @dlreeves

**Comment by dlreeves** [comment] 2016-08-10 17:11
This has been requested before. The team recently has been focusing less on adding special case analysis like this, and more on improvements to the core type checking algorithm with a focus on eliminating type holes.

@andrewjkennedy what are your thoughts about supporting this?

**Comment by lexidor** [comment] 2023-07-30 14:50
Duplicate of #5841

**Comment by lexidor** [comment] 2023-07-30 14:52
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Closing this issue as 5841 is a generalization of the problem described here.

**Closed by lexidor** 2023-07-30 14:52 UTC
Labels: feature request, hack
