### ISSUE TITLE
Prioritize MacOS build/binary support

### ISSUE THREAD

**Issue by Ocramius** [facebook/hhvm#4444] opened 2014-12-13 14:15 UTC
As it stands, `brew install hhvm` provided by https://github.com/mcuadros/homebrew-hhvm is broken.
Same goes for building HHVM from source on MacOS.

While I don't love MacOS too much, I'm currently using it, as most of the people in my github network (according to google analytics).

It would probably be a good idea to provide either binaries or a compilable version, and to prioritize the issue.

I know for sure that builds on MacOS stopped working because of @travis-ci workers being too slow at picking up jobs for this platform, so I'm pinging them as well.

**Comment by christopherowen** [comment] 2015-01-13 07:58
#4636

**Comment by reeze** [comment] 2015-01-13 09:34
:+1:

**Comment by lovek323** [comment] 2015-02-08 00:25
:+1

**Comment by lovek323** [comment] 2015-02-08 00:25
:+1:

**Comment by lima01** [comment] 2015-02-08 00:47
+1

**Comment by ptica** [comment] 2015-02-08 21:06
+1

**Comment by cweagans** [comment] 2015-02-08 22:17
:+1:

**Comment by craigcarnell** [comment] 2015-02-17 09:28
:+1:

**Comment by Ocramius** [comment] 2015-02-17 09:34
Folks, upvoting does not really help: make a contribution instead.

**Comment by lovek323** [comment] 2015-02-17 11:42
Yeah, but it allows me to get notifications of updates to the issue. Though, I'm starting to see the flaw in my thinking. :smile:

**Comment by steveh** [comment] 2015-02-17 15:45
You can subscribe to notifications instead on the right nav bar -->

**Comment by lovek323** [comment] 2015-02-17 19:48
And now I feel stupid :disappointed:

**Comment by santagada** [comment] 2015-02-21 20:23
I feel a little impotent because there is a huge todo list of many patches ready to make it work and none of them are checked, so I think this is waiting for something that I have zero control of. I saw that 3.6 is supposed to be released soon and with support for osx. I wish I knew what is missing.

**Comment by denji** [comment] 2015-02-21 20:28
@santagada [`proxygen`](https://github.com/facebook/proxygen#installing) appeared in HHVM-3.6 and does not support OSX.

**Comment by santagada** [comment] 2015-02-21 20:41
Will it be built using clang or gcc? If it is going to use clang than I think all of those patches for folly, hhvm-thirdparty and proxygen need to be applied.

Knowing wich compiler the main devs want to support and what exactly needs to be done (porting proxygen to osx) then someone can help (my c++ foo is very weak or I would give it a try).

**Comment by simonwelsh** [comment] 2015-02-21 22:59
* It's likely to support gcc first, with clang support coming later
* 3.6.0 won't support OS X (the branch has already been cut). [This](http://hhvm.com/blog/8405/coming-soon-in-hhvm) blog post just says it's coming later in 2015.

**Comment by wjywbs** [comment] 2015-03-19 22:57
After trying several compiler combinations, I built hhvm 3.6.0 on mac 10.10.2 successfully. Only single thread is supported.

Failed attempts:
gcc 4.9.2: ld: Assertion failed: (cfiStartsArray[i] != cfiStartsArray[i-1])
Xcode's clang: Had this bug https://llvm.org/bugs/show_bug.cgi?id=22106. Use FOLLY_USE_LIBCPP might work.
clang 3.6 with gcc c++ header: link successfully, but crash at Repo::schemaExists. This might be caused by static libstdc++ linking.


You should have both clang 3.6 and gcc. I used gcc 4.9.2. (4.8 may also work. gcc is only used to compile an assembly file.)

Follow https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-OSX-10.10, but do not use homebrew's boost.

```
brew install llvm36 --with-clang --rtti --with-libcxx

export CMAKE_PREFIX_PATH=/any/path

# Use Xcode's clang to build boost
wget http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.gz
tar xzvf boost_1_57_0.tar.gz
cd boost_1_57_0
./bootstrap.sh --prefix=$CMAKE_PREFIX_PATH --with-toolset=clang
./b2 toolset=clang cxxflags="-stdlib=libc++" linkflags="-stdlib=libc++" install -j8
cd ..

# Remove async_mysql because it needs some extra work to make it build.
cd hhvm
rm -r hphp/runtime/ext/async_mysql
```

Apply these patches: hhvm_360_mac.diff, third_party_360_mac.diff, folly_360_mac.diff, thrift_360_mac.diff
https://gist.github.com/wjywbs/a417b98644dc9d6fdc85

```
cmake . \
    -DCMAKE_CXX_COMPILER=$(brew --prefix llvm36)/bin/clang++-3.6 \
    -DCMAKE_C_COMPILER=$(brew --prefix llvm36)/bin/clang-3.6 \
    -DCMAKE_ASM_COMPILER=$(brew --prefix llvm36)/bin/clang-3.6 \
    -DLIBIBERTY_LIB=$(brew --prefix binutilsfb)/lib/x86_64/libiberty.a \
    -DCMAKE_INCLUDE_PATH="/usr/local/include:/usr/include" \
    -DCMAKE_LIBRARY_PATH="/usr/local/lib:/usr/lib" \
    -DENABLE_ASYNC_MYSQL=OFF \
    -DENABLE_MCROUTER=OFF \
    -DCMAKE_CXX_FLAGS="-msse4.2 -Wno-#warnings -Wno-unused-local-typedef -Wno-inconsistent-missing-override" \
    -DLIBSQLITE3_INCLUDE_DIR=$(brew --prefix sqlite)/include \
    -DLIBSQLITE3_LIBRARY=$(brew --prefix sqlite)/lib/libsqlite3.0.dylib \
    -DLDAP_INCLUDE_DIR=$(brew --prefix openldap) \
    -DLDAP_LIBRARIES=$(brew --prefix openldap)/lib/libldap.dylib \
    -DLIBGLOG_LIBRARY=$(brew --prefix glog)/lib/libglog.dylib \
    -DLIBGLOG_INCLUDE_DIR=$(brew --prefix glog)/include \
    -DLIBEVENT_LIB=$(brew --prefix libevent)/lib/libevent.dylib \
    -DLIBEVENT_INCLUDE_DIR=$(brew --prefix libevent)/include \
    -DICU_INCLUDE_DIR=$(brew --prefix icu4c)/include \
    -DICU_LIBRARY=$(brew --prefix icu4c)/lib/libicuuc.dylib \
    -DICU_I18N_LIBRARY=$(brew --prefix icu4c)/lib/libicui18n.dylib \
    -DICU_DATA_LIBRARY=$(brew --prefix icu4c)/lib/libicudata.dylib \
    -DREADLINE_INCLUDE_DIR=$(brew --prefix readline)/include \
    -DREADLINE_LIBRARY=$(brew --prefix readline)/lib/libreadline.dylib \
    -DCURL_INCLUDE_DIR=$(brew --prefix curl)/include \
    -DCURL_LIBRARY=$(brew --prefix curl)/lib/libcurl.dylib \
    -DBOOST_INCLUDEDIR=$CMAKE_PREFIX_PATH/include \
    -DBOOST_LIBRARYDIR=$CMAKE_PREFIX_PATH/lib \
    -DBoost_USE_STATIC_LIBS=ON \
    -DJEMALLOC_INCLUDE_DIR=$(brew --prefix jemallocfb)/include \
    -DJEMALLOC_LIB=$(brew --prefix jemallocfb)/lib/libjemalloc.dylib \
    -DLIBINTL_LIBRARIES=$(brew --prefix gettext)/lib/libintl.dylib \
    -DLIBINTL_INCLUDE_DIR=$(brew --prefix gettext)/include \
    -DLIBDWARF_LIBRARIES=$(brew --prefix libdwarf)/lib/libdwarf.3.dylib \
    -DLIBDWARF_INCLUDE_DIRS=$(brew --prefix libdwarf)/include \
    -DLIBMAGICKWAND_INCLUDE_DIRS=$(brew --prefix imagemagick)/include/ImageMagick-6 \
    -DLIBMAGICKWAND_LIBRARIES=$(brew --prefix imagemagick)/lib/libMagickWand-6.Q16.dylib \
    -DMYSQL_INCLUDE_DIR=$(brew --prefix mysql-connector-c)/include \
    -DMYSQL_LIB=$(brew --prefix mysql-connector-c)/lib \
    -DFREETYPE_INCLUDE_DIRS=$(brew --prefix freetype)/include/freetype2 \
    -DFREETYPE_LIBRARIES=$(brew --prefix freetype)/lib/libfreetype.dylib \
    -DLIBMEMCACHED_LIBRARY=$(brew --prefix libmemcached)/lib/libmemcached.dylib \
    -DLIBMEMCACHED_INCLUDE_DIR=$(brew --prefix libmemcached)/include \
    -DLIBELF_LIBRARIES=$(brew --prefix libelf)/lib/libelf.a \
    -DLIBELF_INCLUDE_DIRS=$(brew --prefix libelf)/include/libelf \
    -DOPENSSL_SSL_LIBRARY=$(brew --prefix openssl)/lib/libssl.dylib \
    -DOPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include \
    -DOPENSSL_CRYPTO_LIBRARY=$(brew --prefix openssl)/lib/libcrypto.dylib \
    -DPCRE_LIBRARY=$(brew --prefix pcre)/lib \
    -DPCRE_INCLUDE_DIR=$(brew --prefix pcre)/include \
    -DTBB_INSTALL_DIR=$(brew --prefix tbb)

# Search translator-asm-helpers.S and change clang to /path/to/gcc
# Otherwise, clang -cc1as: fatal error: error in backend: 32-bit absolute addressing is not supported in 64-bit mode
vi hphp/runtime/CMakeFiles/hphp_runtime_static.dir/build.make
```

To run tests, run `brew install homebrew/php/php56; cd hphp; test/run test/quick -m interp`. For me, 36 quick tests failed and 61 of 4793 slow tests failed. (All debug and xdebug tests failed.)

I added a define (-D__thread=) because hhvm (built by clang 3.6) crashed when accessing these variables. Therefore only single thread is supported. Using multiple threads will crash. `-Wl,-segaddr,__text,0` did not link or run properly in mac 10.10 because the pagezero section must be at address 0. `-Wl,-pagezero_size,0x00001000` worked.

To use fastcgi, run `./hhvm --mode server -vServer.Type=fastcgi -vServer.Port=9000 -vEval.Jit=0 -vServer.ThreadCount=1 -vDebug.StackTraceTimeout=1`. Jit mode works partially and crashes on some pages (WordPress 4.1.1).

**Comment by wjywbs** [comment] 2015-04-13 21:03
I forgot to mention one more patch to build hhvm 3.6 successfully on mac 10.10.
```
cd third-party/folly/src
git show 66a076400edfc7cd1dd0b5de178b0c2f29660557 | git apply
```

---

I found out why hhvm crashed when accessing __thread variables if I don't define `-D__thread=""`. Sample program:
```
#include <pthread.h>
#include <stdio.h>

__thread int test = 1;

pthread_key_t key;

void delete(void* arg) {
  printf("delete %d\n", test);
}

void* thread(void* arg) {
  pthread_key_create(&key, delete);
  pthread_setspecific(key, (void*)1);

  test++;
  printf("%d\n", test);
  return NULL;
}

int main() {
  pthread_t example;
  pthread_create(&example, NULL, thread, NULL);
  pthread_join(example, NULL);
  return 0;
}
```

On Mac (regardless of the compiler), the output will be:
```
2
delete 1
```

On Linux, the output will be:
```
2
delete 2
```

which means the __thread variables are freed when pthread calls destructor on Mac. After some debugging, __thread variables are stored in pthread_t->tsd array on Mac, and initialized by `tlv_initialize_descriptors` (dyld-353.2.1/src/threadLocalVariables.c) calling `pthread_key_create` for each __thread variable when the program loads. The pthread keys are cleaned up sequentially, so the __thread variables are freed before the delete() function trying to access them again. delete() gets the default value 1 of variable "test". In hhvm, this could be accessing a null pointer.

After reading some pthread source code, I found that in `_pthread_exit` (libpthread-105.1.4/src/pthread.c), __cleanup_stack handlers are called before `_pthread_tsd_cleanup` which frees the pthread keys. We can register a handler in __cleanup_stack similar to `pthread_cleanup_push`, so the __thread variables will still exist in the handler. I have a patch for the `ThreadLocal` class.

---

JIT on Mac mostly works, but exceptions in vm can't be catched and hhvm will be terminated, such as `throw ExitException` in `interpOneExit`.

**Comment by jwatzman** [comment] 2015-06-18 17:49
If anyone wants to try this, I've been able to build and run HHVM master as of this week with MacPorts, with these instructions: https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-OSX-10.10#macports-install-by-hand -- something similar should work with Homebrew. I'm slowly looking into the test failures (and the test runner will segfault until I get one more diff reviewed and committed, should be very soon).

**Comment by reeze** [comment] 2015-06-19 03:18
:+1:

**Comment by etcinit** [comment] 2015-06-19 06:13
:+1: I was able to compile HHVM by following the steps on the wiki for MacPorts. Simple scripts run fine but many other things cause a segmentation fault. Here's the output I got from running quick tests: https://gist.github.com/etcinit/a1da886439ee439adf11

**Comment by jwatzman** [comment] 2015-06-19 16:52
@etcinit interesting, I haven't hit any of those crashes. If I can't repro, I may circle back around with you to try to figure out what's going on there.

**Comment by christopherowen** [comment] 2015-09-07 14:53
The recently released official homebrew tap is able to compile hhvm 3.9.1 at least on OSX 10.11 Beta (El Capitan).

I believe this issue can be marked resolved.

**Comment by Nyholm** [comment] 2015-09-07 14:58
I can verify that it works on El Capitan.

**Comment by Ocramius** [comment] 2015-09-07 15:56
Can anyone verify for the current stable branch (Yosemite)?

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by danslo** [comment] 2015-09-07 16:06
3.9.1 recipe definitely works on Yosemite.

**Comment by mnapoli** [comment] 2015-09-07 16:07
:+1: can confirm on Yosemite, you can close this everything is right with the world.

**Comment by craigcarnell** [comment] 2015-09-07 16:15
Tried it just, compiled, will test functionality tomorrow :+1:

**Comment by JoelMarcey** [comment] 2015-09-07 16:16
Thanks everyone!!

**Closed by JoelMarcey** 2015-09-07 16:16 UTC
Labels: build

**Comment by etcinit** [comment] 2015-09-10 20:25
Awesome :+1:
