### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function gc_mem_caches()

### ISSUE THREAD

**Issue by donutloop** [facebook/hhvm#7185] opened 2016-06-27 19:50 UTC
HHVM Version 3.14.1 and Nightly

i used that "hhvm --no-config --php composer.phar install" command.

Stacktrace:

`Fatal error: Uncaught Error: Call to undefined function Symfony\Component\ClassLoader\gc_mem_caches() in /var/www/webapplication/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:198
Stack trace:
#0 /var/www/webapplication/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(109): Symfony\Component\ClassLoader\ClassCollectionLoader::fixNamespaceDeclarations()
#1 /var/www/webapplication/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php(282): Symfony\Component\ClassLoader\ClassCollectionLoader::load()
#2 /var/www/webapplication/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php(59): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::doBuildBootstrap()
#3 {main}
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-install-cmd event terminated with an exception`

Best regards,
Marcel

**Comment by Orvid** [comment] 2016-06-28 02:18
The nightly for which OS and compiled when? 24bdc1458bdf7a0da00bd03ca09bb96bd5e978e8 already implemented the function.

**Comment by donutloop** [comment] 2016-06-28 04:41
OS: Debian 8 Jessie
i installed yesterday the nightly version.

`sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
echo deb http://dl.hhvm.com/debian jessie main | sudo tee /etc/apt/sources.list.d/hhvm.list
sudo apt-get update
sudo apt-get install hhvm-nightly`

**Comment by jwatzman** [comment] 2016-06-28 15:41
With the nightly installed, what's the output of `hhvm --version`?

@Orvid it looks like the builds are all broken, at least the internal cron checker has them all failing for like 8 days...

**Comment by donutloop** [comment] 2016-06-28 17:06
HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-gb6c077acfd520ef0bed64407d134ed1bcbd1dd9c
Repo schema: cde63aaf1ca99dcbe9174acf40af08707725d957

**Comment by apeabody** [comment] 2016-06-29 00:33
I'm currently unsure what is going on, but there is certainly something very strange:
- gc_mem_caches() is listed in get_defined_functions(), HOWEVER function_exists('gc_mem_cache') returns False?
- When piped to hhvm it failes: echo '<?php echo gc_mem_caches();' | hhvm --php
Fatal error: Call to undefined function gc_mem_caches() in /tmp/php-wrap-FV73QY on line 1
- However when in an actual php file the underlying .cpp code DOES run/return.

- I didn't include it in hphp/hack/hhi/stdlib/builtins_options.hhi, however that doesn't appear to immediately resolve the problem... have to keep looking.

HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-g993305d8d56f3be02580404a9195560a47e8af68
Repo schema: b1984f9d3997a9320392123ad6902c139ce39e09

**Comment by Orvid** [comment] 2016-06-29 17:20
`function_exists('gc_mem_cache')` is going to return false because there is no `s` at the end of the function name.

@jwatzman The nightlies have been building, I think they just haven't been able to tell the monitor that -_-. (http://dl.hhvm.com/ubuntu/pool/main/h/hhvm-nightly/ is showing builds from last night)

**Comment by apeabody** [comment] 2016-06-29 17:27
@Orvid - yup, I discovered that this morning as well.  Looks like I updated my comment at the same time as you posted! :)

I'm going to put together a new test/slow case and submit it in a little while to prevent any future confusion on this topic.  Forgot to add one when we switched it from a no-op to a "real" function part way through.

@donutloop - I'd suggest confirming that you have ONLY the desired/recent nightly hhvm version installed ('which hhvm' might help as well) and remove everything else to prevent something from finding the wrong version by mistake.

**Comment by donutloop** [comment] 2016-06-29 17:30
HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-gb6c077acfd520ef0bed64407d134ed1bcbd1dd9c
Repo schema: cde63aaf1ca99dcbe9174acf40af08707725d957

**Comment by apeabody** [comment] 2016-06-29 18:21
@donutloop - What are you attempting to install with composer?  symfony (should be in your composer.lock and/or .json file)?

I just installed symfony/symfony with composer 1.1.3 using the current HHVM master without any issue ('hhvm --no-config --php composer.phar require symfony/symfony').  I also checked that your nightly (based on the version info above) is from ~5 days ago, and should have gc_mem_caches() which was added about ~9 days ago...

Also - looking for a root cause: https://github.com/symfony/symfony/issues/19050 it appears you might be able to use HHVM 3.14.1 as long as you specfic PHP5 mode so symfony will skip the gc_mem_caches() call.  That is what triggered issue in the first place #7155

**Comment by donutloop** [comment] 2016-06-30 05:47
i have php7 app. i has enabled the hhvm.php7.all=1 option. i use that flag "--no-config (don't use the default php.ini)" because i have some issues with composer.
https://github.com/facebook/hhvm/issues/7171
                           
i tired once more i get the same error

**Comment by apeabody** [comment] 2016-06-30 19:10
I put the long response with detgailed commands in https://github.com/facebook/hhvm/issues/7178, but everything looks good to me with a fresh and pure Debian Jessie using 6/29 hhm-nightly and composer 1.1.3 from the current composer installer - with the obvious exception of your local pieces which can't be tested.  I'd strongly suggest confirming your composer version and upgrading to 1.1.3 if needed.

```
hhvm --php composer.phar --version
Composer version 1.1.3 2016-06-26 15:42:08
```


HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-gf60e4a7fdeca0a304138e62f9d271c4e0c5633cc
Repo schema: 6fb26ff99e10f592b63f81753e13094fe93059fd

**Comment by donutloop** [comment] 2016-06-30 20:11
HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-gf60e4a7fdeca0a304138e62f9d271c4e0c5633cc
Repo schema: 6fb26ff99e10f592b63f81753e13094fe93059fd

hhvm --no-config --php composer.phar --version
Composer version 1.1.3 2016-06-26 15:42:08

hhvm  --php composer.phar --version
Fatal error: Uncaught TypeError: Argument 1 passed to unserialize() must be an instance of string, null given in /var/www/webapplication/composer.phar:23
Stack trace:
#0 (): unserialize()
#1 (): __SystemLib\PharArchiveHandler->parsePhar()
#2 (): __SystemLib\PharArchiveHandler->__construct()
#3 (): Phar->__construct()
#4 /var/www/webapplication/composer.phar(23): Phar::mapPhar()
#5 {main}

**Comment by apeabody** [comment] 2016-06-30 20:20
Interesting  **Can you post your /etc/hhvm/php.ini?**

This is in Debian Jessie - although pure.  After checking _/etc/hhvm/php.ini_, the next step would be to see if something is unexpected about the docker container.
```
vagrant@debian-jessie:~$ hhvm --version
HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-gf60e4a7fdeca0a304138e62f9d271c4e0c5633cc
Repo schema: 6fb26ff99e10f592b63f81753e13094fe93059fd
vagrant@debian-jessie:~$ hhvm --no-config --php composer.phar --version
Composer version 1.1.3 2016-06-26 15:42:08
vagrant@debian-jessie:~$ hhvm --php composer.phar --version
Composer version 1.1.3 2016-06-26 15:42:08
```

more /etc/hhvm/php.ini
```
; php options
session.save_handler = files
session.save_path = /var/lib/hhvm/sessions
session.gc_maxlifetime = 1440

; hhvm specific
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
```

**Comment by donutloop** [comment] 2016-06-30 20:21
`; HHVM

hhvm.error_handling.call_user_handler_on_fatals = 1

hhvm.server.implicit_flush = 1

hhvm.log.always_log_unhandled_exceptions = 1

hhvm.log.natives_stack_trace = 1

hhvm.mail.sendmail_path = /usr/sbin/sendmail -t -i

hhvm.libxml.ext_entity_whitelist = file,http

;hhvm.php7.scalar_types = 1
hhvm.php7.all = 1

;Extensions
extension_dir = /etc/hhvm/extensions
hhvm.extensions[pgsql] = pgsql.so

; PHP

display_errors = On

log_errors = On

display_startup_errors = On

error_reporting = E_ALL

memory_limit = 512M

upload_max_filesize = 100M

post_max_size = 100M

realpath_cache_size = 512K

register_long_arrays = Off

output_buffering = 4096

date.timezone = Australia/Melbourne
`

**Comment by Orvid** [comment] 2016-06-30 20:55
@apeabody The phar issue is related to php7 mode being enabled. See #7178 for more info.

**Comment by apeabody** [comment] 2016-06-30 21:21
@Orvid Correct - I'd forgotten he was using php7 mode till posting the php.ini above.  That said I'm glad to see at least the composer / composer installer #7171  and gc_mem_caches() stuff is resolved.  I see you closed #7171, I'd suggest closing this one as well as #7178 is correctly titled for the remaining issue.

@donutloop Adding this in php.ini should temporarily work around the issue - assuming of course you don't need PHP7 scalar types:
`hhvm.php7.scalar_types = 0`

**Comment by donutloop** [comment] 2016-07-01 06:59
I want prevent the loading of my default config. The summary and name of the parameter --no-config is misleading. that i can use for my application the php7 features and Composer without php7 feature execute.

Paramter:
hhvm --no--config 
Summary
don't use the default php.ini

**Comment by apeabody** [comment] 2016-07-01 18:03
From what I understand, I doubt that composer will work with HHVM's php7.scalar_types anytime soon due to it's strict type checking #7198.  Assuming you want to keep php7.all enabled, including php7.scalar_types, in your php.ini; my suggestion would be to selectively disable php7.scalar_types when running composer from the command line (this will still use the rest of your php.ini settings):
`hhvm -d hhvm.php7.scalar_types=0 composer.phar`

Alternatively if it's compatible with your application, you might try this in your /etc/hhvm/php.ini
```
hhvm.php7.all = 1
hhvm.php7.scalar_types = 0
```

My guess is one of those two are going to be the best/only options currently for running composer other than running HHVM in PHP5 mode.

**Comment by donutloop** [comment] 2016-07-02 18:06
Isn't working.

i tired 
'hhvm -d hhvm.php7.scalar_types=0 --php composer.phar install'
and 
'hhvm -d hhvm.php7.all=0 --php composer.phar install'

'Fatal error: Uncaught Error: Call to undefined function Symfony\Component\ClassLoader\gc_mem_caches() in /var/www/webapplication/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:198
Stack trace:
#0 /var/www/webapplication/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(109): Symfony\Component\ClassLoader\ClassCollectionLoader::fixNamespaceDeclarations()
#1 /var/www/webapplication/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php(282): Symfony\Component\ClassLoader\ClassCollectionLoader::load()
#2 /var/www/webapplication/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php(59): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::doBuildBootstrap()
#3 {main}'

**Comment by apeabody** [comment] 2016-07-05 16:49
gc_mem_caches() is currently only in hhvm-nightly, it looks like you are now running hhvm-3.14.2

**Comment by donutloop** [comment] 2016-07-20 18:01
HipHop VM 3.14.3 (rel)
Compiler: tags/HHVM-3.14.3-0-gd5933de2633e59a27e37d3da5f48e056706272b2
Repo schema: 26aba134a6aac9ebb47544f8d0f2c2a8e9c07c82

Isn't working.

i tired 
`hhvm -d hhvm.php7.scalar_types=0 --php composer.phar install`
and 
`hhvm -d hhvm.php7.all=0 --php composer.phar install`
and 
'hhvm --no-config  --php composer.phar install'

Always the same issue

`Fatal error: Uncaught Error: Call to undefined function Symfony\Component\ClassLoader\gc_mem_caches() in /var/www/webapplication/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:198
Stack trace:
#0 /var/www/webapplication/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(109): Symfony\Component\ClassLoader\ClassCollectionLoader::fixNamespaceDeclarations()
#1 /var/www/webapplication/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php(282): Symfony\Component\ClassLoader\ClassCollectionLoader::load()
#2 /var/www/webapplication/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php(59): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::doBuildBootstrap()
#3 {main}
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-install-cmd event terminated with an exception

                                                         
  [RuntimeException]                                     
  An error occurred when generating the bootstrap file.`

**Comment by apeabody** [comment] 2016-07-20 22:23
@donutloop it appears that you are now running HHVM 3.14.3 which does not contain gc_mem_caches(), and I would extremely highly doubt any future 3.14.x release.  

Currently gc_mem_caches() is currently only present in hhvm-nightly.  If you don't want to use the nighlies, and are waiting for a release version, *my* guess is it will probably make the cut for HHVM 3.15 - https://docs.hhvm.com/hhvm/installation/release-schedule.

**Comment by Orvid** [comment] 2016-07-21 00:08
`gc_mem_caches()` will be in 3.15.0, we don't currently plan on back-porting it.

**Closed by Orvid** 2016-07-21 00:08 UTC
