### ISSUE TITLE
Speed last version of HHVM vs php7.1

### ISSUE THREAD

**Issue by questionpython** [facebook/hhvm#7723] opened 2017-03-08 17:17 UTC
Hello,
People and a lot of sites , say that PHP 7.1 is Faster than current HHVM.

Is this true?

**Comment by orlangur** [comment] 2017-03-08 17:56
First of all, PHP 7.1 does not seem to be really faster than PHP 7.0 :)

Some quickly googled links:
https://www.phoronix.com/scan.php?page=news_item&px=PTS-PHP-7.1-Benchmarks
https://www.symfony.fi/entry/php-7-1-vs-7-0-benchmarks-symfony

I have never met evidences to "HHVM is WAY faster than PHP 7.0" or "PHP 7.1 is MUCH faster than PHP 7.0". Maybe for some specific scenarios, like when absence of garbage collector by design does matter.

> Is this true?

It's better to do your own benchmarks with your own software and infrastructure to make an informed decision.

**Comment by mofarrell** [comment] 2017-03-08 18:27
These are our last officially published performance numbers.  http://hhvm.com/blog/9293/lockdown-results-and-hhvm-performance
This was almost two years ago, so hopefully we can publish some new numbers soon.

**Comment by mofarrell** [comment] 2017-03-08 18:27
Since this is not an issue with HHVM I am going to close the issue.

**Closed by mofarrell** 2017-03-08 18:27 UTC

**Comment by questionpython** [comment] 2017-03-08 21:30
https://www.phoronix.com/scan.php?page=news_item&px=PTS-PHP-7.1-Benchmarks
oh, sorry, so speed of PHP7.1 is better of HHVM?

**Comment by Orvid** [comment] 2017-03-08 21:55
For a short-running CLI mode script, it's possible that PHP 7 will be faster, but for an actual server, no, HHVM still beats PHP 7 in server mode performance on the frameworks we've tested.

For scripts we have a cli-server system that landed recently (not in any current release) that should significantly improve startup time and may even improve performance for scripts by being able to re-use the same JIT'd code across invocations of the script.

We're working on a blog post with a more complete picture, but based on some of our recent testing, HHVM 3.18 is about 1.8x faster than PHP 7 when running MediaWiki in repo-mode and 1.3x faster than PHP 7 when running without repo-mode.

**Comment by craigcarnell** [comment] 2017-03-09 09:11
@mofarrell Hi, Would love to see a more upto date comparison

**Comment by orlangur** [comment] 2017-03-09 09:46
@mofarrell huge thanks,

> We demonstrated that HHVM is 55.5% faster than PHP 7 on a MediaWiki workload, 18.7% faster on a Wordpress workload, and 10.2% faster on a Drupal 7 workload. 

is exactly what I was referring with "I have never met evidences". Now I have some and HHVM is definitely worth trying with complex applications like Magento 2.

**Comment by nkbrs** [comment] 2017-06-01 14:21
@Orvid  how come you, like many others, didn't post any **evidence**? I'm not talking about percentages, but about how you tested, the setup, the software, the hardware, session handlers, web server setup etc.? 

If anything, our tests have shown that HHVM is unstable.

**Comment by mofarrell** [comment] 2017-06-01 16:03
@nkbrs We have a whole suite dedicated to testing performance https://github.com/hhvm/oss-performance.  http://hhvm.com/blog/9293/lockdown-results-and-hhvm-performance talks about the methodology used to test performance.  The numbers are even still roughly accurate in that post (HHVM has improved a decent amount since then)

**Comment by lilianmoraru** [comment] 2017-06-18 16:06
There still seem to appear misleading benchmarks on the web...
People do not take into consideration that HHVM optimizes the code over time(a server does not run a few seconds and then stop).

While trying to set a Phabricator server today, I've read on HHVM, PHP and Zend, and found this news on the Zend website: https://framework.zend.com/blog/2017-06-06-zf-php-7-1.html .
They seem to drop any support for HHVM because the benchmarks show that the performance difference is small.
