### ISSUE TITLE
htmlentities with bad encoding halts the script instead of emitting a warning

### ISSUE THREAD

**Issue by gggeek** [facebook/hhvm#5177] opened 2015-04-14 23:25 UTC
ex: $x = hmtlentities('a', 'US-ASCII');

is a fatal error in hhvm but not in php

**Comment by paulbiss** [comment] 2015-04-14 23:33
Works fine for me (http://3v4l.org/b7Lf1). Looks like you spelled the function name wrong, which would certainly cause a fatal (http://3v4l.org/WfgjQ).

**Comment by gggeek** [comment] 2015-04-15 08:59
Sorry, my example was a bit contrived.
The correct example is $x = htmlentities('a', ENT_COMPAT,'US-ASCII');
And http://3v4l.org/WbP8S confirms

**Comment by SiebelsTim** [comment] 2015-04-15 14:28
And there's a very descriptive error message saying, that it isn't implemented yet.

**Comment by gggeek** [comment] 2015-04-15 14:37
Well, yes.

But in php, the warning has the same effect (i.e. tell the user 'not implemented') and the script does not die, but carries on doing different stuff.
So the results are different between php and hhvm. Isn't this how you define hhvm bugs?

You can obtain a similar case by inserting random junk instead of 'US-ASCII' as charset name: http://3v4l.org/PVrgn

**Comment by karpa13a** [comment] 2015-04-15 14:39
dupe #943 ?

**Comment by gggeek** [comment] 2015-04-15 14:48
@karpa13a I'd not call it an exact dupe, but a close sibling.
Of course, beauty is in the eye of the beholder :-)

- with cp1251, php does not complain at all, meaning it should implement that charset. While hhvm says it does not support it => the fix should be to implement support for it
- with other, unsupported charsets, the difference is that php gives a warning and hhvm a fatal => the fix should be to give a warning without exiting

**Comment by SiebelsTim** [comment] 2015-04-15 15:53
Oh, sorry! I didn't see that in the first place.

I can imagine that this is by design, but what do I know :P

**Comment by paulbiss** [comment] 2015-04-15 18:28
Hmm, I'm not sure how safe fixing this would be, but I'll reopen.

**Comment by Orvid** [comment] 2016-09-30 21:16
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Closed by Orvid** 2016-09-30 21:16 UTC
