### ISSUE TITLE
HHVM 3.13.0 - Crash

### ISSUE THREAD

**Issue by karek314** [facebook/hhvm#6960] opened 2016-04-02 19:28 UTC
Im experiencing random crash after upgrade to 3.13.0. After downgrade to 3.12.x hhvm works as expected.

If it's important - hhvm error.log was always empty after upgrade. Normally there is couple warnings / errors - nothing important, usually sql slow queries.

server.ini
```
pid = /var/run/hhvm/pid

; hhvm specific

hhvm.server.ip = 127.0.0.1
hhvm.server.port = 9000
;hhvm.server.file_socket=/var/run/hhvm/hhvm.sock

hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.header = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc

hhvm.jit_a_size = 536870912
hhvm.jit_a_cold_size = 268435456
hhvm.jit_a_frozen_size = 536870912
hhvm.jit_a_prof_size = 536870912
hhvm.jit_a_max_usage = 536870912
hhvm.jit_global_data_size=62914560
```

php.ini
```
; php options
session.save_handler = files
session.save_path = /var/lib/php5
session.gc_maxlifetime = 1440
;error_reporting = E_ERROR | E_WARNING | E_PARSE

; hhvm specific
hhvm.log.level = Error
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
hhvm.mysql.socket = /var/run/mysqld/mysqld.sock
hhvm.pdo_mysql.socket = /var/run/mysqld/mysqld.sock
hhvm.mysqli.socket = /var/run/mysqld/mysqld.sock
```

**Comment by simonwelsh** [comment] 2016-04-02 21:49
Likely a dupe of #6950 or #6941

**Comment by shimondoodkin** [comment] 2016-04-03 07:59
+1

**Comment by LZL0** [comment] 2016-04-03 23:01
Same here.
If somebody needs, like the 3.12.1 version just download it from here
http://dl.hhvm.com/ubuntu/pool/main/h/hhvm/
upload it to example /var

and run the command sudo dpkg -i /var/hhvm_3.12.1-trusty_amd64.deb

**Comment by shimondoodkin** [comment] 2016-04-04 06:50
more packages like hhvm-dev here:
http://dl.hhvm.com/ubuntu/pool/main/h/

**Comment by fredemmott** [comment] 2016-04-04 20:14
@LZL0: https://docs.hhvm.com/hhvm/installation/linux#obtaining-lts-releases + `sudo apt-get install hhvm=3.12.1~trusty` is a better way to do that

**Comment by tuannda** [comment] 2016-04-06 05:46
```
sudo apt-get remove hhvm
sudo apt-get autoremove
nano /etc/apt/sources.list
```
Find:
```
deb http://dl.hhvm.com/ubuntu trusty main
```
Or wily (lsb_release -a : find version Ubuntu)
Modify example
```
deb http://dl.hhvm.com/ubuntu trusty-lts-3.12 main
```

or 
```
deb http://dl.hhvm.com/ubuntu wily-lts-3.12 main
```

Then run

```
sudo apt-get update
sudo apt-get install hhvm
```

**Comment by Orvid** [comment] 2016-04-06 18:41
Closing as a duplicate of #6950.

**Closed by Orvid** 2016-04-06 18:41 UTC
Labels: crash, duplicate
