### ISSUE TITLE
Hack's build info generation differs from the rest of hphp's (and depends on git/hg)

### ISSUE THREAD

**Issue by paravoid** [facebook/hhvm#6708] opened 2015-12-28 18:16 UTC
hphp ships with `hphp/util/generate-buildinfo.sh` which generates `kCompilerId` under `$BUILD_DIR/hphp-build-info.cpp`. It's elaborate and has quite a few fallbacks (user-supplied `$COMPILER_ID` -> git -> hg -> date).

The Hack code on the other hand has this under `hphp/hack/src/Makefile`:
```
build-hack-stubs:
        REV="const char* const BuildInfo_kRevision = \"$$(git rev-parse HEAD || hg id -i)\";"; \
        if [ "$$REV" != "$$(cat utils/get_build_id.gen.c 2>/dev/null)" ]; then echo "$$REV" > utils/get_build_id.gen.c; fi
```

This has a few problems, including the fact that a user-supplied COMPILER_ID won't work, and the fact that this adds an implicit dependency on git or hg.

I'd like some guidance on how to move forward, especially given that there are a few things happening in both that are Facebook buildsystem-specific (`hphp/util/generate-buildinfo.sh` hints to that, and Hack's `hphp/hack/src/utils/get_build_id.c` has a comment mentioning a Facebook build system constant).

Does the hphp/hack code live outside of HHVM inside Facebook? Why can't we add code to `hphp/util/generate-buildinfo.sh` to output the `kRevision` stanza to `hphp/hack/utils/get_build_id.gen.c` as well, for example?

**Comment by fredemmott** [comment] 2015-12-28 18:50
Related: https://reviews.facebook.net/D52341

**Comment by fredemmott** [comment] 2015-12-28 18:53
IMO `#ifndef FACEBOOK` we should just copy the HHVM version , eg 3.11.0 or 3.12-dev

**Comment by paravoid** [comment] 2015-12-28 18:56
That sounds fine to me. Basically my goals for both this and #6707 (aka D52341) are:
- No hard dependence on git/hg
- Build reproducibly, i.e. no variance on timestamps, build environment, etc.

**Comment by int3** [comment] 2015-12-29 02:45
> IMO #ifndef FACEBOOK we should just copy the HHVM version , eg 3.11.0 or 3.12-dev

Sounds like a reasonable solution to me.

The build info is still going to be used internally, but I can move those functions out of the OSS build once the abovementioned #ifdef is done.

**Comment by paravoid** [comment] 2015-12-29 14:34
I obviously wouldn't mind that (although I have no idea how to do the #ifdef in OCaml, so I could use the help :)), but if you don't mind me asking, what do you use the build-time for internally?

How is the build-date (assuming you don't use something like [SOURCE_DATE_EPOCH](https://reproducible-builds.org/specs/source-date-epoch/)) useful? Won't the build date change arbitrarily during rebuilds for non-API/ABI breaking reasons? Also, the rest of HHVM doesn't do that, is there an OCaml-specific reason for this? (e.g. the OCaml compiler breaking their ABI often or something?)

**Comment by Orvid** [comment] 2016-02-19 21:14
@int3 Any update on your side of this?

**Comment by int3** [comment] 2016-03-08 20:42
@paravoid: We don't have SOURCE_DATE_EPOCH available, so this is the next best thing. The rest of HHVM doesn't do this because our development process is somewhat loosely coupled :) I don't think it has anything to do with OCaml in particular.

Also, I meant that we could use an #ifdef in C, which can be accessed via the OCaml FFI (like the current build is using). Unfortunately I'm not super familiar with the HHVM versioning code so I'd have to spend some time looking into it, and there are other higher-priority things I'm tackling at the moment... It's something I'd like to do at some point though

**Comment by int3** [comment] 2016-03-16 21:29
81168609 uses the equivalent of SOURCE_DATE_EPOCH, addressing the reproducibility issue. If git/hg isn't available it just sets that date to zero (i.e. the start of epoch time). It still differs from HHVM's versioning though. I'm closing this for now but if you would like to figure out how to get it to match HHVM feel free to reopen and claim the task.

**Closed by int3** 2016-03-16 21:29 UTC
Labels: hack
