### ISSUE TITLE
How to load dynamic extensions in command line mode?

### ISSUE THREAD

**Issue by ahmadazimi** [facebook/hhvm#7648] opened 2017-02-06 07:08 UTC
> HipHop VM 3.17.1 (rel)
Compiler: tags/HHVM-3.17.1-0-gdb3429c2130e5f7539bfd550c27a6bea9444b669
Repo schema: 68c9b831b56bea5d8c90f6fca5ea358cdaaea626

I've built it from the source, also I've built mongodb extension from the source!
Mongodb extension correctly loaded in server mode and  I can see its loaded from /etc/hhvm/mongodb.so in phpinfo output.

But when I'm trying to do something from command line that needs for example mongodb extension, I get some errors that tell me there is no mongodb extension installed!

**How should I use hhvm from the command line to load dynamic extensions?**

for example: `composer require mongodb/mongodb`

BTW:
This is my alias for composer:
`alias composer="hhvm -v ResourceLimit.SocketDefaultTimeout=30 -v Http.SlowQueryThreshold=30000 -v Eval.Jit=false /usr/local/bin/composer"`

**Comment by ahmadazimi** [comment] 2017-02-06 08:32
I've changed the alias for composer and php in the following way and the problem fixed:

```
alias composer="hhvm -d hhvm.dynamic_extensions[mongodb]=/etc/hhvm/mongodb.so -v ResourceLimit.SocketDefaultTimeout=30 -v Http.SlowQueryThreshold=30000 -v Eval.Jit=false /usr/local/bin/composer"
alias php="hhvm -d hhvm.dynamic_extensions[mongodb]=/etc/hhvm/mongodb.so"
```

Is this a good way?

**Comment by DerPapst** [comment] 2017-02-06 11:05
You can put the ini setting in /etc/hhvm/php.ini
This way the extension should be loaded even in cli mode.

**Comment by ahmadazimi** [comment] 2017-02-06 12:37
@DerPapst I've put them into `/etc/hhvm/server.ini`, so you mean I should rename it to php.ini? Or I should have both of them?

**Comment by DerPapst** [comment] 2017-02-06 12:50
I have both files. In php.ini I have all php and runtime related settings and in server.ini I have everything related to hhvm.server.* hhvm.log.* and hhvm.repo.*.

**Comment by mofarrell** [comment] 2017-02-10 22:38
I am closing this issue as it is not a bug with HHVM.

**Closed by mofarrell** 2017-02-10 22:38 UTC
