### ISSUE TITLE
Compatibility issue with phpBB3.1

### ISSUE THREAD

**Issue by JusticeRage** [facebook/hhvm#6245] opened 2015-09-14 16:15 UTC
Hello,

While preparing a migration to HHVM, I have noticed a problem where some template variables were not correctly expanded.

[Here](https://test.kwiatkowski.fr/phpBB3/viewtopic.php?f=2&p=1#p1) is a stock installation of the latest release of phpBB 3.1 I created to reproduce this bug. I'm running [HHVM 3.9.1](https://test.kwiatkowski.fr/test.php) on Debian 7.

As you can see, the quote box and the code box contains "WroteColon" instead of the proper word translation and column sign. The relevant template excerpt is located in `styles/prosilver/template/bbcode.html`

```
<!-- BEGIN code_open --><div class="codebox"><p>{L_CODE}{L_COLON} <a href="#" onclick="selectCode(this); return false;">{L_SELECT_ALL_CODE}</a></p><code><!-- END code_open -->
```

The template variables seem to be defined in localization files, i.e. `language/en/common.php`, but for some reason, the ones from the quoted line don't seem to be taken into account.
When the forum runs on a standard php5-fpm configuration, everything seems to work fine, so I think the problem may come from HHVM.

Let me know if you need any additional information.

**Comment by fredemmott** [comment] 2015-09-14 16:57
Given how many issues there are that don't require installing an application and isolating a failure, it's unlikely that we'll look at this. If you could reduce the problem to a small PHP file with no dependencies, it's much more likely that this will be fixed soon.

**Comment by miras72** [comment] 2016-02-06 10:50
Hello,
I have the same issue. 
How can I debug HHVM to find where the problem is?

**Comment by stathis** [comment] 2016-02-15 15:42
Hello, the issue has to do with the scoping of the original preg_replace with the now deprecated "/e" modifier. HHVM essentially emulates preg_replace_callback(), leaving the $user (and effectively $user->lang[]) out of context.

To fix this temporarily, open `includes/bbcode.php` and replace or comment out:
```
$bbcode_tpl = preg_replace('/{L_([A-Z0-9_]+)}/e', "(!empty(\$user->lang['\$1'])) ? \$user->lang['\$1'] : ucwords(strtolower(str_replace('_', ' ', '\$1')))", $bbcode_tpl);
```
with
```
$bbcode_tpl = preg_replace_callback('/{L_([A-Z0-9_]+)}/', function($m)
{
	global $user;
	return (!empty($user->lang[ $m[1] ])) ? $user->lang[ $m[1] ] : ucwords(strtolower(str_replace('_', ' ',  $m[1] )));
}, $bbcode_tpl);
```

AND
```
$tpl = preg_replace('/{L_([A-Z0-9_]+)}/e', "(!empty(\$user->lang['\$1'])) ? \$user->lang['\$1'] : ucwords(strtolower(str_replace('_', ' ', '\$1')))", $tpl);
```
with
```
$tpl = preg_replace_callback('/{L_([A-Z0-9_]+)}/', function($m)
{
	global $user;
	return (!empty($user->lang[ $m[1] ])) ? $user->lang[ $m[1] ] : ucwords(strtolower(str_replace('_', ' ',  $m[1] )));
}, $tpl);
```

**Note:** In phpBB 3.2, all preg_replace() calls with the /e modifier are supposed to be replaced with preg_replace_callback to make phpBB compatible with PHP7, so I guess this will be fixed as well.

Let me know if there are any issues with my fix.

Regards,
stathis

**Comment by miras72** [comment] 2016-02-16 09:12
It is working:-)
Sometimes HHVM crash with phpBB. Is it possible above issue causes it?

**Comment by Orvid** [comment] 2016-09-28 22:54
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-28 22:54 UTC
Labels: no isolated repro
