### ISSUE TITLE
hhvm crash when broadcasting post on multisite with threewp broadcast

### ISSUE THREAD

**Issue by frenchmedia** [facebook/hhvm#5533] opened 2015-06-25 04:27 UTC
Hi
I use this plugin with no issue under PHP
when i move to HHVM it crash HHVM

I've found this in the PHP logs:

2015/06/25 04:00:00 [alert] 26232#0: *2140966 stalled cache updating, error:0 while closing request, client: 141.101.99.145, server: 0.0.0.0:80
2015/06/25 04:01:58 [error] 26233#0: *2140848 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 108.162.212.239, server: *.myfrenchcity.com, request: "POST /wp-admin/post.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "myfrenchcity.com", referrer: "http://myfrenchcity.com/wp-admin/post.php?post=24771&action=edit"
2015/06/25 04:01:58 [crit] 26233#0: *2140848 connect() to unix:/var/run/php5-fpm-.sock failed (2: No such file or directory) while connecting to upstream, client: 108.162.212.239, server: *.myfrenchcity.com, request: "POST /wp-admin/post.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-.sock:", host: "myfrenchcity.com", referrer: "http://myfrenchcity.com/wp-admin/post.php?post=24771&action=edit"

Something killed HHVM for a few minutes. Maybe HHVM can't handle that type of requests. HHVM log is empty.

https://plainviewplugins.com/wp-content/cache/page_enhanced/plainviewplugins.com//threewp-broadcast-premium-pack//_index.html_gzip

[Thu Jun 25 02:55:24 2015] [hphp] [26375:7fec79d007c0:0:000001] [] mapping self...
[Thu Jun 25 02:55:24 2015] [hphp] [26375:7fec79d007c0:0:000002] [] mapping self took 0'00" (176780 us) wall time
[Thu Jun 25 02:55:24 2015] [hphp] [26375:7fec79d007c0:0:000003] [] loading static content...
[Thu Jun 25 02:55:24 2015] [hphp] [26375:7fec79d007c0:0:000004] [] loading static content took 0'00" (1 us) wall time
[Thu Jun 25 02:55:24 2015] [hphp] [26375:7fec79d007c0:0:000005] [] page server started
[Thu Jun 25 02:55:24 2015] [hphp] [26375:7fec79d007c0:0:000006] [] all servers started
[Thu Jun 25 02:56:27 2015] [hphp] [26375:7fec55fff700:6:000001] [] Finished singleJitRequest 1
[Thu Jun 25 02:56:51 2015] [hphp] [26375:7fec60bff700:17:000001] [] Finished singleJitRequest 2
[Thu Jun 25 02:57:05 2015] [hphp] [26375:7fec507ff700:31:000001] [] Finished singleJitRequest 3
[Thu Jun 25 02:57:11 2015] [hphp] [26375:7fec55fff700:23:000001] [] Finished singleJitRequest 4
[Thu Jun 25 02:57:11 2015] [hphp] [26375:7fec60bff700:19:000001] [] Finished singleJitRequest 5
[Thu Jun 25 04:02:35 2015] [hphp] [26375:7fec507ff700:772:000001] [] Erreur de la base de donn\xc3\xa9es WordPress Table 'myfrenchcity.mfc_wp_8_options' doesn't exist pour la requ\xc3\xaate SELECT option_value FROM mfc_wp_8_options WHERE option_name = 'mfc_wp_8_user_roles' LIMIT 1 faite par WP_List_Table->display, WP_List_Table->display_rows_or_placeholder, WP_Posts_List_Table->display_rows, WP_Posts_List_Table->_display_rows, WP_Posts_List_Table->single_row, do_action('manage_posts_custom_column'), threewp_broadcast\\ThreeWP_Broadcast->manage_posts_custom_column, threewp_broadcast\\actions\\action->execute, do_action('threewp_broadcast_manage_posts_custom_column'), threewp_broadcast\\ThreeWP_Broadcast->threewp_broadcast_manage_posts_custom_column, switch_to_blog, WP_Roles->reinit, get_option
[Thu Jun 25 04:02:35 2015] [hphp] [26375:7fec507ff700:772:000002] [] Erreur de la base de donn\xc3\xa9es WordPress Table 'myfrenchcity.mfc_wp_8_options' doesn't exist pour la requ\xc3\xaate SELECT option_value FROM mfc_wp_8_options WHERE option_name = 'blogname' LIMIT 1 faite par WP_List_Table->display, WP_List_Table->display_rows_or_placeholder, WP_Posts_List_Table->display_rows, WP_Posts_List_Table->_display_rows, WP_Posts_List_Table->single_row, do_action('manage_posts_custom_column'), threewp_broadcast\\ThreeWP_Broadcast->manage_posts_custom_column, threewp_broadcast\\actions\\action->execute, do_action('threewp_broadcast_manage_posts_custom_column'), threewp_broadcast\\ThreeWP_Broadcast->threewp_broadcast_manage_posts_custom_column, get_bloginfo, get_option
[Thu Jun 25 04:03:22 2015] [hphp] [26375:7fec55fff700:748:000001] [] Erreur de la base de donn\xc3\xa9es WordPress Table 'myfrenchcity.mfc_wp_8_options' doesn't exist pour la requ\xc3\xaate SELECT option_value FROM mfc_wp_8_options WHERE option_name = 'mfc_wp_8_user_roles' LIMIT 1 faite par WP_List_Table->display, WP_List_Table->display_rows_or_placeholder, WP_Posts_List_Table->display_rows, WP_Posts_List_Table->_display_rows, WP_Posts_List_Table->single_row, do_action('manage_posts_custom_column'), threewp_broadcast\\ThreeWP_Broadcast->manage_posts_custom_column, threewp_broadcast\\actions\\action->execute, do_action('threewp_broadcast_manage_posts_custom_column'), threewp_broadcast\\ThreeWP_Broadcast->threewp_broadcast_manage_posts_custom_column, switch_to_blog, WP_Roles->reinit, get_option
[Thu Jun 25 04:03:22 2015] [hphp] [26375:7fec55fff700:748:000002] [] Erreur de la base de donn\xc3\xa9es WordPress Table 'myfrenchcity.mfc_wp_8_options' doesn't exist pour la requ\xc3\xaate SELECT option_value FROM mfc_wp_8_options WHERE option_name = 'blogname' LIMIT 1 faite par WP_List_Table->display, WP_List_Table->display_rows_or_placeholder, WP_Posts_List_Table->display_rows, WP_Posts_List_Table->_display_rows, WP_Posts_List_Table->single_row, do_action('manage_posts_custom_column'), threewp_broadcast\\ThreeWP_Broadcast->manage_posts_custom_column, threewp_broadcast\\actions\\action->execute, do_action('threewp_broadcast_manage_posts_custom_column'), threewp_broadcast\\ThreeWP_Broadcast->threewp_broadcast_manage_posts_custom_column, get_bloginfo, get_option

**Comment by Orvid** [comment] 2016-09-30 19:51
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:51 UTC
