### ISSUE TITLE
HHVM + WordPress Multi-site + Apache = 404s and CSS-less Dashboards

### ISSUE THREAD

**Issue by TheBigK** [facebook/hhvm#6695] opened 2015-12-23 20:51 UTC
I'm opting for a sub-directory setup with WP running the the web-root. The problem is I can successfully create a multi-site network; but when I create a new site (other than the default), it's dashboard is rendered without any CSS. In addition, specific pages like 'Manage Comments' or 'Users' throw a 404 'Page Not Found' error.

For example https://domain.io/official/wp-admin/ -> dashboard without CSS.
https://domain.io/official/wp-admin/themes.php -> 404, page not found

Disabling HHVM gets everything working. 

Would really appreciate any pointers  to fix this. Has been troubling me for last 1.5 days!

**Comment by fredemmott** [comment] 2015-12-23 20:56
- what version of HHVM?
 - can you reproduce the problem with HHVM's built in HTTP server?
 - what are your HHVM and Apache configs?

**Comment by TheBigK** [comment] 2015-12-23 21:20
Sorry, I should have provided that information in my first post itself. 

1. Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c

2. Not sure how can I use it. Would appreciate any pointers. 

3. <IfModule mod_proxy_fcgi.c>
ProxyPassMatch ^/(.+\.php(/.*)?)$ fcgi://127.0.0.1:9000/home/user1/public_html/\$1
</IfModule>

Note: Commenting proxypassmatch doesn't work. 

and any specific information from apache that'd help troubleshoot?

**Comment by fredemmott** [comment] 2015-12-23 21:37
- The entire HHVM configuration (from /etc/hhvm/) would be useful
 - Do you have any rewrite rules saying that /wp-admin/ should actually be executed by a php file, eg Index.php ?

**Comment by TheBigK** [comment] 2015-12-24 03:25
I really appreciate all the help, @fredemmott . Here's the config file -

pid = /var/run/hhvm-thebigk/pid
hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.server.fix_path_info = true
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/thebigk-error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc

and I'm using the standard .htaccess rules specified by WordPress after enabling Network (multisite) -

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
RewriteRule . index.php [L]
</IfModule>

# END WordPresss

**Comment by TheBigK** [comment] 2015-12-25 09:26
Update: My web host admins have been trying hard to get apache+HHVM to work with subdirectory multi-site; but have now given up. They could get the 'subdomain' multisite to work; but not the subdirectory. 

Can someone verify this? I'm willing to give it one more try before giving up.

**Comment by aorenste** [comment] 2016-09-27 22:52
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by aorenste** 2016-09-27 22:52 UTC
Labels: needs more info, no isolated repro
