### ISSUE TITLE
Catchable fatal error: Argument passed to mysqli_fetch_object() must be an instance of mysqli_result

### ISSUE THREAD

**Issue by kacy-** [facebook/hhvm#5065] opened 2015-03-23 16:41 UTC
Receiving this Fatal Error in HHVM from a WordPress 4.0.1 lib. 

However, it's not fatal in PHP 5.6.

HipHop VM 3.6.0 (rel)
Compiler: tags/HHVM-3.6.0-0-g6ef13f20da20993dc8bab9eb103f73568618d3e8
Repo schema: 3ab6576af394a33abbb29796c652f06b1c7640ce

`\nCatchable fatal error: Argument 1 passed to mysqli_fetch_object() must be an instance of mysqli_result, bool given in /home/***/public_html/wp-includes/wp-db.php on line 1619`

```php
if ( $this->use_mysqli ) {

  while ( $row = @mysqli_fetch_object( $this->result ) ) { //<-- Fails here

    $this->last_result[$num_rows] = $row;
      $num_rows++;
    }
  } else {
    while ( $row = @mysql_fetch_object( $this->result ) ) {
      $this->last_result[$num_rows] = $row;
      $num_rows++;
    }
```

I corrected the issue by testing the type of `$this->result` in the condition.

Thank you.

**Comment by Dantali0n** [comment] 2015-03-24 07:28
I see another issue with 3.6.0 both use the @ argument in front of the function that returns the fatal error. could that be related?

**Comment by kacy-** [comment] 2015-03-24 17:25
Could be indirectly related, definitely. It works in many cases but perhaps something about the error suppression in specific contexts is at play.

The other issue I posted for reference is https://github.com/facebook/hhvm/issues/5067

**Comment by Orvid** [comment] 2016-09-30 21:27
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:27 UTC
