### ISSUE TITLE
The $_Server variable not working.

### ISSUE THREAD

**Issue by JSummerhill** [facebook/hhvm#5604] opened 2015-07-07 18:57 UTC
Hello,

So when I called the php/hack environment variable " $_SERVER['DOCUMENT_ROOT'].' " plus my hack file, hhvm says it cannot find my file.  So then I did a var_dump($_SERVER['DOCUMENT_ROOT']) and I got the return: string(0) "".  So after doing a tcpdump to check the connect between fastcgi and my nginx server, I could see that it was correctly passing "/var/www/html/".  So I am getting this is an hhvm issue.  I have no idea why $_SERVER['DOCUMENT_ROOT'] is returning string(0) "".  This is very weird.

**Comment by Orvid** [comment] 2016-09-30 19:39
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:39 UTC
Labels: fastcgi
