### ISSUE TITLE
hhvm.debug.server_error_message = true does not show file and line where error appear

### ISSUE THREAD

**Issue by Profforgr** [facebook/hhvm#5515] opened 2015-06-20 06:55 UTC
As title says, in case of fatal error message, output stream does not contain file and line information where error appear. It just says, for example 
```php
syntax error, unexpected T_STRING
```
which is basically hard to use to fix issue.

Would be cool if hhvm will have variable to allow show of file and line in the debug output stream. For example hhvm.debug.server_error_message_verbose. If true - show file and line information in the debug stream.
This is just how plain PHP do.
```php
Parse error:  syntax error, unexpected 'hello' (T_STRING) in /tmp/script.php on line 1
```

**Comment by jwatzman** [comment] 2015-06-20 15:42
Can you elaborate? Pretty sure we do include line information and generally have error messages that are close to PHP5's. For example, http://3v4l.org/piYKh

Can you give a code example where we are significantly different? Are you sure this isn't some error handler swallowing the information?

**Comment by Profforgr** [comment] 2015-06-20 15:45
> Can you elaborate? Pretty sure we do include line information and generally have error messages that are close to PHP5's. For example, http://3v4l.org/piYKh
> 
> Can you give a code example where we are significantly different? Are you sure this isn't some error handler swallowing the information?

I am sorry. I forgot to add, that it only happens in fastcgi mode. In CLI it works just as php5.

**Comment by jwatzman** [comment] 2015-06-22 17:16
With the default trusty packages, and default configuration, when running http://3v4l.org/piYKh I still get a reasonable error in `/var/log/hhvm/error.log`:

```
\nFatal error: syntax error, unexpected T_CONSTANT_ENCAPSED_STRING in /usr/share/nginx/html/foo.php on line 3
```

What code are you running? Does that code install its own error handler that is swallowing HHVM's default error output? Are you sure you haven't made a configuration error that's swallowing the errors? (In particular, we have a bug where in some cases we don't recognize constants in INI files, so if you've set `error_reporting = E_ALL` that might actually turn *off* error reporting.)

**Comment by Profforgr** [comment] 2015-06-22 17:21
> With the default trusty packages, and default configuration, when running http://3v4l.org/piYKh I still get a reasonable error in /var/log/hhvm/error.log:
> 
> \nFatal error: syntax error, unexpected T_CONSTANT_ENCAPSED_STRING in /usr/share/nginx/html/foo.php on line 3
> What code are you running? Does that code install its own error handler that is swallowing HHVM's default error output? Are you sure you haven't made a configuration error that's swallowing the errors? (In particular, we have a bug where in some cases we don't recognize constants in INI files, so if you've set error_reporting = E_ALL that might actually turn off error reporting.)

Seems like i need to fully clarify.

```php
; send the error message to the output stream - corresponds to "display_errors" in PHP
hhvm.debug.server_error_message = true
```

Not in cli and not in log. Only in output stream. And looking in output stream (when you visit web page by HTTP), this is the case when does not contain file and line information where error appear.

**Comment by paulbiss** [comment] 2015-06-22 17:21
Did you look in your error log? I don't think we report error messages to the client in server mode.

**Comment by Profforgr** [comment] 2015-06-22 17:22
> Did you look in your error log? I don't think we report error messages to the client in server mode.

Yes.

But with

```php
; send the error message to the output stream - corresponds to "display_errors" in PHP
hhvm.debug.server_error_message = true
```

HHVM reports error messages to the client (output stream). But for some reason without file and line information about the error.

**Comment by paulbiss** [comment] 2015-06-22 18:36
Ah, that's a pretty old setting, I don't think it was designed to be the same as display_errors. The error message strings are built in handle_exception_helper(). There's an option to generate a backtrace for error messages but it's always false in calls from executePHPRequest(), might be reasonable to add an option to enable that.

**Comment by Orvid** [comment] 2016-09-30 19:55
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:55 UTC
Labels: needs more info

**Comment by asuth** [comment] 2017-02-23 18:45
Note: I had similar a similar issue, and managed to work around it:

Example of problem: 
Call `undefinedFunc()` somewhere in your code. with `hhvm.debug.server_error_message = true`, for web servers it will just print the error with no line number/message.

Workaround:
```php

register_shutdown_function(function() {
	$errorsToHandleOnShutdown = ImmSet{
		E_ERROR,
		E_COMPILE_ERROR,
		E_PARSE,
		// a HACK fatal error:
		// https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/runtime-error.h
	        16777217,
	};

	$e = error_get_last();
	if ($e !== null && $errorsToHandleOnShutdown->contains($e['type'])) {
		echo "Fatal error via shutdown: {$e['message']}\n{$e['file']}({$e['line']})\n";
		// in case there's been any buffering of response
		flush();
	}
});
