### ISSUE TITLE
HHVM crashes and stacktrace file has no trace information

### ISSUE THREAD

**Issue by Chazmo** [facebook/hhvm#4072] opened 2014-10-27 17:38 UTC
After running some load test of my server, I seem to be crashing hhvm.  I saw this same behavior with hhvm 3.1 a few months ago but when I upgraded my server to VM with more memory and CPUs the problem stopped happening.  I am seeing it with hhvm 3.3 with some smaller/older instance types (< 2GB main memory, and <= 2 VCPUs).  This is a pre-built package running under Apache2 (fast CGI) on an Ubuntu 14.04LTS platform.  I don't know why, but the stacktrace files that I'm getting (example below) don't have anything in them after the URL line.  Is there a way I can collect more information for the team?

root@ip-172-31-16-215:/tmp# cat stacktrace.2730.log 
Host: ip-172-31-16-215
ProcessID: 2730
ThreadID: 7ff2e67ff700
ThreadPID: 2734
Name: unknown program
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.3.0-0-g0a3cfb87b8a353fc7e1d15374f4adc413e37aba9
DebuggerCount: 0

ThreadType: Web Request
Server_SERVER_NAME: ec2- ***.compute.amazonaws.com
Server: ec2- ***.compute.amazonaws.com
URL: /***/

**Comment by Mwesome** [comment] 2015-05-04 21:15
@Chazmo Did you ever solve this problem?
I am having same issue.

**Comment by Chazmo** [comment] 2015-05-04 23:41
I'm sorry, Mwesome.  I gave up on this last year.

I presume the leak is being caused by one of the PHP extensions that we use, but I'm just guessing.  We didn't have any of our own in our product at the time (so it's not a bug I created), but it could be SimpleXML or something like that, which we use extensively but perhaps most hhvm users don't.

In the end, what we did was we built our own PHP extension (in C) to speed up some of the arithmetic code that we needed hhvm for in the first place (when it was in PHP) and we went back to using stock PHP.  That was sufficient for our web server purposes.

**Comment by jwatzman** [comment] 2015-06-18 17:58
Sorry to hear you weren't able to get HHVM to work for you. (And doubly-sorry for the belated response here.) FWIW, we have fixed some memory leaks and other issues in the months inbetween here; you might have more luck with 3.6 or 3.7 or the upcoming 3.8 if you want to give it a try. Otherwise, just glad you got to a solution that worked for you.

I'm going to close this, since we'd need more information, and probably on a newer version of HHVM, to do much here, and you've moved off of HHVM. Feel free to reopen if you can still repro on a newer version, and we can help you get us the information we need to look into it.

**Closed by jwatzman** 2015-06-18 17:58 UTC
Labels: crash, memory leak, needs more info, webserver

**Comment by JoelESvensson** [comment] 2015-11-12 13:42
I'm running HHVM 3.10.1 and I get this issue consistently every 3-5th day. HHVM crashes and the stack trace is empty.

<img width="281" alt="screen shot 2015-11-12 at 14 38 56" src="https://cloud.githubusercontent.com/assets/6786740/11119622/26192e36-894b-11e5-87a6-1dadff0dc83d.png">

My current setup is Nginx-HHVM on Ubuntu 15.04. The server is running two OctoberCMS sites.

What should I do to narrow down the cause of this?

**Comment by jwatzman** [comment] 2015-11-12 17:41
Please file a new issue with details: we're going to need a backtrace from gdb. The stacktrace being empty is a KP that isn't likely to be fixed soon, unfortunately. But the root cause is very likely to be different from this issue, so please file a new one.
