### ISSUE TITLE
HHVM Crashing - Memcached::setByKey

### ISSUE THREAD

**Issue by dtrackd** [facebook/hhvm#5022] opened 2015-03-14 08:54 UTC
We run a very busy laravel php website (roughly ~6million page-views per day)

now in development we found no issues with using HHVM as the fastcgi php interpreter but in production under load. it crashes every ~10-20mins. (using debian packages 3.6)

So for debugging I compiled the latest version (1 day ago from master) and its been running very smooth for over 6 hours so far.

here are so far the error output:

```
root@app1:~/dev/gcc-build/dev/hhvm/hphp/hhvm# ./hhvm -c /etc/hhvm/server.ini -m server
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0314 16:08:57.780988  8306 AsyncServerSocket.cpp:758] accept failed: out of file descriptors; entering accept back-off state
E0314 16:08:57.781131  8306 Acceptor.cpp:376] error accepting on acceptor socket: accept() failed
E0314 16:08:58.781551  8306 AsyncServerSocket.cpp:758] accept failed: out of file descriptors; entering accept back-off state
E0314 16:08:58.784643  8306 Acceptor.cpp:376] error accepting on acceptor socket: accept() failed
E0314 16:08:59.781615  8306 AsyncServerSocket.cpp:758] accept failed: out of file descriptors; entering accept back-off state
E0314 16:08:59.781728  8306 Acceptor.cpp:376] error accepting on acceptor socket: accept() failed
E0314 16:09:00.782081  8306 AsyncServerSocket.cpp:758] accept failed: out of file descriptors; entering accept back-off state
E0314 16:09:00.782927  8306 Acceptor.cpp:376] error accepting on acceptor socket: accept() failed
E0314 16:09:01.782346  8306 AsyncServerSocket.cpp:758] accept failed: out of file descriptors; entering accept back-off state
E0314 16:09:01.783643  8306 Acceptor.cpp:376] error accepting on acceptor socket: accept() failed
E0314 16:09:02.938805  8306 AsyncServerSocket.cpp:758] accept failed: out of file descriptors; entering accept back-off state
E0314 16:09:02.938881  8306 Acceptor.cpp:376] error accepting on acceptor socket: accept() failed
E0314 16:09:03.939275  8306 AsyncServerSocket.cpp:758] accept failed: out of file descriptors; entering accept back-off state
E0314 16:09:03.942631  8306 Acceptor.cpp:376] error accepting on acceptor socket: accept() failed
E0314 16:09:04.939795  8306 AsyncServerSocket.cpp:758] accept failed: out of file descriptors; entering accept back-off state
E0314 16:09:04.941396  8306 Acceptor.cpp:376] error accepting on acceptor socket: accept() failed
E0314 16:09:05.940807  8306 AsyncServerSocket.cpp:758] accept failed: out of file descriptors; entering accept back-off state
E0314 16:09:05.945056  8306 Acceptor.cpp:376] error accepting on acceptor socket: accept() failed
error : string is not in UTF-8
encoding error : output conversion failed due to conv error, bytes 0xF1 0x6F 0x6C 0x2F
I/O error : encoder error
error : string is not in UTF-8
encoding error : output conversion failed due to conv error, bytes 0xF1 0x6F 0x6C 0x2F
I/O error : encoder error
error : string is not in UTF-8
encoding error : output conversion failed due to conv error, bytes 0xF1 0x6F 0x6C 0x2F
I/O error : encoder error
error : string is not in UTF-8
encoding error : output conversion failed due to conv error, bytes 0xF1 0x6F 0x6C 0x2F
I/O error : encoder error
error : string is not in UTF-8
encoding error : output conversion failed due to conv error, bytes 0xF1 0x6F 0x6C 0x2F
I/O error : encoder error
error : string is not in UTF-8
encoding error : output conversion failed due to conv error, bytes 0xF1 0x6F 0x6C 0x2F
I/O error : encoder error

```

Is this anything I should be concerned about? and also what is any other means for debuging in production in case there is other things I might have missed

**Comment by jwatzman** [comment] 2015-03-16 15:04
How does it crash -- a segmentation fault? If so, it will usually print something to the error log about a `stacktrace.log` file in `/tmp` or something like that. Can you post that log file, if it exists? If you can get a core dump, or any of this info from a debug package, that would also be helpful.

**Comment by dtrackd** [comment] 2015-05-01 13:40
Thanks for the info @jwatzman 

So now that I am on 3.7 I have crashes happening maybe every 2 hours or so. here is the stacktrace:

```
root@app1:/tmp# cat stacktrace.16958.log
Host: app1
ProcessID: 16959
ThreadID: 7f19301ff700
ThreadPID: 16993
Name: /etc/init.d/hhvm
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.7.0-0-gc8baf9cd3cb603e030969bfe24634d5e85549915
DebuggerCount: 0

Server: domain.com
ThreadType: Web Request
Server_SERVER_NAME: app1
URL: /blahblah/bla

# 0  HPHP::jit::FixupMap::fixupWork(HPHP::ExecutionContext*, HPHP::ActRec*) const at /usr/bin/hhvm:0
# 1  HPHP::jit::MCGenerator::syncWork() at /usr/bin/hhvm:0
# 2  HPHP::createBacktrace(HPHP::BacktraceArgs const&) at /usr/bin/hhvm:0
# 3  HPHP::debug_string_backtrace(bool, bool, long) at /usr/bin/hhvm:0
# 4  raise at /lib/x86_64-linux-gnu/libc.so.6:0
# 5  abort at /lib/x86_64-linux-gnu/libc.so.6:0
# 6  __assert_fail at /lib/x86_64-linux-gnu/libc.so.6:0
# 7  memcached_stat_execute at /usr/lib/x86_64-linux-gnu/libmemcached.so.10:0
# 8  memcached_set_by_key at /usr/lib/x86_64-linux-gnu/libmemcached.so.10:0
# 9  HPHP::c_Memcached_ni_setbykey(HPHP::ObjectData*, HPHP::String const&, HPHP::String const&, HPHP::Variant const&, int) at /usr/bin/hhvm:0
# 10 void HPHP::Native::callFunc<false, false>(HPHP::Func const*, void*, HPHP::TypedValue*, HPHP::TypedValue&) at /usr/bin/hhvm:0
# 11 HPHP::TypedValue* HPHP::Native::methodWrapper<false, false>(HPHP::ActRec*) at /usr/bin/hhvm:0
```

**Comment by paulbiss** [comment] 2015-05-01 17:10
From the backtrace it looks as though memcached is causing an abort when called through Memcached::setByKey(). It's possible we're passing it bad data but it's impossible to say for sure from this trace. If you have a core and gdb handy you can check frames 9 and 8 to look at what we're passing into memcached.

**Comment by dtrackd** [comment] 2015-05-02 04:22
@paulbiss Thank you for the reply. Are you able to give me a cli example of what I will need to run in order to get the info needed (Sorry, I am a slight noob at this)

Thank you

**Comment by dtrackd** [comment] 2015-05-11 04:19
Bump

@paulbiss Whats the easier way for me to do this? are you able to give me an example?

Also this kind of error is happening roughly every 20mins after boot. So I can replicate it with ease.

**Comment by Orvid** [comment] 2016-09-30 21:39
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:39 UTC
Labels: needs more info
