### ISSUE TITLE
HHVM multicore performance

### ISSUE THREAD

**Issue by edwh** [facebook/hhvm#5148] opened 2015-04-08 16:39 UTC
This is similar to https://github.com/facebook/hhvm/issues/5024 .

I'm running HHVM on a machine with 8 cores, and with hhvm.server.thread_count = 64.  The max CPU I can manage to get HHVM to use hovers around 25%-30%, and the latency on my requests is rising upto several seconds.  I can see from my NGINX logs that the response time from HHVM is of that order, and I can see from measurements in my code that the time to execute a script once it starts running is very fast. 

So this bottleneck appears to be in getting HHVM to use multiple cores effectively enough to process more of my requests in parallel.

Are any ways to improve this?  For example, is it possible to run two copies of HHVM on the same server?

**Comment by jwatzman** [comment] 2015-04-08 17:35
@paulbiss any quick perf information we can ask @edwh to get for us? This sounds like it could be lock contention or something like that in the fastcgi layer, but it's hard to tell from what's here.

@edwh what OS are you running? What are you using to drive the load test? Do you have a simple test script that you could post for us to easily reproduce the problem?

**Comment by edwh** [comment] 2015-04-09 07:04
This is Ubuntu 14.04.  I'm using tsung to drive our web application, so I don't have a simple test script.  I'll have a bash (pun intended) at seeing if I can repro with one.

**Comment by paulbiss** [comment] 2015-04-09 07:44
Hmm, it sounds like requests may be stalling. You should try setting `hhvm.server.request_timeout_seconds`, but that won't tell you which requests are stalling (it will just fatal them). If you want to debug, one option is to run a debug build and attach gdb when it stalls, you can dump backtraces from all the worker threads and see what's going on. I don't think we set a default timeout but we probably should.

**Comment by edwh** [comment] 2015-04-09 08:55
I did this script:

<?php

echo "Hey";

Driving that with 10K connections I can see the latency on the requests rising to about 1.5s from the nginx logs, and the CPU is at about 50%.  So that's similar behaviour - there's extra capacity on the machine that it feels as though it ought to be able to use.

strace is a bit unreliable under load, I find, but I noticed this:

[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 139759882}) = 0
[pid   536] gettimeofday({1428569254, 595287}, NULL) = 0
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 139951170}) = 0
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 458
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 140122163}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 461
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 140346922}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 1542
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 140558551}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 1545
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 140803972}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 1546
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 141053285}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 1547
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 141302565}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 1555
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 141550370}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 1556
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 141800148}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 1557
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 142047221}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 2946
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 142296364}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 2947
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 142556375}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 2948
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 142817112}) = 0
[pid   536] write(18, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   536] accept4(17, {sa_family=AF_LOCAL, NULL}, [2], SOCK_NONBLOCK) = 2949
[pid   536] clock_gettime(CLOCK_MONOTONIC, {747209, 143077720}) = 0

I can see other entries on here suggesting that keepalive has been disabled in HHVM.  Perhaps there is a bottleneck in accepting new connections because of that?

**Comment by paulbiss** [comment] 2015-04-09 09:06
KeepAlive has been fixed in the latest release. I've definitely not seen this behavior before, what do you have in your nginx/hhvm configurations, maybe we can repro the problem on our machines?

**Comment by edwh** [comment] 2015-04-09 09:10
Thanks.  Latest official release, or latest nightly?

Here's the fragment of my nginx:

          fastcgi_pass unix:/var/run/hhvm/sock;
          fastcgi_keep_conn on;
          fastcgi_param HTTPS $https;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param REMOTE_ADDR $remote_addr;
          fastcgi_param HTTP_X_REAL_IP $http_x_real_ip;
          fastcgi_hide_header X-Powered-By;
          fastcgi_hide_header Pragma;
          fastcgi_hide_header Set-Cookie;
          fastcgi_ignore_headers "Expires" "Cache-Control" "Set-Cookie";
          fastcgi_buffer_size 16k;
          fastcgi_buffers 4 16k;
          include fastcgi_params;
          break;

Here's my server.ini:

 php options

pid = /var/run/hhvm/pid
include_path = ".:/usr/share/php"

; hhvm specific

hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.file_socket = /var/run/hhvm/sock
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.authoritative = true
hhvm.repo.central.path = /var/run/hhvm/precompiled/hhvm.hhbc
hhvm.server.thread_count = 64
hhvm.server.backlog = 30000

**Comment by edwh** [comment] 2015-04-09 09:35
I see similar behaviour on the latest nightly.

**Comment by Profforgr** [comment] 2015-04-10 00:01
Similar behaviour (Debian 7, nginx, hhvm 3.6.1; also tested nightly - same results). Was just like to ask same question.

In single request HHVM is using two threads in my tests. But it should use max threads or at least (number of cores) threads. It should speed up requests by factor of cores, isn't it?

**Comment by jeroenvermeulen** [comment] 2016-03-22 16:22
I experience the same problem.

We are testing a heavy Magento install on a 12 core server with HyperThreading so 24 cores in Linux.
I know this heavy Magento install is doing far more MySQL queries than it should, some page requests do 800 till 1000 queries.

I am doing a Siege based test on the URLs from the sitemap:
`siege --concurrent=40 --benchmark --time=30s --internet --file=urls.txt`

With `hhvm.server.thread_count = 48` it does around 11 trans/sec.
With `hhvm.server.thread_count = 24` it does around 12 trans/sec.
With `hhvm.server.thread_count = 8` it does around **17** trans/sec.
With `hhvm.server.thread_count = 4` it does around 11 trans/sec.

**Comment by Orvid** [comment] 2016-09-30 21:16
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:16 UTC
