### ISSUE TITLE
Nightly package is latest not nightly

### ISSUE THREAD

**Issue by photodude** [facebook/hhvm#7355] opened 2016-09-19 12:56 UTC
### HHVM Version
Nightly (3.15) (on Ubuntu trusty)
### Standalone code, or other way to reproduce the problem
wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -
echo deb http://dl.hhvm.com/ubuntu saucy main | sudo tee /etc/apt/sources.list.d/hhvm.list
sudo apt-get update
sudo apt-get install hhvm-nightly

### Expected result
HHVM nightly is installed 

### Actual result
The HHVM nightly on the Trusty builds are not actually nightly.

build showing latest hhvm
https://travis-ci.org/photodude/joomla-cms/jobs/160930724

build showing nightly hhvm
https://travis-ci.org/photodude/joomla-cms/jobs/160930722

The Compiler: tags and the Repo schema: are exactly the same Id's I believe that means nightly is latest rather than nightly.

**Comment by photodude** [comment] 2016-09-19 15:51
I see 2016.09.19 packages in http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-amd64/Packages.
Just doesn't seem like they are actually nightly builds

**Comment by Orvid** [comment] 2016-09-19 17:46
@aorenste We do have nightly packages. I suspect the packaging script probably was misbehaving due to 3.15 having been released but the actual version number not having been bumped yet as I needed to update the packaging machines first.

**Comment by photodude** [comment] 2016-09-20 15:01
@Orvid I see the package dates changed but it still seems like the nightly packages are latest rather than nightly.

**Comment by Orvid** [comment] 2016-09-20 17:53
I'm not sure how that travis job is getting it's nightly package, but, after checking, the 2016.09.20 package for Trusty is 3.16.0-dev. What is the Travis job doing to get the nightly package?

**Comment by photodude** [comment] 2016-09-20 18:35
I believe Travis just uses `apt-get`
In the build I linked to I had additionally specified `hhvm-nightly` In the apt packages to install.

**Comment by photodude** [comment] 2016-09-22 22:09
I've tried again to get the nightly build 2016.09.22 version 3.16.0-dev
I have [followed this guide](https://community.linuxmint.com/tutorial/view/1433) to directly install from the `hhvm-nightly_2016.09.22~trusty_amd64.deb` file

yet what got installed is still 3.15.0 (rel) not 3.16.0-dev https://travis-ci.org/photodude/joomla-cms/jobs/162044863

**Comment by Orvid** [comment] 2016-09-22 22:15
Is it possible that this is what's setting the environment to 3.15?
https://travis-ci.org/photodude/joomla-cms/jobs/162044863#L343

**Comment by photodude** [comment] 2016-09-22 22:21
Maybe, I'm trying to alter the install after the initial composer stuff.
https://travis-ci.org/photodude/joomla-cms/jobs/162044863#L363-L418

**Comment by Orvid** [comment] 2016-09-30 22:05
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 22:05 UTC
Labels: build, needs more info

**Comment by photodude** [comment] 2016-10-03 15:18
Thank you For looking into this @Orvid, Travis CI was able to figure out what they had incorrectly set up and nightly builds are now working correctly.
