### ISSUE TITLE
Website/Testing Fail: "we can run the top 20 Github PHP frameworks out of the box."

### ISSUE THREAD

**Issue by ssteinerx** [facebook/hhvm#6290] opened 2015-09-22 22:13 UTC
Just from: http://hhvm.com/frameworks/

Open Source Tests: 0.00%

These tests are run with HHVM from GitHub master. The last run was at 1970-01-01 00:00 UTC.

0 Frameworks at 100%

https://www.dropbox.com/s/s95y145eqtwm80j/Screenshot%202015-09-22%2018.09.44.png?dl=0

**Comment by ssteinerx** [comment] 2015-09-22 22:13
I was just looking to see whether WordPress was there...

**Comment by fredemmott** [comment] 2015-09-22 22:37
The machine got decomissioned, and new machines were IPv6 only + some other changes. I've been working on bringing this back up, and hopefully it'll be back by the end of the week.

**Comment by ssteinerx** [comment] 2015-09-22 23:17
Understood; just wanted to make sure someone noticed as this is not "optimal" when promoting a project.

S

**Comment by askonomm** [comment] 2015-10-02 06:06
Bump. The error still remains.

**Comment by fredemmott** [comment] 2015-10-02 16:43
Yep, sorry, this takes time and I've had to fix things that are blocking other people :(

The delay is basically that we do not have internet access from our internal systems, and with the switch to IPv6, our way of making exceptions to that has changed - which gets a little complicated as the systems have a mix of internet network ops (eg 'fetch HHVM from github') and internal ones (eg talk to the CDN to store the results so they can be retrieved via the API).

As for it being empty despite the JSON not being empty: we're running the tests now, but it's not storing the results - the current JSON just lists the tested frameworks, but not their pass rates.

**Comment by fredemmott** [comment] 2015-10-02 18:13
Data's now on https://graph.facebook.com/hhvm_oss_tests again, website should be fixed in a few hours.

**Comment by fredemmott** [comment] 2015-10-02 18:28
'fixed' now, will leave open until there's a few more data points.

**Comment by ssteinerx** [comment] 2015-10-02 18:45
Uh, that looks like a configuration file...

**Comment by fredemmott** [comment] 2015-10-02 18:49
It's the API that http://hhvm.com/frameworks/ reads to get the data.

**Comment by fredemmott** [comment] 2015-10-02 18:52
search for `"runs":` to see the interesting stuff

**Comment by fredemmott** [comment] 2015-10-02 22:02
Now got 3 data points, 2 of which were unattended, closing. If this re-occurs, please open another issue.

I've also added a monitoring check for 'Last run was at 1970' so this gets picked up sooner if it happens again.

**Comment by ssteinerx** [comment] 2015-10-02 22:17
Not seeing WordPress which was the original motivation for going to the page in the first place...  I know we had an email exchange about WordPress working, but is there a test?

**Comment by fredemmott** [comment] 2015-10-03 02:41
We do not support Wordpress because our framework only supports git, and Wordpress's tests are only in their subversion repository.

**Comment by fredemmott** [comment] 2015-10-03 02:41
* the framework tests page does not support wordpress - HHVM itself does.

**Comment by ssteinerx** [comment] 2015-10-03 13:20
https://make.wordpress.org/core/2014/01/15/git-mirrors-for-wordpress/

and:

https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/

S

**Comment by Orvid** [comment] 2015-10-03 20:30
The problem is those git mirrors don't include the tests.

**Comment by SiebelsTim** [comment] 2015-10-03 21:11
They do include them. However they depend heavily on mysql, which is bad for hhvm.com/frameworks I believe.

**Comment by ssteinerx** [comment] 2015-10-04 01:17
@SiebelsTim I was responding to "We do not support Wordpress because our framework only supports git, and Wordpress's tests are only in their subversion repository."  Ok, so that's not it.

Why would a MySQL dependency be bad?

**Comment by ssteinerx** [comment] 2015-10-04 02:39
@Orvid https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/ specifically gives instructions for running the tests from a git checkout.

**Comment by fredemmott** [comment] 2015-10-05 02:11
Thanks; I wasn't aware of those repositories, only of the github tree. We'd be happy to take a pull request adding a realistic wordpress test.

Using MySQL is not a problem - most of the framework tests use it.

**Comment by SiebelsTim** [comment] 2015-10-05 08:49
> Using MySQL is not a problem - most of the framework tests use it.

I can't find where I have to put the credentials (i.e. I don't know user/password etc. for your test server). Wordpress expects a file containing these.

**Comment by simonwelsh** [comment] 2015-10-05 09:07
From other tests, looks like it's root with no password connecting to localhost.

**Comment by ssteinerx** [comment] 2015-10-05 12:08
@SiebelsTim If you have a minute, could you outline your test setup?  I'd love to have this running locally !

**Comment by SiebelsTim** [comment] 2015-10-05 13:21
#6332 then 

`cd hphp/test/frameworks/ && hhvm ./run.php wordpress`

**Comment by fredemmott** [comment] 2015-10-05 16:32
sorry, my bad, got it confused with the performance tests. Yeah, we don't run tests that need MySQL.

**Comment by fredemmott** [comment] 2015-10-05 18:03
The test page has stopped updating and will fail again in a few days because of what looks like a hardware failure; unfortunately these servers are 'special snowflakes' and we don't currently have any spares. Hopefully it can be repaired quickly, but I don't have an ETA.

**Comment by ssteinerx** [comment] 2015-10-05 18:15
@fredemmott Is that "don't run tests that need MySQL" **yet**?

**Comment by fredemmott** [comment] 2015-10-05 18:30
We have no plans to extend our framework testing functionality, as we no longer directly work on improving framework pass rates; this was very beneficial last year, but given our current pass rates, it's a much better use of time for us to work on reported issues with isolated test cases.

We also can't take a pull request for it, as the main problem is configuring FB infrastructure to create and clean a MySQL instance for each test, not directly the problem of running them.

This isn't the problem for the benchmarks as they aren't ran on our unit testing machines.

**Comment by SiebelsTim** [comment] 2015-10-05 18:46
@ssteinerx Running these locally should work nevertheless. The rate of 85%+ I got locally seem to be real.

**Comment by fredemmott** [comment] 2015-10-05 19:34
Machine's back and running tests again. Leaving issue open for a few days to remind me to check on it.

**Comment by sebmck** [comment] 2015-12-03 10:33
Still broken.

**Comment by fredemmott** [comment] 2015-12-03 16:28
Not still, broken again. Probably going to just remove it as it's a lot of work to keep working, and it's misleading anyway.

**Comment by ssteinerx** [comment] 2015-12-03 16:50
I would think that these tests would be important in making HHVM as compatible with real PHP apps as possible...

**Comment by fredemmott** [comment] 2015-12-03 18:03
We run them automatically against every commit in a separate system. The charts page is misleading as:

 - they're old versions - and updating them takes a significant amount of work to make sure that the tests are still actually reliable - even 'fails 1 out of 1000 times' issues cost us several hours a week, and generally frameworks don't care about that level of test reliability
 - people frequently assume that because something isn't listed, it won't work

**Comment by Orvid** [comment] 2016-03-23 21:33
We killed the page, so closing this.

**Closed by Orvid** 2016-03-23 21:33 UTC
