### ISSUE TITLE
hhvm.server.request_timeout_seconds max value

### ISSUE THREAD

**Issue by dieend** [facebook/hhvm#6174] opened 2015-08-31 07:37 UTC
I found out if setting `hhvm.server.request_timeout_seconds` with value > 2147, hhvm turns strange,  It gives me `Service Unavailable` results (I uses hhvm as fastcgi with nginx). 
```
hhvm --version
HipHop VM 3.8.1 (rel)
Compiler: tags/HHVM-3.8.1-0-g3006bc45691762b5409fc3a510a43093968e9660
Repo schema: 253b3802ce1bcd19e378634342fc9c245ac76c33
```

**Comment by Orvid** [comment] 2016-09-30 19:07
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:07 UTC
