### ISSUE TITLE
HTTPS file wrapper doesn't work for sites with TLSv1.0 disabled

### ISSUE THREAD

**Issue by llimos** [facebook/hhvm#6507] opened 2015-11-03 11:08 UTC
More and more HTTPS websites are disabling TLSv1.0 support (such as [Salesforce](https://help.salesforce.com/HTViewSolution?id=000221207&language=en_US)).
When opening an https link using the file wrapper, on a site with TLSv1.0 disabled, it fails. For example, the Salesforce test site:

    <?php
    echo file_get_contents('https://tls1test.salesforce.com/s/');

results in 

    Warning: Failed to open https://tls1test.salesforce.com/s/ (Cannot communicate securely with peer: no common encryption algorithm(s).)

Tested on HHVM 3.9 and 3.10.1. This works fine on Zend PHP from at least 5.4. (Unfortunately we can't use 3v4l for external links.) In my environment both the Zend PHP and HHVM have an `OPENSSL_VERSION_TEXT` of `OpenSSL 1.0.1e-fips 11 Feb 2013`, so that isn't the issue.

Setting the context parameters doesn't help either:

    <?php
    stream_context_set_default([
        'ssl' => [
            'crypto_type' => \STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT,
            'crypto_method' => \STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT
        ]
    ]);

-- no change, though the constants are defined in HHVM. (Different places in the manual differ over which name to use for the key - but neither works. Zend PHP doesn't need this done at all)

For regular requests it is of course possible to use cURL, but the problem I'm having is using the SoapClient and I have not been able to find any workaround for that at all.

**Comment by fredemmott** [comment] 2016-01-14 18:36
I can't reproduce this on 3.11.0 or nightlies with our binary packages.

**Comment by aorenste** [comment] 2016-09-27 22:03
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by aorenste** 2016-09-27 22:03 UTC
Labels: no isolated repro
