### ISSUE TITLE
Is there a way to make SimpleXMLElement work with the type checker?

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5164] opened 2015-04-12 20:41 UTC
In the [SimpleXML examples](http://php.net/manual/en/simplexml.examples-basic.php), there's code that uses the dynamical properties feature of PHP (called "overloading" in PHP terminology).

Is there a way to make such code pass the type checker, or is the only way to use UNSAFE or HH_FIXME?

Anyone got any suggestions?

**Comment by oyamauchi** [comment] 2015-04-13 15:59
We may be able to special-case `SimpleXMLElement` so that you can read/write dynamic properties to it without errors -- we already special-case `stdClass` in that way.

**Comment by tslettebo** [comment] 2015-04-13 16:52
Thanks for your reply.

**Comment by fredemmott** [comment] 2015-04-13 19:06
I'd prefer we didn't support it:

- for reading, this isn't really arbitrary
- it gives a false sense of security

Given that any use of SimpleXMLElement dynamic properties /is/ unsafe, I don't see why we shouldn't require using // UNSAFE

There's also been some past discussion about removing support for __call(); last I heard we want to do this as soon as Facebook migrates away from some (special-cased) legacy implementations of memoization.

**Comment by paulbiss** [comment] 2015-04-13 20:15
In this specific instance I don't think supporting it would be a problem. SimpleXML is already pretty heavily baked into the runtime, and accessing a property that doesn't exist in the XML document will just give you an empty SimpleXML element, so from a typing standpoint it wouldn't be masking unsafe behavior. For subscript access it can return null, but since that won't raise an error either it can also be typed safely.

I think blanket support for __get/__set/__call is a bad idea, but in this case the extension is part of the runtime and it's safe to assume we understand how it will behave. Anyway, just my 2¢.

**Comment by oyamauchi** [comment] 2015-04-13 20:20
Yeah, I'm in agreement that allowing unknown properties for objects with __get()/__set() is excessively unsafe, but special-casing SimpleXMLElement is OK. That should be a fairly easy typechecker change.

**Comment by jwatzman** [comment] 2015-04-20 02:01
Yeah, special case sounds good to me. I might disallow it in strict mode though?

> we already special-case `stdClass` in that way.

FWIW I'm not a huge fan of this, and feel it should be disallowed in strict mode too, not sure if we ever did that. (But clearly not strongly enough to go fix it myself ;))

**Comment by Daniel15** [comment] 2016-05-31 05:08
Probably a duplicate of #3618

**Comment by lexidor** [comment] 2020-05-23 15:04
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The typesystem added a hole for dynamicness in [3.26.0](https://hhvm.com/blog/2018/05/07/hhvm-3.26.html) namely [dynamic](https://docs.hhvm.com/hack/built-in-types/dynamic).
It is more explicit than the `\stdClass` special cases (which is gone too).

You can make the entire variable dynamic, using `$simplexmlelement as dynamic`.

I'd suggest writing this helper to only cast to dynamic when reading a dynamic property, but while keeping the `$simplexmlelement` a SimpleXMLElement.
```HACK
function dyn(SimpleXMLElement $s): dynamic {
    return $s;
}
```

This allows expressions like this to be handled in a typesafe way:
```HACK
$simplexmlelement = new SimpleXMLElement($xml);
$simplexmlelement_dynamic = dyn($movies);

$simplexmlelement->getIterator(); // checked
$simplexmlelement_dynamic->whateveryoulikewithouttypecheckererrors; // dynamic
```

You'll be checked that you are doing things which are provably safe when you access methods via `$simplexmlelement`, when you use `$simplexmlelement_dynamic` you are on your own, but the typechecker will still look after you when you do something unsafe that may not be caught at runtime with the result of the dynamic expressions.

I think this is the best that Hack can do, without making the typesystem weaker.

I am leaving this issue open, but the chance that SimpleXMLElement will be specialcased now seems small, since we also dropped the `\stdClass` specialcase.

**Comment by Daniel15** [comment] 2020-05-23 17:17
Maybe codegen is the best solution for strongly-typed XML access. Someone could write a code generator that takes an XML schema as input and returns a Hack class as output. Internally the Hack class could use dynamic, but at least it could be hidden from users.

**Comment by lexidor** [comment] 2022-09-16 18:36
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

In hhvm 4.167.0, support for partial mode was completely removed. There is no way to special case simple xml in a weaker checking mode. Hack is effectively always strict now.

The language can't accommodate this level of too-flexible-for-its-own-good. (Don't worry, the runtime still can.) The language has an escape hatch, `\HH\FIX_ME\UNSAFE_CAST<SimpleXml, MyPoho>($sxml)->someProp` which will have the type of MyPoho->someProp, e.g. string.

**Closed by lexidor** 2022-09-16 18:36 UTC
Labels: hack, probably easy
