### ISSUE TITLE
Enum switch exhaustiveness is not checked when `as` is used

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8841] opened 2021-05-26 19:36 UTC
**Describe the bug**
Switch exhaustiveness checking for enums does not apply when `$x as EnumName;` is used. It does apply when `EnumName::assert($x);` is used.

**Standalone code, or other way to reproduce the problem**
```
enum Foo: string {
    BAR = 'bar';
    BAZ = 'baz';
}

function example_switch(string $in): void {
    $example = $in as Foo;
    switch ($example) {
        case Foo::BAR:
            return;
    }
}
```

This produces no errors. Changing it to `$example = Foo::assert($in);` does produce the expected errors.

Run `hh_client` with above code snippet.

**Expected behavior**

This error should be returned:
```
Typing[4019] Switch statement nonexhaustive; the following cases are missing: BAZ
   --> test.hack
  1 | enum Foo: string {
    |      ^^^ Enum declared here
  8 |     switch ($example) {
    |             ^^^^^^^^

1 error found.
```

**Actual behavior**

```
$ hh_client
No errors!
```

**Environment**
 - Operating system
Mac OS Big Sur
 - Installation method
Homebrew
 - HHVM Version
```
HipHop VM 4.110.0 (rel)
Compiler: 1621286413_N
Repo schema: 09d2af8dd22201dd8d48e5dcfcaed281ff9422c7
```

**Comment by fredemmott** [comment] 2021-05-27 16:13
Closing as duplicate of #8563

**Closed by fredemmott** 2021-05-27 16:13 UTC
