### ISSUE TITLE
Update from 3.5 to 3.6 makes the Apache 2.4 + HHVM sending 404 errors

### ISSUE THREAD

**Issue by castarco** [facebook/hhvm#4998] opened 2015-03-11 07:24 UTC
Hello,

Yesterday HHVM was updated from 3.5 to 3.6 via APT (on Ubuntu 14.04 64 bits). Since then my webserver only responds with HTTP 404 error messages : "404 File Not Found".

The used stack is Ubuntu 14.04 64 bits + Apache 2.4 + HHVM 3.6 (through fastcgi, the default HHVM settings).

The server manages two separated websites, an OwnCloud 8.0.0-9, and an updated Wordpress blog. The two websites started to fail when HHVM was updated.

I don't know if that's important (I think no), but I'll tell it to complete the information: I have an Ubuntu 14.04 server 64 bits, but running a linux 3.10 patched kernel from OVH for their kimsufi servers, not the 3.13 version.

It's possible that the bug that I describe is related with #4986 , or that it's exactly the same bug, but the proposed solution in that thread didn't solve my problem.

**Comment by keepxtreme** [comment] 2015-03-11 10:26
Duplicate of issue #4986

**Comment by castarco** [comment] 2015-03-11 12:27
That's not a duplicate of #4987 . Maybe, (and it's not evident) it's a duplicate of #4986 . I'm not suffering the PDO problem because the code isn't even executed.

Yes, I've checked the logs, nothing special :( .

**Comment by tdavis-ourfuture** [comment] 2015-03-12 20:23
Anyone got something? 

Look at castarco and myself.  We are so sad about this that our faces are angled downwards and slightly off center.   Like we are staring into the middle distance between the marginal speed improvement promised by HHVM and our simply adequate present.

Can no one cast light on this?  Rid me of this meddlesome priest?

I've tried this with both nginx and apache on 14.04 and 14.10.  I am so sad that all the color left my face.

**Comment by castarco** [comment] 2015-03-18 07:37
Hello? Anyone can confirm if this report is a duplicate of some other bug? Or if there is any workaround?

**Comment by SiebelsTim** [comment] 2015-03-19 11:22
Are you getting 404s on direct links (i.e. explicitly adding the file you want to access) as well?

**Comment by paulbiss** [comment] 2015-03-19 16:21
Can you paste your ini settings and the relevant portions of your apache config? Does the bug repro in the nightly as well?

**Comment by Dantali0n** [comment] 2015-03-23 08:12
Hello im having the same, the 404 only appears when the files are parsed to hhvm with proxypassmatch when the file ex: a static html page is requested the page is shown. downgrading to 3.5.1 fixes this issue. my OS is ubuntu 14.04 lts x64

**Comment by castarco** [comment] 2015-03-24 10:28
Sorry for my late response, I hadn't time to answer. Yes, I had 404 on direct links (but only for PHP files), with static files I hadn't issues.

Anyway, I uninstalled HHVm for a while and I was working with PHP-FPM these days. Today I've reinstalled HHVM to try it again and it simply works :s , I don't know what's happening.

Have been HHVM updated these days? Or we have a heisenbug here?

**Comment by Dantali0n** [comment] 2015-03-24 10:42
No my problem persist on 3.6 and 3.7 I downgraded to 3.5.1in the mean time, feel free to close this issue as im sure its probably due to my configuration and not really HHVM related.

**Closed** 2015-03-24 15:20 UTC
Labels: fastcgi

**Comment by grep-awesome** [comment] 2015-05-07 04:21
I'm having the same issue... Would love to downgrade to 3.5.1, but it is no longer listed in the repositories...

**Comment by Dantali0n** [comment] 2015-05-13 06:08
@grep-awesome You can find them here: http://dl.hhvm.com
