### ISSUE TITLE
Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock'

### ISSUE THREAD

**Issue by zjhzxhz** [facebook/hhvm#4878] opened 2015-02-22 09:07 UTC
The HHVM 3.5.1 has a bug that it assumes that the socket of MySQL is in `/var/lib/mysql/mysql.sock`.
But it seems be fixed in 3.6.0 dev.

However, the 3.6.0 is not a stable version. So I had to create a symbol link in `/var/lib/mysql/mysql.sock`. Please fix it.

Here's the stack trace of the problem while running a application using Zend Framework 2:

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in :
Stack trace:
#0 /usr/local/nginx/html/itp/vendor/zendframework/zendframework/library/Zend/Db/Adapter/Driver/Pdo/Connection.php(320): PDO->__construct()
#1 /usr/local/nginx/html/itp/vendor/zendframework/zendframework/library/Zend/Db/Adapter/Driver/Pdo/Pdo.php(249): Zend\Db\Adapter\Driver\Pdo\Connection->connect()
#2 /usr/local/nginx/html/itp/vendor/zendframework/zendframework/library/Zend/Db/Sql/Sql.php(120): Zend\Db\Adapter\Driver\Pdo\Pdo->createStatement()
#3 /usr/local/nginx/html/itp/vendor/zendframework/zendframework/library/Zend/Db/TableGateway/AbstractTableGateway.php(232): Zend\Db\Sql\Sql->prepareStatementForSqlObject()
#4 /usr/local/nginx/html/itp/vendor/zendframework/zendframework/library/Zend/Db/TableGateway/AbstractTableGateway.php(208): Zend\Db\TableGateway\AbstractTableGateway->executeSelect()
#5 /usr/local/nginx/html/itp/vendor/zendframework/zendframework/library/Zend/Db/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith()
#6 /usr/local/nginx/html/itp/module/Application/src/Application/Model/OptionTable.php(42): Zend\Db\TableGateway\AbstractTableGateway->select()
#7 /usr/local/nginx/html/itp/module/Application/Module.php(74): Application\Model\OptionTable->getAllOptions()
#8 (): Application\Module->onBootstrap()
#9 /usr/local/nginx/html/itp/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func()
#10 /usr/local/nginx/html/itp/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners()
#11 /usr/local/nginx/html/itp/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(156): Zend\EventManager\EventManager->trigger()
#12 /usr/local/nginx/html/itp/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(260): Zend\Mvc\Application->bootstrap()
#13 /usr/local/nginx/html/itp/public/index.php(17): Zend\Mvc\Application::init()
#14 {main}
```

**Comment by zjhzxhz** [comment] 2015-02-22 14:18
In `/etc/hhvm/php.ini`:
```
hhvm.mysql.socket = /tmp/mysql.sock
```
But this doesn't work.

**Comment by PunKeel** [comment] 2015-03-05 16:57
Duplicate of #4869

**Closed** 2015-03-05 17:09 UTC
Labels: duplicate

**Comment by clwu88** [comment] 2020-01-18 05:52
please try `hhvm --info | grep pdo `,

you will find the output is `pdo_mysql.default_socket => `,
THE VALUE OF **pdo_mysql.default_socket**  IS EMPTY !!!

all your guys above is wrong, the right approach is edit /etc/hhvm/php.ini
`pdo_mysql.default_socket = /var/run/mysqld/mysqld.sock`
