### ISSUE TITLE
DOMXPath:.$document returns invalid document

### ISSUE THREAD

**Issue by ThomasWeinert** [facebook/hhvm#4753] opened 2015-02-02 10:55 UTC
This seems to be introduced with the latest changes (https://github.com/facebook/hhvm/commit/dee50ed62be1889753ec061bd62d462f1ddd05ec).

The `$document` property of an `DOMXPath` instance returns the DOM document it was created for. This works fine for a `DOMDocument` instance:

```php
$dom = new DOMDocument();
$xpath = new DOMXPath($dom);
var_dump($dom == $xpath->document);
```
```
bool(true)
```

However it fails if the document is an instance of a class that extends DOMDocument.

```php
class MyDOM extends DOMDocument {}

$dom = new MyDOM();
$xpath = new DOMXPath($dom);
var_dump($dom == $xpath->document);
```
```
bool(false)
```

http://3v4l.org/iqH7G#vhhvm-330

**Comment by paulbiss** [comment] 2015-02-02 17:01
cc @DmitrySoshnikov

**Comment by DmitrySoshnikov** [comment] 2015-02-03 06:53
I've debugged it, the issue wasn't caused by the recent prop handlers commit, but was always there. The reason is, we register an extended class name _only if_ the `registerNodeClass` method was called explicitly. I.e. this works:

```php
class MyDOM extends DOMDocument {}

$dom = new MyDOM();
$dom->registerNodeClass('DOMDocument', 'MyDOM'); // !
$xpath = new DOMXPath($dom);
var_dump($dom == $xpath->document); // true
```

But that's inconsistent of course with PHP which registers it automatically in case of `DOMDocument` class extension, I'll take a look.

**Comment by ThomasWeinert** [comment] 2015-02-03 13:34
Thanks, this fixes the class problem. But, the DOMXPath always gets a secondary instance of the document. So DOMXPath::document is equal to the provided DOMDocument but never identical.

```php
$dom = new DOMDocument();
$xpath = new DOMXPath($dom);
var_dump($dom === $xpath->document); // false
```
Sorry, I did not noticed that before.

**Comment by DmitrySoshnikov** [comment] 2015-02-03 18:32
Yeah, thanks, that's a separate identity issue, we'll fix them one at a time :)

**Comment by DmitrySoshnikov** [comment] 2015-02-04 22:05
@ThomasWeinert FYI: usage of `registerNodeClass ` is a workaround hack, I have a proper fix for this, should be landed soon.

**Closed** 2015-02-05 09:10 UTC
Labels: php5 incompatibility
