### ISSUE TITLE
dentry memory leak

### ISSUE THREAD

**Issue by noony** [facebook/hhvm#6579] opened 2015-11-20 09:56 UTC
First, As you can see, when running hhvm a couple of days, there is an incrementation of memory used, first drop is a reboot of the server, second drop is due to an execution of a command (see bellow) :

![capture d ecran 2015-11-20 a 10 35 04](https://cloud.githubusercontent.com/assets/580196/11296731/37571256-8f74-11e5-975c-cf9c4cd752d9.png)

In top order by VIRT, current running programs doesn't use all ram told as used, so the question is where is it used ? 

![capture d ecran 2015-11-20 a 10 31 25](https://cloud.githubusercontent.com/assets/580196/11296728/37542a3c-8f74-11e5-9537-aeb6b824c104.png)

It seems that's use for dentry cache, the second drop is due to freed memory with this command :

```
echo 3 > /proc/sys/vm/drop_caches
```

Normally this command free cached memory not used memory. So I think there is something wrong.

result of slabtop :

![capture d ecran 2015-11-20 a 10 44 53](https://cloud.githubusercontent.com/assets/580196/11296729/375582ba-8f74-11e5-9660-40875f94c8f3.png)
![capture d ecran 2015-11-20 a 10 46 02](https://cloud.githubusercontent.com/assets/580196/11296730/37570b44-8f74-11e5-8d82-ee0347822142.png)

**Comment by noony** [comment] 2015-11-22 13:09
It seems related to ubuntu trusty kernel 3.13, I'll close this issue if updating kernel resolve this memory leak.

**Comment by noony** [comment] 2015-11-26 09:23
Update with 3.19 kernel the problem is still there so I reopened this issue.

**Comment by aorenste** [comment] 2016-09-27 21:31
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by aorenste** 2016-09-27 21:31 UTC
Labels: memory leak, needs more info, no isolated repro
