### ISSUE TITLE
Disparity between PHP 5.5.9 and HHVM 3.7.2

### ISSUE THREAD

**Issue by SirTempest** [facebook/hhvm#5540] opened 2015-06-26 04:39 UTC
I run a myBB forum on top of HHVM with a fallback to PHP-FPM in case of issues with HHVM. I ran into one such issue today. I tried to install a plugin. All the PHP files that affect the forum are dynamically created by the plugin PHP script. HHVM builds one of the files incorrectly, and causes a fatal error, but PHP-FPM builds it correctly. I spoke with the developer of the plugin, since I am horrendous with PHP, and found the supposed function that works incorrectly.

Version Info:

```
root@localhost:~# hhvm --version
HipHop VM 3.7.2 (rel)
Compiler: tags/HHVM-3.7.2-0-gfc9f29b2799933d8215faaadfa83de722df64e26
Repo schema: 34f16546e395aed44ad434467b6f96c89b0d8a8b

root@localhost:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

```

The developer figured the buggy function was in this snippit of code:
```php
function xthreads_phptpl_parse_fields($s, $fields, $in_string) {
	if(!empty($fields)) {
		$tr = $ptr = array();
		$do_value_repl = false;
		foreach($fields as $f => $r) {
			if(isset($r)) {
				$tr['{'.$f.'}'] = ($in_string ? $r : '("'.$r.'")');
			} else {
				$ptr[] = '~\\{('.preg_quote($f, '~').')((?:-\>|\[)[^}]+?)?\\}~e';
			}
			if($f == 'RAWVALUE') $do_value_repl = true;
		}
		$str_start = ($in_string?'{':'("".');
		$str_end = ($in_string?'}':'."")');
		if($do_value_repl) $s = preg_replace('~\{((?:RAW)?VALUE)\\\\?\$(\d+)\}~', $str_start.'$vars[\'$1$\'][$2]'.$str_end, $s);
		if(!empty($tr))  $s = strtr($s, $tr);
		if(!empty($ptr)) $s = preg_replace($ptr, '\''.$str_start.'\\$vars[\\\'$1\\\']\'._xthreads_phptpl_expr_parse(\'$2\').\''.$str_end.'\'', $s);
		// careful with _xthreads_phptpl_expr_parse() call above - we avoid infinite looping by not supplying $fields
		// although _xthreads_phptpl_expr_parse should always be called outside string context, the above is safe because the user cannot put in a '}' character at all - that is, achieving something like {$vars['VAL'][0]}".whatever."{$var} should be impossible
		// an issue with the above, is that it's impossible to do something like {VAR[{VALUE}]} because variables are all auto-global'd... (but even if not, the above isn't guaranteed to work anyway, since the end token '}' might match early, eg {VAR[)
	}
	return $s;
}
```

Which is called earlier with $in_string being false:
```php
function xthreads_phptpl_expr_parse($str, $fields=array())
{
	// remove all single quote strings - they mess up all our plans...
	$strpreg = '~\'(|\\\\\\\\|.*?([^\\\\]|[^\\\\](\\\\\\\\)+))\'~s';
	if(preg_match_all($strpreg, $str, $squotstr)) {
		$token = '\'__PHPTPL_PLACEHOLDER_'.md5(mt_rand()).'__\'';
		$str = preg_replace($strpreg, $token, $str);
		$squotstr = $squotstr[0];
	}
	
	// globalise all variables; conveniently will filter out stuff like {VALUE$1}
	$str = preg_replace('~\$([a-zA-Z_][a-zA-Z_0-9]*)~', '$GLOBALS[\'$1\']', $str);
	// won't pick up double variable syntax, eg $$var, or complex variable syntax, eg ${$var}
	
	// fix variables in double-quote and heredoc strings
	$strpreg = '~(")(|\\\\\\\\|.*?([^\\\\]|[^\\\\](\\\\\\\\)+))\\1~s';
	if(xthreads_allow_php())
		$str = preg_replace_callback(array($strpreg, "~\<\<\<([a-zA-Z_][a-zA-Z_0-9]*)\r?\n.*?\r?\n\\1;?\r?\n~s"), 'xthreads_phptpl_expr_parse_fixstr_complex', $str);
	else
		$str = preg_replace_callback($strpreg, 'xthreads_phptpl_expr_parse_fixstr_simple', $str);
	
	if(!empty($fields))
		// we need to parse {VALUE} tokens here, as they need to be parsed a bit differently, and so that they're checked for safe expressions
		$str = xthreads_phptpl_parse_fields($str, $fields, false);
	
	if(!empty($squotstr))
		$str = xthreads_our_str_replace($token, $squotstr, $str);
	
	if(xthreads_allow_php() || xthreads_phptpl_is_safe_expression($str))
		return $str;
	else
		return 'false';
}
```

In HHVM, this function is called and ultimately leads to a badly generated PHP script which fatals on line 47 due to a syntax error: unexpected {. The offending line:
```php
<label class=\"xtarm_label\"".(({$vars['REQUIRED']} and !{$vars['MULTIPLE']})?" style=\"display: none;\"":"")."><input type=\"checkbox\" class=\"xtarm\" name=\"xtarm_{$vars['KEY']}".(({$vars['MULTIPLE']})?"[{$vars['ATTACH']['aid']}]":"")."\"".((!{$vars['MULTIPLE']})?" data=\"xtarow_{$vars['KEY']}\"":"")." value=\"1\"{$vars['REMOVE_CHECKED']} />".(({$vars['REQUIRED']} and !{$vars['MULTIPLE']})?"{$GLOBALS['lang']->xthreads_replaceattach}":"{$GLOBALS['lang']->xthreads_rmattach}")."</label>
```

In PHP-FPM 5.5.9-1ubuntu4, the PHP script is generated correctly:
```php
<label class=\"xtarm_label\"".((("".$vars['REQUIRED']."") and !("".$vars['MULTIPLE'].""))?" style=\"display: none;\"":"")."><input type=\"checkbox\" class=\"xtarm\" name=\"xtarm_{$vars['KEY']}".((("".$vars['MULTIPLE'].""))?"[{$vars['ATTACH']['aid']}]":"")."\"".((!("".$vars['MULTIPLE'].""))?" data=\"xtarow_{$vars['KEY']}\"":"")." value=\"1\"{$vars['REMOVE_CHECKED']} />".((("".$vars['REQUIRED']."") and !("".$vars['MULTIPLE'].""))?"{$GLOBALS['lang']->xthreads_replaceattach}":"{$GLOBALS['lang']->xthreads_rmattach}")."</label>
```

The issue could only be reproduced on PHP-FPM by forcing the $in_string variable to be true in the xthreads_phptpl_parse_fields function:
```php
function xthreads_phptpl_parse_fields($s, $fields, $in_string) {
	if(!empty($fields)) {
		$tr = $ptr = array();
		$do_value_repl = false;
		foreach($fields as $f => $r) {
			if(isset($r)) {
				$tr['{'.$f.'}'] = ($in_string ? $r : '("'.$r.'")');
			} else {
				$ptr[] = '~\\{('.preg_quote($f, '~').')((?:-\>|\[)[^}]+?)?\\}~e';
			}
			if($f == 'RAWVALUE') $do_value_repl = true;
		}
		$str_start = ($in_string?'{':'("".');
		$str_end = ($in_string?'}':'."")');
		if($do_value_repl) $s = preg_replace('~\{((?:RAW)?VALUE)\\\\?\$(\d+)\}~', $str_start.'$vars[\'$1$\'][$2]'.$str_end, $s);
		if(!empty($tr))  $s = strtr($s, $tr);
		if(!empty($ptr)) $s = preg_replace($ptr, '\''.$str_start.'\\$vars[\\\'$1\\\']\'._xthreads_phptpl_expr_parse(\'$2\').\''.$str_end.'\'', $s);
		// careful with _xthreads_phptpl_expr_parse() call above - we avoid infinite looping by not supplying $fields
		// although _xthreads_phptpl_expr_parse should always be called outside string context, the above is safe because the user cannot put in a '}' character at all - that is, achieving something like {$vars['VAL'][0]}".whatever."{$var} should be impossible
		// an issue with the above, is that it's impossible to do something like {VAR[{VALUE}]} because variables are all auto-global'd... (but even if not, the above isn't guaranteed to work anyway, since the end token '}' might match early, eg {VAR[)
	}
	return $s;
}
```

**Comment by Orvid** [comment] 2016-03-21 22:34
I can't reproduce this, and it's been quite a few months since it was reported, so closing.
https://github.com/facebook/hhvm/wiki/Human-Timeouts

**Closed by Orvid** 2016-03-21 22:34 UTC
Labels: needs more info, no isolated repro
