### ISSUE TITLE
HH\Asio\curl_exec() segfault

### ISSUE THREAD

**Issue by 5lava** [facebook/hhvm#5355] opened 2015-05-15 08:53 UTC
HHVM 3.7.0.

```php
<?hh

async function main(): Awaitable <void> {
	await HH\Asio\curl_exec("https://www.baidu.com");
}

/* HH_FIXME[1002] */
main()->getWaitHandle()->join();
```

```
# 0  bt_handler at /tmp/hhvm-3.7.0/hphp/runtime/base/crash-reporter.cpp:82
# 1  folly::AsyncTimeout::scheduleTimeout(std::chrono::duration<long, std::ratio<1l, 1000l> >) at /tmp/hhvm-3.7.0/third-party/folly/folly/io/async/AsyncTimeout.cpp:85
# 2  folly::AsyncTimeout::scheduleTimeout(unsigned int) at /tmp/hhvm-3.7.0/third-party/folly/folly/io/async/AsyncTimeout.cpp:92
# 3  std::_Function_handler<void (), HPHP::CurlMultiAwait::CurlMultiAwait(HPHP::SmartPtr<HPHP::CurlMultiResource>, double)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/functional:2073
# 4  std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/functional:2472
# 5  folly::EventBase::runFunctionPtr(std::function<void ()>*) at /tmp/hhvm-3.7.0/third-party/folly/folly/io/async/EventBase.cpp:752
# 6  folly::EventBase::FunctionRunner::messageAvailable(std::pair<void (*)(void*), void*>&&) at /tmp/hhvm-3.7.0/third-party/folly/folly/io/async/EventBase.cpp:97
# 7  folly::NotificationQueue<std::pair<void (*)(void*), void*> >::Consumer::consumeMessages(bool) at /tmp/hhvm-3.7.0/third-party/folly/folly/io/async/NotificationQueue.h:660
# 8  folly::NotificationQueue<std::pair<void (*)(void*), void*> >::Consumer::handlerReady(unsigned short) at /tmp/hhvm-3.7.0/third-party/folly/folly/io/async/NotificationQueue.h:596
# 9  folly::EventHandler::libeventCallback(int, short, void*) at /tmp/hhvm-3.7.0/third-party/folly/folly/io/async/EventHandler.cpp:154
# 10 event_base_init_common_timeout at /usr/lib64/libevent-2.0.so.5:0
# 11 event_base_init_common_timeout at /usr/lib64/libevent-2.0.so.5:0
# 12 event_base_init_common_timeout at /usr/lib64/libevent-2.0.so.5:0
# 13 event_base_loop at /usr/lib64/libevent-2.0.so.5:0
# 14 folly::EventBase::loopBody(int) at /tmp/hhvm-3.7.0/third-party/folly/folly/io/async/EventBase.cpp:333
# 15 folly::EventBase::loop() at /tmp/hhvm-3.7.0/third-party/folly/folly/io/async/EventBase.cpp:285
# 16 folly::EventBase::loopForever() at /tmp/hhvm-3.7.0/third-party/folly/folly/io/async/EventBase.cpp:432
# 17 _M_run at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/thread:115
# 18 std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/libstdc++.so.6:0
# 19 start_thread at /lib64/libpthread.so.0:0
# 20 clone at /lib64/libc.so.6:0
```

It happens sometimes, not always (pay attention to time taken):
```
box ~ # time hhvm baidu-crash.php

real    0m2.066s
user    0m0.304s
sys     0m0.048s

box ~ # time hhvm baidu-crash.php
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.11929.log
Segmentation fault

real    0m4.913s
user    0m0.588s
sys     0m1.000s

box ~ # time hhvm baidu-crash.php
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.11931.log
Segmentation fault

real    0m4.305s
user    0m0.632s
sys     0m0.776s

box ~ # time hhvm baidu-crash.php
^C

real    1m9.741s
user    0m0.300s
sys     0m0.056s

box ~ # time hhvm baidu-crash.php

real    0m1.955s
user    0m0.288s
sys     0m0.056s

box ~ # time hhvm baidu-crash.php
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.11949.log
Segmentation fault

real    0m2.754s
user    0m0.620s
sys     0m0.596s

box ~ # time hhvm baidu-crash.php
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.11961.log
Segmentation fault

real    0m3.709s
user    0m0.592s
sys     0m0.732s

box ~ # time hhvm baidu-crash.php

real    0m1.799s
user    0m0.268s
sys     0m0.068s

box ~ # time hhvm baidu-crash.php
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.11965.log
Segmentation fault

real    0m3.076s
user    0m0.612s
sys     0m0.616s
```

I couldn't reproduce it with anything but https://www.baidu.com (tried multiple other http/https websites, tried to add artificial network delays, etc.)

**Comment by 5lava** [comment] 2015-05-15 15:21
I simplified the code:
```php
<?hh
HH\Asio\curl_exec("https://www.baidu.com")->getWaitHandle()->join();
```
and tried with HHVM 3.8.0-dev (heads/master-0-gc4857967e52281d73a03d8246ff50e52bd2569cb).

It's crashes rarely, but hangs instead. And sometimes it says:
```
pure virtual method called
terminate called without an active exception
```
(and hangs).

When it crashes following stacktrace is generated:
```
# 0  bt_handler at /var/tmp/portage/hhvm-nightly/hphp/runtime/base/crash-reporter.cpp:82
# 1  folly::AsyncTimeout::scheduleTimeout(std::chrono::duration<long, std::ratio<1l, 1000l> >) at /var/tmp/portage/hhvm-nightly/third-party/folly/folly/io/async/AsyncTimeout.cpp:85
# 2  folly::AsyncTimeout::scheduleTimeout(unsigned int) at /var/tmp/portage/hhvm-nightly/third-party/folly/folly/io/async/AsyncTimeout.cpp:92
# 3  std::_Function_handler<void (), HPHP::CurlMultiAwait::CurlMultiAwait(HPHP::SmartPtr<HPHP::CurlMultiResource>, double)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/functional:2073
# 4  std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/functional:2472
# 5  folly::EventBase::runFunctionPtr(std::function<void ()>*) at /var/tmp/portage/hhvm-nightly/third-party/folly/folly/io/async/EventBase.cpp:752
# 6  folly::EventBase::FunctionRunner::messageAvailable(std::pair<void (*)(void*), void*>&&) at /var/tmp/portage/hhvm-nightly/third-party/folly/folly/io/async/EventBase.cpp:97
# 7  folly::NotificationQueue<std::pair<void (*)(void*), void*> >::Consumer::consumeMessages(bool) at /var/tmp/portage/hhvm-nightly/third-party/folly/folly/io/async/NotificationQueue.h:658
# 8  folly::NotificationQueue<std::pair<void (*)(void*), void*> >::Consumer::handlerReady(unsigned short) at /var/tmp/portage/hhvm-nightly/third-party/folly/folly/io/async/NotificationQueue.h:594
# 9  folly::EventHandler::libeventCallback(int, short, void*) at /var/tmp/portage/hhvm-nightly/third-party/folly/folly/io/async/EventHandler.cpp:154
# 10 event_base_init_common_timeout at /usr/lib64/libevent-2.0.so.5:0
# 11 event_base_init_common_timeout at /usr/lib64/libevent-2.0.so.5:0
# 12 event_base_init_common_timeout at /usr/lib64/libevent-2.0.so.5:0
# 13 event_base_loop at /usr/lib64/libevent-2.0.so.5:0
# 14 folly::EventBase::loopBody(int) at /var/tmp/portage/hhvm-nightly/third-party/folly/folly/io/async/EventBase.cpp:333
# 15 folly::EventBase::loop() at /var/tmp/portage/hhvm-nightly/third-party/folly/folly/io/async/EventBase.cpp:285
# 16 folly::EventBase::loopForever() at /var/tmp/portage/hhvm-nightly/third-party/folly/folly/io/async/EventBase.cpp:432
# 17 _M_run at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/thread:115
# 18 std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/libstdc++.so.6:0
# 19 start_thread at /lib64/libpthread.so.0:0
# 20 clone at /lib64/libc.so.6:0
```

**Comment by fredemmott** [comment] 2015-07-23 17:16
3.8 issue fixed by https://github.com/facebook/hhvm/commit/3b1634257afd6b87393283c88fba2fb6a3e04d59

Unable to reproduce an issue on 3.7

**Comment by fredemmott** [comment] 2015-07-23 21:22
Can repro on master once fix for #5384 is added

**Comment by fredemmott** [comment] 2015-07-23 22:09
A curl_multi_await is captured in a lambda in https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/curl/ext_curl.cpp#L1670 - but it's not captured with a refcount, so it can be freed before the timeout event runs. Capturing the timeout object directly makes the crash rarer, but isn't a correct fix.

**Comment by fredemmott** [comment] 2015-07-23 22:19
Unreviewed fix:

```
diff --git a/hphp/runtime/ext/curl/ext_curl.cpp b/hphp/runtime/ext/curl/ext_curl.cpp
index 6c2c70b..fe791a2 100644
--- a/hphp/runtime/ext/curl/ext_curl.cpp
+++ b/hphp/runtime/ext/curl/ext_curl.cpp
@@ -1679,7 +1679,7 @@ class CurlMultiAwait : public AsioExternalThreadEvent {
     }
     if (m_timeout) {
       std::shared_ptr<CurlTimeoutHandler> to = m_timeout;
-      s_asio_event_base->runInEventBaseThread([to]{
+      s_asio_event_base->runInEventBaseThreadAndWait([to]{
         to.get()->cancelTimeout();
       });
       m_timeout.reset();
```

**Comment by fredemmott** [comment] 2015-07-23 22:25
FB: D2275238

**Closed** 2015-07-24 04:46 UTC
Labels: crash
