### ISSUE TITLE
nginx + hhvm = 502

### ISSUE THREAD

**Issue by smarcet** [facebook/hhvm#5325] opened 2015-05-11 13:22 UTC
hi everyone, i am getting from time to time
a 502 http error, restarting hhvm seems to solve the issue
i am digging on logs ( nginx and hvvm) but no seeing anything unusual

regards

**Comment by Mwesome** [comment] 2015-05-11 13:26
HHVM might be crashing, can you post the stacktrace? 
You can find it in the /tmp folder.

**Comment by smarcet** [comment] 2015-05-11 13:30
this is the last one that i got

ProcessID: 14325
ThreadID: 7f18183ff700
ThreadPID: 14357
Name: unknown program
Type: Aborted
Runtime: hhvm
Version: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
DebuggerCount: 0


# 0  gsignal at /lib/x86_64-linux-gnu/libc.so.6:0
# 1  abort at /lib/x86_64-linux-gnu/libc.so.6:0
# 2  folly::EventBase::runFunctionPtr(std::function<void ()>*) at /usr/bin/hhvm:0
# 3  folly::EventBase::FunctionRunner::messageAvailable(std::pair<void (*)(void*), void*>&&) at /usr/bin/hhvm:0
# 4  folly::NotificationQueue<std::pair<void (*)(void*), void*> >::Consumer::consumeMessages(bool) at /usr/bin/hhvm:0
# 5  event_base_loop at /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5:0
# 6  folly::EventBase::loopBody(int) at /usr/bin/hhvm:0
# 7  folly::EventBase::loopForever() at /usr/bin/hhvm:0
# 8  proxygen::WorkerThread::runLoop() at /usr/bin/hhvm:0
# 9  std::thread::_Impl<std::_Bind_simple<proxygen::WorkerThread::start()::{lambda()#1} ()> >::_M_run() at WorkerThread.cpp:0
# 10 std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) at /usr/lib/x86_64-linux-gnu/libstdc++.so.6:0
# 11 start_thread at /lib/x86_64-linux-gnu/libpthread.so.0:0
# 12 clone at /lib/x86_64-linux-gnu/libc.so.6:0

regards

**Comment by Zhao-Steven** [comment] 2015-05-17 08:48
I am also having this issue. It is crashing every hour or so. There is no sign of what causes this in the logs. Here is the stacktrace: 

```
ProcessID: 23278
ThreadID: 7fc342fff700
ThreadPID: 23319
Name: unknown program
Type: Aborted
Runtime: hhvm
Version: tags/HHVM-3.7.0-0-gc8baf9cd3cb603e030969bfe24634d5e85549915
DebuggerCount: 0

-------------------------------------IRUnit-------------------------------------
: digraph G {
B0 -> B1
B1 -> B4; B1 -> B2 [color=cyan]
B4 -> B6; B4 -> B3 [color=cyan]
B6 -> B7; B6 -> B5 [color=cyan]
B7 -> B9; B7 -> B8 [color=blue]
B9 -> B12; B9 -> B10
B12 -> B11
B10 -> B11
B11 -> B14; B11 -> B13 [color=blue]
B14 -> B19; B14 -> B15 [color=green]
B19 -> B16 [color=cyan]
B15 -> B18 [color=green]; B15 -> B17 [color=blue]
B18 -> B16 [color=cyan]
}

 B0:
Function  at 10
maxStackCells: 6
numLocals: 1
numIterators: 0
    --- bc 49, fp _, spOff 3 ()
  49: CGetM <R PT:"words" EC>
    (00) t0:FramePtr = DefFP
    (01) t1:StkPtr = DefSP<3> t0:FramePtr
    (02) Jmp -> B1
  no fallthrough

 B1: (preds B0)
    --- bc 49, fp 0, spOff 3 () [profTrans=-296632]
  49: CGetM <R PT:"words" EC>
    (05) CheckLoc<Arr,0> t0:FramePtr -> B2<Unlikely>
  -> B4

 B4: (preds B1)
    (08) CheckStk<Obj,BcSpOff 1, IrSpOff 1> t1:StkPtr -> B3<Unlikely>
  -> B6

 B6: (preds B4)
    (11) CheckStk<Str,BcSpOff 0, IrSpOff 0> t1:StkPtr -> B5<Unlikely>
  -> B7

 B7: (preds B6)
    (12) EndGuards
    (14) AssertStk<Cell,IrSpOff 1> t1:StkPtr
    (15) t6:Str = LdStk<Str,IrSpOff 0> t1:StkPtr
    (16) t7:Obj = LdStk<Obj,IrSpOff 1> t1:StkPtr
    (17) t8:PtrToMISGen = DefMIStateBase
    (20) t11:PtrToMISGen = LdMIStateAddr t8:PtrToMISGen, 16
    (21) StMem t11:PtrToMISGen, Uninit
    (23) t13:PtrToMISGen = LdMIStateAddr t8:PtrToMISGen, 32
    (24) StMem t13:PtrToMISGen, Uninit
    (36) t19:PtrToMembGen = PropX<1> t7:Obj, "words", t8:PtrToMISGen -> B8<Catch>
  -> B9

 B9: (preds B7)
    (38) CheckInitMem t11:PtrToMISGen -> B10
  -> B12

 B12: (preds B9)
    (40) t22:Gen = LdMem<Gen> t11:PtrToMISGen
    (41) StMem t13:PtrToMISGen, t22:Gen
    (42) StMem t11:PtrToMISGen, Uninit
    (43) Jmp t13:PtrToMISGen -> B11
  no fallthrough

 B10: (preds B9)
    (44) Jmp t19:PtrToMembGen -> B11
  no fallthrough

 B11: (preds B10 B12)
         t23:PtrToMembGen = phi t19:PtrToMembGen@B10, t13:PtrToMISGen@B12
    (45) t23:PtrToMembGen = DefLabel
    (56) t28:Cell = CGetElem t23:PtrToMembGen, t6:Str, t8:PtrToMISGen -> B13<Catch>
  -> B14

 B14: (preds B11)
    (57) DecRef t6:Str
    (58) DecRef t7:Obj
    (60) t30:Gen = LdMem<Gen> t11:PtrToMISGen
    (61) DecRef t30:Gen
    (63) t32:Gen = LdMem<Gen> t13:PtrToMISGen
    (64) DecRef t32:Gen
    --- bc 65, fp 0, spOff 2 () [profTrans=-296632]
  65: RetC
    (65) t33:Arr = LdLoc<Arr,0> t0:FramePtr
    (66) DecRef t33:Arr

    --- bc 65, fp 0, spOff 1 () [profTrans=-296632]
  65: RetC
    (67) CheckSurpriseFlags -> B15<Unlikely>
  -> B19

 B19: (preds B14)
    (75) Jmp -> B16
  no fallthrough

 B16: (preds B19 B18)
    (71) StRetVal t0:FramePtr, t28:Cell
    (72) t34:StkPtr = RetAdjustStk t0:FramePtr
    (73) RetCtrl<0> t34:StkPtr, t0:FramePtr
  no fallthrough

------------------------cold blocks-------------------------
 B15<Unlikely>: (preds B14)
    (70) ReturnHook t0:FramePtr, t28:Cell -> B17<Catch>
  -> B18<Unlikely>

 B18<Unlikely>: (preds B15)
    (74) Jmp -> B16
  no fallthrough

 B5<Unlikely>: (preds B6)
    --- bc 49, fp 0, spOff 3 () [profTrans=-296632]
  49: CGetM <R PT:"words" EC>
    (10) ReqRetranslate<0> t1:StkPtr
  no fallthrough

 B3<Unlikely>: (preds B4)
    (07) ReqRetranslate<0> t1:StkPtr
  no fallthrough

 B2<Unlikely>: (preds B1)
    (04) ReqRetranslate<0> t1:StkPtr
  no fallthrough

-----------------------frozen blocks------------------------
 B17<Catch>: (preds B15)
    --- bc 65, fp 0, spOff 1 () [profTrans=-296632]
  65: RetC
    (68) BeginCatch
    (69) EndCatch<IrSpOff 2> t0:FramePtr, t1:StkPtr
  no fallthrough

 B13<Catch>: (preds B11)
    --- bc 49, fp 0, spOff 3 () [profTrans=-296632]
  49: CGetM <R PT:"words" EC>
    (46) BeginCatch
    (48) t25:Gen = LdMem<Gen> t11:PtrToMISGen
    (49) DecRef t25:Gen
    (51) t27:Gen = LdMem<Gen> t13:PtrToMISGen
    (52) DecRef t27:Gen
    (53) StStk<IrSpOff 1> t1:StkPtr, t7:Obj
    (54) StStk<IrSpOff 0> t1:StkPtr, t6:Str
    (55) EndCatch<IrSpOff 0> t0:FramePtr, t1:StkPtr
  no fallthrough

 B8<Catch>: (preds B7)
    (26) BeginCatch
    (33) StStk<IrSpOff 1> t1:StkPtr, t7:Obj
    (34) StStk<IrSpOff 0> t1:StkPtr, t6:Str
    (35) EndCatch<IrSpOff 0> t0:FramePtr, t1:StkPtr
  no fallthrough

-----------------------------------RegionDesc-----------------------------------
: Region (1 blocks):
Block -296632 @49 length 2 initSpOff 3 inlineLevel 0
  predict: Local{0} :: Arr
  predict: Stack{2} :: Obj
  predict: Stack{3} :: Str
    49  CGetM <R PT:"words" EC>
    65  RetC
Arcs:
Side-exiting Blocks:


ThreadType: Web Request
Assertion Message: data block = cold
message: Attempted to emit 1 byte(s) into a 122 byte DataBlock with 0 bytes available. This almost certainly means the TC is full. If this is the case, increasing Eval.JitASize, Eval.JitAColdSize, Eval.JitAFrozenSize and Eval.JitGlobalDataSize in the configuration file when running this script or application should fix this problem.

Assertion Failure: /tmp/tmp.0gBHBiCjFb/hphp/runtime/vm/jit/translate-region.cpp:719: HPHP::jit::TranslateResult HPHP::jit::{anonymous}::mcGenRegion(HPHP::jit::IRGS&, const HPHP::jit::RegionDesc&, HPHP::jit::RegionBlacklist&): assertion `0' failed.
URL: /
Server_SERVER_NAME: forums.auroraen.com
Server: forums.auroraen.com

# 0  __GI_raise at /build/buildd/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56
# 1  __GI_abort at /build/buildd/eglibc-2.19/stdlib/abort.c:91
# 2  HPHP::assert_fail(char const*, char const*, unsigned int, char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /usr/bin/hhvm:0
# 3  HPHP::jit::translateRegion(HPHP::jit::IRGS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags, std::vector<HPHP::jit::RegionDesc::TypePred, std::allocator<HPHP::jit::RegionDesc::TypePred> >&) at /usr/bin/hhvm:0
# 4  HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 5  HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 6  HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 7  HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 8  HPHP::jit::MCGenerator::bindJmp(unsigned char*, HPHP::SrcKey, HPHP::jit::ServiceRequest, HPHP::jit::TransFlags, bool&) at /usr/bin/hhvm:0
# 9  MCGenerator_handleServiceRequest at /usr/bin/hhvm:0
# 10 handleSRHelper at /usr/bin/hhvm:0
# 11 enterTCExit at /usr/bin/hhvm:0
# 12 HPHP::jit::x64::(anonymous namespace)::BackEnd::enterTCHelper(unsigned char*, HPHP::ActRec*) at back-end-x64.cpp:0
# 13 HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) at /usr/bin/hhvm:0
# 14 HPHP::enterVM(HPHP::ActRec*, HPHP::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) at bytecode.cpp:0
# 15 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at /usr/bin/hhvm:0
# 16 HPHP::vm_call_user_func(HPHP::Variant const&, HPHP::Variant const&, bool) at /usr/bin/hhvm:0
# 17 HPHP::php_pcre_replace(HPHP::String const&, HPHP::String const&, HPHP::Variant const&, bool, int, int*) at preg.cpp:0
# 18 HPHP::php_replace_in_subject(HPHP::Variant const&, HPHP::Variant const&, HPHP::String, int, bool, int*) at preg.cpp:0
# 19 HPHP::preg_replace_impl(HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, int, HPHP::Variant&, bool, bool) at /usr/bin/hhvm:0
# 20 HPHP::f_preg_replace_callback(HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, int, HPHP::VRefParamValue const&) at /usr/bin/hhvm:0
# 21 HPHP::jit::x64::(anonymous namespace)::BackEnd::enterTCHelper(unsigned char*, HPHP::ActRec*) at back-end-x64.cpp:0
# 22 HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) at /usr/bin/hhvm:0
# 23 HPHP::enterVM(HPHP::ActRec*, HPHP::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) at bytecode.cpp:0
# 24 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at /usr/bin/hhvm:0
# 25 HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at /usr/bin/hhvm:0
# 26 HPHP::invoke_file(HPHP::String const&, bool, char const*) at builtin-functions.cpp:0
# 27 HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at /usr/bin/hhvm:0
# 28 HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at /usr/bin/hhvm:0
# 29 HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) at /usr/bin/hhvm:0
# 30 HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) at /usr/bin/hhvm:0
# 31 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) at /usr/bin/hhvm:0
# 32 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) at /usr/bin/hhvm:0
# 33 HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() at /usr/bin/hhvm:0
# 34 HPHP::AsyncFuncImpl::ThreadFunc(void*) at /usr/bin/hhvm:0
# 35 HPHP::start_routine_wrapper(void*) at /usr/bin/hhvm:0
# 36 start_thread at /build/buildd/eglibc-2.19/nptl/pthread_create.c:312
# 37 clone at /build/buildd/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:113

PHP Stacktrace:

#0  
```

**Comment by paulbiss** [comment] 2015-05-18 05:06
@Zhao-Steven: your crash looks unrelated. I think your TC has filled up try adjusting the settings mentioned in the stacktrace.

> message: Attempted to emit 1 byte(s) into a 122 byte DataBlock with 0 bytes available. This almost certainly means the TC is full. If this is the case, increasing Eval.JitASize, Eval.JitAColdSize, Eval.JitAFrozenSize and Eval.JitGlobalDataSize in the configuration file when running this script or application should fix this problem.

**Comment by alex-mashin** [comment] 2015-05-18 15:24
Check if your /tmp is full.

**Comment by Orvid** [comment] 2016-09-30 21:09
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:09 UTC
Labels: crash
