### ISSUE TITLE
problem with png manipulation's.

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#6351] opened 2015-10-09 11:10 UTC
<img width="768" alt="1421708685flagofdominica" src="https://cloud.githubusercontent.com/assets/4483325/10392335/ae3b0cd2-6e4b-11e5-8136-6959e55fcde7.png">

When uploading the above file, the top left green area of the flag is removed by following code and replaced by transparent fill, due to generic attempt to preserve the alpha layer of png's.

```php
imagesavealpha($fr, true);
$trans_colour = imagecolorallocatealpha($fr, 0, 0, 0, 127);
imagefill($fr, 0, 0, $trans_colour);
imagecopyresampled($fr,$image,0,0,0,0,$z,$z,$size,$size);
imagepng($fr,NULL,2);
```

It has happened on several images thus far, not this one. problem seems to have started occuring in 3.9.1 never saw it before now.

**Comment by r3wt** [comment] 2015-10-10 00:46
further info:

the image is read in with `imagecreatefromstring( file_get_contents( $file ) )`. also, output buffering is used to caputer output of `imagepng()`. not sure exactly where the problem occurs, but it definitely does.

**Comment by jwatzman** [comment] 2015-10-12 16:42
Does the same code work with PHP5?

**Comment by r3wt** [comment] 2015-10-22 12:51
@jwatzman never ran it on PHP. it did work on prior versions of HHVM.

**Comment by JoelMarcey** [comment] 2015-10-24 03:50
Hmmm... there have been some recent changes to `ext_gd` over the last two months, but nothing that stands out to me as what would cause your problem.

https://github.com/facebook/hhvm/commits/master/hphp/runtime/ext/gd/ext_gd.cpp

https://github.com/facebook/hhvm/commits/master/hphp/runtime/ext/gd/ext_gd.php

**Comment by Orvid** [comment] 2016-09-28 22:17
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-28 22:17 UTC
Labels: needs more info
