### ISSUE TITLE
DateTimeZone::__construct(): Unknown or bad timezone ()

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#6882] opened 2016-03-03 11:19 UTC
Only seeing this since recently upgrading to HHVM 3.12.1

<?php
session_start();

Error log:
```
DateTimeZone::__construct(): Unknown or bad timezone ()
```

On the server itself:
date
```
Thu Mar  3 11:16:58 UTC 2016
```

cat /etc/hhvm/php.ini
```
;php options
date.timezone = Europe/London
```

**Comment by craigcarnell** [comment] 2016-03-23 15:32
@Orvid What else do you need?

**Comment by Orvid** [comment] 2016-03-23 21:27
I can't seem to reproduce it with this:
https://3v4l.org/rk3jD

**Comment by wakeless** [comment] 2016-04-05 14:41
I'm seeing this, but I think it's only when there is a datetime stored in the session, the unreproducible code doesn't seem to do that.

**Comment by sckoop** [comment] 2016-04-05 15:23
We run into the same issue. After appyling @wakeless suggestion the exception where no more raised.

**Comment by GauSim** [comment] 2016-04-05 15:27
+1

**Comment by wakeless** [comment] 2016-04-06 00:48
This is a pretty serious problem for me, it's happening on 3.12.1 and I _think_ this should reproduce it.

https://3v4l.org/OBEhl

That site doesn't seem to have 3.12.1 on it so it's hard to actually narrow it down.

I'm very suspicious of this commit: bd25599468aa416a9a3203595c8fcd280c89ef83

**Comment by wakeless** [comment] 2016-04-14 02:06
Further to this, I believe this is stemming from this notice when serializing DateTime

```serialize(): "timezone" returned as member variable from __sleep() but does not exist```

**Comment by wakeless** [comment] 2016-04-20 02:19
Here's the workaround that I'm using, I'm sure it leaves the DateTime in an inconsistent state, but it definitely solves the problem for me.

We have a subclass, and I've put this in the __wakeup method

```
function __wakeup() {
  try {
    parent::__wakeup();
  } catch(Exception $e) {}
}

```

It's hacky as anything, but solves the issue.

**Comment by craigcarnell** [comment] 2016-07-20 15:14
@Orvid any updates on this?

**Comment by wakeless** [comment] 2016-07-20 15:17
IT's definitely still happening for us. I haven't really been able to nail down a limited test case, as it does seem to be rather intermittent.

**Comment by aorenste** [comment] 2016-09-28 17:08
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by aorenste** 2016-09-28 17:08 UTC
Labels: needs more info, no isolated repro

**Comment by craigcarnell** [comment] 2016-09-28 20:32
@aorenste It's still an issue..

**Comment by aorenste** [comment] 2016-09-28 22:48
@craigcarnell Any chance you have a repro case that we can test with?

**Comment by farizluqman** [comment] 2017-02-01 13:54
any update?

**Comment by alex94040** [comment] 2017-05-27 05:14
Still an issue for me as well.
