### ISSUE TITLE
HH fails ocasionally on autocomplete

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#6650] opened 2015-12-11 16:57 UTC
I don't have a strong repo code but it happens quite often for me, as I type and use the `hh_client --autocomplete` I get this text on STDERR

```
Fatal error: exception Sys_error("Broken pipe")
```
Any ideas how I can debug this further?

**Comment by steelbrain** [comment] 2015-12-11 16:57
Just something that I think **might** be related, in my autocomplete package, after writing the file contents via stdin, I close the stdin pipe, because If I don't it waits for input forever

**Comment by jwatzman** [comment] 2015-12-12 04:57
cc @int3 we've had a few reports of `Broken pipe` issues recently -- maybe due to the new monitor or something?

**Comment by steelbrain** [comment] 2015-12-12 05:20
@jwatzman another weird thing I noticed in autocomplete recently is that when you are 4-5 levels deep in braces, it does not show type of some variables, It doesn't even show `_` as their type, for example if a variable is `$User` it would show `$User ` instead of `$User _`

**Comment by oyamauchi** [comment] 2015-12-23 05:34
This is almost certainly from the same root cause as #6671

**Comment by jwatzman** [comment] 2015-12-23 05:52
Ah yeah, good call, missed that when I originally triaged this. Closing in favor of that one.

**Closed by jwatzman** 2015-12-23 05:52 UTC
Labels: hack
