### ISSUE TITLE
HHVM 3.19.1 timezone segfault

### ISSUE THREAD

**Issue by wulftone** [facebook/hhvm#7835] opened 2017-05-09 02:22 UTC
### HHVM Version
3.19.1

### Standalone code, or other way to reproduce the problem
https://github.com/wulftone/hhvm-3.19.1-timezone-segfault

### Expected result
normal `php -i` output

### Actual result
```bash
$ docker build . -t hhvm-3.19.1-timezone-segfault && docker run hhvm-3.19.1-timezone-segfault

Sending build context to Docker daemon 48.64 kB
Step 1/3 : FROM hhvm/hhvm-proxygen:3.19.1
 ---> 1918e5c7bfe9
Step 2/3 : COPY php.ini /etc/hhvm/php.ini
 ---> Using cache
 ---> 5155f8c9cc87
Step 3/3 : CMD php -i
 ---> Using cache
 ---> 19b1b0ce65fe
Successfully built 19b1b0ce65fe

set_mempolicy: Operation not permitted
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.6.log
Segmentation fault
```

**Comment by wulftone** [comment] 2017-05-09 02:25
3.18.2 works fine, both 3.19.0 and 3.19.1 segfault.

**Comment by mofarrell** [comment] 2017-05-09 18:13
I have a fix for this.  Our packages did not depend on the `tzdata` package needed by hhvm.  Almost all systems have this installed, including the base ubuntu 14.04 image used by docker.  The 16.04 image provided does not.  Expect an updated docker image by the end of the week.

**Comment by fredemmott** [comment] 2017-05-10 21:43
Dupe of #7822

**Closed by fredemmott** 2017-05-10 21:43 UTC
Labels: duplicate
