### ISSUE TITLE
Crashing in Production

### ISSUE THREAD

**Issue by DIntertech** [facebook/hhvm#6550] opened 2015-11-13 15:35 UTC
My server keeps crashing in production from an error produced in php. I keep getting this error:

    [Fri Nov 13 15:30:17 2015] [hphp] [8183:7f30571ff700:2632:000001] [] Core dumped: Aborted
    [Fri Nov 13 15:30:17 2015] [hphp] [8183:7f30571ff700:2632:000002] [] Stack trace in /tmp/stacktrace.8183.log

Digging into the stacktrace I am getting this:
PHP Stacktrace:

    #0  wp_bootstrap_navwalker->display_element(Object of class WP_Post could not be converted to string, Array, 2, 0, Array, ) called at [/data/sit$
    #1  Walker->walk(Array, 2, Object of class stdClass could not be converted to string) called at [/data/sites/wpbitm/wp-includes/nav-menu-templat$
    #2  walk_nav_menu_tree(Array, 2, Object of class stdClass could not be converted to string) called at [/data/sites/wpbitm/wp-includes/nav-menu-t$
    #3  wp_nav_menu(Object of class stdClass could not be converted to string) called at [/data/sites/wpbitm/wp-content/themes/kkpn3-theme/header.ph$
    #4  include(/data/sites/wpbitm/wp-content/themes/kkpn3-theme/header.php) called at [/data/sites/wpbitm/wp-includes/template.php:501]
    #5  load_template(/data/sites/wpbitm/wp-content/themes/kkpn3-theme/header.php, 1) called at [/data/sites/wpbitm/wp-includes/template.php:477]
    #6  locate_template(Array, 1) called at [/data/sites/wpbitm/wp-includes/general-template.php:47]
    #7  get_header() called at [/data/sites/wpbitm/wp-content/themes/kkpn3-theme/home.php:9]
    #8  include(/data/sites/wpbitm/wp-content/themes/kkpn3-theme/home.php) called at [/data/sites/wpbitm/wp-includes/template-loader.php:74]
    #9  include(/data/sites/wpbitm/wp-includes/template-loader.php) called at [/data/sites/wpbitm/wp-blog-header.php:16]
   #10 include(/data/sites/wpbitm/wp-blog-header.php) called at [/data/sites/wpbitm/index.php:17]

Does anyone have an idea of what error is causing all of HHVM to crash?

**Comment by DIntertech** [comment] 2015-11-16 17:35
Is there a way I can get more information through a dump/stack to help debug?

**Comment by wjywbs** [comment] 2015-11-17 02:05
These two comments could be useful to get a stacktrace:
https://github.com/facebook/hhvm/issues/6386#issuecomment-149035045
https://github.com/facebook/hhvm/issues/6316#issuecomment-144183928

**Comment by Orvid** [comment] 2016-03-23 00:04
Still waiting on a native stack trace for this.

**Comment by aorenste** [comment] 2016-09-27 21:42
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts

**Closed by aorenste** 2016-09-27 21:42 UTC
Labels: crash, needs more info, no isolated repro
