### ISSUE TITLE
Wrong Tax calculation on Magento

### ISSUE THREAD

**Issue by escapestring** [facebook/hhvm#7266] opened 2016-08-04 20:25 UTC
I'm running Magento 1.9.1.0 at HHVM 3.14.4

I added `hhvm.enable_zend_sorting = 1` to /etc/hhvm/php.ini file and  /etc/hhvm/server.ini, but the tax calculation is actually wrong.
![bildschirmfoto 2016-08-04 um 22 17 59](https://cloud.githubusercontent.com/assets/8549484/17417117/fc55c2b2-5a91-11e6-9fd7-1152281daa2e.png)
34,90*0,07 = 2,429 and not 2,28 like Magento show it.

Has anyone an idea how I can solve my problem?

**Comment by escapestring** [comment] 2016-08-11 08:31
Has nobody an idea? I'm really desperate

**Comment by Orvid** [comment] 2016-08-11 17:29
I don't know enough about the calculation code in Magento to know where the issue is.

**Comment by paulbiss** [comment] 2016-08-11 20:54
Hmm, the last time I saw this the problem was zend sorting, if you've already enabled that I'm not sure where else to look. It would help if you could boil it down to a small script we could execute to demonstrate the problem without needing to install magento.

**Comment by aorenste** [comment] 2016-09-29 18:30
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by aorenste** 2016-09-29 18:30 UTC
