### ISSUE TITLE
Missing notice when recursing with pcre_match_all and magic __get

### ISSUE THREAD

**Issue by mylanyuer** [facebook/hhvm#1418] opened 2013-12-22 14:48 UTC
Script as follows.
--------------------------------------------------
<?php

class MM{
    function getVar(){
        return $this;
    }
    function __get($name){
        return NULL;
    }
};

$t = new MM();
echo preg_match_all("/./", 'some', $t->getVar()->value);
echo "\n";
?>

Hhvm's version is 2.2, and I've seen https://github.com/silvermine/hhvm/commit/0b59973c71ebfed5bb90976f8b6467f835170d60, but problem remains with that.

**Comment by JoelMarcey** [comment] 2015-08-27 15:28
Closing as duplicate of #4664 and has more recent and generalized data.

**Closed by JoelMarcey** 2015-08-27 15:28 UTC
Labels: php5 incompatibility, wishlist
