### ISSUE TITLE
HHVM fails to build with -DENABLE_MCROUTER=OFF

### ISSUE THREAD

**Issue by kristapsk** [facebook/hhvm#6079] opened 2015-08-20 15:48 UTC
Current master on Gentoo.
```
$ cmake . -DENABLE_MCROUTER=OFF
-- Build type not specified: cmake build type Release.
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   system
--   program_options
--   filesystem
--   context
-- System PCRE does not have JIT enabled - will use hhvm-third-party/pcre
-- Found libevent: /usr/lib64/libevent.so
-- Using third-party bundled libsqlite3
-- Found DOUBLE_CONVERSION: /usr/lib64/libdouble-conversion.so  
-- Found double-conversion: /usr/lib64/libdouble-conversion.so
-- Found LZ4: /usr/lib64/liblz4.so  
-- Found LZ4: /usr/lib64/liblz4.so
-- Could NOT find FastLZ (missing:  FASTLZ_LIBRARY FASTLZ_INCLUDE_DIR) 
-- Using third-party bundled fastlz
-- Found LIBZIP: /usr/lib64/libzip.so  
-- Found libzip: /usr/lib64/libzip.so 1.0.1
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib64/libicuuc.so
-- Found jemalloc: /usr/lib64/libjemalloc.so
-- Found Intel TBB
-- Found LibDwarf: TRUE  
-- Looking for dwarf_producer_init
-- Looking for dwarf_producer_init - found
-- Performing Test DW_CONST
-- Performing Test DW_CONST - Failed
-- Looking for dwarf_producer_init_c
-- Looking for dwarf_producer_init_c - found
-- Performing Test DW_CONST
-- Performing Test DW_CONST - Failed
-- libdwarf uses char* type
-- libdwarf has dwarf_producer_init_c
Generating Release build
-- Did not find system RE2
-- Building RE2 from third-party
-- Performing Test FOLLY_FUNCTEXCEPT
-- Performing Test FOLLY_FUNCTEXCEPT - Success
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   system
--   program_options
--   filesystem
--   regex
--   context
CMake Error at third-party/wangle/CMakeLists.txt:41 (list):
  list sub-command REMOVE_ITEM requires list to be present.


You have called ADD_LIBRARY for library wangle without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   system
--   thread
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   thread
--   system
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   thread
--   system
-- Found libevent: /usr/lib64/libevent.so
-- Found libevent 2.0.9+
-- Found Readline: /usr/include
-- 
-- 
-- PCRE configuration summary:
-- 
--   C compiler ...................... : /usr/bin/cc
--   C++ compiler .................... : /usr/bin/c++
--   C compiler flags ................ :   -ftrack-macro-expansion=0 -fno-builtin-memcmp -w -O3 -DNDEBUG
--   C++ compiler flags .............. :  -Wall -std=gnu++11 -ffunction-sections -fdata-sections -fno-gcse -fno-omit-frame-pointer -Woverloaded-virtual -Wno-deprecated -Wno-strict-aliasing -Wno-write-strings -Wno-invalid-offsetof -fno-operator-names -Wno-error=array-bounds -Wno-error=switch -Werror=format-security -Wno-unused-result -Wno-sign-compare -Wno-attributes -Wno-maybe-uninitialized -Wno-unused-local-typedefs -fno-canonical-system-headers -Wno-deprecated-declarations -Wno-unused-function  -ftrack-macro-expansion=0 -fno-builtin-memcmp -mcrc32 -O3 -DNDEBUG -fno-gcse -momit-leaf-frame-pointer --param max-inline-insns-auto=100 --param early-inlining-insns=200 --param max-early-inliner-iterations=50
-- 
--   Build 8 bit PCRE library ........ : ON
--   Build 16 bit PCRE library ....... : OFF
--   Build 32 bit PCRE library ....... : OFF
--   Build C++ library ............... : ON
--   Enable JIT compiling support .... : ON
--   Enable UTF support .............. : ON
--   Unicode properties .............. : ON
--   Newline char/sequence ........... : LF
--   \R matches only ANYCRLF ......... : OFF
--   EBCDIC coding ................... : OFF
--   EBCDIC coding with NL=0x25 ...... : OFF
--   Rebuild char tables ............. : OFF
--   No stack recursion .............. : OFF
--   POSIX mem threshold ............. : 10
--   Internal link size .............. : 2
--   Parentheses nest limit .......... : 250
--   Match limit ..................... : 10000000
--   Match limit recursion ........... : MATCH_LIMIT
--   Build shared libs ............... : OFF
--   Build static libs ............... : ON
--   Build pcregrep .................. : ON
--   Enable JIT in pcregrep .......... : ON
--   Buffer size for pcregrep ........ : 20480
--   Build tests (implies pcretest  .. : ON
--                and pcregrep)
--   Link pcregrep with libz ......... : ON
--   Link pcregrep with libbz2 ....... : ON
--   Link pcretest with libeditline .. : OFF
--   Link pcretest with libreadline .. : ON
--   Support Valgrind .................: OFF
--   Support coverage .................: OFF
-- 
-- Build type not specified: cmake build type Release.
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   system
--   program_options
--   filesystem
--   context
-- System PCRE does not have JIT enabled - will use hhvm-third-party/pcre
-- Found libevent: /usr/lib64/libevent.so
-- Using third-party bundled libsqlite3
-- Found double-conversion: /usr/lib64/libdouble-conversion.so
-- Found LZ4: /usr/lib64/liblz4.so
-- Could NOT find FastLZ (missing:  FASTLZ_LIBRARY FASTLZ_INCLUDE_DIR) 
-- Using third-party bundled fastlz
-- Found libzip: /usr/lib64/libzip.so 1.0.1
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib64/libicuuc.so
-- Found jemalloc: /usr/lib64/libjemalloc.so
-- Found Intel TBB
-- Looking for dwarf_producer_init
-- Looking for dwarf_producer_init - found
-- Performing Test DW_CONST
-- Performing Test DW_CONST - Failed
-- Looking for dwarf_producer_init_c
-- Looking for dwarf_producer_init_c - found
-- Performing Test DW_CONST
-- Performing Test DW_CONST - Failed
-- libdwarf uses char* type
-- libdwarf has dwarf_producer_init_c
Generating Release build
-- Found ocamlc: /usr/bin/ocamlc
-- Found ocamlc.opt: /usr/bin/ocamlc.opt
-- Using built-in JSON parser
-- Could NOT find LibVPX (missing:  LIBVPX_LIBRARIES LIBVPX_INCLUDE_DIRS) 
-- Building the wddx extension.
-- Building the memcached extension.
-- Building the thread extension.
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib64/libicuuc.so
-- Building the icu extension.
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib64/libicuuc.so
-- Building the datetime extension.
-- Building the objprof extension.
-- Building the hh extension.
-- Building the DOMDocument extension.
-- Building the openssl extension.
-- Building the zlib extension.
-- Building the pdo extension.
-- Building the pdo_mysql extension.
-- Building the pdo_sqlite extension.
-- Building the apc extension.
-- Building the soap extension.
-- Building the xhprof extension.
-- Building the iconv extension.
-- Building the enum extension.
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib64/libicuuc.so
-- Building the fb extension.
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib64/libicuuc.so
-- Building the xenon extension.
-- Building the bz2 extension.
-- Building the intervaltimer extension.
-- Building the simplexml extension.
-- Building the filter extension.
-- Building the memcache extension.
-- Building the xml extension.
-- Building the curl extension.
-- Could NOT find LibUODBC (missing:  LIBUODBC_LIBRARIES LIBUODBC_INCLUDE_DIRS) 
-- The odbc extension was disabled because resolving the dependency 'libUODBC' failed.
Not building the odbc extension.
-- Building the pcre extension.
-- Building the session extension.
-- Building the fileinfo extension.
-- Building the thrift extension.
-- Building the xmlwriter extension.
-- Building the reflection extension.
-- Building the ldap extension.
-- Building the zip extension.
-- Building the server extension.
-- Building the stream extension.
-- Building the Async MySQL extension.
-- Building the mailparse extension.
CMake Error at CMake/HHVMExtensionConfig.cmake:529 (message):
  The mcrouter extension was forcefully enabled, but resolving the dependency
  'varENABLE_MCROUTER' failed!
Call Stack (most recent call first):
  CMake/HHVMExtensionConfig.cmake:481 (HHVM_EXTENSION_INTERNAL_SET_FAILED_DEPENDENCY)
  CMake/HHVMExtensionConfig.cmake:343 (HHVM_EXTENSION_INTERNAL_RESOLVE_DEPENDENCIES_OF_EXTENSION)
  hphp/runtime/ext/CMakeLists.txt:41 (HHVM_EXTENSION_RESOLVE_DEPENDENCIES)


-- Configuring incomplete, errors occurred!
```

**Comment by Orvid** [comment] 2015-08-20 19:27
Add `ENABLE_EXTENSION_MCROUTER=OFF`. This is part of an issue caused by one of the changes made to my extension config mechanism before it was merged.  #5897 should solve this issue.

**Comment by kristapsk** [comment] 2015-08-21 10:48
Is there a reason to keep `ENABLE_MCROUTER` in addition to `ENABLE_EXTENSION_MCROUTER`?

**Comment by Orvid** [comment] 2015-08-21 19:03
Unless it enables more than just ext_mcrouter, no.

**Comment by Orvid** [comment] 2016-03-21 22:01
Fixed.

**Closed by Orvid** 2016-03-21 22:01 UTC
