### ISSUE TITLE
AsyncMysqlConnectionPool error with connect (mysql error: 1041) with some behavior

### ISSUE THREAD

**Issue by Arilas** [facebook/hhvm#5143] opened 2015-04-07 20:59 UTC
I've have the following benchmark code that works fine: http://pastebin.com/aGCU2dci

But when I've try to create some sort of Abstraction:
```php
<?hh //strict

namespace Krona\PPA\Connection\MySQL;

use AsyncMysqlConnection;
use AsyncMysqlConnectionPool;
use Krona\PPA\Configuration\ConnectionConfiguration;

class PoolManager
{
    protected ConnectionConfiguration $configuration;
    protected AsyncMysqlConnectionPool $pool;

    public function __construct(ConnectionConfiguration $configuration)
    {
        $this->configuration = $configuration;
        $this->pool = new AsyncMysqlConnectionPool([]);
    }

    public async function getConnection(bool $reusable = false):Awaitable<AsyncMysqlConnection>
    {
        $connection = await $this->pool->connect(
            $this->configuration->getHost(),
            $this->configuration->getPort(),
            $this->configuration->getDbname(),
            $this->configuration->getUsername(),
            $this->configuration->getPassword(),
        );

        if (!$reusable) {
            $connection->setReusable(false);
        }

        return $connection;
    }
}

```
And use in following way:
```php
<?hh //partial

$start = microtime(true);
require "vendor/autoload.php";

$configuration = new \Krona\PPA\Configuration\ConnectionConfiguration(
    '127.0.0.1',
    'orm-test',
    'root',
    'freeware'
);

$poolManager = new \Krona\PPA\Connection\MySQL\PoolManager($configuration);
$queries = Vector {};
for ($i = 0; $i < 100; $i++) {
    $connection = $poolManager->getConnection()->join();
    $queries->add($connection->queryf('INSERT INTO test(test) VALUES (%s)', 'Test'));
}


foreach($queries as $result) {
    echo($result->join()->lastInsertId()) . PHP_EOL;
    $end = microtime(true);
}

echo PHP_EOL . ($end - $start) . PHP_EOL;
```
I've receive the following error:
```
Fatal error: Uncaught exception 'AsyncMysqlConnectException' with message 'Error executing AsyncMysql operation: TimedOut (mysql error: 1041: connection to 127.0.0.1:3306 timed out in pool(open 0, opening 0) (took 999.41ms))' in :
```
I've use:
HHVM: 3.6.1
MariaDB: 10.0.16
Linux: 3.19.0-10-generic

I've think that something wrong with ConnectionPool, or need some explanation of this behavior

**Comment by fredemmott** [comment] 2015-04-13 20:11
cc @drilibo

What's the stack for that error?

**Comment by fredemmott** [comment] 2015-04-13 20:14
Also, given this is a 'benchmark': keep in mind that calling join() on each query or connection is not going to give you good results.

**Comment by Arilas** [comment] 2015-04-14 10:32
I've added simple test for reproduce error: [ConnectionPoolTest.hh](https://github.com/Kr0na/hpa/blob/feature/native-pool/test/Connection/ConnectionPoolTest.hh)
with following PoolManager: [ConnectionPool.hh](https://github.com/Kr0na/hpa/blob/feature/native-pool/src/Connection/MySQL/ConnectionPool.hh)
Current Stack Trace display nothing:
```
Message: Error executing AsyncMysql operation: TimedOut (mysql error: 1041: connection to localhost:3306 timed out in pool(open 0, opening 0) (took 999.35ms)). Code: 0
Stack Trace:
array(2) {
  [0]=>
  array(6) {
    ["file"]=>
    string(50) ".../hpa/test/TestTrait.hh"
    ["line"]=>
    int(39)
    ["function"]=>
    string(4) "join"
    ["class"]=>
    string(13) "HH\WaitHandle"
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(0) {
    }
  }
  [1]=>
  array(6) {
    ["file"]=>
    string(50) ".../hpa/test/Bootstrap.hh"
    ["line"]=>
    int(11)
    ["function"]=>
    string(3) "run"
    ["class"]=>
    string(43) "Krona\HPATest\Connection\ConnectionPoolTest"
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(0) {
    }
  }
}
```

P.S. for test change configuration inside [ConfigurationManager.hh](https://github.com/Kr0na/hpa/blob/feature/native-pool/test/Configuration/ConfigurationManager.hh)

**Comment by fredemmott** [comment] 2015-04-14 15:45
Where's TestTrait? Please provide a self-contained example, preferably single-script. You don't appear to have provided either of the files the stacktrace points at.

**Comment by Arilas** [comment] 2015-04-14 17:10
This is the most simple version:
```php
<?hh

class ConnectionPool {
    protected AsyncMysqlConnectionPool $pool;

    public function __construct() {
        $this->pool = new AsyncMysqlConnectionPool([]);
    }

    public async function getConnection():Awaitable<AsyncMysqlConnection> {
        return await $this->pool->connect(
            'localhost',
            '3306',
            'test',//dbname
            'root',//user
            'freware'//password
        );
    }
}

$pool = new ConnectionPool();

$pool->getConnection()->join();
```
Output:
```
Fatal error: Uncaught exception 'AsyncMysqlConnectException' with message 'Error executing AsyncMysql operation: TimedOut (mysql error: 1041: connection to localhost:3306 timed out in pool(open 0, opening 0) (took 999.36ms))' in :
Stack trace:
#0 AsyncMysqlConnectionPoolError.hh(23): HH\WaitHandle->join()
#1 {main}
```

**Comment by fredemmott** [comment] 2015-04-14 17:27
Using the pool fails for me, even without the abstraction, but AsyncMysqlClient::connect does work.

**Comment by fredemmott** [comment] 2015-04-14 17:50
I can't see the cause. Talking to Squangle now.

**Comment by Arilas** [comment] 2015-05-11 12:10
Any updates?

**Comment by fredemmott** [comment] 2015-05-11 16:57
I'll reach out to them again, sorry for the delay

**Comment by fredemmott** [comment] 2015-05-11 19:23
@drilibo found the fix - https://gist.github.com/fredemmott/51898340e7e880ac2bf8

Will hopefully get this committed and synced shortly

**Comment by fredemmott** [comment] 2015-05-11 20:17
FB: D2061657

**Closed** 2015-05-13 20:11 UTC

**Comment by fredemmott** [comment] 2015-05-13 21:11
Going to merge this into 3.6
