### ISSUE TITLE
fb_get_code_coverage doesn't return else line as executed

### ISSUE THREAD

**Issue by slashmili** [facebook/hhvm#4922] opened 2015-03-01 07:27 UTC
Hey!

I'm trying to use fb_get_code_coverage to get coverage report of my code:

```php
<?php
fb_enable_code_coverage();

function foo($bar) {
    if ($bar == 5) {
        echo 'bar is 5';
    } else {
        echo 'bar is not 5';
    }
}

foo(6);

$codeCoverage = fb_get_code_coverage(true);
var_dump($codeCoverage);
```

The output is 
```
array(1) {
  ["/tmp/1.php"]=>
  array(6) {
    [2]=>
    int(1)
    [5]=>
    int(1)
    [8]=>
    int(1)
    [10]=>
    int(1)
    [12]=>
    int(2)
    [14]=>
    int(1)
  }
}
```
As you can see in the output line 7 which is the `else` line is not reported as executed.

**Comment by Orvid** [comment] 2016-03-21 23:25
Line 8 is marked as executed, so this is working as intended.

**Closed by Orvid** 2016-03-21 23:25 UTC

**Comment by slashmili** [comment] 2016-03-22 01:43
Ok! It's totally weird and unexpected intention though.

**Comment by Orvid** [comment] 2016-03-22 02:09
Line 8 is the body of the else statement, the else part, on line 7, has no executable code, so there's nothing to mark.

**Comment by SiebelsTim** [comment] 2016-03-22 12:19
@Orvid Line 10 doesn't have executable code either...

**Comment by Orvid** [comment] 2016-03-23 00:08
It does; There's an implicit `return` there.

**Comment by SiebelsTim** [comment] 2016-03-23 08:25
Okay, you got me.
