### ISSUE TITLE
upstream prematurely closed connection while reading response header from upstream

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#5063] opened 2015-03-23 15:28 UTC
Under load, I am getting the following from my nginx error logs. I am using gatling to simulate 4000 concurrent users hitting a login page.

In general the page is timing out, and I am seeing the following error message in nginx:

nginx error log:
```
2015/03/23 15:20:03 [error] 26583#0: *230 upstream prematurely closed connection while reading response header from upstream, client: 54.195.242.14, server: xx.co.uk, request: "GET /turpentine/esi/getBlock/method/esi/access/private/ttl/14400/hmac/b82c3c1b61237523a747f499410e168f6b742fb038dc7b7963412579e54cd9d7/data/fEXCPLs0mXLMM6KsT-LmLKuRVbKPWjgFpmizQHw3DMa7Gbad2yNZKSU-aUCjoIoD6mW0CWEhqI5IUaVEQpQCVXfkJWDxngr41qzGK7ivhjiAo9B6Zp4OkP9uL5bEtZo-qhYsAxuuQagg559rSIUGas0BWyFY48KVDriYuCaRb75UhAyQbQoWYnBzFg1Fhnhuv8lSfpIyVUql9z8GrPaP6x5QDYun3csmsRdX0NpWMvrLXSLTfeXIgLFZtkv-LlWN3YX1f5.ED.2sQEAXsOpGsZzPmLZRteeBMy8bd0L1xFrjQSO.0D4M1ab24D5pC3VBlL48srSfCJiqx-.lE4nrm0BD2VPC9LbkQdL3uTruyA6MnZVMYKC2OIAwdqq7r6iw/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/hhvm/hhvm.sock:", host: "www.xx.co.uk"
```

nginx.conf
```
user www-data;
worker_processes 32;
worker_rlimit_nofile 100000;

pid        /var/run/nginx.pid;
error_log  /var/log/nginx/error.log;


events {
  worker_connections 8000;
    multi_accept on;
    use epoll;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  access_log  off;

  sendfile    on;
  tcp_nopush on;

  # Add Support for Real IPs if Varnish is Enabled
  
  set_real_ip_from 127.0.0.1;
  real_ip_header X-Cluster-Client-Ip;
  
  
  server_tokens off;

  types_hash_max_size 2048;
  types_hash_bucket_size 512;

  server_names_hash_bucket_size 72;
  server_names_hash_max_size 512;

  keepalive_timeout 15;
  tcp_nodelay on;
  
  gzip         on;
  gzip_disable "MSIE [1-6]\.(?!.*SV1)";
  gzip_types   text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript;


  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/sites-enabled/*;
}
```

proxy.conf
```
proxy_temp_path         /var/nginx/proxy_temp;
client_body_temp_path   /var/nginx/client_body_temp;
proxy_redirect          off;
client_max_body_size    10m;
client_body_buffer_size 128k;
proxy_connect_timeout   300;
proxy_send_timeout      90;
proxy_read_timeout      300;
proxy_buffers           32 4k;
proxy_buffer_size       8k;
proxy_set_header        Host $host;
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_headers_hash_bucket_size 64;
```

fastcgi.conf
```
fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;
```

fastcgi_params
```
fastcgi_param	QUERY_STRING		$query_string;
fastcgi_param	REQUEST_METHOD	  	$request_method;
fastcgi_param	CONTENT_TYPE		$content_type;
fastcgi_param	CONTENT_LENGTH	  	$content_length;

fastcgi_param	SCRIPT_FILENAME	  	$request_filename;
fastcgi_param	SCRIPT_NAME		    $fastcgi_script_name;
fastcgi_param	REQUEST_URI		    $request_uri;
fastcgi_param	DOCUMENT_URI		$document_uri;
fastcgi_param	DOCUMENT_ROOT		$document_root;
fastcgi_param	SERVER_PROTOCOL	  	$server_protocol;

fastcgi_param	GATEWAY_INTERFACE	CGI/1.1;
fastcgi_param	SERVER_SOFTWARE		nginx/$nginx_version;

fastcgi_param	REMOTE_ADDR		    $remote_addr;
fastcgi_param	REMOTE_PORT		    $remote_port;
fastcgi_param	SERVER_ADDR		    $server_addr;
fastcgi_param	SERVER_PORT		    $server_port;
fastcgi_param	SERVER_NAME		    $server_name;

fastcgi_param	HTTPS			    $https;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param	REDIRECT_STATUS		200;

# Increase number of fastcgi_buffers
fastcgi_buffer_size 128k;
fastcgi_buffers 256 16k; # 4096k total
fastcgi_busy_buffers_size 256k;
fastcgi_temp_file_write_size 256k;
            
# Disable buffering to disk if replies exceed fastcgi buffer size
```

/etc/hhvm/php.ini
```
;php options

date.timezone = Europe/London


;additional options
	max_execution_time=120
```

/etc/hhvm/server.ini
```
; php options
pid = /var/run/hhvm/hhvm.pid

; hhvm specific
hhvm.server.port = 9000
hhvm.server.file_socket= /var/run/hhvm/hhvm.sock
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php

; logging settings
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.log.header = true
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191

hhvm.mysql.typed_results = false
hhvm.repo.central.path = /tmp/.hhvm.hhbc
hhvm.server.source_root = /var/www/html

; php compatibility
hhvm.server.allow_duplicate_cookies = 0
hhvm.enable_obj_destruct_call = 1
hhvm.enable_zend_sorting = 1

; logging
hhvm.log.admin_log.file = /var/log/hhvm/admin.log

; admin server

hhvm.admin_server.password = xyz

hhvm.admin_server.port = 8088
hhvm.admin_server.thread_count = 1

; required for magento2
hhvm.libxml.ext_entity_whitelist = "file"

; apc
hhvm.server.apc.enable_apc = true

; jit
hhvm.jit = true
hhvm.jit_warmup_requests = 5

; debugger
hhvm.debugger.enable_debugger = false
hhvm.debugger.enable_debugger_server = false
hhvm.debugger.port = 8089
hhvm.debugger.default_sandbox_path = /var/www/html

	hhvm.jit_a_cold_size=201326592
	hhvm.jit_a_frozen_size=201326592
	hhvm.jit_a_size=201326592
	hhvm.jit_global_data_size=201326592
	hhvm.mysql.connect_timeout=6000
	hhvm.server.connection_timeout_seconds=120
	hhvm.server.implicit_flush=1
	hhvm.server.request_timeout_seconds=120
	hhvm.server.thread_count=10000
```

Any ideas on how to get HHVM to deal with so many requests?

My stack is a Cloud Load Balancer -> each host is a 30 core CPU with 120gb RAM (8 machines) running Varnish, nginx, hhvm 3.7.0-dev connected to a local redis cache instance 2.8.19, a shared redis session instance, a dedicated mysql server running Percona.

CPU usage on the Percona instance is about 6%. It's configured for upto 10000 users.

CPU usage on the server running hhvm seems quite high.

/etc/sysctl.conf
```
net.ipv4.conf.eth0.arp_notify=1
vm.swappiness=0
net.ipv4.tcp_max_syn_backlog=12000
vm.overcommit_memory=1
net.netfilter.nf_conntrack_max=131072
net.core.netdev_max_backlog=400000
net.core.somaxconn=65535
net.ipv4.ip_local_port_range=1024	65535
```

ulimit -a
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 966734
max locked memory       (kbytes, -l) 82000
max memory size         (kbytes, -m) unlimited
open files                      (-n) 131072
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 966734
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

kernel - Ubuntu 14.04 LTS
```
3.13.0-46-generic
```

**Comment by craigcarnell** [comment] 2015-03-23 16:46
If I repeat the same test using php5-fpm, the test completes just fine and I am able to still browse the site while the test is running. If it's HHVM, I am not able to do this. So how or why is my HHVM badly configured?

**Comment by craigcarnell** [comment] 2015-03-31 08:46
How do I configure HHVM to deal with a lot of load!

```
*11696 upstream prematurely closed connection while reading response header from upstream
```

**Comment by hieuvo** [comment] 2015-04-28 20:17
just restart php-fpm, it worked for me!

**Comment by craigcarnell** [comment] 2015-04-29 08:46
@hieuvo Except a) it's not php-fpm, it's hhvm b) restarting a running service isn't really a good idea

**Comment by paulbiss** [comment] 2015-04-29 19:22
Hmm, if you can attach gdb to your server and dump backtraces of all the active threads it may give you some indication as to where they're stuck.

Best guess, they're stalling inside an extension (the connection/execution limits aren't always checked when running extension code), you might try lowering the connection time limit for mysql, but to know for sure where things are getting stuck attaching gdb is probably the way to go.

**Comment by 5outh** [comment] 2016-03-08 20:37
@craigcarnell Were you ever able to fix this? I am experiencing the same issue with the same setup.

**Comment by paulocoghi** [comment] 2016-05-25 15:02
Same issue here under high load

**Comment by Bogdaan** [comment] 2016-06-11 12:57
Same issues :( without high load

**Comment by yhl3692319** [comment] 2016-06-16 11:16
our web-site met same issues without high load

https://gitlab.com/gitlab-org/gitlab-ce/issues/18643

**Comment by Orvid** [comment] 2016-06-16 19:21
@yhl3692319 What does your setup with HHVM look like? Gitlab doesn't normally use HHVM, as it's mostly ruby.

**Comment by Orvid** [comment] 2016-09-30 21:27
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:27 UTC
