### ISSUE TITLE
hhvm 3.21.1 Use of the word 'Type' in namespace causes runtime error

### ISSUE THREAD

**Issue by jsonfry** [facebook/hhvm#8005] opened 2017-09-21 10:38 UTC
### HHVM Version
HipHop VM 3.21.1 (rel)
Compiler: tags/HHVM-3.21.1-0-gc8603b5a88feea9f5f2fc99d2c7d051d878ccc75
Repo schema: afcd80435695be5c36f9204c827b13a583504338

### Standalone code, or other way to reproduce the problem
https://github.com/jsonfry/hhvm-type-bug

That repo has two docker-compose files that run some sample code in hhvm 3.21.0 and 3.21.1

It's using this docker image: https://hub.docker.com/r/ocasta/nginx-hhvm-wp/
Which has this conf: https://github.com/ocastastudios/docker-nginx-hhvm-wp/tree/master/conf/hhvm

### Expected result
Sample code runs and says hello

### Actual result
`Fatal error: Uncaught Error: syntax error, unexpected T_TYPE, expecting '[' or '{' in /src/main.php:8`

### Other notes
I can't seem to find any release notes, tags etc related to hhvm 3.21.1, I only see it in the apt repo e.g. http://dl.hhvm.com/ubuntu/dists/xenial/main/

**Comment by fredemmott** [comment] 2017-09-21 18:51
So, Type is a semi-reserved word. Not saying 'wontfix' for sure, but it's definitely a strong possibility - especially given the introduction of `use type \Foo\bar;` in 3.21. It would also likely be impossible for us to make this *fully* work in a consistent manner, eg `use Foo\Type;`, `use type Foo\Type;` followed by `const type Foo = shape();`

**Comment by jsonfry** [comment] 2017-09-21 19:01
Oh.

Shame that happened in a patch release. Should I raise a separate issue for the typechecker not picking this up as an error?

**Comment by fredemmott** [comment] 2017-09-21 19:02
Ah, sorry, this was an issue in 3.21.1, but not 3.21.0?

**Comment by jsonfry** [comment] 2017-09-21 19:06
Correct, the use of Type worked fine in 3.21.0 but gives the runtime error in 3.21.1.

**Comment by fredemmott** [comment] 2017-09-21 19:10
Caused by https://github.com/hhvm/hhvm-staging/commit/f025f649645ef90d41a8b75a9ae64c326cc85629

Single-file repro:

```Hack
<?hh

namespace Example\Type {
    class Hello {
        public function __construct() {
            var_dump(__FUNCTION__);
        }
    }
}

namespace Example {
    function init() {
        new Type\Hello();
    }
    init();
}
```

**Comment by fredemmott** [comment] 2017-09-21 22:04
Thanks, we should have another 3.21.z up soon

**Comment by fredemmott** [comment] 2017-09-22 03:21
Turns out that PHPUnit does this, so we're unlikely to break it for a while once it's fixed :)

**Closed** 2017-09-22 17:54 UTC
