### ISSUE TITLE
hhvm 3.6, 3.7 - PDO fetch not working with class private members

### ISSUE THREAD

**Issue by janez89** [facebook/hhvm#5033] opened 2015-03-17 18:46 UTC
HHVM 3.6, 3.7 - PDO not fill my class private variables.

HHVM 3.5 and PHP 5.5 - worked for me in private variables.

```php
class Campaign
{
    private $id;
    private $name;
    private $allowed;
    private $created_at;

    public function init($id, $name,  $allowed = false, $created_at = null) {
         $this->id = $id;
         // ...
    }
}
```

```php
$st = $this->db->prepare('SELECT * FROM campaigns WHERE id = :id LIMIT 1');
$st->execute(['id' => $id]);

var_dump($st->fetchObject('\app\models\Campaign'));
```

Result with hhvm 3.6 and 3.7:
```
object(app\models\Campaign)#65 (4) {
  ["id":"app\models\Campaign":private]=>
  NULL
  ["name":"app\models\Campaign":private]=>
  NULL
  ["allowed":"app\models\Campaign":private]=>
  NULL
  ["created_at":"app\models\Campaign":private]=>
  NULL
}

```

Result with constructor (PHP 5.5.22):
```
class app\models\Campaign#65 (4) {
  private $id =>
  string(1) "1"
  private $name =>
  string(14) "Sample"
  private $allowed =>
  string(1) "0"
  private $created_at =>
  string(19) "2015-03-17 17:14:05"
}

```

My system informations: 
Elementary OS Luna (based on Ubuntu 12.04)

**Comment by Orvid** [comment] 2016-09-30 21:38
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:38 UTC
