### ISSUE TITLE
hhvm --modules = SIGSEV

### ISSUE THREAD

**Issue by IngwiePhoenix** [facebook/hhvm#9237] opened 2022-10-01 23:21 UTC
**Describe the bug**
```
$ hhvm --modules
fish: “hhvm --modules” terminated by signal SIGSEGV (Address boundary error)
```

Not much else to say, really. :)

**Standalone code, or other way to reproduce the problem**

1. Go to a terminal
2. run `hhvm --modules`
3. Observe

**Expected behavior**

A list of available built-in modules.

**Actual behavior**

A `SIGSEV`.

**Environment**
 - Operating system: Debian 11
 - Installation method: DEB
 - HHVM Version: 
 ```
$ hhvm --version
HipHop VM 4.169.0 (rel) (non-lowptr)
Compiler: 1663625384_767271319
Repo schema: 3085e89610edd5d4be612d9d4bb2964cb20e5ecb

$ hh_client --version
hackc-03a29dec4c8b43dde03aab1f400bf978228c82e0-4.169.0
```

**Additional context**
I observed the issue a long, long time ago and attributed it to a small bug. Well it's still here so I decided to report on it! :)

**Comment by lexidor** [comment] 2022-10-02 11:37
Hi, this issue is a duplicate of #6857. That issue also includes some gdb dumps. Would it be an idea to merge your findings into that issue instead via a reply? This also has the effect of reordering the original issue in the `Recently updated` sort order.

**Comment by IngwiePhoenix** [comment] 2022-10-02 12:25
Alright, did that. :)

Would love to see this resolved eventually... Turns out I posted about this in 2020 too, so this issue is far from new.

**Comment by lexidor** [comment] 2023-06-04 12:53
The issue is a duplicate. This issue provides little additional value to #6857. It might be better to cluster the conversation on that issue instead, since it already contains a whole lot of context.

**Closed by lexidor** 2023-06-04 12:53 UTC
Labels: crash, duplicate
