### ISSUE TITLE
SegmentationFault in xDebug implementation

### ISSUE THREAD

**Issue by Norfavrell** [facebook/hhvm#6093] opened 2015-08-22 12:09 UTC
I have encountered a SegmentationFault while debugging a remote application today. 

## Exception ##
    Program received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7fe43dbff700 (LWP 31476)]
    0x0000000001596d18 in HPHP::is_numeric_string (str=0x20200a0d3e6e6f69 <Address 0x20200a0d3e6e6f69 out of bounds>, length=538976288, 
        lval=lval@entry=0x7fe43dbfa240, dval=dval@entry=0x7fe43dbfa250, allow_errors=allow_errors@entry=0, overflow_info=overflow_info@entry=0x7fe43dbfa238)
        at /usr/src/hhvm/hphp/runtime/base/zend-functions.cpp:75
    75	  if (!length || ((unsigned char)(*str)) > '9') {

## Stacktrace ##
    #0  0x0000000001596d18 in HPHP::is_numeric_string (str=0x20200a0d3e6e6f69 <Address 0x20200a0d3e6e6f69 out of bounds>, length=538976288, 
        lval=lval@entry=0x7fe43dbfa240, dval=dval@entry=0x7fe43dbfa250, allow_errors=allow_errors@entry=0, overflow_info=overflow_info@entry=0x7fe43dbfa238)
        at /usr/src/hhvm/hphp/runtime/base/zend-functions.cpp:75
    #1  0x000000000159a7a2 in HPHP::StringData::isNumericWithVal (this=0x7fe43d015d10, lval=@0x7fe43dbfa240: 140618265240288, 
        dval=@0x7fe43dbfa250: 6.9474654033222649e-310, allow_errors=allow_errors@entry=0, overflow=overflow@entry=0x7fe43dbfa238)
        at /usr/src/hhvm/hphp/runtime/base/string-data.cpp:855
    #2  0x000000000159a974 in HPHP::StringData::numericCompare (this=this@entry=0x7fe43d015d10, v2=v2@entry=0x7fe4575a8cf0)
        at /usr/src/hhvm/hphp/runtime/base/string-data.cpp:958
    #3  0x0000000002d82f4b in HPHP::StringData::equal (this=0x7fe43d015d10, s=0x7fe4575a8cf0) at /usr/src/hhvm/hphp/runtime/base/string-data.cpp:941
    #4  0x000000000146e9f8 in equal (v2=<optimized out>, v1=<optimized out>) at /usr/src/hhvm/hphp/runtime/base/comparisons.h:440
    #5  equal (v2=..., v1=<optimized out>) at /usr/src/hhvm/hphp/runtime/base/comparisons.h:443
    #6  HPHP::String::operator!= (this=this@entry=0x7fe441feefa0, v=...) at /usr/src/hhvm/hphp/runtime/base/type-string.cpp:477
    #7  0x000000000243b483 in HPHP::XDebugHookHandler::onFileLoad (this=<optimized out>, unit=0x7fe46b781100)
        at /usr/src/hhvm/hphp/runtime/ext/xdebug/xdebug_hook_handler.cpp:516
    #8  0x00000000018baf9e in HPHP::phpDebuggerFileLoadHook (unit=unit@entry=0x7fe46b781100) at /usr/src/hhvm/hphp/runtime/vm/debugger-hook.cpp:315
    #9  0x0000000002da7ed9 in HPHP::lookupUnit (path=0x7fe4575a8c70, currentDir=currentDir@entry=0x2dddb29 "", initial_opt=initial_opt@entry=0x7fe43dbfa47d)
        at /usr/src/hhvm/hphp/runtime/base/unit-cache.cpp:463
    #10 0x000000000147a1ff in HPHP::invoke_file_impl (res=..., path=..., once=once@entry=true, currentDir=currentDir@entry=0x2dddb29 "")
        at /usr/src/hhvm/hphp/runtime/base/builtin-functions.cpp:796
    #11 0x0000000002dc1981 in HPHP::invoke_file (s=..., once=once@entry=true, currentDir=currentDir@entry=0x2dddb29 "")
        at /usr/src/hhvm/hphp/runtime/base/builtin-functions.cpp:812
    #12 0x00000000014837d4 in HPHP::include_impl_invoke (file=..., once=once@entry=true, currentDir=currentDir@entry=0x2dddb29 "")
        at /usr/src/hhvm/hphp/runtime/base/builtin-functions.cpp:823
    #13 0x00000000015b50e0 in HPHP::hphp_invoke (context=context@entry=0x7fe45759c010, cmd="/srv/www/index.php", func=func@entry=false, 
        funcParams=..., funcRet=..., reqInitFunc=..., reqInitDoc="", error=@0x7fe43dbfa70f: false, errorMsg="Internal Server Error", once=once@entry=true, 
        warmupOnly=warmupOnly@entry=false, richErrorMsg=richErrorMsg@entry=false) at /usr/src/hhvm/hphp/runtime/base/program-functions.cpp:1977
    #14 0x00000000016df09b in HPHP::HttpRequestHandler::executePHPRequest (this=this@entry=0x7fe441ed4a10, transport=transport@entry=0x7fe46c7d9c98, reqURI=..., 
        sourceRootInfo=..., cacheableDynamicContent=<optimized out>) at /usr/src/hhvm/hphp/runtime/server/http-request-handler.cpp:476
    #15 0x00000000016e151e in HPHP::HttpRequestHandler::handleRequest (this=0x7fe441ed4a10, transport=0x7fe46c7d9c98)
        at /usr/src/hhvm/hphp/runtime/server/http-request-handler.cpp:387
    #16 0x000000000173d382 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl (this=0x7fe465a5e1c0, 
        job=std::shared_ptr (count 3, weak 0) 0x7fe465b1ad48, abort=abort@entry=false) at /usr/src/hhvm/hphp/runtime/server/server-worker.h:106
    #17 0x000000000173d6cb in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob (this=<optimized out>, job=...)
        at /usr/src/hhvm/hphp/runtime/server/server-worker.h:56
    #18 0x000000000173d0e2 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start (
        this=0x7fe465a5e1c0) at /usr/src/hhvm/hphp/util/job-queue.h:463
    #19 0x0000000001737301 in HPHP::AsyncFunc<HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits> >::run_ (obj=<optimized out>)
        at /usr/src/hhvm/hphp/util/async-func.h:213
    #20 0x00000000027c1b0b in HPHP::AsyncFuncImpl::threadFuncImpl (this=this@entry=0x7fe465a99000) at /usr/src/hhvm/hphp/util/async-func.cpp:131
    #21 0x00000000027c1e59 in HPHP::AsyncFuncImpl::ThreadFunc (obj=0x7fe465a99000) at /usr/src/hhvm/hphp/util/async-func.cpp:51
    #22 0x00000000015fa4b0 in HPHP::start_routine_wrapper (arg=0x7fe465af47c0) at /usr/src/hhvm/hphp/runtime/base/thread-hooks.cpp:95
    #23 0x00007fe470dd0df5 in start_thread () from /lib64/libpthread.so.0
    #24 0x00007fe4702df1ad in clone () from /lib64/libc.so.6
    
## xDebug log ##
    <<  <?xml version="1.0" encoding="iso-8859-1"?>
    <<  <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///srv/www/index.php" language="PHP" protocol_version="1.0" appid="2328" idekey="phpstorm"><engine version=""><![CDATA[xdebug]]></engine><author><![CDATA[HHVM]]></author><url><![CDATA[http://hhvm.com/]]></url><copyright><![CDATA[Copyright (c) 2002-2013 by Derick Rethans]]></copyright></init>
    >>  feature_set -i 1 -n show_hidden -v 1
    <<  <?xml version="1.0" encoding="iso-8859-1"?>
    <<  <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="1" feature="show_hidden" success="1"></response>
    >>  feature_set -i 2 -n max_depth -v 1
    <<  <?xml version="1.0" encoding="iso-8859-1"?>
    <<  <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="2" feature="max_depth" success="1"></response>
    >>  feature_set -i 3 -n max_children -v 100
    <<  <?xml version="1.0" encoding="iso-8859-1"?>
    <<  <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="3" feature="max_children" success="1"></response>
    >>  status -i 4
    <<  <?xml version="1.0" encoding="iso-8859-1"?>
    <<  <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="status" transaction_id="4" status="starting" reason="ok"></response>
    >>  step_into -i 5
    <<  <?xml version="1.0" encoding="iso-8859-1"?>
    <<  <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" status="break" reason="ok" command="step_into" transaction_id="5"><xdebug:message lineno="26" filename="file:///srv/www/index.php"></xdebug:message></response>
    >>  breakpoint_set -i 6 -t line -f file:///srv/www/external_module/Observer.php -n 33
    >>  breakpoint_set -i 7 -t line -f file:///srv/www/external_module/Observer.php -n 26
    >>  stack_get -i 8
    <<  <?xml version="1.0" encoding="iso-8859-1"?>
    <<  <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="6" id="2" state="enabled"></response>
    <<  <?xml version="1.0" encoding="iso-8859-1"?>
    <<  <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="7" id="3" state="enabled"></response>300<?xml version="1.0" encoding="iso-8859-1"?>
    <<  <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stack_get" transaction_id="8"><stack where="{main}" level="0" type="file" filename="file:///srv/www/index.php" lineno="26"></stack></response>
    >>  run -i 9

## Details##
    HipHop VM 3.8.1 (dbg)
    Compiler: tags/HHVM-3.8.1-0-g3006bc45691762b5409fc3a510a43093968e9660
    Repo schema: 253b3802ce1bcd19e378634342fc9c245ac76c33
* The issue only occurs when breakpoints are set
* The exception does not happen for every request - it seems to occur randomly, normally every few dozen xDebug connections
* It does not seem to matter what file is being executed - I have seen this happen with bot h complex applications like Magento as well as simple 'phpinfo' scripts

**Comment by Norfavrell** [comment] 2015-08-22 15:53
Same issue seems to occur on 

    HipHop VM 3.9.1-dev (rel)
    Compiler: heads/HHVM-3.9-0-gba5f30e09198251723200828b823a4d73e5f57d8
    Repo schema: 053287dc798229a2099ba239b16792c167077df2

**Comment by Norfavrell** [comment] 2015-08-31 15:04
Is there any way to potentially use the origin [xDebug](http://xdebug.org/) extension instead of the HHVM's one?

**Comment by paulbiss** [comment] 2015-08-31 19:14
Unfortunately our extension layer isn't source compatible with PHP 5 or 7.

cc @alexmalyshev about the crash

**Comment by Orvid** [comment] 2016-09-30 19:08
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:08 UTC
