### ISSUE TITLE
HHVM crashed and stopped service with empty stacktrace file!

### ISSUE THREAD

**Issue by mohamadx** [facebook/hhvm#6386] opened 2015-10-18 14:44 UTC
Hi,

I install hhvm 3.10.0 on ubuntu 14.04 LTS with nginx as webserver
This server get 1000-2000 request per second and the hhvm was stopped after 2-3 minutes and in /tmp folder i have some stacktrace...log files. These stacktrace files are empty!
How can i find the probelm without any log files??!

**Comment by karpa13a** [comment] 2015-10-18 14:46
install -dbg package

**Comment by mohammadx2** [comment] 2015-10-18 14:52
I install -dbg package, but this package works with 3.9.1 and i think problem is on 3.10.0 !

**Comment by SiebelsTim** [comment] 2015-10-18 15:02
Yep, looks like hhvm-dbg is still on 3.9.1 (http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-amd64/Packages).

The nightly-dbg however is fresh it looks like. 


cc @jwatzman

**Comment by mohammadx2** [comment] 2015-10-18 15:08
I install 3.6.6 for getting stacktrace log.
hhvm stopped in 3.6.6 after 4 mintues with this stacktrace log:

Host: HHVM
ProcessID: 19485
ThreadID: 7fb53cbff700
ThreadPID: 19497
Name: unknown program
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.6.6-0-gead6875c956d4bd5e906ebea899c71c3b8a7182d
DebuggerCount: 0

Server: ...
ThreadType: Web Request
Server_SERVER_NAME: ...

# 0  onig_node_str_cat at /usr/lib/libonig.so.2:0
# 1  onig_scan_env_set_error_string at /usr/lib/libonig.so.2:0
# 2  onig_scan_env_set_error_string at /usr/lib/libonig.so.2:0
# 3  onig_scan_env_set_error_string at /usr/lib/libonig.so.2:0
# 4  onig_parse_make_tree at /usr/lib/libonig.so.2:0
# 5  onig_compile at /usr/lib/libonig.so.2:0
# 6  onig_new at /usr/lib/libonig.so.2:0
# 7  regcomp at /usr/lib/libonig.so.2:0
# 8  HPHP::php_split(HPHP::String const&, HPHP::String const&, int, bool) at /usr/bin/hhvm:0
# 9  HPHP::f_split(HPHP::String const&, HPHP::String const&, int) at /usr/bin/hhvm:0
# 10 HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::ActRec*) at /usr/bin/hhvm:0
# 11 HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) at /usr/bin/hhvm:0
# 12 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at /usr/bin/hhvm:0
# 13 HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at /usr/bin/hhvm:0
# 14 HPHP::invoke_file(HPHP::String const&, bool, char const*) at builtin-functions.cpp:0
# 15 HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at /usr/bin/hhvm:0
# 16 HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at /usr/bin/hhvm:0
# 17 HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) at /usr/bin/hhvm:0
# 18 HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) at /usr/bin/hhvm:0
# 19 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) at /usr/bin/hhvm:0
# 20 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) at /usr/bin/hhvm:0
# 21 HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() at /usr/bin/hhvm:0
# 22 HPHP::AsyncFuncImpl::ThreadFunc(void*) at /usr/bin/hhvm:0
# 23 HPHP::start_routine_wrapper(void*) at /usr/bin/hhvm:0
# 24 start_thread at /lib/x86_64-linux-gnu/libpthread.so.0:0
# 25 clone at /lib/x86_64-linux-gnu/libc.so.6:0

**Comment by mohammadx2** [comment] 2015-10-18 15:14
and fore more info, i running hhvm service on port (not using socket)

**Comment by jwatzman** [comment] 2015-10-18 17:52
- I haven't finished building the 3.10 debug packages, sorry, they should be up in a day or two.
- Stacktrace files being empty or mostly empty for recent versions of HHVM is unfortunately expected. You'll need to use `gdb` to get a backtrace.
- It sounds like you are able to reproduce the same issue on 3.6 and 3.10? Can you use gdb on 3.10 to verify it's the same issue?
- Do you have any info on the code causing the issue? An isolated repro case is *much* more likely to have the issue get looked at.

**Comment by mohammadx2** [comment] 2015-10-18 20:29
I find a new info
When hhvm stopped, I see this error in end of error.log file
`Failed to initialize central HHBC repository:\n  Failed to open /var/run/hhvm/hhvm.hhbc: 14 - unable to open database file\n`

**Comment by wjywbs** [comment] 2015-10-19 00:43
According to the stack trace above, this is a known issue. See #5531, #4373 and #1111.

**Comment by mohammadx2** [comment] 2015-10-19 06:24
I have an issue with `split` function in php. Replace this with `explode` and the above stacktrace log resolved. But i have new problem with `file_get_content` function!
@jwatzman 
```
Host: HHVM
ProcessID: 27348
ThreadID: 7ff83a3ff700
ThreadPID: 27358
Name: unknown program
Type: Aborted
Runtime: hhvm
Version: tags/HHVM-3.6.6-0-gead6875c956d4bd5e906ebea899c71c3b8a7182d
DebuggerCount: 0

Failed Assertion: /tmp/tmp.O0on3Ig1yk/hphp/runtime/vm/repo.cpp:576: void HPHP::Repo::initCentral(): assertion `false' failed.
false: Failed to initialize central HHBC repository:
  Failed to open /var/run/hhvm/hhvm.hhbc: 14 - unable to open database file

ThreadType: Web Request
URL: ...
Server_SERVER_NAME: ...
Server: ...

# 0  gsignal at /lib/x86_64-linux-gnu/libc.so.6:0
# 1  abort at /lib/x86_64-linux-gnu/libc.so.6:0
# 2  HPHP::assert_fail(char const*, char const*, unsigned int, char const*) at /usr/bin/hhvm:0
# 3  HPHP::Repo::initCentral() at /usr/bin/hhvm:0
# 4  HPHP::Repo::Repo() at /usr/bin/hhvm:0
# 5  HPHP::ThreadLocal<HPHP::Repo>::create() at /usr/bin/hhvm:0
# 6  HPHP::Repo::get() at /usr/bin/hhvm:0
# 7  HPHP::loadLineTable(HPHP::Unit const*) at unit.cpp:0
# 8  HPHP::Unit::getLineNumber(int) const at /usr/bin/hhvm:0
# 9  HPHP::createBacktrace(HPHP::BacktraceArgs const&) at /usr/bin/hhvm:0
# 10 HPHP::ExtendedException::ExtendedException(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /usr/bin/hhvm:0
# 11 HPHP::ExecutionContext::handleError(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool, HPHP::ExecutionContext::ErrorThrowMode, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) at /usr/bin/hhvm:0
# 12 HPHP::raise_warning(char const*, ...) at /usr/bin/hhvm:0
# 13 HPHP::FileStreamWrapper::open(HPHP::String const&, HPHP::String const&, int, HPHP::SmartPtr<HPHP::StreamContext> const&) at /usr/bin/hhvm:0
# 14 HPHP::File::Open(HPHP::String const&, HPHP::String const&, int, HPHP::SmartPtr<HPHP::StreamContext> const&) at /usr/bin/hhvm:0
# 15 HPHP::f_fopen(HPHP::String const&, HPHP::String const&, bool, HPHP::Variant const&) at /usr/bin/hhvm:0
# 16 HPHP::f_file_get_contents(HPHP::String const&, bool, HPHP::Variant const&, long, long) at /usr/bin/hhvm:0
# 17 HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::ActRec*) at /usr/bin/hhvm:0
# 18 HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) at /usr/bin/hhvm:0
# 19 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at /usr/bin/hhvm:0
# 20 HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at /usr/bin/hhvm:0
# 21 HPHP::invoke_file(HPHP::String const&, bool, char const*) at builtin-functions.cpp:0
# 22 HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at /usr/bin/hhvm:0
# 23 HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at /usr/bin/hhvm:0
# 24 HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) at /usr/bin/hhvm:0
# 25 HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) at /usr/bin/hhvm:0
# 26 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) at /usr/bin/hhvm:0
# 27 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) at /usr/bin/hhvm:0
# 28 HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() at /usr/bin/hhvm:0
# 29 HPHP::AsyncFuncImpl::ThreadFunc(void*) at /usr/bin/hhvm:0
# 30 HPHP::start_routine_wrapper(void*) at /usr/bin/hhvm:0
# 31 start_thread at /lib/x86_64-linux-gnu/libpthread.so.0:0
# 32 clone at /lib/x86_64-linux-gnu/libc.so.6:0
```

**Comment by mohammadx2** [comment] 2015-10-19 07:48
I'm using `fopen`, `fread`, `fclose` as replacement for `file_get_contents` and my problem resolved!
But i think it's a temporary fix and HHVM still problem with `file_get_contents` in high requests.
I'm waiting for your kindly response.

**Comment by jwatzman** [comment] 2015-10-19 14:59
- The onig issue is an upstream issue, as kindly linked by @wjywbs.
- The issue you're seeing now, with the repo and with `file_get_contents` (for some reason) are due to this:

`  Failed to open /var/run/hhvm/hhvm.hhbc: 14 - unable to open database file`

Can you make sure that file/directory are readable and writable by the user HHVM is running as?

**Comment by Orvid** [comment] 2016-03-21 21:50
Closing, still needs more info (https://github.com/facebook/hhvm/wiki/Human-Timeouts) - will reopen if provided.

**Closed by Orvid** 2016-03-21 21:50 UTC
Labels: crash, no isolated repro
