### ISSUE TITLE
HHVM problem on Wordpress imports

### ISSUE THREAD

**Issue by ioannisa** [facebook/hhvm#5258] opened 2015-05-06 12:31 UTC
Hello,

I have found a problem when it comes to php://filter.

More specifically.....

I am experiensing a strange problem that appears when HHVM is started (not when php-fpm is active) on a plugin in wordpress.  I have made some research and found some lines that if I modify them the problem gets fixed.

The problem is on the plugin "WP All Import" in both payed and free version.  I managed to make fix on  version 4.1.5 (thats the latest version).

The plugin takes some xml and parses it and imports posts found in that xml to wordpress.

WHEN HHVM IS ACTIVE it indicates less items than the ones that exist in the xml file.

-----------------------------
VERSIONS:

OS: Ubuntu 14.04.2
HHVM: (I have tried this with HHVM 3.6.1, and with 3.7.0)
Currently my HHVM version reports
HipHop VM 3.7.0 (rel)
Compiler: tags/HHVM-3.7.0-0-gc8baf9cd3cb603e030969bfe24634d5e85549915
Repo schema: 1988ce75e6a571ce9c79c60fd7dc3ca8a5a5d403

Nginx version is 1.8.0
Wordpress 4.2.1 (wordpress version is insignificant, occures in all versions of wordpress)

--------------------------------

WHERE I FOUND THE BROKEN CODE:
When the plugin tries to register a filter (only when hhvm is active), the indicated items are significantly less than the xml entries.

In the plugin's code, at file "chunk.php", the following code is found two times in that php file:

      if (function_exists('stream_filter_register')){
        stream_filter_register('preprocessxml', 'preprocessXml_filter');
        $path = 'php://filter/read=preprocessxml/resource=' . $this->file;   
      }
      else $path = $this->file;

If I comment out the above code and replace it with

      $path = $this->file;

the pluginreturns the correct ammount of records.

------------------------------------------------------

Is there some problem assigning $path with php://filter?  I have talked with the "WP All Import" plugin support team and they asked me to post here, since this problem is HHVM related and not php related - aka no problem in their source.

**Comment by jwatzman** [comment] 2015-05-07 23:33
This looks kind of tied up in the wordpress logic -- do you have an isolated test case that demonstrates the problem?

**Comment by ioannisa** [comment] 2015-05-08 10:48
I have a test server running this example.

http://92.222.88.93/wp-admin/
username: Admin
password: anifantakisvps

To replicate the problem follow these three steps

A)  go to "All Import" -> "New Import" -> "Download from URL"

Give any xml news feed, for example
http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml

(This example RSS feed contains 20 posts)

Then press "Continue to Step 2"... you will see less items (I see 7 on this example).

------------------------------

B) Now... to apply my fix....

Go to
"Plugins" -> "Installed Plugins"
on "Wp All Import Pro", press the "edit" option
Navigate to the file "chunk.php"

Find the following code (exists 2 times in that file)
      
      if (function_exists('stream_filter_register') and $this->options['filter']){
        stream_filter_register('preprocessxml', 'preprocessXml_filter');
        $path = 'php://filter/read=preprocessxml/resource=' . $this->file;   
      }
      else $path = $this->file;

and replace it with

      if (function_exists('stream_filter_register') and $this->options['filter']){
        stream_filter_register('preprocessxml', 'preprocessXml_filter');
        $path = $this->file;
        //$path = 'php://filter/read=preprocessxml/resource=' . $this->file;   
      }
      else $path = $this->file;

---------------------

C) Repeat Step (A) and you will see now with this fix that it indicates all 20 items correctly.  Therefore the problem relays on line

$path = 'php://filter/read=preprocessxml/resource=' . $this->file;   

And occurs only under HHVM

**Comment by ioannisa** [comment] 2015-05-17 12:51
Hi its been over a week, and I haven't heard something.  Have you managed to replicate the problem?

**Comment by paulbiss** [comment] 2015-05-18 05:04
Thanks for your patience, sorry about the delay. We're all in the midst of a performance lockdown, so our response time is going to be a bit delayed until the 25th. In this case it also looks like there's no isolated example of the problem.

Generally speaking we're not going to be able to setup something as complicated as wordpress and track down the source of a bug for every reported issue. If you can point us to code we can run in isolation (read: no more than a few hundred lines, ideally run in CLI mode, with no external dependencies or frameworks) to replicate the specific incompatibility with PHP 5 we can usually come up with a fix pretty quickly.

**Comment by cvladan** [comment] 2015-05-27 13:11
Also have the same problem.

**Comment by blueprintmrk** [comment] 2015-09-16 19:46
I hope this is helpful
https://wordpress.org/support/topic/hhvm-compatibilty?replies=12#post-7435396
Anyway, here is the workaround: in file
wp-all-import-pro/classes/chunk.php
in 2 places, make changes like this:

$path = $this->file;
// $path = 'php://filter/read=preprocessxml/resource=' . $this->file;
and in essence, completely avoid PHP Filter that is not compatible with HHVM. So far, I have no noticeable problems.

**Comment by pratham2003** [comment] 2016-01-31 12:48
Can anyone getting these errors please check their /var/log/message when it shows less records than usual?

In my case there is an error in /var/log/message (My hhvm log level is set to verbose)
hhvm: php://filter/read=preprocessxml/resource=/home/............./try_1.xml:148: parser error : internal error: detected an error in element content
hhvm: <_custom_excerpt><![CDAT[CDA
hhvm: ^

The line 147 and 148 in the XML are as follows. (This is the 2nd xml item)
                <custom_excerpt><![CDATA[]]></custom_excerpt>
                <_custom_excerpt><![CDATA[field_5555e95d54c2c]]></_custom_excerpt>


The first xml item also has similar content but it doesn't generate an error at that line.
                <custom_excerpt><![CDATA[some text here?]]></custom_excerpt>
                <_custom_excerpt><![CDATA[field_5555e95d54c2c]]></_custom_excerpt>


According to the error printed out in /var/log/messages the <![CDAT[CDA part is weird..
I opened up the xml file in a text editor and its 16090 characters up to the <![CDAT   in <![CDAT[CDA
Looks like some weird memory problem?

**Comment by Orvid** [comment] 2016-09-30 21:13
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:13 UTC
Labels: no isolated repro, php5 incompatibility
