### ISSUE TITLE
3.18.0 CLI args don't take precedence over configs

### ISSUE THREAD

**Issue by wulftone** [facebook/hhvm#7678] opened 2017-02-16 05:31 UTC
### HHVM Version
3.18.0

### Standalone code, or other way to reproduce the problem
nginx + fastcgi to hhvm 3.18.0

### Expected result
```
curl -I localhost:9000/health
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 16 Feb 2017 05:28:21 GMT
Content-Type: application/json
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: HHVM/3.18.0
Access-Control-Allow-Origin: *
Access-Control-Request-Method: *
Access-Control-Allow-Methods: OPTIONS,GET,PUT,POST,DELETE
Access-Control-Allow-Headers: *
```
### Actual result
```
curl -I localhost:9000/health
HTTP/1.1 502 Bad Gateway
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 16 Feb 2017 05:26:23 GMT
Content-Type: text/html
Content-Length: 181
Connection: keep-alive
```
Nginx log complains: 
```
2017/02/15 21:20:20 [error] 11#0: *5 upstream sent unsupported FastCGI protocol version: 72 while reading response header from upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "myhost:9000"
```
...and rightly so!  If I curl the port HHVM is supposed to be doing fastcgi on, it works fine--it makes me suspect it is really running on proxygen because it should not respond to a curl like this:
```
curl -I localhost:9002/health
HTTP/1.1 200 OK
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: OPTIONS,GET,PUT,POST,DELETE
Access-Control-Request-Method: *
Access-Control-Allow-Origin: *
Content-Type: application/json
Vary: Accept-Encoding
X-Powered-By: HHVM/3.18.0
Date: Thu, 16 Feb 2017 05:25:19 GMT
Connection: keep-alive
Content-Length: 0
```
Notice no `Server: nginx/1.4.6 (Ubuntu)` on that one.  Also if I rebuild my docker container with the only change being switching to HHVM 3.17.2 it works fine.  This is all using the docker containers from hhvm/hhvm-proxygen.

Started via something like 
```
hhvm -m server -c /app/config/server.ini -p 9002 --admin-port=9001 -d hhvm.server.type="fastcgi" -d pid="/tmp/hhvm-pid" &
```

**Comment by mofarrell** [comment] 2017-02-16 17:54
I have nginx running with fastcgi to HHVM 3.18  just fine.  You will have to provide more info about your particular configuration.  Perhaps your nginx conf files, and your hhvm ini files.
This report is not readily reproducible

**Comment by wulftone** [comment] 2017-02-17 03:20
Example here: https://github.com/wulftone/hhvm-3.18.0-fastcgi-test

Maybe an option changed or I've configured nginx slightly wrong?  Works fine on HHVM 3.17.2.  The README there should demonstrate all of it.

**Comment by Norbyte** [comment] 2017-02-17 08:38
You have this line in your HHVM config file:
`hhvm.server.type = proxygen` (at https://github.com/wulftone/hhvm-3.18.0-fastcgi-test/blob/master/config/server.ini#L26).

proxygen uses HTTP, not the FastCGI protocol. Maybe you meant `hhvm.server.type = fastcgi` ?

**Comment by mofarrell** [comment] 2017-02-17 15:17
@wulftone Like @Norbyte said you are setting up HHVM to use proxygen rather than fastcgi.  It is worth noting that we recommend using proxygen due to its improved performance.  I am closing this issue since there is not a bug in HHVM, but feel free to comment here if you still have trouble getting it working.

**Comment by wulftone** [comment] 2017-02-17 15:50
@mofarrell @Norbyte Yeah I suppose it's not a bug.  Changing that fixes it, but I didn't see this change of precedence anywhere.. So the config file overrides the CLI arguments now?  Perhaps I just missed it in a changelog.

**Comment by mofarrell** [comment] 2017-02-17 18:23
@wulftone That might be a real issue.  I think it makes sense for CLI args to take precedence.  I will try to identify what has changed.

**Closed** 2017-02-23 21:41 UTC

**Comment by mofarrell** [comment] 2017-02-23 23:26
I will have the fix cherrypicked into the next 3.18 build.

**Comment by mofarrell** [comment] 2017-02-28 18:35
3.18.1 is released, and should include the patch.

**Comment by wulftone** [comment] 2017-03-01 03:44
Looks good, thank you for fixing that!  When do you normally push the docker tag?

**Comment by aorenste** [comment] 2017-03-01 17:36
@wulftone Docker files should be available now
