### ISSUE TITLE
PHP putenv is not propagated to libc calls

### ISSUE THREAD

**Issue by cmuellner** [facebook/hhvm#7533] opened 2016-12-07 09:06 UTC
HHVM version: git HEAD

I've been analysing a failed test on HHVM (arm64 and x64) and noticed
that test/zend/good/ext/calendar/tests/easter_date.php fails, because
our machine has CET set at local timezone.

easter.php calls putenv('TZ=UTC') and afterwards easter_date(2000).
That goes into easter.cpp, which 1) calculates the date of easter of the
given year and 2) calls mktime(3) with the calculated date (and minute, hour
and second set to 0) and 3) returns the resulting time_t.

The problem is that mktime(3) creates the time_t based on local
timezone settings (i.e. evaluating the TZ variable).
However, HHVM seems to not propagate them to libc (by putenv(3)).

The result is that, easter_date(2000) returns the time
2000-04-23 CET 00:00:00, which equals 2000-04-22 UTC 23:00:00.

As easter_date.php prints the date with date("Y-m-d", ...) it prints
the wrong day ("2000-04-22" instead of "2000-04-23").

I've searched through the codebase and found the following invocations
of mktime(), which might have a similar problem:

hphp/runtime/ext/openssl/ext_openssl.cpp:  time_t ret = mktime(&thetime);
hphp/runtime/ext_zend_compat/calendar/easter.cpp:          Z_LVAL_P(return_value) = mktime(&te);
hphp/runtime/ext_zend_compat/ftp/ftp.cpp:       tm.tm_sec += stamp - mktime(gmt);
hphp/runtime/ext_zend_compat/ftp/ftp.cpp:       stamp = mktime(&tm);

I did not check for other libc calls, which might be affected as well.

**Comment by mofarrell** [comment] 2016-12-07 19:28
A nice simple example:
```
putenv("AAA='hello'");
echo shell_exec('echo $AAA');
```

This seems to be causing issues in the oss performance test with certain targets.

**Comment by jesseschalken** [comment] 2017-05-05 04:13
This is a duplicate of https://github.com/facebook/hhvm/issues/7378

**Comment by cmuellner** [comment] 2017-05-05 14:54
Thanks @jesseschalken for finding the duplicate.

I've just made an proposal for fixing this behaviour in a comment to #7378.

**Closed** 2017-05-05 17:02 UTC
Labels: php5 incompatibility, php7 incompatibility
