### ISSUE TITLE
Feature request: Support HTTP PATCH method

### ISSUE THREAD

**Issue by wulftone** [facebook/hhvm#7430] opened 2016-10-18 05:47 UTC
Looking through the code [here](https://github.com/facebook/hhvm/blob/HHVM-3.15.2/hphp/runtime/server/proxygen/proxygen-transport.cpp#L200-L204) it looks like it's purposefully returning 400 for a PATCH request.  Are there plans to support it? Can you support it?  Am I in the wrong part of town?  😸 

There's been a small amount of simmering about PATCH in HHVM for a while it seems.  Here's a [recent stackoverflow question](http://stackoverflow.com/questions/38792049/does-hhvm-proxygen-support-the-http-patch-method) asking the same thing.  The comment in the source code seems to indicate that proxygen supports it.

Please tell us!

**Comment by simnare** [comment] 2017-04-07 14:30
+1

**Comment by mofarrell** [comment] 2017-06-26 20:18
Going to close this as a duplicate of a newer issue with more info https://github.com/facebook/hhvm/issues/7892

**Closed by mofarrell** 2017-06-26 20:18 UTC
Labels: duplicate, feature request
