### ISSUE TITLE
HHVM  worker threads gradually hangs up till only 1 process running.

### ISSUE THREAD

**Issue by zoglun** [facebook/hhvm#5429] opened 2015-05-31 17:38 UTC
Basically, the HHVM worker threads starts with all CPU used (in my case 12 threads for 6 core), and will gradually hangs up till only 1 process took 100% of CPU0. (usually within 10 mins) And then the running process number will not increase. response will be very slow during this period.
![20150531123714](https://cloud.githubusercontent.com/assets/721486/7902949/cc39ac0a-0791-11e5-9d30-3cfb5ca85fcd.jpg)

The only thing in error log beside Finished singleJitRequest is
[Sun May 31 17:16:23 2015] [hphp] [23300:7fe92dbff700:1206:000001] [] \nFatal error: Object does not implement ArrayAccess in /wiki/includes/specialpage/SpecialPageFactory.php on line 281
However, this error does not shows up every time.

This problem happens for both HHVM 3.5 to 3.7

Environment:
Linode 8G RAM, 6 core
MediaWiki	1.24.2
HHVM	3.5.0 (srv) (same error for 3.7)
MySQL	5.6.20
Elasticsearch	1.4.2

HipHop VM 3.5.0 (rel)
Compiler: tags/HHVM-3.5.0-0-ga90f4733cfa0d8fefdafc7433f758f78cdc75424
Repo schema: b88b6fee8ef78ab638506d212abcbefe74a276ac

Extension list:
http://zh.moegirl.org/Special:Version?uselang=en

**Comment by jwatzman** [comment] 2015-06-01 18:25
Can you attach `gdb` and get a backtrace, to figure out what it's doing? Also, do you have some sort of more isolated repro case? It looks like you're using MediaWiki, which is known to work (Wikipedia uses HHVM for their deploy :)).

**Comment by zoglun** [comment] 2015-06-01 18:40
I can't reproduce this problem in most of other environment. (I tried debian 8 and centos 7 with hhvm 3.7.1 and exactly same MW file)
I do get 1 CPU full problem when $wgEnableUploads  = false; on centos 7 with hhvm 3.7.1 once but can't reproduce this anymore. probably due to setting error.

This problem took me too much time to solve. I am really tired now. The server with problem is deleted. So I can't get backtrace.

I guess this issue could be safely ignored and may be closed too. 

Thank you for help from everyone.

**Comment by jwatzman** [comment] 2015-06-01 19:42
OK, going to close it then. If you can reproduce on 3.6 or 3.7, and can get the backtrace as above, please do post it and reopen.

**Closed by jwatzman** 2015-06-01 19:42 UTC
Labels: needs more info, no isolated repro, performance
