### ISSUE TITLE
ENT_DISALLOWED constant not defined (htmlspecialchars())

### ISSUE THREAD

**Issue by rdpse** [facebook/hhvm#5845] opened 2015-08-03 16:01 UTC
I've encountered the following error while trying to use HHVM with [IPS4 Forums](https://www.invisionpower.com/features/apps#forums). Everything works fine with PHP.

    Fatal error: Uncaught exception 'ErrorException' with message 'htmlspecialchars() expects parameter 2 to be integer, string given' in /var/www/domain.tld/system/Theme/Theme.php(643) : eval()'d code:296
    Stack trace:
    #0 (): IPS\\IPS::errorHandler()
    #1 /var/www/domain.tld/system/Theme/Theme.php(643) : eval()'d code(296): htmlspecialchars()
    #2 /var/www/domain.tld/system/Helpers/Form/Form.php(131): IPS\\Theme\\class_core_global_forms->button()
    #3 /var/www/domain.tld/system/Login/Login.php(247): IPS\\Helpers\\_Form->__construct()
    #4 /var/www/domain.tld/system/Login/Login.php(308): IPS\\_Login->forms()
    #5 /var/www/domain.tld/applications/core/modules/front/system/login.php(52): IPS\\_Login->authenticate()
    #6 /var/www/domain.tld/system/Dispatcher/Controller.php(94): IPS\\core\\modules\\front\\system\\_login->manage()
    #7 /var/www/domain.tld/system/Dispatcher/Dispatcher.php(129): IPS\\Dispatcher\\_Controller->execute()
    #8 /var/www/domain.tld/index.php(13): IPS\\_Dispatcher->run()
    #9 {main}

    Fatal error: Uncaught exception 'ErrorException' with message 'Session callback expects true/false return value' in :0
    Stack trace:
    #0 (): IPS\\IPS::errorHandler()
    #1 (): session_write_close()
    #2 {main}

Any ideas?

**Comment by fredemmott** [comment] 2015-08-03 16:15
Can you track down exactly what your code is passing to htmlspecialchars?

**Comment by rdpse** [comment] 2015-08-03 17:06
Sorry, I completely butchered that log. Here's the full thing:
https://gist.github.com/rdpse/1ec8e20a3a56932ee3bb

Some relevant files:
https://gist.github.com/rdpse/d8eb966d931828ec579c

**Comment by fredemmott** [comment] 2015-08-03 17:21
https://gist.github.com/rdpse/d8eb966d931828ec579c#file-init-php-L97

As a workaround (and a better check anyway) consider replacing the version_compare() with an if defined('ENT_DISALLOWED')

**Comment by rdpse** [comment] 2015-08-03 23:29
That did it. Thanks!

**Comment by Orvid** [comment] 2015-08-04 00:36
Should probably leave this open as an issue for something that needs implementing.

**Comment by fredemmott** [comment] 2015-08-04 00:39
Reopening - glad you've got something that works for you, but it'd still be good to add it :)

**Comment by Orvid** [comment] 2015-11-19 00:43
Randomly digging, I noticed this is a duplicate of #4938

**Closed** 2015-11-19 01:25 UTC
Labels: duplicate, php5 incompatibility
