### ISSUE TITLE
PHPUnit MockForAbstractClass not working with HHVM

### ISSUE THREAD

**Issue by ct-jensschulze** [facebook/hhvm#5572] opened 2015-07-02 09:32 UTC
```
Fatal error: Class Mock_<class>_<mocknumber> contains abstract method (<methodName>) and must therefore be declared abstract or implement the remaining methods in vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(301) : eval()'d code on line 1
```

When trying to test an abstract class with PHPUnit HHVM throws a fatal error.

Example:
```
abstract class MyClass {
  public function doSomething() {
    return "doneSomething";
  }
  abstract public function doSomethingElse();
}
```

Test:
```
class MyClassTest extends \PHPUnit_Framework_TestCase
{
   public function testDoSomething() {
     $object = $this->getMockForAbstractClass('MyClass')
     $this->assertSame('doneSomething', $object->doSomething());
   }
}
```

**Comment by Orvid** [comment] 2015-07-02 10:55
Which version of the PHPUnit mock framework? In the git HEAD version, [Generator.php line 301](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/Generator.php#L301) is in the middle of a doc comment. (it's likely referring to [line 295](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/Generator.php#L295))

**Comment by ct-jensschulze** [comment] 2015-07-02 13:15
Finally got it working at 3v4l.org :)

http://3v4l.org/2DeHY

**Comment by ct-jensschulze** [comment] 2015-07-02 13:35
Seems to happen only when the abstract class doesn't add the interface methods as abstract function. 

See with these adjustments here:
http://3v4l.org/jnBvq
http://3v4l.org/tb6LT

Funny side note:
http://3v4l.org/LRGhL
The assert seems to not work correctly in HHVM?

**Comment by bd808** [comment] 2015-08-04 22:03
Duplicate of https://github.com/facebook/hhvm/issues/5170?

**Comment by jwatzman** [comment] 2015-08-05 17:09
Very likely -- http://3v4l.org/2DeHY (linked above) says that PHP >= 5.4 and HHVM 3.8 all have the same result (no output). Going to close this, thanks! (Feel free to reopen if my analysis is wrong.)

**Closed by jwatzman** 2015-08-05 17:09 UTC
