### ISSUE TITLE
LTS break: error_get_last() ignores userland error handlers

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#8107] opened 2018-01-18 21:34 UTC
### HHVM Version

3.18.7

### Operating System and Version

Ubuntu

### Standalone code, or other way to reproduce the problem

(see comment below)

**Comment by fredemmott** [comment] 2018-01-18 21:37
I'm not able to reproduce this:

```
fredemmott-pro:src fredemmott$ docker run -it hhvm/hhvm:3.18.7 /bin/bash -l
Unable to find image 'hhvm/hhvm:3.18.7' locally
3.18.7: Pulling from hhvm/hhvm
50aff78429b1: Already exists
f6d82e297bce: Already exists
275abb2c8a6f: Already exists
9f15a39356d6: Already exists
fc0342a94c89: Already exists
8cd1096007fc: Pull complete
Digest: sha256:424ac7d0421f634f2226220e468a75e93ed8f63c7be77cbe62f5e3e25933d2eb
Status: Downloaded newer image for hhvm/hhvm:3.18.7
root@628abde766c7:/# cat > test.php
<?php

set_error_handler(function () {});

$a = $b;

print_r(error_get_last());
root@628abde766c7:/# hhvm test.php
root@628abde766c7:/#
```

What specific distribution version, what package, and can you reproduce if running `hhvm --no-config test.php`?

**Comment by nicolas-grekas** [comment] 2018-01-18 21:58
Oh, I'm sorry, actually my reproducer doesn't work, yet that's the behavior I observe in a more complex scenario.

So, the full fledged reproducer is this one:
```sh
git clone https://github.com/symfony/symfony
cd symfony
git chekout origin/2.7
composer install
./phpunit --filter Debug
echo $?
```

This outputs 255 - I spent hours figuring out why, and the reason is that the call to `error_get_last()` on line 600 in `src/Symfony/Component/Debug/ErrorHandler.php` returns something, while all errors have been caught by a userland error handler: the one in `vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php` on line 100. (you can verify by echoing the message that get caught there.)

Note that this behavior doesn't exist in any previous version of PHP not HHVM - the code is fine, nothing to see there. The bug is really in HHVM 3.18.7.

**Comment by fredemmott** [comment] 2018-01-18 22:26
- can you provide an isolated example? The steps you've given are somewhat unwieldly, especially as `./phpunit` invokes composer again
 - what exact versions are you seeing differing behavior on? I am getting identical test output and exit code on 3.18.0 and 3.18.7 - I don't see an LTS break here.

**Comment by fredemmott** [comment] 2018-01-18 22:30
For 3.18.0, 3.18.7, 3.24.0, I'm getting exit code 0 with:

    Tests: 6, Assertions: 3, Errors: 3.

These 3 are all due to us banning XML entity inclusion by default.

**Comment by nicolas-grekas** [comment] 2018-01-18 22:30
I cannot provide a short reproducer yet sorry, too much code around for now. I just skipped the tests...
I'm using the hhvm from `deb https://dl.hhvm.com/ubuntu xenial-lts-3.18 main`, on Ubuntu Xenial, and the same behavior appeared first on Travis' hhvm, which is the same I guess, on Trusty.

> ./phpunit invokes composer again

this happens only once, to compile a custom phpunit

**Comment by fredemmott** [comment] 2018-01-18 22:32
I'm doing these tests with the hhvm/hhvm:$VERSION docker images; these are also Xenial.

In particular, I did:

```
git clone https://github.com/symfony/symfony
cd symfony
git chekout origin/2.7
hhvm ~/composer.phar install
cp ~/composer.phar .
docker run -v $(pwd):/tmp/symfony hhvm/hhvm:3.18.7 bash -c "cd /tmp/symfony; hhvm ./phpunit --filter debug; echo $?"
```

... replacing the version number

**Comment by nicolas-grekas** [comment] 2018-01-18 22:33
upper case Debug needed in --filter

**Comment by nicolas-grekas** [comment] 2018-01-18 22:36
just to eliminate any php.ini-related issue: same result on my side with
`hhvm --no-config -dhhvm.libxml.ext_entity_whitelist=file ./phpunit --filter Debug ; echo $?`

**Comment by fredemmott** [comment] 2018-01-18 22:47
Re-running. What HHVM versions are you comparing? HHVM 3.18 support ended on Tuesday - though if we broke it in the last two weeks of its support (.6 and .7), we're likely to make an exception.

**Comment by nicolas-grekas** [comment] 2018-01-18 22:49
AFAIK, Travis only has 3.18 pre-installed in the LTS series, but maybe I missed an update on that topic?

**Comment by fredemmott** [comment] 2018-01-18 22:54
So, I'm not seeing any regression with the 3.18 series:

```
fredemmott-pro:symfony fredemmott$ docker run --rm -v $(pwd):/tmp/symfony hhvm/hhvm:3.18.7 bash -c "cd /tmp/symfony; hhvm --no-config -dhhvm.libxml.ext_entity_whitelist=file ./phpunit --filter Debug; echo $?"
#!/usr/bin/env php
PHPUnit 5.7.26 by Sebastian Bergmann and contributors.

Testing Symfony Test Suite
..........SS.F.................S......S........................  63 / 135 ( 46%)
............................................................... 126 / 135 ( 93%)
.........                                                       135 / 135 (100%)

Time: 3.42 minutes, Memory: 206.23MB

There was 1 failure:

1) Symfony\Component\Debug\Tests\DebugClassLoaderTest::testFileCaseMismatch
Failed asserting that exception of type "\RuntimeException" is thrown.

FAILURES!
Tests: 135, Assertions: 327, Failures: 1, Skipped: 4.

Legacy deprecation notices (26)
0
fredemmott-pro:symfony fredemmott$ docker run --rm -v $(pwd):/tmp/symfony hhvm/hhvm:3.18.0 bash -c "cd /tmp/symfony; hhvm --no-config -dhhvm.libxml.ext_entity_whitelist=file ./phpunit --filter Debug; echo $?"
#!/usr/bin/env php
PHPUnit 5.7.26 by Sebastian Bergmann and contributors.

Testing Symfony Test Suite
..........SS.F.................S......S........................  63 / 135 ( 46%)
............................................................... 126 / 135 ( 93%)
.........                                                       135 / 135 (100%)

Time: 3.41 minutes, Memory: 207.34MB

There was 1 failure:

1) Symfony\Component\Debug\Tests\DebugClassLoaderTest::testFileCaseMismatch
Failed asserting that exception of type "\RuntimeException" is thrown.

FAILURES!
Tests: 135, Assertions: 327, Failures: 1, Skipped: 4.

Legacy deprecation notices (26)
0
```

3.18 was the last HHVM release for Ubuntu Trusty; one way to get a supported release on Travis is to use Docker - for example https://github.com/hhvm/xhp-lib/blob/master/.travis.yml https://github.com/hhvm/xhp-lib/blob/master/.travis.sh

**Comment by fredemmott** [comment] 2018-01-18 23:01
That said, the major reasons we dropped support for trusty are much less of an issue given work we've done on packaging; it might be worth bringing back support. I'll try doing a nightly build with our new environment and see what happens.

**Comment by nicolas-grekas** [comment] 2018-01-18 23:03
OK, thanks for trying! That failure may hide the behavior I have... I skipped the tests in our CI for now, we'll see if people report anything related in real world apps.

**Comment by fredemmott** [comment] 2018-01-18 23:10
Ok, I'm closing this for now - will happily re-open if:
 - there's a reproducible issue introduced in 3.18.6 or 3.18.7
 - any LTS regression in 3.21
 - the issue exists in 3.24 (or 3.24+ in PHP7 mode)

**Closed by fredemmott** 2018-01-18 23:10 UTC
Labels: needs more info, no isolated repro, regression

**Comment by fredemmott** [comment] 2018-01-19 01:04
I re-ran yesterday's nightly build with support for Trusty, and it seems to have worked fine. Hopefully will bring 3.21 an 3.24 to Trusty in the next week or two.
