### ISSUE TITLE
gcc6 build issue with folly

### ISSUE THREAD

**Issue by momkin** [facebook/hhvm#8101] opened 2018-01-16 23:58 UTC
### HHVM Version
master
### Operating System and Version
CentOS Linux release 7.4.1708 (Core)
### Standalone code, or other way to reproduce the problem
cmake3 .  -DCMAKE_C_FLAGS="-O2 -pipe -march=native" -DCMAKE_CXX_FLAGS="-O2 -pipe -march=native" -DCMAKE_ASM_FLAGS="-O2 -pipe -march=native"  -DCMAKE_BUILD_TYPE="Release"
time ionice -c2 -n7 nice -n19 make -j7  
### Expected result
To be rebuild
### Actual result
Warning: Element Clflags.include_dirs not found
Warning: Element Config.load_path not found
Warning: Element Clflags.open_modules not found
Warning: Element Clflags.for_package not found
Warning: Element Clflags.debug not found
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_args, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_html, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_info, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_args, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_html, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_info, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_module, and its interface was not compiled with -opaque
File "/tmp/ocamlppc9b998", line 1:
Error: Some fatal warnings were triggered (3 occurrences)
Makefile:283: recipe for target 'generators/odoc_literate.cmxs' failed
make[6]: *** [generators/odoc_literate.cmxs] Error 2
File "/tmp/ocamlppdbc081", line 1:
Error: Some fatal warnings were triggered (4 occurrences)
Makefile:283: recipe for target 'generators/odoc_todo.cmxs' failed
make[6]: *** [generators/odoc_todo.cmxs] Error 2
make[6]: Target 'opt.opt' not remade because of errors.
Makefile:1030: recipe for target 'ocamldoc.opt' failed
make[5]: *** [ocamldoc.opt] Error 2
Makefile:457: recipe for target 'opt.opt' failed
make[4]: *** [opt.opt] Error 2
Makefile:531: recipe for target 'world.opt' failed
make[3]: *** [world.opt] Error 2
make[3]: warning: -jN forced in submake: disabling jobserver mode.
[ 19%] Compiling ocamlbuild
55 states, 419 transitions, table size 2006 bytes
251 states, 1051 transitions, table size 5710 bytes
4334 additional bytes used for bindings
[ 19%] Built target ocaml
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

real    2m21.638s
user    10m9.386s
sys     0m58.927s
[root@server hhvm]#

**Comment by fredemmott** [comment] 2018-01-18 17:02
Can you share more complete build output? I'm seeing this in a bunch of places, but the ocamldoc-related stuff doesn't appear to be build blocking.

**Comment by fredemmott** [comment] 2018-01-18 17:04
Yeah, we try it once with -j, and try again without. This is likely not the cause of the issue you're seeing.

https://github.com/hhvm/hhvm-third-party/blob/master/ocaml/CMakeLists.txt#L40-L41

**Comment by momkin** [comment] 2018-01-18 23:20
so if i remove -j7 in the command the error will go away ?

**Comment by fredemmott** [comment] 2018-01-18 23:22
Possibly, though that's not what causing your overall build to fail, as the parrael build failure for ocaml is ignored

**Comment by momkin** [comment] 2018-01-19 13:44
I have successfully build the old versions like 3.23 tell 3.23.4 , the problem only exist in HHVM-3.24.0 version !

**Comment by fredemmott** [comment] 2018-01-19 16:14
Can you share more complete build output? In particular, their may be 'Error' lines significantly earlier in either stdout or stderr; it's not necessarily near the end given how parallel builds work. We're not able to reproduce the problem on any of our supported distributions, and the message you have shared does not show anything unexpected.

**Comment by momkin** [comment] 2018-01-19 18:15
can you tell me how to capture the whole build output ??
sorry i'm still newbie :(

**Comment by fredemmott** [comment] 2018-01-19 18:32
add `2>stderr.log >stdout.log`, then look in the two new .log files

It'll be *much* slower to remove `-j` from your build arguments, but it may make the error clearer.

**Comment by momkin** [comment] 2018-01-19 20:06
Hi
i tried to remove the -j from the command like this
time ionice -c2 -n7 nice -n19 make 2>stderr.log >stdout.log

and the build has failed after seconds of the start i have attached the requested files !

[stderr.log](https://github.com/facebook/hhvm/files/1647786/stderr.log)
[stdout.log](https://github.com/facebook/hhvm/files/1647787/stdout.log)

**Comment by fredemmott** [comment] 2018-01-19 20:12
What does g++ —version show?

**Comment by momkin** [comment] 2018-01-19 20:26
[root@server hhvm]# g++ --version
g++ (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@server hhvm]#


i have used https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/ for that !

**Comment by fredemmott** [comment] 2018-01-19 20:38
Your best option for now is probably to use https://github.com/hhvm/packaging/blob/master/build-deps/build-gcc to get G++ 5, and use that to build HHVM and Folly

**Comment by fredemmott** [comment] 2018-01-19 22:05
Using Ubuntu Artful, I just confirmed that we can build with GCC7; as I understand it, this means that you should be able to use https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/

Closing: the fact it's fixed in GCC7 means it is reasonably likely to be a compiler bug, and even if not, we're extremely unlikely to invest time in supporting a new compiler that isn't the latest - though we would welcome pull requests as long as they are clean.

**Closed by fredemmott** 2018-01-19 22:05 UTC
Labels: build, won't fix

**Comment by momkin** [comment] 2018-01-19 22:33
Hi again ,
i just tried building it with GCC version 7 and the some issue !
[root@server hhvm]# gcc --version
gcc (GCC) 7.2.1 20170829 (Red Hat 7.2.1-1)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@server hhvm]#

`[ 25%] Building CXX object third-party/folly/CMakeFiles/folly.dir/src/folly/system/Shell.cpp.o
In file included from /tmp/hhvm/third-party/folly/src/folly/synchronization/LifoSem.cpp:17:0:
/tmp/hhvm/third-party/folly/src/folly/synchronization/LifoSem.cpp: In static member function ‘static folly::detail::LifoSemRawNode<Atom>::Pool& folly::detail::LifoSemRawNode<Atom>::pool() [with Atom = std::atomic; folly::detail::LifoSemRawNode<Atom>::Pool = folly::IndexedMemPool<folly::detail::LifoSemRawNode<std::atomic>, 32, 200, std::atomic, folly::IndexedMemPoolTraits<folly::detail::LifoSemRawNode<std::atomic>, false, true> >]’:
/tmp/hhvm/third-party/folly/src/folly/synchronization/LifoSem.h:144:48: warning: ‘new’ of type ‘folly::detail::LifoSemRawNode<std::atomic>::Pool {aka folly::IndexedMemPool<folly::detail::LifoSemRawNode<std::atomic>, 32, 200, std::atomic, folly::IndexedMemPoolTraits<folly::detail::LifoSemRawNode<std::atomic>, false, true> >}’ with extended alignment 128 [-Waligned-new=]
     static Pool* instance = new Pool((capacity));            \
                                                ^
/tmp/hhvm/third-party/folly/src/folly/synchronization/LifoSem.cpp:29:1: note: in expansion of macro ‘LIFOSEM_DECLARE_POOL’
 LIFOSEM_DECLARE_POOL(std::atomic, 1000000)
 ^~~~~~~~~~~~~~~~~~~~
/tmp/hhvm/third-party/folly/src/folly/synchronization/LifoSem.h:144:48: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
     static Pool* instance = new Pool((capacity));            \
                                                ^
/tmp/hhvm/third-party/folly/src/folly/synchronization/LifoSem.cpp:29:1: note: in expansion of macro ‘LIFOSEM_DECLARE_POOL’
 LIFOSEM_DECLARE_POOL(std::atomic, 1000000)
 ^~~~~~~~~~~~~~~~~~~~
/tmp/hhvm/third-party/folly/src/folly/synchronization/LifoSem.h:144:48: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
     static Pool* instance = new Pool((capacity));            \
                                                ^
/tmp/hhvm/third-party/folly/src/folly/synchronization/LifoSem.cpp:29:1: note: in expansion of macro ‘LIFOSEM_DECLARE_POOL’
 LIFOSEM_DECLARE_POOL(std::atomic, 1000000)
 ^~~~~~~~~~~~~~~~~~~~
[ 25%] Building CXX object third-party/folly/CMakeFiles/folly.dir/src/folly/system/ThreadName.cpp.o
[ 25%] Building CXX object third-party/folly/CMakeFiles/folly.dir/src/folly/system/VersionCheck.cpp.o
[ 25%] Building CXX object third-party/folly/CMakeFiles/folly.dir/src/folly/tools/BenchmarkCompare.cpp.o
[ 25%] Building CXX object third-party/folly/CMakeFiles/folly.dir/gen/EscapeTables.cpp.o
[ 25%] Building CXX object third-party/folly/CMakeFiles/folly.dir/gen/FingerprintTables.cpp.o
[ 25%] Building CXX object third-party/folly/CMakeFiles/folly.dir/gen/FormatTables.cpp.o
[ 25%] Building CXX object third-party/folly/CMakeFiles/folly.dir/gen/GroupVarintTables.cpp.o
16 states, 280 transitions, table size 1216 bytes
[ 26%] Linking CXX static library libfolly.a
[ 26%] Built target folly
Scanning dependencies of target wangle
Scanning dependencies of target squangle
[ 26%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/acceptor/Acceptor.cpp.o
[ 26%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/acceptor/AcceptorHandshakeManager.cpp.o
Scanning dependencies of target hphp_util
[ 26%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/base/ConnectionKey.cpp.o
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/abi-cxx.cpp.o
[ 26%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/logger/DBEventCounter.cpp.o
Scanning dependencies of target version
[ 26%] Building CXX object hphp/tools/version/CMakeFiles/version.dir/version.cpp.o
[ 26%] Linking CXX executable version
[ 26%] Built target version
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/afdt-util.cpp.o
Scanning dependencies of target hphp_system
[ 26%] Building CXX object hphp/system/CMakeFiles/hphp_system.dir/systemlib.cpp.o
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/alloc.cpp.o
In file included from /tmp/hhvm/hphp/runtime/base/rds-inl.h:19:0,
                 from /tmp/hhvm/hphp/runtime/base/rds.h:546,
                 from /tmp/hhvm/hphp/runtime/base/rds-util.h:19,
                 from /tmp/hhvm/hphp/runtime/vm/class.h:22,
                 from /tmp/hhvm/hphp/runtime/base/object-data.h:27,
                 from /tmp/hhvm/hphp/runtime/base/type-object.h:20,
                 from /tmp/hhvm/hphp/runtime/base/tv-conversions.h:23,
                 from /tmp/hhvm/hphp/runtime/base/type-variant.h:22,
                 from /tmp/hhvm/hphp/runtime/base/array-data-defs.h:24,
                 from /tmp/hhvm/hphp/runtime/base/array-init.h:21,
                 from /tmp/hhvm/hphp/system/systemlib.cpp:18:
/usr/include/tbb/concurrent_vector.h: In member function ‘tbb::concurrent_vector<T, A>::iterator tbb::concurrent_vector<T, A>::grow_by(tbb::concurrent_vector<T, A>::size_type)’:
/usr/include/tbb/concurrent_vector.h:667:38: error: operands to ?: have different types ‘tbb::internal::concurrent_vector_base_v3::size_type {aka long unsigned int}’ and ‘tbb::atomic<long unsigned int>’
         return iterator(*this, delta ? internal_grow_by( delta, sizeof(T), &initialize_array, NULL ) : my_early_size);
                                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/tbb/concurrent_vector.h:667:38: note:   and each type can be converted to the other
/usr/include/tbb/concurrent_vector.h: In member function ‘tbb::concurrent_vector<T, A>::iterator tbb::concurrent_vector<T, A>::grow_by(tbb::concurrent_vector<T, A>::size_type, tbb::concurrent_vector<T, A>::const_reference)’:
/usr/include/tbb/concurrent_vector.h:680:38: error: operands to ?: have different types ‘tbb::internal::concurrent_vector_base_v3::size_type {aka long unsigned int}’ and ‘tbb::atomic<long unsigned int>’
         return iterator(*this, delta ? internal_grow_by( delta, sizeof(T), &initialize_array_by, static_cast<const void*>(&t) ) : my_early_size);
                                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/tbb/concurrent_vector.h:680:38: note:   and each type can be converted to the other
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/arena.cpp.o
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/asm-x64.cpp.o
make[2]: *** [hphp/system/CMakeFiles/hphp_system.dir/build.make:63: hphp/system/CMakeFiles/hphp_system.dir/systemlib.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2047: hphp/system/CMakeFiles/hphp_system.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/assertions.cpp.o
[ 26%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/acceptor/ConnectionManager.cpp.o
[ 26%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/acceptor/EvbHandshakeHelper.cpp.o
[ 26%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/logger/DBEventLogger.cpp.o
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/async-func.cpp.o
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/boot-stats.cpp.o
In file included from /tmp/hhvm/third-party/wangle/src/wangle/acceptor/EvbHandshakeHelper.cpp:16:0:
/tmp/hhvm/third-party/folly/wangle/acceptor/EvbHandshakeHelper.h:86:3: warning: multi-line comment [-Wcomment]
   //                              \
   ^
/tmp/hhvm/third-party/folly/wangle/acceptor/EvbHandshakeHelper.h:97:3: warning: multi-line comment [-Wcomment]
   //                 /\
   ^
/tmp/hhvm/third-party/folly/wangle/acceptor/EvbHandshakeHelper.h:127:3: warning: multi-line comment [-Wcomment]
   //                 \
   ^
/tmp/hhvm/third-party/folly/wangle/acceptor/EvbHandshakeHelper.h:190:3: warning: multi-line comment [-Wcomment]
   //     \
   ^
[ 26%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/mysql_client/AsyncConnectionPool.cpp.o
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/brotli.cpp.o
[ 26%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/acceptor/LoadShedConfiguration.cpp.o
[ 26%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/acceptor/ManagedConnection.cpp.o
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/bstring.cpp.o
[ 26%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/mysql_client/AsyncHelpers.cpp.o
[ 26%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/mysql_client/AsyncMysqlClient.cpp.o
[ 26%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/acceptor/SSLAcceptorHandshakeHelper.cpp.o
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/build-info.cpp.o
[ 26%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/mysql_client/Connection.cpp.o
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/capability.cpp.o
In file included from /tmp/hhvm/third-party/folly/src/folly/Format-inl.h:28:0,
                 from /tmp/hhvm/third-party/folly/src/folly/Format.h:498,
                 from /tmp/hhvm/third-party/squangle/src/squangle/mysql_client/Row.h:32,
                 from /tmp/hhvm/third-party/squangle/src/squangle/mysql_client/DbResult.h:15,
                 from /tmp/hhvm/third-party/squangle/src/squangle/mysql_client/AsyncMysqlClient.h:53,
                 from /tmp/hhvm/third-party/squangle/squangle/mysql_client/AsyncMysqlClient.cpp:11:
/tmp/hhvm/third-party/squangle/squangle/mysql_client/AsyncMysqlClient.cpp: In member function ‘virtual void facebook::common::mysql_client::ConnectionSocketHandler::handlerReady(uint16_t)’:
/tmp/hhvm/third-party/folly/src/folly/Exception.h:138:37: warning: throw will always call terminate() [-Wterminate]
       throw E("Check failed: " #cond); \
                                     ^
/tmp/hhvm/third-party/squangle/squangle/mysql_client/AsyncMysqlClient.cpp:636:3: note: in expansion of macro ‘CHECK_THROW’
   CHECK_THROW(
   ^
[ 26%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/acceptor/SecureTransportType.cpp.o
[ 26%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/acceptor/SocketOptions.cpp.o
[ 26%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/compatibility.cpp.o
[ 26%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/mysql_client/DbResult.cpp.o
[ 26%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/acceptor/TLSPlaintextPeekingCallback.cpp.o
[ 27%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/acceptor/TransportInfo.cpp.o
[ 27%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/channel/Pipeline.cpp.o
[ 27%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/compression.cpp.o
[ 28%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/mysql_client/FutureAdapter.cpp.o
[ 28%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/mysql_client/Operation.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/conv-10.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/cronolog.cpp.o
[ 29%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/mysql_client/OperationBatch.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/client/ssl/SSLSessionCacheData.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/client/ssl/SSLSessionCacheUtils.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/client/ssl/SSLSessionCallbacks.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/cronoutils.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/client/ssl/ThreadSafeSSLSessionCache.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/current-executable.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/data-block.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/codec/LengthFieldBasedFrameDecoder.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/disasm.cpp.o
[ 29%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/mysql_client/Query.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/eh-frame.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/codec/LengthFieldPrepender.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/embedded-data.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/codec/LineBasedFrameDecoder.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/embedded-vfs.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/deprecated/rx/Dummy.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/ssl/PasswordInFile.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/exception.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/file-cache.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/ssl/SSLContextManager.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/hardware-counter.cpp.o
[ 29%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/mysql_client/Row.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/hash.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/ssl/SSLSessionCacheManager.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/hdf.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/ssl/SSLUtil.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/ssl/ServerSSLContext.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/ssl/TLSCredProcessor.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/hfsort-plus.cpp.o
[ 29%] Building CXX object third-party/squangle/CMakeFiles/squangle.dir/squangle/mysql_client/SSLOptionsProviderBase.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/hfsort.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/hugetlb.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/ssl/TLSTicketKeyManager.cpp.o
[ 29%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/util/FilePoller.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/kernel-version.cpp.o
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/light-process.cpp.o
41 states, 1026 transitions, table size 4350 bytes
1285 additional bytes used for bindings
[ 29%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/lock.cpp.o
[ 29%] Linking CXX static library libsquangle.a
[ 29%] Built target squangle
5 shift/reduce conflicts.
5 shift/reduce conflicts.
251 states, 2458 transitions, table size 11338 bytes
50 states, 614 transitions, table size 2756 bytes
20 states, 264 transitions, table size 1176 bytes
111 states, 2871 transitions, table size 12150 bytes
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/log-file-flusher.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/logger.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/managed-arena.cpp.o
[ 30%] Linking CXX static library libwangle.a
[ 30%] Built target wangle
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/maphuge.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/network.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/numa.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/perf-event.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/process-exec.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/process.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/rank.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/read-only-arena.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/ringbuffer.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/safe-cast.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/service-data.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/shm-counter.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/ssl-init.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/stack-trace.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/stacktrace-profiler.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/string-bag.cpp.o
[ 30%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/string-vsnprintf.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/struct-log.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/synchronizable-multi.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/synchronizable.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/text-art.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/text-color.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/text-util.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/thread-local.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/timer.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/trace.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/type-scan.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/cache/cache-data.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/cache/cache-manager.cpp.o
Warning: Element Clflags.include_dirs not found
Warning: Element Config.load_path not found
Warning: Element Clflags.open_modules not found
Warning: Element Clflags.for_package not found
Warning: Element Clflags.debug not found
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/cache/cache-saver.cpp.o
[ 31%] Building CXX object hphp/util/CMakeFiles/hphp_util.dir/cache/mmap-file.cpp.o
[ 31%] Building ASM object hphp/util/CMakeFiles/hphp_util.dir/hash-crc-arm.S.o
[ 31%] Building ASM object hphp/util/CMakeFiles/hphp_util.dir/hash-crc-x64.S.o
[ 31%] Building ASM object hphp/util/CMakeFiles/hphp_util.dir/memcpy-x64.S.o
[ 31%] Building ASM object hphp/util/CMakeFiles/hphp_util.dir/memset-x64-avx2.S.o
[ 31%] Building ASM object hphp/util/CMakeFiles/hphp_util.dir/strcmp-sse42.S.o
[ 32%] Linking CXX static library libhphp_util.a
[ 32%] Built target hphp_util
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_args, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_html, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_info, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_args, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_html, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_info, and its interface was not compiled with -opaque
File "/tmp/hhvm/third-party/ocaml/src/ocamldoc/_none_", line 1:
Warning 58: no cmx file was found in path for module Odoc_module, and its interface was not compiled with -opaque
File "/tmp/ocamlpp9200cc", line 1:
Error: Some fatal warnings were triggered (3 occurrences)
make[6]: *** [Makefile:283: generators/odoc_literate.cmxs] Error 2
File "/tmp/ocamlpp79e0a0", line 1:
Error: Some fatal warnings were triggered (4 occurrences)
make[6]: *** [Makefile:283: generators/odoc_todo.cmxs] Error 2
make[6]: Target 'opt.opt' not remade because of errors.
make[5]: *** [Makefile:1030: ocamldoc.opt] Error 2
make[4]: *** [Makefile:466: opt.opt] Error 2
make[3]: *** [Makefile:531: world.opt] Error 2
make[3]: warning: -jN forced in submake: disabling jobserver mode.
[ 32%] Compiling ocamlbuild
55 states, 419 transitions, table size 2006 bytes
251 states, 1051 transitions, table size 5710 bytes
4334 additional bytes used for bindings
[ 32%] Built target ocaml
make: *** [Makefile:128: all] Error 2

real    4m16.139s
user    23m7.256s
sys     1m59.093s
[root@server hhvm]# ./hphp/hhvm/hhvm --version
bash: ./hphp/hhvm/hhvm: No such file or directory
[root@server hhvm]#
`

**Comment by fredemmott** [comment] 2018-01-19 22:52
That's a different issue - it looks like your version of TBB is too old; you might have luck installing the latest version into /usr/local and doing a clean build (so cmake picks up the new version)

**Comment by fredemmott** [comment] 2018-01-19 23:07
- we do not support centos7 - the distributions we support are listed on https://docs.hhvm.com/hhvm/installation/linux
- that said, have you tried upgrading TTB, per previous comment?

**Comment by momkin** [comment] 2018-01-19 23:44
@fredemmott  that's weird i can build every version prior to 3.24.0

what could been changed in the new version that might cause this ?

**Comment by fredemmott** [comment] 2018-01-20 00:00
GCC6: most likely a change to Folly; we periodically update the version we build against
GCC7/TBB: don't know if this previously worked

**Comment by momkin** [comment] 2018-01-20 14:59
@fredemmott i managed to get it worked with gcc version 5

thanks for your help !
