### ISSUE TITLE
[hackc] factsparse is not usable in concurrent requests

### ISSUE THREAD

**Issue by bredman** [facebook/hhvm#8259] opened 2018-07-13 17:38 UTC
### HHVM Version

```
$ hhvm --version
HipHop VM 3.26.3 (rel)
Compiler: remotes/origin/3.26.3-slack-0-ge55735806565ae3d946946755a95c99a88bd94de
Repo schema: 33e4259f518a58857c48aff195ff7e076fe0b4e9
[bredman@slack-dev191 dev431] 2018-07-13 10:08:57
$ hh_client --version
hh--3.26.3 Mon Jul  2 15:57:48 2018
[bredman@slack-dev191 dev431] 2018-07-13 10:09:02
$
```

### Operating System and Version

'Ubuntu 16.04.3'

### Standalone code, or other way to reproduce the problem

Sadly I don't have this but here are some seeming preconditions:

* Have code that `hh_client` is unhappy with deployed to the host
* Have the new HackC compiler enabled

Sometimes I will also need to delete our repo to trigger this issue (we are not running in repo auth mode).

### Actual result

Shortly after restart the HHVM process is unresponsive and consumes lots of memory as shown by the output of this script below:
```
#!/bin/zsh


while true;
do
  HHVM_PID=`pgrep -x 'hhvm' -P 1`
  VM_SIZE=`egrep '^VmSize:' /proc/$HHVM_PID/status`
  TIME=`date +"%F %T %z"`
  echo "[$HHVM_PID] $TIME => $VM_SIZE"
  sleep 10
done
```
Script output:
```
[22711] 2018-07-13 10:14:16 -0700 => VmSize:     2857540 kB
[22711] 2018-07-13 10:14:26 -0700 => VmSize:     2857540 kB
[28916] 2018-07-13 10:14:37 -0700 => VmSize:     4564412 kB
[28916] 2018-07-13 10:14:47 -0700 => VmSize:     9241100 kB
[28916] 2018-07-13 10:14:57 -0700 => VmSize:    11543052 kB
[28916] 2018-07-13 10:15:07 -0700 => VmSize:    11543052 kB
[28916] 2018-07-13 10:15:17 -0700 => VmSize:    13378060 kB
[28916] 2018-07-13 10:15:27 -0700 => VmSize:    13992460 kB
[28916] 2018-07-13 10:15:37 -0700 => VmSize:    14074892 kB
[28916] 2018-07-13 10:15:47 -0700 => VmSize:    16016396 kB
[28916] 2018-07-13 10:15:57 -0700 => VmSize:    16638988 kB
[28916] 2018-07-13 10:16:07 -0700 => VmSize:    16647180 kB
[28916] 2018-07-13 10:16:17 -0700 => VmSize:    18555916 kB
[28916] 2018-07-13 10:16:27 -0700 => VmSize:    19203084 kB
[28916] 2018-07-13 10:16:37 -0700 => VmSize:    19211276 kB
[28916] 2018-07-13 10:16:47 -0700 => VmSize:    21132300 kB
[28916] 2018-07-13 10:16:57 -0700 => VmSize:    21837324 kB
[28916] 2018-07-13 10:17:07 -0700 => VmSize:    21919756 kB
[28916] 2018-07-13 10:17:17 -0700 => VmSize:    23989260 kB
[28916] 2018-07-13 10:17:27 -0700 => VmSize:    24698380 kB
[28916] 2018-07-13 10:17:37 -0700 => VmSize:    24780812 kB
[28916] 2018-07-13 10:17:47 -0700 => VmSize:    26854412 kB
[28916] 2018-07-13 10:17:57 -0700 => VmSize:    27563532 kB
[28916] 2018-07-13 10:18:07 -0700 => VmSize:    27645964 kB
[28916] 2018-07-13 10:18:17 -0700 => VmSize:    29715468 kB
[28916] 2018-07-13 10:18:27 -0700 => VmSize:    30428684 kB
[28916] 2018-07-13 10:18:37 -0700 => VmSize:    30511116 kB
[28916] 2018-07-13 10:18:47 -0700 => VmSize:    32580620 kB
[28916] 2018-07-13 10:18:57 -0700 => VmSize:    33302028 kB
[28916] 2018-07-13 10:19:07 -0700 => VmSize:    33384460 kB
[28916] 2018-07-13 10:19:17 -0700 => VmSize:    35441676 kB
[28916] 2018-07-13 10:19:27 -0700 => VmSize:    36171276 kB
[28916] 2018-07-13 10:19:37 -0700 => VmSize:    36253708 kB
[28916] 2018-07-13 10:19:47 -0700 => VmSize:    37678604 kB
[28916] 2018-07-13 10:19:57 -0700 => VmSize:    39028236 kB
[28916] 2018-07-13 10:20:07 -0700 => VmSize:    39106572 kB
[28916] 2018-07-13 10:20:17 -0700 => VmSize:    41108492 kB
```

Once a process gets into this state it does not recover on its own and has to be restarted. No log messages are emitting while it is in this state. Trigger a dump of the thread state indicates there are 100s of threads blocked on `HPHP::acquire_facts_parser()` (see https://gist.github.com/bredman/34c2e144f00178db16eafc8867eb4770)

### Expected result

HHVM continues forward until it needs to execute the invalid code as it did previously or it exits quickly and gracefully (ideally the former for us).

**Comment by fredemmott** [comment] 2018-07-13 18:16
Based on the trace, this *might* have been resolved with https://github.com/facebook/hhvm/commit/93c31ec66fdd74eb691b6e400de7ffc465d14a5d

**Comment by ssandler** [comment] 2018-07-23 16:32
Unfortunately this still repros on HHVM 3.27.1 if we enable HackC. Within a couple minutes of starting up HHVM, we see over 100 GB of virtual memory consumed across multiple different hosts.

Any ideas on next steps to investigate this?

**Comment by ssandler** [comment] 2018-07-23 16:59
Here's a snapshot of cpu/memory stats from boxes receiving similar traffic with the same code:

HackC disabled:
```
VIRT - 5.2g
RES - 446m
%CPU - 22.5
```

HackC enabled:
```
VIRT - 123g
RES - 8.328g
%CPU - 300.3
```

We've tried this across quite a few different hosts in different environments and are seeing the behavior consistently, load spikes on the hosts with HackC and they become unavailable pretty quickly, serving 503s on every request.

This is happening on our dev servers where the autoload map is not precompiled, it's generated upon requests and cached in APC based on recursive mtime of directories. I assume this is why `HPHP::acquire_facts_parser()` is at play, since that's used in generating the map. Since developers can change the code at any time we don't use a static autoload map. Is the facts parser significantly slower or more resource intensive under HackC?

**Comment by fredemmott** [comment] 2018-07-23 17:02
Are you able to test on nightlies, or provide a way to test this? I'll check with others, but I don't think we've seen this even in our development environments

**Comment by ssandler** [comment] 2018-07-23 18:02
I just installed `hhvm-nightly` (3.28.0-dev) and yes, still repros. 

I've got a reliable repro now by:
1. using `siege` to generate traffic to the box (default concurrency is enough, and the requests are all the same simple request)
2. Modifying a file inside one of the autoloaded directories, which updates `mtime` of the directory, causing the next request to trigger the fact parser. 
Memory immediately spikes up and all requests from that moment forward are either 504 or 503.

I think the key here is that there needs to be enough traffic on the box so that, multiple threads are competing to run the fact parser at the same time.

The facts parser is invoked like this:

```
$facts = \HH\facts_parse($this->path,
			$this->getMatchingFiles(),
			false, // allowHipHopSyntax
			true); // Use threads
```

I also tried setting `allowHipHopSyntax` to true but it doesn't make a difference.

I'm guessing the reason we're seeing this and you're not is because we don't use hh-autoload and use our custom autoloader?

I can look at pulling together a minimal repository to reproduce the issue.

**Comment by ssandler** [comment] 2018-07-23 19:21
## Repro steps with open source code:

1. Clone https://github.com/ssandler/user-documentation, which is the hhvm user documentation repo with one commit added to switch out hh_autoload for a slightly slimmed version of our custom autoloader
2. Build the site using the normal instructions on user-documentation README (I did the whole composer install, gem install, bin/build thing though I'm not sure it's necessary for this test)
3. Start the server: `cd user-documentation/public; hhvm -m server -p 8080 -c ../hhvm.dev.ini`
4. Observe that requests to localhost are returning a correct html response: `curl localhost:8080`
5. Install siege: `sudo apt-get install siege`, or use your favorite load testing tool
6. Start a load test: `siege localhost:8080`

Observe that requests are working fine.

Now, possibly a few times if necessary, touch a file inside `src` to trigger a purge of the APC cache (because of directory mtime) and the autoloader will have to run the fact parser for every request for a few seconds:

`touch user-documentation/src/test.txt`
`rm user-documentation/src/test.txt`

Run `top`, and you should see VIRT memory go up and **stay up** each time this happens. Very quickly, `siege` will start complaining about socket failures, and if you curl localhost:8080 it'll just hang. The hhvm server becomes unresponsive although it doesn't actually stop.

Do the whole thing over with `hhvm.hack_compiler_default = false` in `hhvm.dev.ini` and observe this doesn't happen. Memory still spikes for a moment, but it **goes back down** and the server recovers gracefully from the flood of autoloader requests.

**Comment by ssandler** [comment] 2018-07-23 19:38
There are a couple ways we can think of to work around this:

1. Use a lock in APC to make it so that only one request can run facts_parser at a time
2. Add a step to precompile the map in our dev environments and specify the `HHClientFallbackHandler` from `hhvm-autoload` as a failure handler to pick up added/moved symbols

Still interested in whether this is seen as a fixable bug with HackC though.

**Comment by ssandler** [comment] 2018-07-24 22:13
We put in a change to use locking via `apc_add` so that only one request will run `facts_parse` at a time, but still saw the server become unavailable with the same behavior in about 5 minutes :-(.

In the new thread dump, https://gist.github.com/ssandler/7b90fa64f3517ed246354b8a135aee5d, there are fewer threads waiting on `acquire_facts_parser`, and more waiting on things beneath `AutoloadHandler` and similar. The number of blocked threads appears to be growing over time, and this only clears up when we restart the hhvm process.

- Is running facts_parser more resource intensive under HackC?
- Is pre-compiling the map for dev environments our only way forward?

**Comment by fredemmott** [comment] 2018-07-24 22:29
FYI, you'll probably see this even with hhvm-autoload; it's most likely trying to use ext_factparse while the server is under load.

This is a bug; unsure yet if fixable. I think the next question is is it just ineffecient, or is it somehow breaking/deadlocking?

When this happens, how many `hh_parse` processes are a live, and for how long? What state are they in?

**Comment by ssandler** [comment] 2018-07-24 22:36
No `hh_parse` processes, just a bunch of short lived `hh_single_compile`:

```www 118320  0.0  0.0  17000  5564 ?        S    15:30   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118322  7.1  0.0  75392 27444 ?        S    15:30   0:15 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118344  0.0  0.0  17000  5572 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118346  0.0  0.0  17000  5420 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118347  4.1  0.0  46720 27440 ?        S    15:31   0:08 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118349  0.0  0.0  17000  5568 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118350  2.6  0.0  46720 25468 ?        S    15:31   0:05 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118352  0.0  0.0  17000  5580 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118353  2.6  0.0  67200 28272 ?        S    15:31   0:05 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118355  0.0  0.0  17000  5588 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118357  0.0  0.0  17000  5552 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118358  2.9  0.0  46720 25364 ?        S    15:31   0:06 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118360  2.7  0.0  46720 27436 ?        S    15:31   0:05 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118361  0.0  0.0  17000  5604 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118363  3.1  0.0  46720 25308 ?        S    15:31   0:06 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118364  0.0  0.0  17000  5432 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118366  0.0  0.0  17000  5604 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118367  2.8  0.0  46720 27596 ?        S    15:31   0:05 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118368  2.9  0.1  54912 35788 ?        S    15:31   0:06 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118370  0.0  0.0  17000  5560 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118371  2.6  0.0  46720 25344 ?        S    15:31   0:05 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118373  0.0  0.0  17000  5424 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118374  2.5  0.0  46720 27412 ?        S    15:31   0:05 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118376  0.0  0.0  17000  5556 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118378  0.0  0.0  17000  5560 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118379  2.5  0.0  46720 27472 ?        S    15:31   0:05 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118381  0.0  0.0  17000  5552 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118383  2.7  0.0  46720 25392 ?        S    15:31   0:05 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118384  0.0  0.0  17000  5560 ?        S    15:31   0:00 sh -c /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118386  2.8  0.0  46720 25348 ?        S    15:31   0:05 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118387  2.9  0.0  63104 27144 ?        S    15:31   0:06 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon
www 118388  2.7  0.0  46720 27468 ?        S    15:31   0:05 /usr/bin/hh_single_compile -v Hack.Compiler.SourceMapping=1 --daemon```

**Comment by fredemmott** [comment] 2018-08-09 00:14
Isolated repro:

```
<?hh

HH\facts_parse('/', [__FILE__], /* force_hh = */ false, /* multithreaded = */ true);
```

Then:

```
hhvm --no-config --daemon -p 8080
```

This is completely fine:

```
 ab -n 1000 -c 1 http://localhost:8080/test.php
```

(1000 requests, no currency, apachebench)

This pretty reliably fails:

```
ab -n 10 -c 2 http://localhost:8080/test.php
```

10 requests, 2 concurrent.

Increase c (with n >= c) to increase reliability of repro

**Comment by fredemmott** [comment] 2018-08-09 00:17
FB T32608459

**Comment by fredemmott** [comment] 2018-08-09 00:25
This does not repro for me if I set multithreaded (arg 4) to false

**Closed** 2018-08-11 00:13 UTC
Labels: Diff Ready
