### ISSUE TITLE
ElideAutoloadInvokes option brokes Drupal8 execution on oss-performance.

### ISSUE THREAD

**Issue by racardoso** [facebook/hhvm#7477] opened 2016-11-08 13:26 UTC
This optimization option was introduced on https://github.com/facebook/hhvm/commit/2deffa0 and is enabled by default https://github.com/facebook/hhvm/blob/master/hphp/hhbbc/options.h#L252 but this option broke Drupal8 execution on oss-performance. Tested it on x86_64 and PPC64 machines with Ubuntu 16.04. Disabling this option this problem not happen. Maybe this option should be disabled by default instead enabled by default (see attached patch).

### HHVM Version
HHVM-3.16 (master) x86_64
HHVM-3.16 (upstream/master) PPC64

### Standalone code, or other way to reproduce the problem
Git clone last HHVM version from master, build and install. Git clone last version of oss-performance, install and run:

`hhvm perf.php --drupal8 --hhvm=$HHVM_PATH`

### Expected result
Siege results for Drupal8 test.

### Actual result
```
**************************
** 2016-11-08 08:07:45 EST
** Running sanity check

Warning: Failed to open http://rcardoso:8090/ () in /home/rcardoso/oss-performance/base/PerfTarget.php on line 30

Fatal error: Uncaught exception 'HH\InvariantException' with message 'Failed to find string "Read more" in http://rcardoso:8090/' in /home/rcardoso/oss-performance/base/PerfTarget.php:34
Stack trace:
#0 /home/rcardoso/oss-performance/base/PerfTarget.php(34): HH\invariant_violation()
#1 /home/rcardoso/oss-performance/base/PerfRunner.php(99): PerfTarget->sanityCheck()
#2 /home/rcardoso/oss-performance/base/PerfRunner.php(42): PerfRunner::RunWithOptionsAndEngine()
#3 /home/rcardoso/oss-performance/base/PerfRunner.php(17): PerfRunner::RunWithOptions()
#4 /home/rcardoso/oss-performance/perf.php(15): PerfRunner::RunWithArgv()
#5 /home/rcardoso/oss-performance/perf.php(19): perf_main()
#6 {main}

Warning: Failed to open http://localhost:8091/check-health (Failed to connect to localhost port 8091: Connection refused) in /home/rcardoso/oss-performance/base/HHVMDaemon.php on line 343
Terminated
```

###Patch
```
From 1b79f82a588b2ed62018e765c55d4564ae5777ab Mon Sep 17 00:00:00 2001          
From: Rogerio Alves <rogealve@br.ibm.com>                                       
Date: Tue, 8 Nov 2016 06:08:17 -0600                                            
Subject: [PATCH] Disable ElideAutoloadInvokes option by default.                
                                                                                
Summary:                                                                        
                                                                                
ElideAutoloadInvokes is a new optimization that lower a HHBC FPushFuncU to a    
FPushFuncD and is enabled by default. This otimization brokes Drupal8 execution 
on oss-performance (issue #158).                                                
                                                                                
This commit make this option disabled by default instead. That commit wont fix  
ElideAutoloadInvokes just disable that option.                                  
---                                                                             
 hphp/hhbbc/options.h               | 2 +-                                      
 hphp/runtime/vm/repo-global-data.h | 2 +-                                      
 2 files changed, 2 insertions(+), 2 deletions(-)                               
                                                                                
diff --git a/hphp/hhbbc/options.h b/hphp/hhbbc/options.h                        
index 2f08d3f..6bfb104 100644                                                   
--- a/hphp/hhbbc/options.h                                                      
+++ b/hphp/hhbbc/options.h                                                      
@@ -249,7 +249,7 @@ struct Options {                                            
    * autoloader, if it can be proven the invocation would not find a viable    
    * function.                                                                 
    */                                                                          
-  bool ElideAutoloadInvokes = true;                                            
+  bool ElideAutoloadInvokes = false;                                           
                                                                                
   /*                                                                           
    * The filepath where to save the stats file.  If the path is empty, then we 
diff --git a/hphp/runtime/vm/repo-global-data.h b/hphp/runtime/vm/repo-global-data.h
index 74e755c..6298590 100644                                                   
--- a/hphp/runtime/vm/repo-global-data.h                                        
+++ b/hphp/runtime/vm/repo-global-data.h                                        
@@ -77,7 +77,7 @@ struct Repo::GlobalData {                                     
    * potential invocations of the autoloader may have been optimized away if it
    * could be proven the invocation would not find a viable function.          
    */                                                                          
-  bool ElideAutoloadInvokes = true;                                            
+  bool ElideAutoloadInvokes = false;                                           
                                                                                
   /*                                                                           
    * Indicates whether the repo was compiled with PHP7 integer semantics. This 
--                                                                              
2.7.4   
```

**Comment by mofarrell** [comment] 2016-11-08 16:12
It looks like the HHVM daemon being used to service the perf requests crashed.  Is there anyway you could provide the backtrace for that?  I think we should be able to fix this rather than just disable it.

**Comment by racardoso** [comment] 2016-11-08 20:45
@mofarrell thanks for the reply. I'll see if i can get more backtrace for it and past it here.

**Comment by racardoso** [comment] 2016-11-14 12:06
@mofarrell  do you have a suggestion how can i get a backtrace for those requests? Beside i found another problem:

```
***************************************************************
** 2016-11-10 07:23:59 CST
** Configuration: Drupal8PageCacheTarget on /usr/local/bin/hhvm

**************************
** 2016-11-10 07:23:59 CST
** Installing framework
PHP Fatal error:  Uncaught Error: Call to undefined function Drupal\Core\Cache\mb_check_encoding() in /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php:435
Stack trace:
#0 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php(78): Drupal\Core\Cache\DatabaseBackend->normalizeCid('system.filter')
#1 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/CachedStorage.php(93): Drupal\Core\Cache\DatabaseBackend->getMultiple(Array)
#2 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(166): Drupal\Core\Config\CachedStorage->readMultiple(Array)
#3 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(109): Drupal\Core\Config\ConfigFactory->doLoadMultiple(Array, true)
#4 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(94): Drupal\Core\Config\ConfigFactory->doGet('system.filter')
#5 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupa in /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php on line 435
Drush command terminated abnormally due to an unrecoverable error.                                                                                 [error]
Error: Uncaught Error: Call to undefined function Drupal\Core\Cache\mb_check_encoding() in
/tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php:435
Stack trace:
#0 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php(78):
Drupal\Core\Cache\DatabaseBackend->normalizeCid('system.filter')
#1 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/CachedStorage.php(93):
Drupal\Core\Cache\DatabaseBackend->getMultiple(Array)
#2 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(166):
Drupal\Core\Config\CachedStorage->readMultiple(Array)
#3 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(109):
Drupal\Core\Config\ConfigFactory->doLoadMultiple(Array, true)
#4 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(94):
Drupal\Core\Config\ConfigFactory->doGet('system.filter')
#5 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupa in
/tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php, line 435

**************************
** 2016-11-10 07:25:18 CST
** There is no setUpTest

**************************
** 2016-11-10 07:25:18 CST
** Starting Nginx
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)

**************************
** 2016-11-10 07:25:18 CST
** Starting PHP Engine
running hphp...
all files saved in /tmp/hhvm-nginx01OGqH ...
running hphp took 0'19" (19737990 us) wall time
BootStats: mapping self...
BootStats: mapping self block done, took 1ms wall, 0ms cpu, 0 MB RSS
BootStats: pagein_self done, took 1ms wall, 5ms cpu, 0 MB RSS
BootStats: loading static content...
loaded file cache from /tmp/hhvm-nginx01OGqH/static.content
BootStats: loading static content block done, took 12ms wall, 13ms cpu, 2 MB RSS
BootStats: pthread_init done, took 13ms wall, 13ms cpu, 2 MB RSS
BootStats: Process::InitProcessStatics done, took 0ms wall, 0ms cpu, 0 MB RSS
BootStats: timezone_init done, took 0ms wall, 0ms cpu, 4 MB RSS

**************************
** 2016-11-10 07:25:41 CST
** Running sanity check

Warning: Failed to open http://rcardoso:8090/ () in /home/rcardoso/oss-performance/base/PerfTarget.php on line 30

Fatal error: Uncaught exception 'HH\InvariantException' with message 'Failed to find string "Read more" in http://rcardoso:8090/' in /home/rcardoso/oss-performance/base/PerfTarget.php:34
Stack trace:
#0 /home/rcardoso/oss-performance/base/PerfTarget.php(34): HH\invariant_violation()
#1 /home/rcardoso/oss-performance/base/PerfRunner.php(99): PerfTarget->sanityCheck()
#2 /home/rcardoso/oss-performance/base/PerfRunner.php(42): PerfRunner::RunWithOptionsAndEngine()
#3 /home/rcardoso/oss-performance/base/PerfRunner.php(17): PerfRunner::RunWithOptions()
#4 /home/rcardoso/oss-performance/perf.php(15): PerfRunner::RunWithArgv()
#5 /home/rcardoso/oss-performance/perf.php(19): perf_main()
#6 {main}

Warning: Failed to open http://localhost:8091/check-health (Failed to connect to localhost port 8091: Connection refused) in /home/rcardoso/oss-performance/base/HHVMDaemon.php on line 343
Terminated
```

This error don't happens when link php with hhvm with:

```
$  update-alternatives --config php
There are 2 choices for the alternative php (providing /usr/bin/php).

  Selection    Path                 Priority   Status
------------------------------------------------------------
  0            /usr/bin/php7.0       70        auto mode
 *1           /usr/local/bin/hhvm   60        manual mode
```

**Comment by racardoso** [comment] 2016-11-14 13:15
There's another thing. If i don't update-alternative to use hhvm instead PHP (like bellow) i still got errors when run Drupal8.
``` 
$  update-alternatives --config php
There are 2 choices for the alternative php (providing /usr/bin/php).

  Selection    Path                 Priority   Status
------------------------------------------------------------
  0            /usr/bin/php7.0       70        auto mode
 *1           /usr/local/bin/hhvm   60        manual mode
```

**Comment by jim-saxman** [comment] 2016-12-07 17:42
I confirmed this is an issue on AArch64 with Ubuntu 16.04.

**Comment by jim-saxman** [comment] 2016-12-10 23:50
For now, I am using the --no-repo-auth parameter to OSS so that I can verify correctness of the ARM port with the drupal8* tests.

@swalk-cavium Do you run the OSS performance suite?

**Comment by swalk-cavium** [comment] 2016-12-12 15:24
@jim-saxman I have not run this suite yet.

**Comment by mofarrell** [comment] 2017-01-09 16:27
I was wondering if this is working now that this issue is fixed https://github.com/facebook/hhvm/issues/7572

**Comment by jim-saxman** [comment] 2017-01-09 17:27
@mofarrell I just confirmed that I can run OSS performance suite --drupal8-page-cache without the --no-repo-auth parameter, so yes, this issue appears to be fixed now.

**Comment by mofarrell** [comment] 2017-01-09 18:26
Awesome!

**Closed by mofarrell** 2017-01-09 18:26 UTC
Labels: crash, needs more info
