### ISSUE TITLE
Segmentation fault, any fix or way to auto restart hhvm after it?

### ISSUE THREAD

**Issue by Karabaja** [facebook/hhvm#7152] opened 2016-06-12 22:46 UTC
### HHVM Version 3.13.2
I get core dumped, segmentation fault logged in hhvm log. The site is running vbulletin forums. And stack trace mentions global.php file that belongs to vbulletin, line 607 that contains this:
($hook = vBulletinHook::fetch_hook('parse_templates')) ? eval($hook) : false;
It is an older version of vbulletin 3.8 and I am not sure if this problem is because of some incompatibility with new php or caused by some plugin in our vbulletin. I was hoping that this piece of code could be altered somehow to stop the segmentation fault.
But alternatively I'd appreciate any help on how to auto restart hhvm after segmentation fault. I have a script that checks if hhvm pid is present and restarts it if it is not but after segfault pid still remains there so hhvm won't start until I manually start it. 

PHP Stacktrace:
#0  include() called at [/home/mysite/global.php:607]
#1  include(/home/mysite/global.php) called at [/home/mysite/showthread.php:104]

**Comment by Orvid** [comment] 2016-06-13 02:07
The PHP stacktrace isn't much help, we'd need the native stacktrace. It looks like the error is occurring inside the code that is being passed to eval.

**Comment by Karabaja** [comment] 2016-06-14 09:52
Is there a way for me to get native stack trace without rebuilding, like add something in INI files. It's a live site and I'd rather not cause additional downtime. 
Is there a way for me to automate hhvm restart since these crashes don't happen that often. 
I guess I could come up with some bash script that will tail the error log and restart if it finds segmentation fault. But I was wondering if there is another way.

**Comment by kristapsk** [comment] 2016-06-15 11:57
We use the these scripts for auto-restarts. They are for Gentoo Linux but should not be a big problem to modify for other distributions. https://github.com/skyfms/gentoo-hhvm-scripts

**Comment by Vahanerevan** [comment] 2016-07-07 22:11
You  can use  foreverjs .

**Comment by fcorriga** [comment] 2016-08-02 16:27
... or monit.

**Comment by alex-mashin** [comment] 2016-08-19 15:23
I use `etc/cron.d/restart-hhvm`:
```
#
# restart HHVM if crashed
* *     * * *   root    /var/www/restart_hhvm >/dev/null
```
and `/var/www/restart_hhvm`:
```
#!/bin/bash
if [[ ! "$(/usr/sbin/service hhvm status)" =~ "active (running)" ]]
then
    /usr/sbin/service hhvm force-reload
else
    echo "HHVM is already running!"
fi
```
under Ubuntu 16.04 to poke HHVM with a stick. You may need to adjust the regex according to `sudo service hhvm status` output when HHVM is gead and cold.

Unfortunately, sometimes HHVM has the appearance of being alive, but is dead (Rev. 3:1), utilising about 0% or 100% of CPU but effectively being hung. To deal with such cases, you also need to restart HHVM hourly or more often unconditionally.

**Comment by aorenste** [comment] 2016-09-29 16:21
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by aorenste** 2016-09-29 16:21 UTC
Labels: crash, needs more info
