### ISSUE TITLE
install_fastcgi.sh reset my apache config

### ISSUE THREAD

**Issue by paska27** [facebook/hhvm#6277] opened 2015-09-19 19:19 UTC
Hey,

Getting started guide says "Our included script sudo /usr/share/hhvm/install_fastcgi.sh will configure nginx correctly for stock installs". But doesn't mention it will also (re)configure apache !
It overwrote my config and now i have to restore the stuff ... :(

**Comment by jwatzman** [comment] 2015-09-26 06:45
Sorry about that... none of us here are really apache users. If you want to submit a PR against the [packaging repo](https://github.com/hhvm/packaging) (the script in question [lives here](https://github.com/hhvm/packaging/tree/master/hhvm/deb/skeleton/usr/share/hhvm)) to fix the problem, that would be awesome.

**Comment by Orvid** [comment] 2016-09-28 22:45
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-28 22:45 UTC
