### ISSUE TITLE
Unable to Issue External Commands

### ISSUE THREAD

**Issue by Haravikk** [facebook/hhvm#6622] opened 2015-12-02 18:08 UTC
I'm unable to use any of the functions for executing external commands, such as: `exec()`, `passthru()` and `system()`.

All of these functions are defined, but when called result in an entry in the error log like so:

    Warning: Unable to execute 'echo "Foo"' in <file> on line <line>

Even extremely simple commands like this aren't working, so it doesn't appear to be an issue with path restrictions or permissions.

I've confirmed that `hhvm.server.whitelist_exec` is turned off, which seems like the only option that should prevent the use of external commands, is there something else that could be causing this problem?

I'm using HHVM 3.10.1 with nginx 1.8.0 on Ubuntu Server 14.04

**Comment by Haravikk** [comment] 2015-12-02 18:14
Nevermind, it seems that although `hhvm.server.whitelist_exec` appeared blank (which I took to mean off) in `phpinfo` it seems that it was indeed on, setting it to off explicitly appears to have resolved this issue.

That said, I'd like to recommend that the error message be altered to clarify why the command failed to execute (i.e- execute etc. not on whitelist), or that the functions be removed if disabled, such that `function_exists()` can be used to verify if they are enabled (I've seen a number of scripts that do this that will therefore fail mysteriously with HHVM's behaviour).

**Comment by Haravikk** [comment] 2015-12-02 19:26
Scratch that "nevermind"; external commands are failing intermittently. Sometimes they work, other times they just fail without error, there's definitely some major problem with issuing external commands through HHVM.

**Comment by fredemmott** [comment] 2015-12-18 20:12
Sorry; given that we have no other reports of this and can't reproduce the problem, we're not going to be able to act on this. If you can provide an isolated example (even if it's intermittent, we're happy to run it a few thousand times), we can look at this.

**Comment by Haravikk** [comment] 2015-12-18 20:55
I can't seem to either; it appears to be behaving itself once again, so I'm at a loss as to why it was failing. 

I guess I'll just have to keep an eye on it and see if it happens again; all I know is that while vanilla PHP (which I hadn't uninstalled at that point) ran a command just fine, HHVM wouldn't, and even after removing vanilla PHP HHVM still wasn't executing external commands.

But now it seems perfectly happy to run thousands of them in rapid succession, so I have no idea what's going on. For now I suppose I'll add some kind of logging of failures to my script, and have another process monitor the log-file so that I can capture some extra data about load etc., though I'm not sure what to look for really as it's a complete head-scratcher.

Could be that it wasn't HHVM's fault at all and somehow vanilla PHP was just getting preferential treatment, or sheer dumb luck. Not very scientific though!

**Comment by fredemmott** [comment] 2016-01-14 18:12
Closing as not evidence that there was an HHVM issue here.

**Closed by fredemmott** 2016-01-14 18:12 UTC
Labels: no isolated repro
