### ISSUE TITLE
Throwing PDOException if comment within PDOStatement::prepare query produced

### ISSUE THREAD

**Issue by nokitakaze** [facebook/hhvm#5092] opened 2015-03-28 20:00 UTC
This code makes HHVM throws PDOException "Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute"

```php
<?php
    header('Content-type: text/plain; ');

    try {
        $pdo = new PDO(
            'mysql:host='.$this->options->database->host.';dbname='.$this->options->database->db,
            $this->options->database->login,
            $this->options->database->password);
    } catch (PDOException $e) {
        echo "\nCan not connect\n";
        var_dump($e);

        return;
    }

    echo "\nbefore\n";
    try {
        //$sth = $pdo->prepare('set @foo=?; --');
        $sth = $pdo->prepare('select * from (select "bar" as `ret`) as `a` where CONNECTION_ID()=?; --');
        $sth->execute(array(183));
        $q = $pdo->query('select connection_id();');
    } catch (PDOException $e) {
        echo "\nPDO Exec exception\n";
        var_dump($e);

        return;
    }
    echo "\nafter\n";
?>
```

You can see result on that pages:
http://a.ascet.g.kanaria.ru/test/pdo-unbuf-query.php PHP Impementation
http://h.ascet.g.kanaria.ru/test/pdo-unbuf-query.php HHVM Implementation

```
HipHop VM 3.5.1 (dbg)
Compiler: tags/HHVM-3.5.1-0-gb723e67c88bc008676687a04dff00db1faf250b3
Repo schema: a395edf8708632a3d09f417dbd9b1bd1d5b50bbe
```

I think this is not the same issue as #4141.

**Comment by Orvid** [comment] 2016-09-30 21:25
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:25 UTC
