### ISSUE TITLE
Leaked AsyncMysqlClient when the pool is static

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#6653] opened 2015-12-11 22:22 UTC
I've got an `AsyncMysqlConnectionPool` as a static attribute on a class and, whenever the script exits, I get a dump about how the `AsyncMysqlClient` has a reference and is being leaked.

This example, which produces the exact same error output, uses a static variable rather than a static attribute on a class. If I use a non-static variable, then the error isn't dumped.

```hack
<?hh

async function run() {
  static $pool = null;
  if ($pool === null) {
    $pool = new AsyncMysqlConnectionPool(['pool_connection_limit' => 10]);
  }

  $con = await $pool->connect('127.0.0.1', 3306, 'mysql', 'homestead', 'secret');
  return await $con->query('SHOW TABLES');
}

var_dump(run()->getWaitHandle()->join()
```

```
$ hhvm --version
HipHop VM 3.11.0 (rel)
Compiler: tags/HHVM-3.11.0-0-g3dd564a8cde23e3205a29720d3435c771274085e
Repo schema: 52047bdda550f21c2ec2fcc295e0e6d02407be51
$ hhvm test.php 
object(AsyncMysqlQueryResult)#7 (0) {
}
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1211 22:18:29.107916  6587 Singleton-inl.h:134] Singleton of type N8facebook6common12mysql_client16AsyncMysqlClientE has a living reference at destroyInstances time; beware! Raw pointer is 0x7f95c13bff80. It is very likely that some other singleton is holding a shared_ptr to it. Make sure dependencies between these singletons are properly defined.
E1211 22:18:29.115344  6587 Singleton.cpp:41] Singletons of the following types had living references after destroyInstances was finished:
	N8facebook6common12mysql_client16AsyncMysqlClientE
beware! It is very likely that those singleton instances are leaked.
```

**Comment by fredemmott** [comment] 2015-12-11 22:32
cc @drilibo

**Comment by JoelMarcey** [comment] 2015-12-11 22:34
Unrelated probably, but why aren't you using `HH\Asio\join(run())` instead of explicitly grabbing wait handles and stuff?

**Comment by simonwelsh** [comment] 2015-12-11 22:38
Cause I can never remember what namespace it's in ;)

**Comment by aloiret** [comment] 2016-02-04 00:53
I ran into the same issue bit with a different code.

```php
<?hh

class pool {
    private AsyncMysqlConnectionPool $pool;

    public function __construct() {
        $this->pool = new AsyncMysqlConnectionPool(['pool_connection_limit' => 10]);
    }

    public async function connect(): Awaitable<AsyncMysqlConnection> {
        return await $this->pool->connect('127.0.0.1', 3306, 'db', 'user', 'passwd');
    }

    public async function query(string $query): Awaitable<AsyncMysqlQueryResult> {
        $connection = await $this->connect();
        return await $connection->query($query);
    }
}

// This is OK.
async function run(): Awaitable<void> {
    $pool = new pool();
    await $pool->query ('SHOW TABLES');
}
\HH\Asio\join(run());

// This is OK.
class test1 {
    public async function run(): Awaitable<void> {
        $pool = new pool();
        await $pool->query ('SHOW TABLES');
    }
}
$test = new test1();
\HH\Asio\join($test->run());

// This is not OK.
$pool = new pool();
\HH\Asio\join($pool->query('SHOW TABLES'));

// This is not OK.
class test2 {
    public pool $pool;
    public function __construct () {
        $this->pool = new pool();
    }

    public async function run(): Awaitable<void> {
        await $this->pool->query ('SHOW TABLES');
    }
}
$test = new test2();
\HH\Asio\join($test->run());
```

The first two `join`s are find. Any of the other two triggers:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0204 00:34:44.097833 30000 Singleton-inl.h:134] Singleton of type N8facebook6common12mysql_client16AsyncMysqlClientE has a living reference at destroyInstances time; beware! Raw pointer is 0x69b784865300. It is very likely that some other singleton is holding a shared_ptr to it. Make sure dependencies between these singletons are properly defined.
E0204 00:34:44.103170 30000 Singleton.cpp:41] Singletons of the following types had living references after destroyInstances was finished:
        N8facebook6common12mysql_client16AsyncMysqlClientE
beware! It is very likely that those singleton instances are leaked.
```

HHVM version is:
```
HipHop VM 3.11.1 (rel)
Compiler: tags/HHVM-3.11.1-0-g64d37362bc0b6aee919492ad61cf65ce0a5d5e92
Repo schema: 8b80ba45250a6669cd610c189dbbb55b6218c2a3
```

Is there something wrong with the code or is it a bug?

**Comment by aloiret** [comment] 2016-02-04 01:11
Two additional informations.

The problem occurs when running HHVM from the command line. It looks like it doesn't occur when running over FastCGI.

Setting the object holding the pool to `null` fixes the leak. For example, in the code pasted over, add the line:

```
$test = new test2();
\HH\Asio\join($test->run());
$test = null; // Fixes the leak
```

**Comment by aorenste** [comment] 2016-09-27 22:38
I cannot reproduce this in 3.14. Closing.

**Closed by aorenste** 2016-09-27 22:38 UTC

**Comment by inche-ali** [comment] 2016-10-30 22:39
our hhvm version 3.14.5 
seems like they need to open the issue..

**Comment by paulbiss** [comment] 2016-10-31 20:10
3.14 is no longer supported, are you seeing this problem with 3.12, 3.15, or master?
