### ISSUE TITLE
Getting blank page on phpmyadmin AFTER login

### ISSUE THREAD

**Issue by afritsch** [facebook/hhvm#4975] opened 2015-03-07 17:10 UTC
After searching around the interwebs the issue seems to be connected to the mysqli extension.
none of the workarounds I found, works (e.g. adding port number to the phpmyadmin config).
No errors in the logs, I just get a blank page, while other services like wordpress and codiad just work fine.
Using nginx which communicates with a socket to hhvm (/var/run/hhvm/hhvm.sock). the database is mysql (mariadb).
nginx/1.6.2, HipHop VM 3.5.1 (rel), mysql  Ver 15.1 Distrib 10.0.17-MariaDB

If additional infos are required I will be glad to provide them.

**Comment by bauerj** [comment] 2015-03-10 12:53
phpmyadmin works for me. Which version of phpmyadmin have you tried?

Have you checked `/var/log/hhvm/error.log` and not `/var/log/nginx/error.log`?

**Comment by afritsch** [comment] 2015-03-10 18:16
Sorry I forgot to mention the phpmyadmin version, it's the most recent stable, 4.3.11.1.

Yes, I checked both error logs you mentioned. as I said, sadly nothing  appears there (there is an error for roundcube though, which seems to be roundcube's fault).
The entries in the hhvm error log I assume are normal behaviour.
```
Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5
```

I also rechecked the configs, everything appears to be fine.

**Comment by adams-david** [comment] 2015-09-10 13:29
If you follow the simple instructions at https://www.rosehosting.com/blog/how-to-install-phpmyadmin-with-hhvm-nginx-and-mariadb-on-an-ubuntu-14-04-vps/ , like I did, you should be able to install and use phpMyAdmin with HHVM, Nginx and MariaDB in no time.

**Comment by afritsch** [comment] 2015-09-10 14:09
Sadly that guide is mostly useless since my server runs Arch Linux. Yet I compared it with my config files and I did not find anything out of order (only that my stack is interconnected via sockets, not tcp).
I am still getting a blank page after all this time with up to date components. Funnily, when viewing the page source of the blank page, there is a lot while being blank.
I've been using adminer with no issues in the mean time.

My current versions are 
nginx version: nginx/1.8.0
mysql  Ver 15.1 Distrib 10.0.21-MariaDB, for Linux (x86_64) using readline 5.1
phpmyadmin: 4.4.13.1-1
hhvm: 3.9.0-2

If it helped, I will gladly provide any log or configuration snippets if you give me some directions.

**Comment by bauerj** [comment] 2015-09-10 14:12
> Funnily, when viewing the page source of the blank page, there is a lot while being blank.

What is "a lot"? A lot of whitespaces? A lot of HTML? A lot of error messages? Can you post what you're seeing there?

**Comment by afritsch** [comment] 2015-09-10 14:18
Sorry, that statement was unprecise. take a look, the source of the blank page: http://pastebin.com/yYvfyx4W
I have no idea why the result is blank.

**Comment by adams-david** [comment] 2015-09-10 14:32
Edit your config.inc.php file and add the following line:

$cfg['Servers'][$i]['port'] = '3306';

**Comment by bauerj** [comment] 2015-09-10 14:59
You can also try to run index.php from CLI:

    hhvm index.php

Maybe that will show an error.

**Comment by afritsch** [comment] 2015-09-10 15:18
that file does not exist there (maybe ubuntu has an outdated phpmyadmin?) and I am not sure if I can add something in the file i found below. A future update would break it anyway again (overwrite).
```fish
root@ouwsome ~# mcedit /usr/share/webapps/phpMyAdmin/libraries/dbi/
…ries/dbi/DBIDrizzle.class.php  …ries/dbi/DBIExtension.int.php  …ries/dbi/DBIMysqli.class.php
…ries/dbi/DBIDummy.class.php    …ries/dbi/DBIMysql.class.php    …ries/dbi/drizzle-wrappers.lib.php
root@ouwsome ~# grep -r logging.lib.php /usr/share/webapps/phpMyAdmin/
/usr/share/webapps/phpMyAdmin/libraries/DatabaseInterface.class.php:require_once './libraries/logging.lib.php';
/usr/share/webapps/phpMyAdmin/libraries/common.inc.php:        include_once './libraries/logging.lib.php';
```
Also, how should adding a port help for a socket connection?
I disabled tcp/ip in my.cnf ("skip-networking").
Also, my phpmyadmin config look like this:
/etc/webapps/phpmyadmin/config.inc.php:
```php
/* Server parameters */
// $cfg['Servers'][$i]['host'] = 'localhost';
// $cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['socket'] = '/run/mysqld/mysqld.sock';
// $cfg['Servers'][$i]['port'] = '3306';
```

**Comment by bauerj** [comment] 2015-09-10 15:21
Oh - so the error occurs after you log in?

**Comment by afritsch** [comment] 2015-09-10 15:22
Indeed, this is what the issue title says ;-)

**Comment by bauerj** [comment] 2015-09-10 15:37
Okay, now I see it :smile: 

I suspect the error has something to do with sockets.

When HHVM encounters an error, it doesn't show it to the browser but instead send a blank 500 response. I think that's what's hapenning here.

If phpmyadmin works with PHP5, it's clearly a bug in HHVM and should be solved. To debug this, more information is needed, like the original error message.

There are a few methods to get an error message in HHVM:
Firstly, you can register a custom error handler (like explained in @Yogu's post in #4818).
Secondly, which might be better, you can just look at the error log to get the message. As you stated that there is no such message in the log, I think it's a configuration issue.

Something like this (in `server.ini`, for example) should give you a log file with the relevant output:


    hhvm.log.level = Warning
    hhvm.log.always_log_unhandled_exceptions = true
    hhvm.log.use_log_file = true
    hhvm.log.file = /var/log/hhvm/error.log
    hhvm.log.header = true

**Comment by iamkingsleyf** [comment] 2015-10-06 21:58
I am having same problem

**Comment by alex-mashin** [comment] 2016-07-24 04:45
Looks like since about HHVM 3.12, phpmyadmin is totally broken, A whole lot in type mismatches.

**Comment by Orvid** [comment] 2016-09-30 21:47
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:47 UTC
