### ISSUE TITLE
HHVM-3.3.0 Core dumped: Aborted - stack trace

### ISSUE THREAD

**Issue by soundslocke** [facebook/hhvm#3902] opened 2014-10-03 15:03 UTC
We've been running HHVM in production for a few weeks to great effect. Unfortunately it randomly crashed this morning with the line "Core dumped: Aborted". The PHP function it crashed on is a simple text parsing/printing function, called frequently.

The stack trace message mentions "increasing Eval.JitASize, Eval.JitAColdSize, Eval.JitAFrozenSize and Eval.JitGlobalDataSize" -- is there a page somewhere documenting these and/or recommendations on values?

Here's the stack trace:

```
ProcessID: 26834
ThreadID: 7ff179bff700
ThreadPID: 26845
Name: unknown program
Type: Aborted
Runtime: hhvm
Version: tags/HHVM-3.3.0-0-g0a3cfb87b8a353fc7e1d15374f4adc413e37aba9
DebuggerCount: 0

Failed Assertion: /tmp/tmp.0fAfwqfjdP/hphp/runtime/vm/jit/translator.cpp:1937: HPHP::jit::Translator::TranslateResult HPHP::jit::Translator::translateRegion(const HPHP::jit::RegionDesc&, bool, HPHP::jit::Translator::RegionBlacklist&, HPHP::jit::TransFlags): assertion `0' failed.
URL: /
Server: www.gigsalad.com
0: data block = cold
message: Attempted to emit 19 byte(s) into a 69 byte DataBlock with 14 bytes available. This almost certainly means the TC is full. If this is the case, increasing Eval.JitASize, Eval.JitAColdSize, Eval.JitAFrozenSize and Eval.JitGlobalDataSize in the configuration file when running this script or application should fix this problem.

Server_SERVER_NAME: www.gigsalad.com
ThreadType: Web Request

# 0  gsignal at /lib/x86_64-linux-gnu/libc.so.6:0
# 1  abort at /lib/x86_64-linux-gnu/libc.so.6:0
# 2  HPHP::assert_fail(char const*, char const*, unsigned int, char const*) at /usr/bin/hhvm:0
# 3  HPHP::jit::Translator::translateRegion(HPHP::jit::RegionDesc const&, bool, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags) at /usr/bin/hhvm:0
# 4  HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 5  HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 6  HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 7  HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 8  HPHP::jit::MCGenerator::getCallArrayPrologue(HPHP::Func*) at /usr/bin/hhvm:0
# 9  HPHP::jit::funcBodyHelper(HPHP::ActRec*, void*) at /usr/bin/hhvm:0
# 10 HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) at /usr/bin/hhvm:0
# 11 HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) at /usr/bin/hhvm:0
# 12 HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) at /usr/bin/hhvm:0
# 13 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at /usr/bin/hhvm:0
# 14 HPHP::ExecutionContext::createFunction(HPHP::String const&, HPHP::String const&) at /usr/bin/hhvm:0
# 15 HPHP::f_create_function(HPHP::String const&, HPHP::String const&) at /usr/bin/hhvm:0
# 16 HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) at /usr/bin/hhvm:0
# 17 HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) at /usr/bin/hhvm:0
# 18 HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) at /usr/bin/hhvm:0
# 19 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at /usr/bin/hhvm:0
# 20 HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at /usr/bin/hhvm:0
# 21 HPHP::invoke_file(HPHP::String const&, bool, char const*) at builtin-functions.cpp:0
# 22 HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at /usr/bin/hhvm:0
# 23 HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at /usr/bin/hhvm:0
# 24 HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) at /usr/bin/hhvm:0
# 25 HPHP::HttpRequestHandler::handleRequestImpl(HPHP::Transport*) at /usr/bin/hhvm:0
# 26 HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) at /usr/bin/hhvm:0
# 27 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) at /usr/bin/hhvm:0
# 28 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) at /usr/bin/hhvm:0
# 29 HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() at /usr/bin/hhvm:0
# 30 HPHP::AsyncFuncImpl::ThreadFunc(void*) at /usr/bin/hhvm:0
# 31 start_thread at /lib/x86_64-linux-gnu/libpthread.so.0:0
# 32 clone at /lib/x86_64-linux-gnu/libc.so.6:0
```

**Comment by Orvid** [comment] 2016-04-29 19:31
Closing as duplicate of #2851.

**Closed by Orvid** 2016-04-29 19:31 UTC
Labels: crash, documentation, duplicate
