### ISSUE TITLE
ReflectionMethod::__toString with variadics throws ReflectionException

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#7624] opened 2017-01-26 15:57 UTC
See https://3v4l.org/qUaQE

```php

class FooVariadic
{
    public function __construct(Foo $foo)
    {
    }

    public function bar(...$arguments)
    {
    }
}

$r = new ReflectionMethod('FooVariadic', 'bar');

echo $r;
```

```
    Fatal error: Uncaught exception 'ReflectionException' with message 'Parameter is not optional' in /in/qUaQE:17
    Stack trace:
    #0 (): ReflectionParameter->getDefaultValue()
    #1 (): ReflectionParameter->__toString()
    #2 (): ReflectionFunctionAbstract->__toStringHelper()
    #3 /in/qUaQE(17): ReflectionMethod->__toString()
    #4 {main}

    Process exited with code 255.
```

**Comment by mofarrell** [comment] 2017-01-26 16:10
This is a duplicate of this issue: https://github.com/facebook/hhvm/issues/5762

**Closed by mofarrell** 2017-01-26 16:10 UTC
Labels: duplicate
