### ISSUE TITLE
Unexpected breakage in 3.18.0 involving classname<Tfoo> and instanceof

### ISSUE THREAD

**Issue by pbl64k** [facebook/hhvm#7690] opened 2017-02-23 09:50 UTC
### HHVM Version

3.18.0

### Standalone code, or other way to reproduce the problem

We've been relying on similar code in our persistence layer, but after moving from 3.12.0 to 3.18.0 we've started receiving type checking errors which seem nonsensical to me. 3v4l.org seems to indicate that this worked up until and including 3.17.1, so the change in behavior is probably in 3.18.0. I don't see how type erasure can affect this, as neither `$cn` nor `$val` are of a generic type. It's possible that I'm missing some subtle loophole that would allow unsafe behavior, but it seems safe to me. The change has been highly inconvenient, as we've had to resort to very fugly workarounds to deal with this.

    <?hh // strict

    interface A
    {
    }

    function cast<T as A>(classname<T> $cn, mixed $val): ?T
    {
        return $val instanceof $cn ? $val : null;
    }

### Expected result

    No errors!

### Actual result

    test.hh:9:12,30: 'instanceof' cannot be used on a generic classname because types are erased at runtime (Typing[4162])

**Comment by andrewjkennedy** [comment] 2017-02-23 10:36
This has been reported in https://github.com/facebook/hhvm/pull/7632. The message is misleading, but the problem is real: `instanceof` on a `classname<T>` isn't sound, because `T` can be instantiated with a type (e.g. `List<int>`) some of which gets erased (to `List`) at runtime.

**Comment by pbl64k** [comment] 2017-02-23 11:04
I reported this very unsoundness problem with `instanceof` and type erasure in #6407. And it *still* breaks, despite the fact that in that case it's known at compile time that the type to the right of `instanceof` is generic. And yet this particular case (which is used safely in practice) no longer type checks. What gives?

**Comment by pbl64k** [comment] 2017-02-27 22:59
Can anyone perhaps clarify the status of this issue? It's been closed, then reopen, then marked duplicate but kept open.

I can't come up with an explanation as to why a straightforward, guaranteed-broken case described in #6407 remains broken, but the behavior described in this issue is now caught by the type checker. I think that for consistency's sake either both need to be fixed, or `instanceof` should remain unchecked for this particular cause of potential unsoundness altogether.

**Comment by andrewjkennedy** [comment] 2017-02-28 00:54
Commit https://github.com/facebook/hhvm/commit/603cbd7cbf79f059365a1ff7787fef7b193e7ec3 puts the rejection of classname<T> under the same experimental flag as the "safe instanceof" feature that supports instanceof on generic classes in a safe way. If the flag isn't set, the old behaviour is maintained.

**Comment by pbl64k** [comment] 2017-02-28 08:52
That sounds reasonable. Would it make sense to close this issue then? As well as #6407, for that matter?

**Comment by mofarrell** [comment] 2017-03-13 19:09
I'm going to close this one.  The other issues might be worth keeping open and pointing people towards https://github.com/facebook/hhvm/commit/603cbd7cbf79f059365a1ff7787fef7b193e7ec3.

**Closed by mofarrell** 2017-03-13 19:09 UTC
Labels: duplicate
