### ISSUE TITLE
assertion with self:: fails

### ISSUE THREAD

**Issue by bcopeland** [facebook/hhvm#6862] opened 2016-02-25 21:37 UTC
In 3.12+, we have noticed that some uses of self:: are no longer handled the same as in PHP or earlier hhvm.  For example:

```
class X {
// ...
public static function y() {
    $x = new X();
    assert('$x instanceof self');  // fails
  }
}
```

Full reproducer here:

https://3v4l.org/gldpC

**Comment by SiebelsTim** [comment] 2016-02-26 08:52
This never worked.
https://3v4l.org/Xpika

**Comment by bcopeland** [comment] 2016-02-26 13:14
I see -- so default settings around asserts changed?  I removed the "regression" from the title.

**Comment by bcopeland** [comment] 2016-02-26 15:28
Here's a similar issue where $this is not evaluated in the assert.  I've disabled assertions in our code as a workaround.

https://3v4l.org/S4eA6

**Comment by spekary** [comment] 2016-03-01 16:02
Having the same issue. This is a new problem with the latest release.

```
				assert ('!empty($this->strAlias)');
```
now fails, whereas
```
				assert (!empty($this->strAlias));
```
succeeds.

Before upgrading to v 3.12.0 both succeeded.

**Comment by spekary** [comment] 2016-03-01 16:15
Confirmed that this is still the case with 3.12.1

**Comment by Orvid** [comment] 2016-03-14 17:42
Closing as not an issue.

**Comment by bcopeland** [comment] 2016-03-14 17:50
Could you at least close it as wontfix :)  Very clearly it's a compat difference with PHP...

**Comment by SiebelsTim** [comment] 2016-03-14 18:05
@Orvid This is very much an issue. This is incompatible with php5 and php7.

**Comment by Orvid** [comment] 2016-03-14 19:00
Ah, whoops, missed what this actually was.

This is an issue and does need to be fixed.

**Comment by aorenste** [comment] 2016-09-28 23:02
It looks like php 7.1rc* has dropped support for this (although that may have been a mistake): https://3v4l.org/bhR3n

**Comment by lexidor** [comment] 2020-05-25 10:55
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

In Hack, `self` is not a type. I believe hhvm starts looking for a class named "self" instead. Since that class does not does not exist, the assertion fails.

You get the same error from this assertion: `assert($x is nonexistant);`.
If you want to assert that something is an `X`, use `$x is X` or `$x is this` when in the class context of X.

**Closed by lexidor** 2020-05-25 10:55 UTC
Labels: php5 incompatibility, php7 incompatibility
