### ISSUE TITLE
HHVm 3.6.0 - MySQL PDO not respecting socket path

### ISSUE THREAD

**Issue by keepxtreme** [facebook/hhvm#4987] opened 2015-03-10 12:25 UTC
starting with 3.6.0 I observed a problem using localhost-connections. Further investigations proofed HHVM using a different default path (now: /tmp/mysql.sock) while it's /var/run/mysqld/mysqld.sock in debian by default.

I set the "hhvm.mysql.socket" to that path in HHVMs php.ini and most pages started working correctly however Drupal still doesn't.
Finally I found the reason (well, I hope): Drupal is using the PDO-Extension which still searches the wrong path for the socket due not respectiong hhvm.mysql.socket:
````
\nFatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)' in :\nStack trace:\n#0 /var/www/extern/includes/database/database.inc(307): PDO->__construct()\n#1 /var/www/extern/includes/database/mysql/database.inc(51): DatabaseConnection->__construct()\n#2 /var/www/extern/includes/database/database.inc(1689): DatabaseConnection_mysql->__construct()\n#3 /var/www/extern/includes/database/database.inc(1479): Database::openConnection()\n#4 /var/www/extern/includes/database/database.inc(2350): Database::getConnection()\n#5 /var/www/extern/includes/bootstrap.inc(1933): db_query()\n#6 /var/www/extern/includes/bootstrap.inc(1946): drupal_is_denied()\n#7 /var/www/extern/includes/bootstrap.inc(2397): drupal_block_denied()\n#8 /var/www/extern/includes/bootstrap.inc(2252): _drupal_bootstrap_page_cache()\n#9 /var/www/extern/index.php(20): drupal_bootstrap()\n#10 {main}
````

I solved this using a symlink however this should be fixed cause it's realy confusing

**Comment by daankortenbach** [comment] 2015-03-10 12:51
Temporary fix by editing `/etc/hhvm/php.ini` and add: `hhvm.mysql.socket = /var/run/mysqld/mysqld.sock`.

**Comment by keepxtreme** [comment] 2015-03-10 12:53
please read again - I did it already (and yesm restarted HHVM). It works for mysql & mysqli but not for pdo

**Comment by daankortenbach** [comment] 2015-03-10 12:56
Have you configured HHVM with PDO?
http://docs.hhvm.com/manual/en/ref.pdo-mysql.php

**Comment by keepxtreme** [comment] 2015-03-10 12:58
I'm using the package provided in HHVMs repository for debian

**Comment by daankortenbach** [comment] 2015-03-10 12:59
Did you try to set `pdo_mysql.default_socket` in php.ini?

**Comment by keepxtreme** [comment] 2015-03-10 13:11
no, thanks for the help, man. However, it'S default should be equal to hhym.mysql.socket

**Comment by daankortenbach** [comment] 2015-03-10 13:27
Can't help you further other than pointing you to:
http://docs.hhvm.com/manual/en/pdo.installation.php
http://docs.hhvm.com/manual/en/ref.pdo-mysql.php

**Comment by keepxtreme** [comment] 2015-03-10 14:00
as I mentioned, it's a bug: this setting isn't taken in account and if I create a symlink pointing from /tmp/mysql.sock => /var/run/mysqld/mysqld.sock it's working

**Comment by fcorriga** [comment] 2015-03-10 16:33
confirmed. hhvm ignores the default_socket directives in ini files except for hhvm.mysql.socket. but that's not enough for PDO.

**Comment by markggn** [comment] 2015-03-10 16:34
Same here. Pointing to /var/run/mysqld/mysqld.sock in /etc/hhvm/php.ini works for me.

**Comment by keepxtreme** [comment] 2015-03-10 16:38
@markggn did you try with PDO? running 3.6.0?

**Comment by markggn** [comment] 2015-03-10 16:51
Yes, 3.6.0. All I did was adding the line to /etc/hhvm/php.ini. As I wrote, that worked for me.

**Comment by fcorriga** [comment] 2015-03-10 17:11
ok, PDO seems to work

**Comment by keepxtreme** [comment] 2015-03-10 17:14
@markggn problem occurs only in application using PDO, mysql & mysqli are influenced by the option, PDO has its own defalt_socket setting  (see above) which has no effect for me

**Comment by jg-development** [comment] 2015-03-10 17:39
I can confirm this. The only solution was a symlink. The "hhvm.mysql.socket = /var/run/mysqld/mysqld.sock" doesnt work for me or at least not for all applications.

**Comment by the-infinity** [comment] 2015-03-10 19:55
I also had to symlink because all three options did not work:
pdo_mysql.default_socket = /run/mysqld/mysqld.sock
mysqli.default_socket = /run/mysqld/mysqld.sock
hhvm.mysql.socket = /run/mysqld/mysqld.sock

**Comment by MarkGavalda** [comment] 2015-03-11 01:04
I can confirm, with WordPress 4.1. Setting **hhvm.mysql.socket = /var/run/mysqld/mysqld.sock** is not enough, you need a symlink.

**Comment by ChrisWiegman** [comment] 2015-03-11 02:05
I'll also confirm. Took me way to long of beating my head against a wall to come up with a workaround. The following in /etc/hhvm/php.ini on Ubuntu 14.10 worked for me:

hhvm.mysql.socket = /var/run/mysqld/mysqld.sock
hhvm.pdo_mysql.socket = /var/run/mysqld/mysqld.sock
hhvm.mysqli.socket = /var/run/mysqld/mysqld.sock

**Comment by paulbiss** [comment] 2015-03-11 02:06
@fredemmott: Could this be related to the switch to webscalesql?

**Comment by gordboy** [comment] 2015-03-11 02:22
Thanks ChrisWiegman I was going bananas trying to fix this. Part of the problem is that it does not say _anywhere_ that you need to prefix settings with hhvm. in the php.ini file. It might be obvious to some, but my powers of telepathy are limited :)

**Comment by keepxtreme** [comment] 2015-03-11 06:09
@ChrisWiegman thanks for the hint, however, PDO still isn't respecting this setting
@paulbiss can you add the Documentation label as well?

**Comment by jeroenvermeulen-eu** [comment] 2015-03-11 09:15
I am running Magento 1.9.0.1 on HHVM 3.6.0, Nginx 1.4.6, Ubuntu 14.04
I tried all this:
```
hhvm.mysql.socket              = /var/run/mysqld/mysqld.sock
hhvm.mysql.default_socket      = /var/run/mysqld/mysqld.sock
hhvm.mysqli.socket             = /var/run/mysqld/mysqld.sock
hhvm.mysqli.default_socket     = /var/run/mysqld/mysqld.sock
hhvm.pdo_mysql.socket          = /var/run/mysqld/mysqld.sock
hhvm.pdo_mysql.default_socket  = /var/run/mysqld/mysqld.sock
mysql.socket                   = /var/run/mysqld/mysqld.sock
mysql.default_socket           = /var/run/mysqld/mysqld.sock
mysqli.default_socket          = /var/run/mysqld/mysqld.sock
mysqli.socket                  = /var/run/mysqld/mysqld.sock
pdo_mysql.socket               = /var/run/mysqld/mysqld.sock
pdo_mysql.default_socket       = /var/run/mysqld/mysqld.sock
```
But it keeps saying:
`SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)`
The only solution is the symlink:
`ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock`

**Comment by CremboC** [comment] 2015-03-11 09:52
From my experience a workaround for this is to set the host as ```127.0.0.1``` instead of ```localhost```. Obviously, in this case it will not use sockets, which may be slower (according to MySQL docs).

**Comment by gordboy** [comment] 2015-03-11 10:49
@CremboC yes this is an option but it meant going through all the sites, and finding every instance and changing it and commenting the old line out, ready to be re-instated when HHVM stops playing silly-beggars. I tried this.

The other obvious fix is to ditch HHVM and go back to php-fpm, which doesn't change the settings at a whim without any warning, thus breaking all the sites. I also tried this.

Issuing this release as a so-called LTS is a joke. I'm sorry for the harsh words, but this simply WILL NOT DO. If this happens again, we will be parting company. It is the most basic and fundamental rule of updates that you do not break absolutely everything and leave all the sites broken, necessitating costly and time-consuming fixes.

**Comment by Backenkoehler** [comment] 2015-03-11 13:31
I had the same problem with a wordpress instance on Ubuntu 14.04. Setting `hhvm.mysql.socket = /var/run/mysqld/mysqld.sock` in the php.ini worked for me.

**Comment by bauerj** [comment] 2015-03-11 14:57
Maybe this is what's happening here:
1. [cmake sets  `MYSQL_UNIX_SOCK_ADDR` to /tmp/mysql.sock on the build machine](https://github.com/facebook/hhvm/blob/cb02e599fab0e24c0f8e90b2cfd64c6e72fb7c6f/CMake/HPHPFunctions.cmake#L96)
2. [This constant is then used in the PDO extension as the default socket](https://github.com/facebook/hhvm/blob/472a65bbc648162ccb6b0cf820a4f4cb7def0ba1/hphp/runtime/ext/pdo_mysql.cpp#L33)

But I couldn't test it right now so it's just a guess. I also couldn't find any recent change in the code I linked.

**Comment by jeroenvermeulen-eu** [comment] 2015-03-11 15:32
@bauerj Maybe you didn't find a change in the code because of the switch to webscalesql?

**Comment by MarkGavalda** [comment] 2015-03-11 16:17
@bauerj but that code (1) searches for a sock file location (see lines 77-93) and should use the one it finds... And at least on our machines it should definitely find one. So it should be something else IMO.

**Comment by bauerj** [comment] 2015-03-11 16:23
@MarkGavalda As I said, it's only a guess. I thought these problems would only occur if HHVM was built on another machine (e.g. the packages were installed) and not if you build it yourself.

**Comment by AbhishekGhosh** [comment] 2015-03-11 17:22
@CremboC  Agreed. My problem (WordPress with HHVM + PHP5-FPM fallback; Ubuntu 14.10 ) got solved with symlinking. No question to use any version of HHVM. Out of fear, we'll not update and upgrade and NSA will run spyware. This is NOT normal that they never tested for the common setups. WordPress with Nginx+HHVM+PHP5-FPM+MariaDB is not an exceptional setup.

**Comment by fredemmott** [comment] 2015-03-11 17:24
This doesn't look like a recent change, or to be related to webscalesql:

- pdo_mysql.cpp appears to only use the compiled-in default, empty string, or 'localhost'. I don't see anything there to look at an INI setting (based on searching the file for 'socket').
- mysqli appears to use correctly use mysqli.default_socket
- non-PDO mysql does not appear to have direct INI support - it uses the HDF support. We automatically map HDF 'Foo[Bar][Baz]' to 'hhvm.foo.bar.baz'

**Comment by fredemmott** [comment] 2015-03-11 17:31
Also, 'prefix with hhvm.' is *not* general advice. 'hhvm.' settings are not guaranteed to be compatible, and are generally a relic from our other configuration format.

Whenever you need one that isn't truly HHVM-specific (eg hhvm.force_hh is), that's a bug, not a documentation issue.

**Comment by fredemmott** [comment] 2015-03-11 17:33
@jwatzman : can you take a look at where the mysql socket is on the build machines, and what the timestamp on it is?

**Comment by MarkGavalda** [comment] 2015-03-11 17:34
@bauerj I know however I still partially misunderstood because it would seem that indeed the MySQL socket was in a different place on the build machine that produced the current .deb file and that screwed it up for everyone else who's using the default MySQL socket location.

Update:
@fredemmott exactly. The socket must be in /tmp on the build machine!

**Comment by jwatzman** [comment] 2015-03-11 17:52
@fredemmott not totally sure what you're asking, I think the below answers your question? If not, grab me in person (or on IRC if you're WFH today) and I can help you out, or just add your SSH key to the machine. I'm gone after about noon, @paulbiss and Sara also have access and can help / add you.

14.04 machine:

```
ptarjan@ubuntu1404:~$ ls -l /var/run/mysqld/mysqld.sock
ls: cannot access /var/run/mysqld/mysqld.sock: No such file or directory
ptarjan@ubuntu1404:~$ ls -l /var/tmp/mysql.sock
ls: cannot access /var/tmp/mysql.sock: No such file or directory
ptarjan@ubuntu1404:~$ ls -l /var/run/mysql/mysql.sock
ls: cannot access /var/run/mysql/mysql.sock: No such file or directory
ptarjan@ubuntu1404:~$ ls -l /var/lib/mysql/mysql.sock
ls: cannot access /var/lib/mysql/mysql.sock: No such file or directory
ptarjan@ubuntu1404:~$ ls -l /var/mysql/mysql.sock
ls: cannot access /var/mysql/mysql.sock: No such file or directory
ptarjan@ubuntu1404:~$ ls -l /usr/local/mysql/var/mysql.sock
ls: cannot access /usr/local/mysql/var/mysql.sock: No such file or directory
ptarjan@ubuntu1404:~$ ls -l /Private/tmp/mysql.sock
ls: cannot access /Private/tmp/mysql.sock: No such file or directory
ptarjan@ubuntu1404:~$ ls -l /private/tmp/mysql.sock
ls: cannot access /private/tmp/mysql.sock: No such file or directory
ptarjan@ubuntu1404:~$ ls -l /tmp/mysql.sock
ls: cannot access /tmp/mysql.sock: No such file or directory
```

Debian 7 (wheezy/stable) machine:

```
hiphop@debian7:~$ ls -l /var/run/mysqld/mysqld.sock
ls: cannot access /var/run/mysqld/mysqld.sock: No such file or directory
hiphop@debian7:~$ ls -l /var/tmp/mysql.sock
ls: cannot access /var/tmp/mysql.sock: No such file or directory
hiphop@debian7:~$ ls -l /var/run/mysql/mysql.sock
ls: cannot access /var/run/mysql/mysql.sock: No such file or directory
hiphop@debian7:~$ ls -l /var/lib/mysql/mysql.sock
ls: cannot access /var/lib/mysql/mysql.sock: No such file or directory
hiphop@debian7:~$ ls -l /var/mysql/mysql.sock
ls: cannot access /var/mysql/mysql.sock: No such file or directory
hiphop@debian7:~$ ls -l /usr/local/mysql/var/mysql.sock
ls: cannot access /usr/local/mysql/var/mysql.sock: No such file or directory
hiphop@debian7:~$ ls -l /Private/tmp/mysql.sock
ls: cannot access /Private/tmp/mysql.sock: No such file or directory
hiphop@debian7:~$ ls -l /private/tmp/mysql.sock
ls: cannot access /private/tmp/mysql.sock: No such file or directory
hiphop@debian7:~$ ls -l /tmp/mysql.sock
ls: cannot access /tmp/mysql.sock: No such file or directory
```

**Comment by fredemmott** [comment] 2015-03-11 18:04
Ah, so, this is the switch to webscalesql: https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.23.71/cmake/mysql_version.cmake#L85

Both it and MySQL default to /tmp/mysql.sock when build from source; we should pass in something different.

The behavior of the options has not changed in 3.6, just the defaults.

**Comment by fredemmott** [comment] 2015-03-11 18:07
Given the location is distribution-dependent, the right fix for the default location is probably just to install mysql-server on the build machines, and let our cmake files pick up the right location.

**Comment by fredemmott** [comment] 2015-03-11 18:08
Might also want to change our cmake to bail out if it can't find a mysql socket path.

**Comment by fredemmott** [comment] 2015-03-11 18:16
@paulbiss : why is this a documentation issue?

**Comment by paulbiss** [comment] 2015-03-11 18:20
> @paulbiss can you add the Documentation label as well?
 Presumably something to do with needing to prefix the settings with hhvm? I can remove it.

**Comment by fredemmott** [comment] 2015-03-11 18:21
This isn't fixed, but closing it as it covers at least 3 separate issues,which are now filed separately.

Not a documentation issue, prefixing settings with hhvm is not something we should document or recommend.

**Closed by fredemmott** 2015-03-11 18:21 UTC
Labels: php5 incompatibility

**Comment by Falki** [comment] 2015-03-16 13:23
Ubuntu 14.04 (Nginx + HHVM 3.6.0):

ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock

This was all i need. But on a running system not so good....

**Comment by jwatzman** [comment] 2015-03-16 14:39
This will be fixed in 3.6.1

**Comment by Fohlen** [comment] 2015-03-19 16:05
Bug confirmed under Ubuntu 14.04 binary package #4987
Using the workaround
```
hhvm.mysql.socket = /var/run/mysqld/mysqld.sock
```
is the sanest solution I found. Linking the socket may result in bugs (due to updating by the system).
Hope to see that in 3.6.1, cheers!

**Comment by cortopy** [comment] 2015-03-24 16:16
HHVM 3.6.1 released a few hours ago. I was having loads of issues with mySQL PDO. Upgrade seems to have sorted all out :)

**Comment by cortopy** [comment] 2015-03-24 16:37
HHVM 3.6.1 was released a few hours ago. I was having a lot of problems with mySQL PDO and HHVM but with new upgrade they all seem to have vanished :+1:

**Comment by Fohlen** [comment] 2015-03-25 14:21
Upgraded using Ubuntu PPA to stable 3.6.1 - works great :+1:

**Comment by dangtanxp** [comment] 2015-04-03 05:04
;fixed mariadb nginx hhvm run in centos 7; in file server.ini

; mysql MARIADB
hhvm.mysql.socket = /var/lib/mysql/mysql.sock
hhvm.mysql.typed_results = true

;[root@www ~]# ln -s /var/lib/mysql/mysql.sock /tmp/mysql.sock

ALL MY CONFIG server.ini

pid = /var/run/hhvm/pid
;hhvm.server.ip = 127.0.0.1
;hhvm.server.port = 9000
hhvm.server.file_socket = /var/run/hhvm/hhvm.sock
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.server.always_use_relative_path = false
hhvm.server.thread_count = 32
hhvm.resource_limit.max_socket = 65536
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc

hhvm.jit = true
hhvm.jit_a_size = 67108864
hhvm.jit_a_stubs_size = 22554432
hhvm.jit_global_data_size = 22554432

; mysql MARIADB
hhvm.mysql.socket = /var/lib/mysql/mysql.sock
hhvm.mysql.typed_results = true

; logging
hhvm.log.use_syslog = false
hhvm.log.use_log_file = true
hhvm.log.file = /etc/hhvm/log/error.log
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191

**Comment by simonmilz** [comment] 2015-04-15 09:12
I still get this issue with 3.6.1

**Comment by fcorriga** [comment] 2015-04-17 16:33
what OS (and version)?

**Comment by florianbeer** [comment] 2015-04-23 10:18
I just installed hhvm on my server to use it for Piwik (which is hhvm compatible according to their devs). I still have this issue, even with the proposed workaround. If I refresh the website a few times I am quickly hitting my MySQL max_connecitons limit. It seems none of the opened connections are closed afterwards.

OS: Debian 7.8
hhvm: 3.6.1~wheezy
mysqld:  5.5.40-0+wheezy1

**Comment by paulbiss** [comment] 2015-04-23 11:19
Please open a separate issue, this issue is unrelated and has been resolved.

**Comment by florianbeer** [comment] 2015-04-23 11:24
Yea, sorry I just saw afterwards that this isn't related to mysql having too many connections. Will open a new issue. Thanks!

**Comment by jg-development** [comment] 2015-04-23 16:39
Hi,
I already opened a ticket a piwik.
https://github.com/piwik/piwik/issues/7555#issuecomment-92759840
Greetings Jan
