### ISSUE TITLE
HHVM Load/Performance issue

### ISSUE THREAD

**Issue by OskHa** [facebook/hhvm#5024] opened 2015-03-15 12:47 UTC
Hello everyone,

we have some test hhvm servers, each with 8 cores.

Setup is Debian + Nginx + HHVM 3.6.

hhvm/php.ini
```
; php options
session.save_handler = memcached
session.save_path = "10.0.0.0:11211"
session.gc_maxlifetime = 86400

memcached.sess_locking = on
memcached.sess_lock_wait = 150000
memcached.sess_prefix = "memc.sess.key."

expose_php = false

; hhvm specific 
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
hhvm.enable_zend_compat = true
```

hhvm/server.ini

```
; php options

pid = /var/run/hhvm/pid

; hhvm specific 
hhvm.server.thread_count = 32
hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc

hhvm.admin_server.port = 9001
;hhvm.admin_server.password = ""

; JIT
hhvm.jit_a_size = 536870912
hhvm.jit_a_cold_size = 	268435456
hhvm.jit_a_frozen_size = 536870912
hhvm.jit_a_prof_size = 536870912
hhvm.jit_a_max_usage = 536870912
```

Health-check
```
{
 "load":32
, "queued":224
, "hhbc-roarena-capac":0
, "tc-hotsize":0
, "tc-size":413762
, "tc-profsize":175007
, "tc-coldsize":173222
, "tc-frozensize":335452
, "targetcache":6896
, "rds":6896
, "units":45
, "funcs":6676
}
```

*With php-fpm 5.6 we had even load 10, with hhvm ist never higher than 2*

# So how can we configure the server to achieve the max stress scenario ?
## How can we handle more connections ? its seems to be hhvm specific.

We tried to increase the thread_count, also to configure the JIT. Nothing helps. Its even worser than with the default settings.

Any ideas ?

Thank you!

**Comment by OskHa** [comment] 2015-03-15 12:53
Just as an info. We have highly optimized / performance php application that doesn't need much resources. It seems its just about threads.

**Comment by Orvid** [comment] 2016-09-30 21:39
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:39 UTC
