### ISSUE TITLE
Test fail for PayumBundle

### ISSUE THREAD

**Issue by inssein** [facebook/hhvm#5656] opened 2015-07-10 07:35 UTC
Issue: https://github.com/Payum/PayumBundle/issues/288
Failing Travis Build: https://travis-ci.org/Payum/PayumBundle/jobs/68263279
Failing Test: https://github.com/Payum/PayumBundle/blob/master/Tests/Functional/Form/Type/CreditCardTypeTest.php#L43

Reasons: The Payum library uses a SensitiveValue class to encapsulate sensitive values (which seem to erase themselves after they are read). I think the Symfony DateTime Transformer tries to convert the sensitive value (in this case, the card expiry date), into a timestamp, but fails, possibly when it is null.

**Comment by jwatzman** [comment] 2015-07-11 20:32
If you could get this down to an isolated test case (something short that doesn't rely on the rest of Payum, e.g., a 3v4l.org link) that would be useful.

**Comment by Orvid** [comment] 2016-09-30 19:32
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:32 UTC
Labels: framework parity, needs more info, php5 incompatibility
