### ISSUE TITLE
Core dump & abortion while running OwnCloud 8.0.9

### ISSUE THREAD

**Issue by castarco** [facebook/hhvm#4968] opened 2015-03-06 15:22 UTC
Hello, I'm using the HHVM 3.5 version on an Ubuntu 14.04. The HHVM service installed on my server crashed because OwnCloud 8.0.9. I don't know if the problem is already solved in the HHVM 3.6 beta/RC version.

Before the core dump, a lot of ''FastCGI protocol: received an invalid record'' messaged appeared in the /var/log/hhvm/error.log file, but because there aren't timestamps, I can't know if there is a relation between those messages and the core dump.

That's the stacktrace refered in the /var/log/hhvm/error.log file , placed in /tmp/stacktrace.4040.log .
```
Host: ks358068.kimsufi.com
ProcessID: 4065
ThreadID: 7f75ad7ff700
ThreadPID: 4581
Name: /sbin/start-stop-daemon
Type: Aborted
Runtime: hhvm
Version: tags/HHVM-3.5.1-0-gb723e67c88bc008676687a04dff00db1faf250b3
DebuggerCount: 0

Failed Assertion: /tmp/tmp.bAjDnOUcO9/hphp/runtime/vm/jit/translator.cpp:2002: HPHP::jit::TranslateResult HPHP::jit::translateRegion(HPHP::jit::HTS&, const HPHP::jit::RegionDesc&, HPHP::jit::RegionBlacklist&, HPHP::jit::TransFlags): assertion `0' failed.
URL: /index.php/apps/documents/ajax/otpoll.php
Server: drive.litipk.org
0: data block = cold
message: Attempted to emit 4 byte(s) into a 23 byte DataBlock with 2 bytes available. This almost certainly means the TC is full. If this is the case, increasing Eval.JitASize, Eval.JitAColdSize, Eval.JitAFrozenSize and Eval.JitGlobalDataSize in the configuration file when running this script or application should fix this problem.

Server_SERVER_NAME: drive.litipk.org
ThreadType: Web Request

# 0  gsignal at /lib/x86_64-linux-gnu/libc.so.6:0
# 1  abort at /lib/x86_64-linux-gnu/libc.so.6:0
# 2  HPHP::assert_fail(char const*, char const*, unsigned int, char const*) at /usr/bin/hhvm:0
# 3  HPHP::jit::translateRegion(HPHP::jit::HTS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags) at /usr/bin/hhvm:0
# 4  HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 5  HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 6  HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 7  HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) at /usr/bin/hhvm:0
# 8  HPHP::jit::MCGenerator::getCallArrayPrologue(HPHP::Func*) at /usr/bin/hhvm:0
# 9  HPHP::jit::funcBodyHelper(HPHP::ActRec*, void*) at /usr/bin/hhvm:0
# 10 HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) at /usr/bin/hhvm:0
# 11 HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) at /usr/bin/hhvm:0
# 12 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at /usr/bin/hhvm:0
# 13 HPHP::ExecutionContext::createFunction(HPHP::String const&, HPHP::String const&) at /usr/bin/hhvm:0
# 14 HPHP::f_create_function(HPHP::String const&, HPHP::String const&) at /usr/bin/hhvm:0
# 15 void HPHP::Native::callFunc<false, false>(HPHP::Func const*, void*, HPHP::TypedValue*, HPHP::TypedValue&) at /usr/bin/hhvm:0
# 16 HPHP::TypedValue* HPHP::Native::functionWrapper<false, false>(HPHP::ActRec*) at /usr/bin/hhvm:0
# 17 HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) at /usr/bin/hhvm:0
# 18 HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) at /usr/bin/hhvm:0
# 19 HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at /usr/bin/hhvm:0
# 20 HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at /usr/bin/hhvm:0
# 21 HPHP::invoke_file(HPHP::String const&, bool, char const*) at builtin-functions.cpp:0
# 22 HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at /usr/bin/hhvm:0
# 23 HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at /usr/bin/hhvm:0
# 24 HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) at /usr/bin/hhvm:0
# 25 HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) at /usr/bin/hhvm:0
# 26 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) at /usr/bin/hhvm:0
# 27 HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() at /usr/bin/hhvm:0
# 28 HPHP::AsyncFuncImpl::ThreadFunc(void*) at /usr/bin/hhvm:0
# 29 HPHP::start_routine_wrapper(void*) at /usr/bin/hhvm:0
# 30 start_thread at /lib/x86_64-linux-gnu/libpthread.so.0:0
# 31 timerfd_settime at /lib/x86_64-linux-gnu/libc.so.6:0

PHP Stacktrace:

#0  include()
#1  create_function($param, unset($param["_route"]);$_GET=array_merge($_GET, $param);unset($param);require_once "settings/ajax/removeRootCertificate.php";) called at [/var/www/owncloud/lib/private/route/route.php:135]
#2  OC\Route\Route->actionInclude(settings/ajax/removeRootCertificate.php) called at [/var/www/owncloud/settings/routes.php:80]
#3  include(/var/www/owncloud/settings/routes.php) called at [/var/www/owncloud/lib/private/route/router.php:142]
#4  OC\Route\Router->loadRoutes(documents) called at [/var/www/owncloud/lib/private/route/router.php:213]
#5  OC\Route\Router->match(/apps/documents/ajax/otpoll.php) called at [/var/www/owncloud/lib/base.php:763]
#6  OC::handleRequest() called at [/var/www/owncloud/index.php:36]
```

**Comment by wjywbs** [comment] 2015-03-06 17:20
You should check #4453, #4398 and #2851. create_function causes memory leak, so you should restart hhvm nightly or write a monitor script to restart it when it stops.

**Comment by fredemmott** [comment] 2015-04-01 19:38
Yep, dupe of https://github.com/facebook/hhvm/issues/4250

**Closed by fredemmott** 2015-04-01 19:38 UTC
Labels: duplicate
