### ISSUE TITLE
Updating from 3.7 to 3.8 caused 301 redirect infinite loop

### ISSUE THREAD

**Issue by frankh** [facebook/hhvm#5816] opened 2015-07-29 09:57 UTC
I wasn't able to figure out why, but updating to HHVM 3.8 caused certain pages on our site to have an infinite redirect loop (with 301 redirects).

It's a bit of a mess how our site works, with nginx proxying a url path to wordpress. I don't really have time to debug or come up with a minimal test case, so I'm just hoping someone else has a similar problem that could help with this.

**Comment by paulbiss** [comment] 2015-07-29 18:59
You may have more luck asking around in our irc channel on Freenode, #hhvm.

**Comment by wjywbs** [comment] 2015-07-30 23:00
I suspect this is an issue in the chrome browser:
https://code.google.com/p/chromium/issues/detail?id=501842

**Comment by Orvid** [comment] 2016-09-30 19:26
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:26 UTC
Labels: no isolated repro
