### ISSUE TITLE
mPDF 6.0 crashes with HHVM 3.10.0 (debian jessie)

### ISSUE THREAD

**Issue by 0x64616E69656C** [facebook/hhvm#6381] opened 2015-10-16 20:49 UTC
Hi,

after upgrading to 3.10.0 today, HHVM starts crashing again when calling mPDF library (previous crashes where fixed in 3.9.1, see #5528).

> [Fri Oct 16 08:23:57 2015] [hphp] [17350:7fcefdfff700:57:000001] [] Core dumped: Segmentation fault

```
#0  mPDF->SubstituteChars() called at [/var/www/xxx/vendor/mpdf/mpdf/mpdf.php:14118]
#1  mPDF->WriteHTML(<html stuff>) called at [/var/www/[...]/pdf.php:147]
#2  include(/var/www/[...]/pdf.php) called at [/var/www/[]/bootstrap.php:196]
#3  include(/var/www/[...]/bootstrap.php) called at [/var/www/[...]/htdocs/index.php:2]
```

**Comment by 0x64616E69656C** [comment] 2015-10-16 21:30
A litte more verbosity:

PoC:
```php
<?php
ini_set('max_execution_time', '30');

require __DIR__ . '/vendor/autoload.php';

ob_start();
?>

<p>Hello World!</p>

<?php
$content = ob_get_contents();
ob_end_clean();
$mpdf = new mPDF('c', 'a4');
$mpdf->debug = true;
$mpdf->allow_charset_conversion = true;
$mpdf->WriteHTML($content);
$mpdf->Output('foo.pdf', 'D');

```

Valgrind:
```

==10731== Memcheck, a memory error detector
==10731== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==10731== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==10731== Command: php pdf_test.php
==10731==
==10731== brk segment overflow in thread #1: can't grow to 0x11200000
==10731== Conditional jump or move depends on uninitialised value(s)
==10731==    at 0x10CE959: HPHP::jit::(anonymous namespace)::Vxls::allocate(HPHP::jit::(anonymous namespace)::Interval*) (in /usr/bin/hhvm)
==10731==    by 0x10EFA4F: HPHP::jit::allocateRegisters(HPHP::jit::Vunit&, HPHP::jit::Abi const&) (in /usr/bin/hhvm)
==10731==    by 0x12024EA: HPHP::jit::optimizeX64(HPHP::jit::Vunit&, HPHP::jit::Abi const&) (in /usr/bin/hhvm)
==10731==    by 0x12D9E18: HPHP::jit::Vauto::~Vauto() (in /usr/bin/hhvm)
==10731==    by 0x139DE57: HPHP::jit::UniqueStubs::emitAll() (in /usr/bin/hhvm)
==10731==    by 0x135D746: HPHP::jit::MCGenerator::initUniqueStubs() (in /usr/bin/hhvm)
==10731==    by 0xA17107: HPHP::ProcessInit() (in /usr/bin/hhvm)
==10731==    by 0xC8FBAF: HPHP::hphp_process_init() (in /usr/bin/hhvm)
==10731==    by 0xCA2C1A: HPHP::execute_program_impl(int, char**) (in /usr/bin/hhvm)
==10731==    by 0xCA58FE: HPHP::execute_program(int, char**) (in /usr/bin/hhvm)
==10731==    by 0xA1D61F: HPHP::emulate_zend(int, char**) (in /usr/bin/hhvm)
==10731==    by 0xA158F7: main (in /usr/bin/hhvm)
==10731==
==10731== Conditional jump or move depends on uninitialised value(s)
==10731==    at 0x102BC1C: HPHP::jit::collect_aliases(HPHP::jit::IRUnit const&, std::vector<HPHP::jit::Block*, std::allocator<HPHP::jit::Block*> > const&) (in /usr/bin/hhvm)
==10731==    by 0x1033472: HPHP::jit::optimizeLoads(HPHP::jit::IRUnit&) (in /usr/bin/hhvm)
==10731==    by 0x11D4539: HPHP::jit::optimize(HPHP::jit::IRUnit&, HPHP::jit::IRBuilder&, HPHP::jit::TransKind) (in /usr/bin/hhvm)
==10731==    by 0x135DCE8: HPHP::jit::MCGenerator::traceCodeGen(HPHP::jit::IRGS&) (in /usr/bin/hhvm)
==10731==    by 0x11B72C9: HPHP::jit::translateRegion(HPHP::jit::IRGS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags, HPHP::jit::PostConditions&) (in /usr/bin/hhvm)
==10731==    by 0x1364721: HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x136575A: HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x13659F3: HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1365D5A: HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x13669CA: HPHP::jit::MCGenerator::bindJccFirst(unsigned char*, HPHP::SrcKey, HPHP::SrcKey, bool, bool&) (in /usr/bin/hhvm)
==10731==    by 0x136BAAC: MCGenerator_handleServiceRequest (in /usr/bin/hhvm)
==10731==    by 0x1525845: ??? (in /usr/bin/hhvm)
==10731==
==10731== Conditional jump or move depends on uninitialised value(s)
==10731==    at 0x10180D8: HPHP::jit::(anonymous namespace)::RefineTmpsRec::go(HPHP::jit::Block*) (in /usr/bin/hhvm)
==10731==    by 0x101A236: HPHP::jit::refineTmps(HPHP::jit::IRUnit&, std::vector<HPHP::jit::Block*, std::allocator<HPHP::jit::Block*> > const&, HPHP::jit::StateVector<HPHP::jit::Block, HPHP::jit::Block*> const&) (in /usr/bin/hhvm)
==10731==    by 0x10B037F: HPHP::jit::optimizeRefcounts2(HPHP::jit::IRUnit&) (in /usr/bin/hhvm)
==10731==    by 0x11D4524: HPHP::jit::optimize(HPHP::jit::IRUnit&, HPHP::jit::IRBuilder&, HPHP::jit::TransKind) (in /usr/bin/hhvm)
==10731==    by 0x135DCE8: HPHP::jit::MCGenerator::traceCodeGen(HPHP::jit::IRGS&) (in /usr/bin/hhvm)
==10731==    by 0x11B72C9: HPHP::jit::translateRegion(HPHP::jit::IRGS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags, HPHP::jit::PostConditions&) (in /usr/bin/hhvm)
==10731==    by 0x1364721: HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x136575A: HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x13659F3: HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1365D5A: HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1366663: HPHP::jit::MCGenerator::bindJmp(unsigned char*, HPHP::SrcKey, HPHP::jit::ServiceRequest, HPHP::jit::TransFlags, bool&) (in /usr/bin/hhvm)
==10731==    by 0x136BA58: MCGenerator_handleServiceRequest (in /usr/bin/hhvm)
==10731==
==10731== Conditional jump or move depends on uninitialised value(s)
==10731==    at 0x10180D8: HPHP::jit::(anonymous namespace)::RefineTmpsRec::go(HPHP::jit::Block*) (in /usr/bin/hhvm)
==10731==    by 0x1018294: HPHP::jit::(anonymous namespace)::RefineTmpsRec::go(HPHP::jit::Block*) (in /usr/bin/hhvm)
==10731==    by 0x101A236: HPHP::jit::refineTmps(HPHP::jit::IRUnit&, std::vector<HPHP::jit::Block*, std::allocator<HPHP::jit::Block*> > const&, HPHP::jit::StateVector<HPHP::jit::Block, HPHP::jit::Block*> const&) (in /usr/bin/hhvm)
==10731==    by 0x10B037F: HPHP::jit::optimizeRefcounts2(HPHP::jit::IRUnit&) (in /usr/bin/hhvm)
==10731==    by 0x11D4524: HPHP::jit::optimize(HPHP::jit::IRUnit&, HPHP::jit::IRBuilder&, HPHP::jit::TransKind) (in /usr/bin/hhvm)
==10731==    by 0x135DCE8: HPHP::jit::MCGenerator::traceCodeGen(HPHP::jit::IRGS&) (in /usr/bin/hhvm)
==10731==    by 0x11B72C9: HPHP::jit::translateRegion(HPHP::jit::IRGS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags, HPHP::jit::PostConditions&) (in /usr/bin/hhvm)
==10731==    by 0x1364721: HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x136575A: HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x13659F3: HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1365D5A: HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1366663: HPHP::jit::MCGenerator::bindJmp(unsigned char*, HPHP::SrcKey, HPHP::jit::ServiceRequest, HPHP::jit::TransFlags, bool&) (in /usr/bin/hhvm)
==10731==
==10731== Conditional jump or move depends on uninitialised value(s)
==10731==    at 0x10180D8: HPHP::jit::(anonymous namespace)::RefineTmpsRec::go(HPHP::jit::Block*) (in /usr/bin/hhvm)
==10731==    by 0x1018294: HPHP::jit::(anonymous namespace)::RefineTmpsRec::go(HPHP::jit::Block*) (in /usr/bin/hhvm)
==10731==    by 0x1018294: HPHP::jit::(anonymous namespace)::RefineTmpsRec::go(HPHP::jit::Block*) (in /usr/bin/hhvm)
==10731==    by 0x101A236: HPHP::jit::refineTmps(HPHP::jit::IRUnit&, std::vector<HPHP::jit::Block*, std::allocator<HPHP::jit::Block*> > const&, HPHP::jit::StateVector<HPHP::jit::Block, HPHP::jit::Block*> const&) (in /usr/bin/hhvm)
==10731==    by 0x10B037F: HPHP::jit::optimizeRefcounts2(HPHP::jit::IRUnit&) (in /usr/bin/hhvm)
==10731==    by 0x11D4524: HPHP::jit::optimize(HPHP::jit::IRUnit&, HPHP::jit::IRBuilder&, HPHP::jit::TransKind) (in /usr/bin/hhvm)
==10731==    by 0x135DCE8: HPHP::jit::MCGenerator::traceCodeGen(HPHP::jit::IRGS&) (in /usr/bin/hhvm)
==10731==    by 0x11B72C9: HPHP::jit::translateRegion(HPHP::jit::IRGS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags, HPHP::jit::PostConditions&) (in /usr/bin/hhvm)
==10731==    by 0x1364721: HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x136575A: HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x13659F3: HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1365D5A: HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==
==10731== Conditional jump or move depends on uninitialised value(s)
==10731==    at 0x10180D8: HPHP::jit::(anonymous namespace)::RefineTmpsRec::go(HPHP::jit::Block*) (in /usr/bin/hhvm)
==10731==    by 0x1018294: HPHP::jit::(anonymous namespace)::RefineTmpsRec::go(HPHP::jit::Block*) (in /usr/bin/hhvm)
==10731==    by 0x1018294: HPHP::jit::(anonymous namespace)::RefineTmpsRec::go(HPHP::jit::Block*) (in /usr/bin/hhvm)
==10731==    by 0x1018294: HPHP::jit::(anonymous namespace)::RefineTmpsRec::go(HPHP::jit::Block*) (in /usr/bin/hhvm)
==10731==    by 0x101A236: HPHP::jit::refineTmps(HPHP::jit::IRUnit&, std::vector<HPHP::jit::Block*, std::allocator<HPHP::jit::Block*> > const&, HPHP::jit::StateVector<HPHP::jit::Block, HPHP::jit::Block*> const&) (in /usr/bin/hhvm)
==10731==    by 0x10B037F: HPHP::jit::optimizeRefcounts2(HPHP::jit::IRUnit&) (in /usr/bin/hhvm)
==10731==    by 0x11D4524: HPHP::jit::optimize(HPHP::jit::IRUnit&, HPHP::jit::IRBuilder&, HPHP::jit::TransKind) (in /usr/bin/hhvm)
==10731==    by 0x135DCE8: HPHP::jit::MCGenerator::traceCodeGen(HPHP::jit::IRGS&) (in /usr/bin/hhvm)
==10731==    by 0x11B72C9: HPHP::jit::translateRegion(HPHP::jit::IRGS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags, HPHP::jit::PostConditions&) (in /usr/bin/hhvm)
==10731==    by 0x1364721: HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x136575A: HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x13659F3: HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==
==10731== Conditional jump or move depends on uninitialised value(s)
==10731==    at 0x10A9D3A: HPHP::jit::(anonymous namespace)::build_graphs(HPHP::jit::(anonymous namespace)::Env&, HPHP::jit::(anonymous namespace)::RCAnalysis const&) (in /usr/bin/hhvm)
==10731==    by 0x10AF5A3: HPHP::jit::optimizeRefcounts2(HPHP::jit::IRUnit&) (in /usr/bin/hhvm)
==10731==    by 0x11D4524: HPHP::jit::optimize(HPHP::jit::IRUnit&, HPHP::jit::IRBuilder&, HPHP::jit::TransKind) (in /usr/bin/hhvm)
==10731==    by 0x135DCE8: HPHP::jit::MCGenerator::traceCodeGen(HPHP::jit::IRGS&) (in /usr/bin/hhvm)
==10731==    by 0x11B72C9: HPHP::jit::translateRegion(HPHP::jit::IRGS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags, HPHP::jit::PostConditions&) (in /usr/bin/hhvm)
==10731==    by 0x1364721: HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x136575A: HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x13659F3: HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1365D5A: HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1366663: HPHP::jit::MCGenerator::bindJmp(unsigned char*, HPHP::SrcKey, HPHP::jit::ServiceRequest, HPHP::jit::TransFlags, bool&) (in /usr/bin/hhvm)
==10731==    by 0x136BA58: MCGenerator_handleServiceRequest (in /usr/bin/hhvm)
==10731==    by 0x1525845: ??? (in /usr/bin/hhvm)
==10731==
==10731== Conditional jump or move depends on uninitialised value(s)
==10731==    at 0x10A84C3: void HPHP::jit::(anonymous namespace)::rc_analyze_inst<HPHP::jit::(anonymous namespace)::build_graphs(HPHP::jit::(anonymous namespace)::Env&, HPHP::jit::(anonymous namespace)::RCAnalysis const&)::{lambda(HPHP::jit::Block*)#1}, HPHP::jit::(anonymous namespace)::NodeAdder>(HPHP::jit::(anonymous namespace)::Env&, HPHP::jit::IRInstruction&, HPHP::jit::(anonymous namespace)::RCState&, HPHP::jit::(anonymous namespace)::build_graphs(HPHP::jit::(anonymous namespace)::Env&, HPHP::jit::(anonymous namespace)::RCAnalysis const&)::{lambda(HPHP::jit::Block*)#1}, HPHP::jit::(anonymous namespace)::NodeAdder) (in /usr/bin/hhvm)
==10731==    by 0x10A9CD4: HPHP::jit::(anonymous namespace)::build_graphs(HPHP::jit::(anonymous namespace)::Env&, HPHP::jit::(anonymous namespace)::RCAnalysis const&) (in /usr/bin/hhvm)
==10731==    by 0x10AF5A3: HPHP::jit::optimizeRefcounts2(HPHP::jit::IRUnit&) (in /usr/bin/hhvm)
==10731==    by 0x11D4524: HPHP::jit::optimize(HPHP::jit::IRUnit&, HPHP::jit::IRBuilder&, HPHP::jit::TransKind) (in /usr/bin/hhvm)
==10731==    by 0x135DCE8: HPHP::jit::MCGenerator::traceCodeGen(HPHP::jit::IRGS&) (in /usr/bin/hhvm)
==10731==    by 0x11B72C9: HPHP::jit::translateRegion(HPHP::jit::IRGS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags, HPHP::jit::PostConditions&) (in /usr/bin/hhvm)
==10731==    by 0x1364721: HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x136575A: HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x13659F3: HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1365D5A: HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1366663: HPHP::jit::MCGenerator::bindJmp(unsigned char*, HPHP::SrcKey, HPHP::jit::ServiceRequest, HPHP::jit::TransFlags, bool&) (in /usr/bin/hhvm)
==10731==    by 0x136BA58: MCGenerator_handleServiceRequest (in /usr/bin/hhvm)
==10731==
==10731== Conditional jump or move depends on uninitialised value(s)
==10731==    at 0x10AAEA7: HPHP::jit::(anonymous namespace)::find_alias_sets(HPHP::jit::(anonymous namespace)::Env&)::{lambda(HPHP::jit::SSATmp*)#1}::operator()(HPHP::jit::SSATmp*) const (in /usr/bin/hhvm)
==10731==    by 0x10AE9EE: HPHP::jit::optimizeRefcounts2(HPHP::jit::IRUnit&) (in /usr/bin/hhvm)
==10731==    by 0x11D4524: HPHP::jit::optimize(HPHP::jit::IRUnit&, HPHP::jit::IRBuilder&, HPHP::jit::TransKind) (in /usr/bin/hhvm)
==10731==    by 0x135DCE8: HPHP::jit::MCGenerator::traceCodeGen(HPHP::jit::IRGS&) (in /usr/bin/hhvm)
==10731==    by 0x11B72C9: HPHP::jit::translateRegion(HPHP::jit::IRGS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags, HPHP::jit::PostConditions&) (in /usr/bin/hhvm)
==10731==    by 0x1364721: HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x136575A: HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x13659F3: HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1365D5A: HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1366FDB: HPHP::jit::MCGenerator::handleResume(bool) (in /usr/bin/hhvm)
==10731==    by 0x1D6001D6: ???
==10731==    by 0x26C1C18: ??? (in /usr/bin/hhvm)
==10731==
==10731== Conditional jump or move depends on uninitialised value(s)
==10731==    at 0x10AAF05: HPHP::jit::(anonymous namespace)::find_alias_sets(HPHP::jit::(anonymous namespace)::Env&)::{lambda(HPHP::jit::SSATmp*)#1}::operator()(HPHP::jit::SSATmp*) const (in /usr/bin/hhvm)
==10731==    by 0x10AE9EE: HPHP::jit::optimizeRefcounts2(HPHP::jit::IRUnit&) (in /usr/bin/hhvm)
==10731==    by 0x11D4524: HPHP::jit::optimize(HPHP::jit::IRUnit&, HPHP::jit::IRBuilder&, HPHP::jit::TransKind) (in /usr/bin/hhvm)
==10731==    by 0x135DCE8: HPHP::jit::MCGenerator::traceCodeGen(HPHP::jit::IRGS&) (in /usr/bin/hhvm)
==10731==    by 0x11B72C9: HPHP::jit::translateRegion(HPHP::jit::IRGS&, HPHP::jit::RegionDesc const&, HPHP::hphp_hash_set<HPHP::jit::ProfSrcKey, HPHP::jit::ProfSrcKey::Hasher, std::equal_to<HPHP::jit::ProfSrcKey> >&, HPHP::jit::TransFlags, HPHP::jit::PostConditions&) (in /usr/bin/hhvm)
==10731==    by 0x1364721: HPHP::jit::MCGenerator::translateWork(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x136575A: HPHP::jit::MCGenerator::translate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x13659F3: HPHP::jit::MCGenerator::retranslate(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1365D5A: HPHP::jit::MCGenerator::createTranslation(HPHP::jit::TranslArgs const&) (in /usr/bin/hhvm)
==10731==    by 0x1366FDB: HPHP::jit::MCGenerator::handleResume(bool) (in /usr/bin/hhvm)
==10731==    by 0x1D6001D6: ???
==10731==    by 0x26C1C18: ??? (in /usr/bin/hhvm)
==10731==

Fatal error: Maximum execution time of 30 seconds exceeded in /home/daniel/mpdf_test/vendor/mpdf/mpdf/mpdf.php on line 1526
==10731==
==10731== HEAP SUMMARY:
==10731==     in use at exit: 13,495,534 bytes in 21,373 blocks
==10731==   total heap usage: 1,316,991 allocs, 1,295,618 frees, 223,032,920 bytes allocated
==10731==
==10731== LEAK SUMMARY:
==10731==    definitely lost: 1,592 bytes in 198 blocks
==10731==    indirectly lost: 0 bytes in 0 blocks
==10731==      possibly lost: 0 bytes in 0 blocks
==10731==    still reachable: 13,493,942 bytes in 21,175 blocks
==10731==                       of which reachable via heuristic:
==10731==                         stdstring          : 11,690 bytes in 291 blocks
==10731==                         newarray           : 2,928 bytes in 152 blocks
==10731==         suppressed: 0 bytes in 0 blocks
==10731== Rerun with --leak-check=full to see details of leaked memory
==10731==
==10731== For counts of detected and suppressed errors, rerun with: -v
==10731== Use --track-origins=yes to see where uninitialised values come from
==10731== ERROR SUMMARY: 144 errors from 10 contexts (suppressed: 0 from 0)
```

can't get a ```bt``` in gdb (I tried ```gdb --args hhvm --php --mode=debug ./pdf_test.php```) though.

**Comment by keepxtreme** [comment] 2015-10-18 17:24
can you check if mPDF->SubstituteChars() calls strtr()? If so, this may be a duplicate of #6384

**Comment by jwatzman** [comment] 2015-10-19 14:46
> can't get a bt in gdb (I tried gdb --args hhvm --php --mode=debug ./pdf_test.php) though.

This would be most useful. The stracktrace files don't contain much useful due to a packaging issue in recent versions of HHVM, and the valgrind output isn't useful (the script didn't get to the point where it crashes, it's just spew from AFAICT valgrind not understanding our JIT).

> can you check if mPDF->SubstituteChars() calls strtr()? If so, this may be a related to #6384

This seems the most likely explanation.

**Comment by jwatzman** [comment] 2015-10-19 14:49
> > can you check if mPDF->SubstituteChars() calls strtr()? If so, this may be a related to #6384
>
> This seems the most likely explanation.

Yes, it does. From https://raw.githubusercontent.com/mpdf/mpdf/9f2d761e7ac1d89a6752a18036a597fa9ce2d8c7/mpdf.php:

```php
function SubstituteChars($html) {
	// only substitute characters between tags
	if (count($this->substitute)) {
		$a=preg_split('/(<.*?>)/ms',$html,-1,PREG_SPLIT_DELIM_CAPTURE);
		$html = '';
		foreach($a as $i => $e) {
			if($i%2==0) {
			   $e = strtr($e, $this->substitute);
			}
			$html .= $e;
		}
	}
	return $html;
}
```

Going to close this as a dupe of #6384.

**Closed by jwatzman** 2015-10-19 14:49 UTC
Labels: crash, needs more info, no isolated repro
