### ISSUE TITLE
Ubuntu 16.10 Yakkety build request

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#7541] opened 2016-12-09 07:17 UTC
Ubuntu 16.10 is available for more than a month already, can you add it to repository?
Otherwise lots of packages from 16.04 distro needs to be installed which starts causing conflicts with more up to date packages.

**Comment by photodude** [comment] 2016-12-13 17:25
duplicate of #7489

**Closed** 2016-12-13 17:42 UTC
