### ISSUE TITLE
Memory Leak with Wordpress.

### ISSUE THREAD

**Issue by vishirockz** [facebook/hhvm#4398] opened 2014-12-06 10:16 UTC
I am using HHVM/3.3.0 on one of my production server. performance is far better than any other php compiler.

But it stops after 4-5 days may be due to memory leaks which make the daemon to stop.

I personally think that if we guys can fix this issue then HHVM will be at a different height.
Its just awesome performance wise..

Thanks,
Vishal

**Comment by corientdev** [comment] 2015-02-03 10:11
Hi,

I am on `HHVM/3.5.0` Currently. Just Sharing This with you guys!

Memory Leak is decreased but its still there.
It actually need restart after 4-5 Days. Else it gets terminated automatically.

**Comment by fredemmott** [comment] 2015-03-12 18:22
Do you have a stack trace? This sounds like a dupe of #4250

**Comment by fredemmott** [comment] 2015-04-01 19:39
Closing as dupe of #4250.

**Closed by fredemmott** 2015-04-01 19:39 UTC
Labels: Memory Leak, needs more info

**Comment by corientdev** [comment] 2015-07-24 11:35
Finally I think it is resolved. HHVM is not crashing now with my set up :+1:
