### ISSUE TITLE
[Typechecker] Intersections contain two types on both sides of a `&`

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8535] opened 2019-07-12 18:40 UTC
### HHVM Version

```
HipHop VM 4.14.0-dev (rel)
Compiler: heads/master-0-g8e3fcca1a55b1cb6429a69485defbe419285cde1
Repo schema: 1f83a484891318b6b207071257df148e668d40e6
Git log last commit: 3e7e6ddc21b7c2699099345360143379d01b4ba0
```

### Operating System and Version
Ubuntu 18.04

### Standalone code, or other way to reproduce the problem
```HACK
use namespace HH\Lib\Vec;

<<__EntryPoint>>
function main(): void {
	$vec_of_float_and_string = vec[1.1, 'string'];
	$type = Vec\map($vec_of_float_and_string, $el ==> $el as string);
}
```

### Actual result
Hovering over `$type` results in `vec<(string & (float | string))>`. String appears twice. #8534 also noted that the parenthesis makes it look like a tuple.

### Expected result
`vec<string>`

**Comment by CatherineGasnier** [comment] 2019-07-15 10:37
Duplicate of #8534

**Closed by CatherineGasnier** 2019-07-15 10:37 UTC
Labels: hack
