### ISSUE TITLE
HHVM serialize/unserialize functions different than PHP 

### ISSUE THREAD

**Issue by gadelkareem** [facebook/hhvm#5698] opened 2015-07-14 14:20 UTC
- Symfony 2.7
- HipHop VM 3.7.3 (rel)
- PHP 5.6.10  ( failback )
- Ubuntu-trusty-64
- nginx/1.4.6

Error:
```
Notice: Object of class Symfony\Bundle\FrameworkBundle\Templating\TemplateReference could not be converted to int
```

To produce
```
sudo service hhvm start
composer run-script post-update-cmd
```

When trying to unserialize the array in app/cache/dev/appDevUrlMatcher.php.meta, it generated different results with HHVM than PHP

HHVM unserialize:
```

array(8) {
  [0]=>
  object(Symfony\Component\Config\Resource\FileResource)#6 (1) {
    ["resource":"Symfony\Component\Config\Resource\FileResource":private]=>
    string(54) "/var/www/application/app/cache/dev/assetic/routing.yml"
  }
  [1]=>
  object(Symfony\Bundle\AsseticBundle\Config\AsseticResource)#7 (1) {
    ["resource":"Symfony\Bundle\AsseticBundle\Config\AsseticResource":private]=>
    object(Symfony\Bundle\AsseticBundle\Factory\Resource\FileResource)#8 (5) {
      ["loader":protected]=>
      object(Symfony\Bundle\FrameworkBundle\Templating\Loader\FilesystemLoader)#9 (1) {
        ["locator":protected]=>
        object(Symfony\Bundle\FrameworkBundle\Templating\Loader\TemplateLocator)#10 (2) {
          ["locator":protected]=>
          object(Symfony\Component\HttpKernel\Config\FileLocator)#12 (3) {
            ["kernel":"Symfony\Component\HttpKernel\Config\FileLocator":private]=>
            object(AppKernel)#13 (10) {
              ["bundles":protected]=>
              array(0) {
              }
              ["bundleMap":protected]=>
              NULL
              ["container":protected]=>
              NULL
              ["rootDir":protected]=>
              string(24) "/var/www/application/app"
              ["environment":protected]=>
              string(3) "dev"
              ["debug":protected]=>
              bool(true)
              ["booted":protected]=>
              bool(false)
              ["name":protected]=>
              string(3) "app"
              ["startTime":protected]=>
              float(1436880985.9472)
              ["loadClassCache":protected]=>
              NULL
            }
            ["path":"Symfony\Component\HttpKernel\Config\FileLocator":private]=>
            string(34) "/var/www/application/app/Resources"
            ["paths":protected]=>
            array(1) {
              [0]=>
              string(34) "/var/www/application/app/Resources"
            }
          }
          ["cache":protected]=>
          array(2) {
            ["::base.html.twig"]=>
            string(55) "/var/www/application/app/Resources/views/base.html.twig"
            [":default:index.html.twig"]=>
            string(64) "/var/www/application/app/Resources/views/default/index.html.twig"
          }
        }
      }
      ["bundle":protected]=>
      string(0) ""
      ["baseDir":protected]=>
      string(41) "/var/www/application/app/Resources/views/"
      ["path":protected]=>
      string(55) "/var/www/application/app/Resources/views/base.html.twig"
      ["template":protected]=>
      object(Symfony\Bundle\FrameworkBundle\Templating\TemplateReference)#15 (1) {
        ["parameters":protected]=>
        array(5) {
          ["bundle"]=>
          string(0) ""
          ["controller"]=>
          string(0) ""
          ["name"]=>
          string(4) "base"
          ["format"]=>
          string(4) "html"
          ["engine"]=>
          string(4) "twig"
        }
      }
    }
  }
  [2]=>
  object(Symfony\Bundle\AsseticBundle\Config\AsseticResource)#16 (1) {
    ["resource":"Symfony\Bundle\AsseticBundle\Config\AsseticResource":private]=>
    object(Symfony\Bundle\AsseticBundle\Factory\Resource\FileResource)#17 (5) {
      ["loader":protected]=>
      object(Symfony\Bundle\FrameworkBundle\Templating\Loader\FilesystemLoader)#9 (1) {
        ["locator":protected]=>
        object(Symfony\Bundle\FrameworkBundle\Templating\Loader\TemplateLocator)#10 (2) {
          ["locator":protected]=>
          object(Symfony\Component\HttpKernel\Config\FileLocator)#12 (3) {
            ["kernel":"Symfony\Component\HttpKernel\Config\FileLocator":private]=>
            object(AppKernel)#13 (10) {
              ["bundles":protected]=>
              array(0) {
              }
              ["bundleMap":protected]=>
              NULL
              ["container":protected]=>
              NULL
              ["rootDir":protected]=>
              string(24) "/var/www/application/app"
              ["environment":protected]=>
              string(3) "dev"
              ["debug":protected]=>
              bool(true)
              ["booted":protected]=>
              bool(false)
              ["name":protected]=>
              string(3) "app"
              ["startTime":protected]=>
              float(1436880985.9472)
              ["loadClassCache":protected]=>
              NULL
            }
            ["path":"Symfony\Component\HttpKernel\Config\FileLocator":private]=>
            string(34) "/var/www/application/app/Resources"
            ["paths":protected]=>
            array(1) {
              [0]=>
              string(34) "/var/www/application/app/Resources"
            }
          }
          ["cache":protected]=>
          array(2) {
            ["::base.html.twig"]=>
            string(55) "/var/www/application/app/Resources/views/base.html.twig"
            [":default:index.html.twig"]=>
            string(64) "/var/www/application/app/Resources/views/default/index.html.twig"
          }
        }
      }
      ["bundle":protected]=>
      string(0) ""
      ["baseDir":protected]=>
      string(41) "/var/www/application/app/Resources/views/"
      ["path":protected]=>
      string(64) "/var/www/application/app/Resources/views/default/index.html.twig"
      ["template":protected]=>
      object(Symfony\Bundle\FrameworkBundle\Templating\TemplateReference)#18 (1) {
        ["parameters":protected]=>
        array(5) {
          ["bundle"]=>
          string(0) ""
          ["controller"]=>
          string(7) "default"
          ["name"]=>
          string(5) "index"
          ["format"]=>
          string(4) "html"
          ["engine"]=>
          string(4) "twig"
        }
      }
    }
  }
  [3]=>
  object(Symfony\Component\Config\Resource\FileResource)#19 (1) {
    ["resource":"Symfony\Component\Config\Resource\FileResource":private]=>
    string(47) "/var/www/application/app/config/routing_dev.yml"
  }
  [4]=>
  object(Symfony\Component\Config\Resource\FileResource)#20 (1) {
    ["resource":"Symfony\Component\Config\Resource\FileResource":private]=>
    string(132) "/var/www/application/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/config/routing/webconfigurator.xml"
  }
  [5]=>
  object(Symfony\Component\Config\Resource\FileResource)#21 (1) {
    ["resource":"Symfony\Component\Config\Resource\FileResource":private]=>
    string(43) "/var/www/application/app/config/routing.yml"
  }
  [6]=>
  object(Symfony\Component\Config\Resource\DirectoryResource)#22 (2) {
    ["resource":"Symfony\Component\Config\Resource\DirectoryResource":private]=>
    string(46) "/var/www/application/src/AppBundle/Controller/"
    ["pattern":"Symfony\Component\Config\Resource\DirectoryResource":private]=>
    string(8) "/\.php$/"
  }
  [7]=>
  object(Symfony\Component\Config\Resource\FileResource)#23 (1) {
    ["resource":"Symfony\Component\Config\Resource\FileResource":private]=>
    string(67) "/var/www/application/src/AppBundle/Controller/DefaultController.php"
  }
}
```

```
sudo service hhvm stop
```
PHP unserialize:
```

array(8) {
  [0]=>
  object(Symfony\Component\Config\Resource\FileResource)#6 (1) {
    ["resource":"Symfony\Component\Config\Resource\FileResource":private]=>
    string(54) "/var/www/application/app/cache/dev/assetic/routing.yml"
  }
  [1]=>
  object(Symfony\Bundle\AsseticBundle\Config\AsseticResource)#7 (1) {
    ["resource":"Symfony\Bundle\AsseticBundle\Config\AsseticResource":private]=>
    object(Symfony\Bundle\AsseticBundle\Factory\Resource\FileResource)#8 (5) {
      ["loader":protected]=>
      object(Symfony\Bundle\FrameworkBundle\Templating\Loader\FilesystemLoader)#9 (1) {
        ["locator":protected]=>
        object(Symfony\Bundle\FrameworkBundle\Templating\Loader\TemplateLocator)#10 (2) {
          ["locator":protected]=>
          object(Symfony\Component\HttpKernel\Config\FileLocator)#12 (3) {
            ["kernel":"Symfony\Component\HttpKernel\Config\FileLocator":private]=>
            object(AppKernel)#11 (10) {
              ["bundles":protected]=>
              array(0) {
              }
              ["bundleMap":protected]=>
              NULL
              ["container":protected]=>
              NULL
              ["rootDir":protected]=>
              string(24) "/var/www/application/app"
              ["environment":protected]=>
              string(3) "dev"
              ["debug":protected]=>
              bool(true)
              ["booted":protected]=>
              bool(false)
              ["name":protected]=>
              string(3) "app"
              ["startTime":protected]=>
              float(1436881033.4976)
              ["loadClassCache":protected]=>
              NULL
            }
            ["path":"Symfony\Component\HttpKernel\Config\FileLocator":private]=>
            string(34) "/var/www/application/app/Resources"
            ["paths":protected]=>
            array(1) {
              [0]=>
              string(34) "/var/www/application/app/Resources"
            }
          }
          ["cache":protected]=>
          array(2) {
            ["::base.html.twig"]=>
            string(55) "/var/www/application/app/Resources/views/base.html.twig"
            [":default:index.html.twig"]=>
            string(64) "/var/www/application/app/Resources/views/default/index.html.twig"
          }
        }
      }
      ["bundle":protected]=>
      string(0) ""
      ["baseDir":protected]=>
      string(41) "/var/www/application/app/Resources/views/"
      ["path":protected]=>
      string(55) "/var/www/application/app/Resources/views/base.html.twig"
      ["template":protected]=>
      object(Symfony\Bundle\FrameworkBundle\Templating\TemplateReference)#14 (1) {
        ["parameters":protected]=>
        array(5) {
          ["bundle"]=>
          string(0) ""
          ["controller"]=>
          string(0) ""
          ["name"]=>
          string(4) "base"
          ["format"]=>
          string(4) "html"
          ["engine"]=>
          string(4) "twig"
        }
      }
    }
  }
  [2]=>
  object(Symfony\Bundle\AsseticBundle\Config\AsseticResource)#13 (1) {
    ["resource":"Symfony\Bundle\AsseticBundle\Config\AsseticResource":private]=>
    object(Symfony\Bundle\AsseticBundle\Factory\Resource\FileResource)#15 (5) {
      ["loader":protected]=>
      object(Symfony\Bundle\AsseticBundle\Factory\Resource\FileResource)#8 (5) {
        ["loader":protected]=>
        object(Symfony\Bundle\FrameworkBundle\Templating\Loader\FilesystemLoader)#9 (1) {
          ["locator":protected]=>
          object(Symfony\Bundle\FrameworkBundle\Templating\Loader\TemplateLocator)#10 (2) {
            ["locator":protected]=>
            object(Symfony\Component\HttpKernel\Config\FileLocator)#12 (3) {
              ["kernel":"Symfony\Component\HttpKernel\Config\FileLocator":private]=>
              object(AppKernel)#11 (10) {
                ["bundles":protected]=>
                array(0) {
                }
                ["bundleMap":protected]=>
                NULL
                ["container":protected]=>
                NULL
                ["rootDir":protected]=>
                string(24) "/var/www/application/app"
                ["environment":protected]=>
                string(3) "dev"
                ["debug":protected]=>
                bool(true)
                ["booted":protected]=>
                bool(false)
                ["name":protected]=>
                string(3) "app"
                ["startTime":protected]=>
                float(1436881033.4976)
                ["loadClassCache":protected]=>
                NULL
              }
              ["path":"Symfony\Component\HttpKernel\Config\FileLocator":private]=>
              string(34) "/var/www/application/app/Resources"
              ["paths":protected]=>
              array(1) {
                [0]=>
                string(34) "/var/www/application/app/Resources"
              }
            }
            ["cache":protected]=>
            array(2) {
              ["::base.html.twig"]=>
              string(55) "/var/www/application/app/Resources/views/base.html.twig"
              [":default:index.html.twig"]=>
              string(64) "/var/www/application/app/Resources/views/default/index.html.twig"
            }
          }
        }
        ["bundle":protected]=>
        string(0) ""
        ["baseDir":protected]=>
        string(41) "/var/www/application/app/Resources/views/"
        ["path":protected]=>
        string(55) "/var/www/application/app/Resources/views/base.html.twig"
        ["template":protected]=>
        object(Symfony\Bundle\FrameworkBundle\Templating\TemplateReference)#14 (1) {
          ["parameters":protected]=>
          array(5) {
            ["bundle"]=>
            string(0) ""
            ["controller"]=>
            string(0) ""
            ["name"]=>
            string(4) "base"
            ["format"]=>
            string(4) "html"
            ["engine"]=>
            string(4) "twig"
          }
        }
      }
      ["bundle":protected]=>
      string(0) ""
      ["baseDir":protected]=>
      string(41) "/var/www/application/app/Resources/views/"
      ["path":protected]=>
      string(64) "/var/www/application/app/Resources/views/default/index.html.twig"
      ["template":protected]=>
      object(Symfony\Bundle\FrameworkBundle\Templating\TemplateReference)#16 (1) {
        ["parameters":protected]=>
        array(5) {
          ["bundle"]=>
          string(0) ""
          ["controller"]=>
          string(7) "default"
          ["name"]=>
          string(5) "index"
          ["format"]=>
          string(4) "html"
          ["engine"]=>
          string(4) "twig"
        }
      }
    }
  }
  [3]=>
  object(Symfony\Component\Config\Resource\FileResource)#17 (1) {
    ["resource":"Symfony\Component\Config\Resource\FileResource":private]=>
    string(47) "/var/www/application/app/config/routing_dev.yml"
  }
  [4]=>
  object(Symfony\Component\Config\Resource\FileResource)#18 (1) {
    ["resource":"Symfony\Component\Config\Resource\FileResource":private]=>
    string(132) "/var/www/application/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/config/routing/webconfigurator.xml"
  }
  [5]=>
  object(Symfony\Component\Config\Resource\FileResource)#19 (1) {
    ["resource":"Symfony\Component\Config\Resource\FileResource":private]=>
    string(43) "/var/www/application/app/config/routing.yml"
  }
  [6]=>
  object(Symfony\Component\Config\Resource\DirectoryResource)#20 (2) {
    ["resource":"Symfony\Component\Config\Resource\DirectoryResource":private]=>
    string(46) "/var/www/application/src/AppBundle/Controller/"
    ["pattern":"Symfony\Component\Config\Resource\DirectoryResource":private]=>
    string(8) "/\.php$/"
  }
  [7]=>
  object(Symfony\Component\Config\Resource\FileResource)#21 (1) {
    ["resource":"Symfony\Component\Config\Resource\FileResource":private]=>
    string(67) "/var/www/application/src/AppBundle/Controller/DefaultController.php"
  }
}
```

On the PHP output there is a repeated call to ```Symfony\Bundle\AsseticBundle\Factory\Resource\FileResource::loader```

```
  object(Symfony\Bundle\AsseticBundle\Config\AsseticResource)#13 (1) {
    ["resource":"Symfony\Bundle\AsseticBundle\Config\AsseticResource":private]=>
    object(Symfony\Bundle\AsseticBundle\Factory\Resource\FileResource)#15 (5) {
      ["loader":protected]=>
      object(Symfony\Bundle\AsseticBundle\Factory\Resource\FileResource)#8 (5) {
        ["loader":protected]=>
        object(Symfony\Bundle\FrameworkBundle\Templating\Loader\FilesystemLoader)#9 (1) {
          ["locator":protected]=>
          object(Symfony\Bundle\FrameworkBundle\Templating\Loader\TemplateLocator)#10 (2) {
```

**Comment by fabpot** [comment] 2015-07-18 12:44
@gadelkareem Can you try with HHVM 3.8.0? It looks like it could have been fixed in this version as commented in this Silex issue: https://github.com/silexphp/Silex/issues/992#issuecomment-122511340

**Comment by gadelkareem** [comment] 2015-07-19 00:14
@fabpot I just tested with HipHop VM 3.8.0 (rel) and got the same problem.

**Comment by paulbiss** [comment] 2015-07-20 16:33
How was the data serialized in the first place? In hhvm we would like the behavior of `unserialize(serialize($x))` to be identical in hhvm and php 5, however, we make no guarantee that a string created with `serialize($x)` under php 5 will yield the same result when unserialized using hhvm as php.

**Comment by gadelkareem** [comment] 2015-07-20 17:53
@paulbiss most of the servers using HHVM are set with a fallback to PHP-FPM not the risk outage on segfault, not to mention using php cli during Composer update and install.

**Comment by paulbiss** [comment] 2015-07-20 17:55
If you can narrow it down to some specific examples things that don't unserialize properly (something isolated that can be run on its own), we can look at it. We've discussed this before, and broadly speaking having our unserialize be identical to PHP 5 would be difficult to maintain and keep in sync.

**Comment by gadelkareem** [comment] 2015-07-20 18:11
Well the problem was solved [here](https://github.com/gadelkareem/symfony/commit/4152a2c9b2fb6f2639c9774a50e1e2b49b9ec917) by separately serialising each object in the array instead of serialising the array of objects at once. This workaround produced a serialized string that can be read by either PHP or HHVM.

I think @fabpot can explain more on how this works in Symfony or give a simpler code example.

**Comment by Orvid** [comment] 2016-09-30 19:34
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:34 UTC

**Comment by farizluqman** [comment] 2017-02-01 08:53
Hello, I can confirm the problem still persists especially when serializing Carbon\Carbon or DateTime objects.

```
Error: exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/DriverAbstract.php:618 Stack trace: #0 (): DateTime->__wakeup() #1 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/DriverAbstract.php(618): unserialize() #2 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/files.php(138): phpFastCache\Core\DriverAbstract->decode() #3 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/DriverAbstract.php(157): phpFastCache\Drivers\files->driver_get() #4 /Applications/MAMP/htdocs/Rai-DigitalOcean/app/Service/Product/ProductService.php(142): phpFastCache\Core\DriverAbstract->get() #5 /Applications/MAMP/htdocs/Rai-DigitalOcean/resources/views/admin/products.php(8): Service\Product\ProductService->getAllProducts() #6 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/damnstupidsimple/core/src/Viewer.php(107): include() #7 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/damnstupidsimple/core/src/Viewer.php(75): Core\Viewer::render() #8 /Applications/MAMP/htdocs/Rai-DigitalOcean/app/Controller/Admin.php(41): Core\Viewer::file() #9 (): Controller\Admin->displayAnyPage() #10 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/damnstupidsimple/core/src/Router.php(818): call_user_func_array() #11 /Applications/MAMP/htdocs/Rai-DigitalOcean/app/bootstrap.php(130): Core\Router::dispatch() #12 /Applications/MAMP/htdocs/Rai-DigitalOcean/index.php(56): include() #13 {main}
```
