### ISSUE TITLE
RequestInitDocument Not Found when using authoritative mode

### ISSUE THREAD

**Issue by edwh** [facebook/hhvm#5076] opened 2015-03-25 08:15 UTC
I'm trying to use authoritative mode to speed up HHVM by not checking PHP files to see if they've changed.

Ideally there would be an HHVM config parameter which controlled how frequently it did this check, but I don't think there is one.

I've set this in server.ini:

hhvm.repo.authoritative = true

Then I've compiled my PHP files using:

hhvm --hphp -thhbc -o /var/run/hhvm --input-dir <where my code lives>

(I did this as root, but since hhvm runs as www-data on my machine I had to manually set permissions on:

/var/run/hhvm/hhvm.hhbc

...without this hhvm exits on startup without any useful logs, but I could see using strace that it was having a permissions error.)

Now once I've done this it starts, but my web pages are returning this:

RequestInitDocument Not Found

If I disable authoritative mode then it runs fine.

Any suggestions?

**Comment by paulbiss** [comment] 2015-03-25 20:32
Can you paste your configuration files?

**Comment by edwh** [comment] 2015-03-26 17:46
Thanks for your reply.  Here's the server.ini.  Let me know if you mean something else?

; php options

pid = /var/run/hhvm/pid

; hhvm specific

hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.file_socket = /var/run/hhvm/sock
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.authoritative = true
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
hhvm.server.thread_count = 200
hhvm.server.backlog = 30000
hhvm.server.connection_limit = 30000

**Comment by paulbiss** [comment] 2015-03-26 18:46
Hmm, you can try setting hhvm.server.source_root to the root of your source tree (the directory you ran hhvm --hphp from).

**Comment by edwh** [comment] 2015-03-26 18:52
That gets me a little further - I get an error in error.log now:

Failed to initialize central HHBC repository:\n  Failed to initialize schema in /usr/share/projectc/hhvm.hhbc: \n  Failed to open /var/www/.hhvm.hhbc: 14 - unable to open database file\n

/usr/share/projectc/hhvm.hhbc is the new one I've just compiled.

**Comment by paulbiss** [comment] 2015-03-26 19:07
Sounds like the repo may be corrupted? Try remaking it.

**Comment by edwh** [comment] 2015-04-08 16:20
I've tried.  Here's a bash -x of the script I'm using to recompile.

root@web1:/usr/share/projectc/scripts# bash -x ./hhvmcompile
+ WWW_DIR=/usr/share/projectc
+ FILE_MASK='\*.php'
+ INDEX_TMP=/var/run/hhvm/precompiled/fileindex
+ REPO_DIR=/var/run/hhvm/precompiled
+ WWWDATA=www-data:www-data
+ rm -r /var/run/hhvm/precompiled
+ mkdir /var/run/hhvm/precompiled
+ chown www-data:www-data /var/run/hhvm/precompiled
+ echo 'make sure /var/run/hhvm/precompiled is writable - or change this script to point to a different path'
make sure /var/run/hhvm/precompiled is writable - or change this script to point to a different path
+ cd /tmp
+ sudo find /usr/share/projectc -name '*.php'
+ find /usr/share/usr/share/projectc -name '*.php'
find: `/usr/share/usr/share/projectc': No such file or directory
+ ls -lh /var/run/hhvm/precompiled/fileindex
-rw-r--r-- 1 root root 0 Apr  8 16:18 /var/run/hhvm/precompiled/fileindex
+ echo 'WARNING: This requires some Gigabytes of RAM - make there is enough swap ;-)'
WARNING: This requires some Gigabytes of RAM - make there is enough swap ;-)
+ cd /usr/share/projectc
+ sudo hhvm --hphp -thhbc -o /var/run/hhvm/precompiled --input-list /var/run/hhvm/precompiled/fileindex
running hphp...
parsing inputs...
analyzeProgram...
analyzeProgram took 0'00" (65482 us) wall time
parsing inputs took 0'00" (65632 us) wall time
pre-optimizing...
pre-optimizing took 0'00" (117838 us) wall time
creating binary HHBC files...
creating binary HHBC files took 0'00" (927295 us) wall time
all files saved in /var/run/hhvm/precompiled ...
running hphp took 0'01" (1877497 us) wall time
+ sudo chown www-data:www-data /var/run/hhvm/precompiled/hhvm.hhbc
+ ls -lh /var/run/hhvm/precompiled/hhvm.hhbc
-rw-r--r-- 1 www-data www-data 3.1M Apr  8 16:18 /var/run/hhvm/precompiled/hhvm.hhbc
+ sudo service hhvm restart
 * Restarting HHVM FastCGI Daemon hhvm 

I still get the RequestInitDocument Not Found error.

Here's my server.ini:

; php options

pid = /var/run/hhvm/pid

; hhvm specific

hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.file_socket = /var/run/hhvm/sock
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.authoritative = true
hhvm.repo.central.path = /var/run/hhvm/precompiled/hhvm.hhbc
hhvm.server.thread_count = 64
hhvm.server.backlog = 30000
hhvm.server.connection_limit = 30000

Any suggestions?

**Comment by edwh** [comment] 2015-04-08 16:31
In case anyone else finds this, I got it working using the script here:

https://gist.github.com/colin-kiegel/a9d7045a73a715ce2478

**Comment by Orvid** [comment] 2016-09-30 21:24
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:24 UTC

**Comment by Excelautomation** [comment] 2017-03-22 12:32
I was getting this error due to wrong permissions. I changed the file back to www-data:www-data and it worked again.
