### ISSUE TITLE
Autoloader working, but errors keep saying it isn't.

### ISSUE THREAD

**Issue by tarsupin** [facebook/hhvm#6075] opened 2015-08-20 00:49 UTC
I'm seeing a highly unusual issue with my system right now. I've set up an autoloader, and the autoloader has been working fine on everything I've used - mostly localhost wamp servers without HHVM and linode servers *with* HHVM. Anyway, I downloaded vagrant recently and have been using the same code as always, but for some reason I'm now getting an extremely unusual behavior when using HHVM on my local vagrant system.

Here's the autoloader, reduced for simplicity:

```
// Create our custom Auto-Loader Function
function AutoLoader($class)
{
	echo "SHOUT #1!";
	
	$preClass = str_replace("_", "/", $class);
	
	$special = (USE_HHVM ? array("hhvm/", "") : array(""));
	
	foreach($special as $opt)
	{
		// Search System Classes
		if($classFile = realpath(SYS_PATH . "/core-classes/$preClass/" . $opt . $class . ".php"))
		{
			require($classFile); return true;
		}
	}
	
	// The plugin was not located. Return false.
	return false;
}

// Register our custom Auto-Loader
spl_autoload_register('AutoLoader');

// Security_Sanitize::variable("ASDF1234!@#$");  // If I uncomment this line within this file, it gets even stranger
```

And here's the class I'm loading:

```
Security_Sanitize::variable("ASDF1234!@#$");
```

And for temporary purposes, I've added this in the /core-classes/Security/Sanitize/Security_Sanitize.php file:

```
<?php echo "YELL #2!"; exit; 
```

And this is the response that I'm getting:

```
Warning: File not found: security_sanitize.php in /vagrant/apps/myapp/public/index.php on line 74
SHOUT #1!YELL #2!
```

... which, as I said, is highly confusing. It's outputting the warning BEFORE it outputs "SHOUT #1", and yet, the file is clearly being loaded (see "YELL #2").

What's even more bizarre is that if I call the function within the autoloader.php page immediately after registering it, it will process normally without the warning.

And if I put this at the top of the autoloader, it also works as expected:

```
require(SYS_PATH . "/core-classes/Security/Sanitize/Security_Sanitize.php"); return true;
```

I have no idea what's going on here... Is there any explanation as to why this is happening? I can run this without any error reporting in wamp, and also without issues on the linode servers (on hhvm) as of a few months ago. I haven't updated hhvm on those servers for a while, though.

**Comment by Orvid** [comment] 2016-09-29 20:35
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-29 20:35 UTC
