### ISSUE TITLE
Hack: Memoize doesn't play nice with LSB

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#6639] opened 2015-12-08 00:23 UTC
See example run: https://3v4l.org/fKi0j

``` hack
<?hh

class A {
    protected static string $string = 'Hello';

    <<__Memoize>>
    public static function foo(): string {
        return static::$string;
    }
}

class B extends A {
    protected static string $string = 'World';
}
```

I'd expect `B::foo()` to return `'World'` in this case, whereas it returns `Hello`.

**Comment by paulbiss** [comment] 2015-12-08 01:42
I'm fairly certain this is by design. __Memoize caches are keyed based only on parameters, and an extending class doesn't have its own cache for memoized statics in the parent.

**Comment by jwatzman** [comment] 2015-12-08 22:41
Yeah, I suspect this is `wontfix`, poke @dlreeves @dabek and @int3 just in case.

**Comment by HRMsimon** [comment] 2015-12-08 22:41
If that's the case, should `static::` usage through an error in a `__Memoize` method?

**Comment by HRMsimon** [comment] 2016-09-06 23:15
Have managed to work around this with a nasty hack:

```hack
<?hh

class A {
    protected static string $string = 'Hello';

    <<__Memoize>>
    public static function foo($class = get_called_class()): string {
        // UNSAFE
        return $class::$string;
    }
}

class B extends A {
    protected static string $string = 'World';
}
```

Is slightly nicer than how we've been polluting the global namespace with a bunch of functions that are basically:
```hack
<<__Memoize>>
function getMemoizedB(): string {
  return B::foo();
}
```

An actual solution will be nicer though.

**Comment by paulbiss** [comment] 2016-09-07 00:31
This topic tends to come up from time to time internally. The consensus now seems to be that both behaviors are potentially surprising (one could easily assume the memoization was per declaration site or per LSB target).

Changing `__Memoize` is unlikely to be a viable option as we've found that most of the time the LSB isn't something we care about, but adding a `__MemoizedLSB` has been proposed a few times and is generally something I'd be in favor of adding (though I've not had time to poke at it myself).

**Comment by fredemmott** [comment] 2018-08-28 22:57
3.28 includes `<<__MemoizeLSB>>` as an experimental feature

**Closed by fredemmott** 2018-08-28 22:57 UTC
Labels: hack
