### ISSUE TITLE
HHVM hang in flock below FileSessionData::openImpl

### ISSUE THREAD

**Issue by edwh** [facebook/hhvm#5450] opened 2015-06-04 14:59 UTC
I see an occasional hang in the HHVM server process where all the threads are stuck doing an flock.

This persisted for a few minutes.  I had some other cron jobs which were running scripts using HHVM, which I killed, and the server process came back into life.  That was a bit foolish of me, as a) I was hoping to experiment to find a monit incantation which could spot this and kill it and b) it was probably the background scripts which were the interesting ones to look at.

Anyone seen this?  Here's a backtrace of the server process hung in this state.

http://pastebin.com/sPe6uyA5

**Comment by 1Conan** [comment] 2015-06-04 21:10
Mind moving the log to pastebin?

**Comment by jwatzman** [comment] 2015-06-04 22:37
Moved to a pastebin :) (FB folks, I also copied into the internal paste tool at P19864781, in case the pastebin goes away.)

Thanks for the backtraces, they look potentially useful. Someone will look when they get a chance.

**Comment by edwh** [comment] 2015-06-05 11:37
Thanks.  I'm going to try storing the sessions in Redis as a workaround.

**Comment by Orvid** [comment] 2016-09-30 21:04
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:04 UTC
Labels: crash, no isolated repro
