### ISSUE TITLE
Update CakePHP 3 framework tests

### ISSUE THREAD

**Issue by lorenzo** [facebook/hhvm#4928] opened 2015-03-02 10:06 UTC
Cake 3 is already passing all tests in hhvm according to travis, https://travis-ci.org/cakephp/cakephp/jobs/52712798

This should be reflected in the tests bundled in the source code.

**Comment by garex** [comment] 2015-03-02 10:16
+1 nice news!

**Comment by bauerj** [comment] 2015-03-02 16:00
I updated the test runner file to use CakePHP 3.0.0-RC2 (20 days old - latest stable version I could find).

The amount of passing tests, however, only raised from 98.51% to 99.03% which is still not what they got in their Travis run: https://travis-ci.org/cakephp/cakephp/jobs/50006611

**Comment by garex** [comment] 2015-03-02 16:09
Mmm... Those skipped tests are not from HHVM -- it's a policy of cake's team: for some bug we create test and mark it as skipped. See latest cake's tests -- they also have same if not more skipped tests.

**Comment by bauerj** [comment] 2015-03-02 16:25
What exactly do you mean by 
> for some bug we create test and mark it as skipped.
? The test runner does skip tests that use `$this->skipIf()`, if that's what you mean.

**Comment by garex** [comment] 2015-03-02 16:47
@bauerj Sorry, I'm wrong. But anyway most of them are just something like "extension X not loaded/function not exists/bla not writable".  May be if someone on cakephp side will play with travis setup — it will increase all numbers.

**Comment by bauerj** [comment] 2015-03-02 18:22
@garex Actually you were not that wrong:

I investigated a bit and found out that e.g. the redis and memcached tests fail when there is no redis/memcached server running.

If the server that runs the framework tests got that enabled, the number of passing tests should go up. I guess that is at least a part of the issue and I'm going to report it upstream.

**Comment by garex** [comment] 2015-03-02 19:42
@bauerj I was wrong as it's not Cake's policy — it's wordpress policy. See https://make.wordpress.org/core/handbook/automated-testing/

**Comment by lorenzo** [comment] 2015-03-03 08:34
@bauerj @garex The cakephp test suite was updated to skip tests when those services are not available

https://github.com/cakephp/cakephp/commit/f07025f8ffc8dfa5d45054033211282a27c9a773

**Comment by garex** [comment] 2015-03-03 08:38
@lorenzo @bauerj As I understand for HHVM guys it will be still not 100% as tests will be skipped. It's better to play with travis's setup and add/setup those classes to have 100% tests running. Not only in raw PHP, but in HHVM also.

**Comment by lorenzo** [comment] 2015-03-03 08:45
@garex You can check the travis HHVM job for that commit https://travis-ci.org/cakephp/cakephp/jobs/52862230

**Comment by garex** [comment] 2015-03-03 08:52
@lorenzo it's running under container-based arch. We can't customize there build nodes. To have 100% of tests we need to avoid container-based (even if they faster) and customize travis build by apt-getin needed packages and servers. Then we will get 100% of tests.

**Comment by lorenzo** [comment] 2015-03-03 09:02
@garex sorry, I don't get what "container-based" and what it has to do with the tests themselves. What should be done?

**Comment by garex** [comment] 2015-03-03 09:05
@lorenzo in terms of travis "container-based" is a builder node that runs under Docker container and that allows you to use only what is inside of that container. So if travis gives us only PHP in it — we will have only PHP. In traditional travis builds (non-containers) we can run `sudo apt-get redis-or-else` and install it. then another piece of sh code and it will be up and running.

See http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by bauerj** [comment] 2015-03-03 17:09
Well, the problem here is not Travis. The Travis tests runs that they make get 100% succeeding tests.

**Comment by garex** [comment] 2015-03-03 17:42
@bauerj Then where is our problem? As I understand when they not see 100% tests which will be in case of 185 skipped, they not think it's 100% succeeded.

**Comment by bauerj** [comment] 2015-03-03 17:58
> Then where is our problem?

Good question :smile: I think we talk past each other a bit. Okay, I'll try to clarify a bit:

Skipping tests appears quite often because you need a specific platform for some tests to work correctly. The graph on hhvm.com shows 100% even if the test runner skipped a few tests which is the expected behaviour.

The problem _was_ that CakePHP did not skip tests they should have skipped. They fixed that by now and I'm gonna re-run the new tests as soon as my server finished building (which will be in a few hours). I assume that we get much closer to 100% this time so from my perspective there is no real problem.

I will also update my Pull Request to get the latest CakePHP version that got the fixed tests.

Sorry if I confused you with what I said earlier! I hope that everything is clear now :smiley:

**Comment by garex** [comment] 2015-03-03 18:37
@bauerj Ahhh! :)) Now I see. But anyway — even if formally we will have 100%. Why then we can't to play with testing node to have *even more free* non-skipped tests (now with peanuts)?

**Comment by bauerj** [comment] 2015-03-03 18:42
Sure, that would be a good thing. You can't run _all_ tests together though, some might only run on Linux, some others only on Windows...

Anyway, only a Facebook employee could do that and I think there are plenty of other (more important) things to do for them :dizzy_face:

**Comment by bauerj** [comment] 2015-03-03 20:08
Okay, now we're at 99,61% :+1:

**Comment by garex** [comment] 2015-03-03 20:12
![goodnewseveryone](https://cloud.githubusercontent.com/assets/77981/6471282/67ce5e80-c20b-11e4-8c19-be129f1e67cf.png)

Only 0.39% left — who are those bad guys?

**Comment by bauerj** [comment] 2015-03-03 20:18
Well...

	Cake\Test\TestCase\Console\ShellTest::testCreateFileNoPermissions
	Cake\Test\TestCase\Database\ConnectionTest::testWrongCredentials
	Cake\Test\TestCase\Database\Type\DateTimeTypeTest::testMarshalWithLocaleParsing
	Cake\Test\TestCase\Database\Type\DateTimeTypeTest::testMarshalWithLocaleParsingWithFormat
	Cake\Test\TestCase\Database\Type\DateTypeTest::testMarshalWithLocaleParsing
	Cake\Test\TestCase\Database\Type\DateTypeTest::testMarshalWithLocaleParsingWithFormat
	Cake\Test\TestCase\Database\Type\TimeTypeTest::testMarshalWithLocaleParsing
	Cake\Test\TestCase\Filesystem\FolderTest::testRecursiveCreateFailure
	Cake\Test\TestCase\Filesystem\FolderTest::testReset
	Cake\Test\TestCase\I18n\NumberTest::testFormatDelta
	Cake\Test\TestCase\Network\SocketTest::testTimeOutConnection
	Cake\Test\TestCase\ORM\TableTest::testReciprocalBelongsToLoading
	Cake\Test\TestCase\ORM\TableTest::testReciprocalBelongsToMany
	Cake\Test\TestCase\ORM\TableTest::testReciprocalHasManyLoading
	Cake\Test\TestCase\Shell\PluginAssetsShellTest::testCopy
	Cake\Test\TestCase\Shell\PluginAssetsShellTest::testSymlinkWhenVendorDirectoryExits
	Cake\Test\TestCase\Shell\PluginAssetsShellTest::testSymlinkingSpecifiedPlugin
	Cake\Test\TestCase\Utility\HashTest::testSortNatural

Seems like these are all "real" errors.

**Comment by garex** [comment] 2015-03-03 20:20
Can you add a little `--verbose`  ?

**Comment by bauerj** [comment] 2015-03-03 20:44
Sure: http://bauerj.link/p/Dpin!8

**Comment by lorenzo** [comment] 2015-03-04 09:12
@bauerj Failure 15 was a hhvm bug fixed recently, maybe the versions run in cakephp's travis and your version differ?

**Comment by bauerj** [comment] 2015-03-04 18:09
> maybe the versions run in cakephp's travis and your version differ?

It would be a huge coincidence if they didn't differ :wink: I compiled it from source but I don't know exactly if I pulled the latest changes before :flushed: 

Anyway, we'll see the real numbers on hhvm.com once my Pull Request landed :+1:

**Comment by bauerj** [comment] 2015-03-19 13:00
Now it's 99,75%: http://hhvm.com/frameworks/

:facepunch:

**Comment by garex** [comment] 2015-03-19 13:05
@bauerj rocks ))

Now we need to destroy those last 0.25% and we can officialy tell everyone, that cake is fullly hhvmed.

**Comment by bauerj** [comment] 2015-03-19 16:49
> Now we need to destroy those last 0.25% and we can officialy tell everyone, that cake is fullly hhvmed.

That would be great :smiley:  However, I don't have enough time to track these issues down right now. Maybe someone else will look into this?

**Comment by JoelMarcey** [comment] 2015-06-18 20:27
This was closed by #4931, right?

**Closed by JoelMarcey** 2015-06-18 20:27 UTC
