### ISSUE TITLE
HHVM stopped sending emails.

### ISSUE THREAD

**Issue by pratham2003** [facebook/hhvm#7094] opened 2016-05-24 06:26 UTC
HHVM had stopped allowing to send email after a few weeks.
We are using wordpress and woocommerce, we noticed that emails were not being delivered, I watched the mail log while trying to manually send email from wordpress and there was noting in the mail log.. No errors in HHVM's error log either.. After restarting the HHVM process the emails started working again.

### HHVM Version
HipHop VM 3.12.0 (rel)
Compiler: tags/HHVM-3.12.0-0-g440e6a096b2db8a449b9690a72f2f1792530e86a
Repo schema: 033b8dedf4af99b892f2488b103a8d67a58ff816

### Standalone code, or other way to reproduce the problem
Its the first time we came across this issue on HHVM, it might be very rare. I'm just reporting this in case someone else has anything to add.
Wordpress uses PhpMailer to send emails.
PhpMailer is set to use PHP's mail()
https://developer.wordpress.org/reference/functions/wp_mail/#source-code

**Comment by aorenste** [comment] 2016-09-29 01:15
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by aorenste** 2016-09-29 01:15 UTC

**Comment by benedict-w** [comment] 2018-07-13 15:16
+1 for this issue.

Running HHVM on Siteground with WordPress / WooCommerce. Any resolution, or suggestions?

**Comment by pratham2003** [comment] 2018-07-13 15:43
I don't recall the resolution to the issue back then, but in case you are using a plugin like SES Mailer that relies on Amazon API do verify that your system time is in sync with a NTP server. The issue is most probably not with HHVM itself.

Try checking your mail log ( /var/log/mail...something ) for additional information.
or check this out https://www.codeforest.net/debugging-wp-mail-like-a-boss-debugger
