### ISSUE TITLE
HHVM 3.13.0

### ISSUE THREAD

**Issue by EpicUsaMan** [facebook/hhvm#6959] opened 2016-04-02 13:29 UTC
HHVM 3.13.0, NGINX 1.9.13

Error 502 after update to 3.13.0 from 3.12

/usr/share/hhvm/install_fastcgi.sh -> Don`t work

My configuration (from the internet):

**hhvm.conf**
```
location ~ \.(hh|php)$ {
    fastcgi_keep_conn on;
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include        fastcgi_params;
}
```

**server.ini**
```
; php options

pid = /var/run/hhvm/pid

; hhvm specific

hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
```

**/var/log/nginx/error.log**
`2016/04/02 05:27:55 [error] 2564#2564: *5 connect() failed (111: Connection refused) while connecting to upstream, client: ip_adress, server: *.example.com, request: "GET /profile/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "example.com"`

After downgrade to 3.12.1 work fine.

**Comment by simonwelsh** [comment] 2016-04-02 21:50
Likely a dupe of #6950 or #6941

**Comment by Orvid** [comment] 2016-04-06 18:42
Yep, looks like HHVM had already crashed, which is why you were getting errors.
Closing as a duplicate of #6950.

**Closed by Orvid** 2016-04-06 18:42 UTC
Labels: crash, duplicate
