### ISSUE TITLE
Cannot call properties that are functions without wrapping in lambda

### ISSUE THREAD

**Issue by acrylic-origami** [facebook/hhvm#7120] opened 2016-06-01 04:26 UTC
### HHVM Version
```
$ hhvm --version
HipHop VM 3.13.1 (rel)
Compiler: tags/HHVM-3.13.1-0-g4f382ad928a6e2a0607a8dcb251002aca77f11f6
Repo schema: 655b5912cb8136e9df6f9be972153e38ac446e0f
```

### Standalone code, or other way to reproduce the problem
```hack
<?hh // strict
class A {
  public function __construct(
    public (function(): int) $foo
  ) {}
  public function call_foo(): int {
    return $this->foo();
    // return ($this->foo)(); // also fails
  }
}
```

### Expected result
`No errors!`, calling `(new A(() ==> 42))->callFoo()` somewhere else yields `42`

### Actual result
```
File "sandbox/A.php", line 7, characters 19-21:
Could not find method foo in an object of type A (Typing[4053])
File "sandbox/A.php", line 7, characters 12-16:
This is why I think it is an object of type A
File "sandbox/A.php", line 2, characters 7-7:
Declaration of A is here
```

### Messy hack (literally)

```hack
public function call_foo(): int {
  return ((() ==> $this->foo)())();
}
```

**Comment by simonwelsh** [comment] 2016-06-01 06:58
Duplicate of #2730.

**Comment by jwatzman** [comment] 2016-06-01 17:04
Yeah see details on that issue. Note that you can pull out into a local:

```hack
public function call_foo(): int {
  // Not legal in PHP or Hack (this is a method call not an invocation of a closure in a member variable):
  // return $this->foo();

  // Should be legal but isn't due to typechecker implementation details:
  // return ($this->foo)();

  // This works:
  $foo = $this->foo;
  $foo();
}
```

**Closed by jwatzman** 2016-06-01 17:04 UTC
