### ISSUE TITLE
array_multisort does not work correctly with SORT_DESC and SORT_NATURAL

### ISSUE THREAD

**Issue by lorenzo** [facebook/hhvm#4567] opened 2015-01-03 23:04 UTC
Please take a look to this script http://3v4l.org/ftFM8

You can see there that HHVM is not able to sort correctly in descending order, unlike zend's implementation.

**Comment by WizKid** [comment] 2015-01-04 05:52
I think the problem is https://github.com/facebook/hhvm/blob/cbeea88ed6355a80fb6858d158552a62f97d4db2/hphp/runtime/ext/array/ext_array.cpp#L2569-2572 . It doesn't care about the ascending flag that is passed in for natural sort

**Comment by reeze** [comment] 2015-01-13 02:47
I didn't add automatic close tag in my commit, this was fixed, could you please close it?

**Closed** 2015-01-13 05:29 UTC
Labels: php5 incompatibility, probably easy
