### ISSUE TITLE
every 30-40 min afer start HHVM crash with Failed to initialize central HHBC repository error

### ISSUE THREAD

**Issue by RUnnerTomsk** [facebook/hhvm#5529] opened 2015-06-24 09:03 UTC
Jun 24 10:53:54 hhvm: Assertion failure: /opt/hhvm/hphp/runtime/vm/repo.cpp:576: void HPHP::Repo::initCentral(): assertion `false' failed.
Jun 24 10:53:54 hhvm: Failed to initialize central HHBC repository:
Jun 24 10:53:54 hhvm: Failed to open /var/run/hhvm/hhvm.hhbc: 14 - unable to open database file

HipHop VM 3.8.0-dev (rel)
Compiler: heads/master-0-gf9cc1f7102b8138e6b25dc8895368c02e2e5ee1d
Repo schema: b13e1b5baa4d868dfe02a6061e7ff352eecb74f0

**Comment by paulbiss** [comment] 2015-06-24 18:40
Can the user hhvm is running under write to the directory /var/run/hhvm? Does /var/run/hhvm/hhvm.hhbc already exist?

**Comment by RUnnerTomsk** [comment] 2015-06-25 05:53
Yes, directory exist, chmod 777 on it.
hhvm work good about 30-40 min, when quit with this error.

**Comment by paulbiss** [comment] 2015-06-25 19:29
Hmm, it's either database corruption or something else. When you get the error is the hhvm.hhbc file still there?

**Comment by RUnnerTomsk** [comment] 2015-06-26 04:41
[root@hhvm]# ls -la
итого 3868
drwxrwxrwx  2 nginx nginx     100 июн 24 14:54 .
drwxr-xr-x 26 root  root      800 июн 25 09:53 ..
-rw-r--r--  1 nginx nginx 3955712 июн 24 14:54 hhvm.hhbc
srwxrw----  1 nginx nginx       0 июн 24 14:54 hhvm.sock
-rw-r--r--  1 nginx nginx       4 июн 24 14:54 pid
[root@hhvm]# 

last two lines in file hhvm.hhbc:
INSERT INTO "Func_b13e1b5baa4d868dfe02a6061e7ff352eecb74f0" VALUES(114,0,-1,'',0,X'0179000A8080040001000001000000000000000000000100000000');
INSERT INTO "Func_b13e1b5baa4d868dfe02a6061e7ff352eecb74f0" VALUES(114,1,-1,'calcWnEight',1,X'1E3B0AA2050000BB072F2A2A0A202A20D0A0D0B0D181D187D0B5D18220D180D0B5D0B9D182D0B8D0BDD0B3D0B020574E380A202A0A202A2
INSERT INTO "Func_b13e1b5baa4d868dfe02a6061e7ff352eecb74f0" VALUES(114,2,-1,'setWnEightToUser',1,X'5279A205DE080000CD072F2A2A0A202A20D0A0D0B0D181D187D0B5D18220D180D0B5D0B9D182D0B8D0BDD0B3D0B020574E382C20D0
CREATE TABLE Litstr_b13e1b5baa4d868dfe02a6061e7ff352eecb74f0(litstrId INTEGER, litstr TEXT, PRIMARY KEY (litstrId));
COMMIT;

**Comment by Orvid** [comment] 2016-09-30 19:50
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:50 UTC
Labels: crash
