### ISSUE TITLE
zend compat PHPAPI php_version_compare not implemented

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#5244] opened 2015-05-03 19:43 UTC
The two functions:
  php_canonicalize_version
  php_version_compare
are part of the zend php API.  They are defined as PHPAPI in
  ./hphp/runtime/ext_zend_compat/php-src/ext/standard/php_versioning.h
but are never implemented in a way that's visible to the zend compatibility extensions.

Note that the source code for these functions appear to have been dropped more or less unmodified from PHP5 into ./hphp/runtime/ext/std/ext_std_options.cpp, but their linkage is static and C++ naming, and so is not visible to satisfy the linkage requirement of PHPAPI.

**Comment by paulbiss** [comment] 2015-05-04 05:38
Would lining them non-statically and declaring them extern "C" be a viable solution, or are these functions hot? (In which case declaring an alternate set with C linkage may be preferable)

**Comment by Orvid** [comment] 2016-09-30 21:14
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Comment by Orvid** [comment] 2016-09-30 21:14
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Closed by Orvid** 2016-09-30 21:14 UTC
