### ISSUE TITLE
Segmentation fault after 12 page request in Repo Authoritative

### ISSUE THREAD

**Issue by emidelgo** [facebook/hhvm#5391] opened 2015-05-22 23:13 UTC
Hi,
I tested this bug on Debian 8, with official hhvm repository, hhvm 3.7 and the nightly.

I start hhvm, I refresh a page 12 times, and hhvm crashes. This only in repo authoritative mode. In normal mode it works fine.

HHVM Version:
HipHop VM 3.8.0-dev (rel)
Compiler: heads/master-0-ga92695ac1527b970fb8a7c6d1170e3d431501f66
Repo schema: 779f49b7062dfe0798d7379b57875cafdc7c9e75

This is the stacktrace: http://pastebin.com/KNsUiNt4

These are the files indicated in the stacktrace: http://pastebin.com/n7acjJzG http://pastebin.com/JRhuwy6U

**Comment by jwatzman** [comment] 2015-05-23 09:52
Do you have driver files that cause those scripts to execute we can use to try to reproduce this? While what you've provided is useful, it's not quite enough for a repro case, which is even more useful :)

@paulbiss does anything in the backtrace look suspicious to you? Looks like we crashed while JITing code.

**Comment by emidelgo** [comment] 2015-05-23 10:04
For driver files, do you mean you need other files to test?

**Comment by emidelgo** [comment] 2015-05-23 10:26
Hi. I isolated a test case. I removed all other package and code, there is only composer and the segfault still appear. This is the minimal test case:
https://www.dropbox.com/s/q3d326878d3yknt/testcase.zip?dl=0

**Comment by jwatzman** [comment] 2015-05-26 17:29
Thanks, that's useful! I can't reproduce the issue though. What how are you building the repo, and what options are you passing to HHVM (both when building the repo and when running it)? Here's what I did:

```
$ hhvm --version
HipHop VM 3.8.0-dev (dbg)
Compiler: heads/master-0-g874e02db63997598fd2f5dc534bc5f03b83f10c8
Repo schema: f385e1b46349562111d1fc5fd65c41c0cb6774dc

$ find . -type f > file_list
$ cat file_list 
./vendor/composer/installed.json
./vendor/composer/autoload_real.php
./vendor/composer/autoload_namespaces.php
./vendor/composer/autoload_psr4.php
./vendor/composer/ClassLoader.php
./vendor/composer/autoload_classmap.php
./vendor/composer/autoload_files.php
./vendor/autoload.php
./file_list
./composer.phar
./index.php
./testcase.zip
./composer.json

$ hhvm --hphp --target hhbc --output-dir . --input-list file_list -l3
running hphp...
parsing inputs...
Unable to stat file phar:/composer.phar/bin/composer
analyzeProgram...
analyzeProgram took 0'00" (56102 us) wall time
parsing inputs took 0'00" (65344 us) wall time
pre-optimizing...
pre-optimizing took 0'00" (19912 us) wall time
creating binary HHBC files...
creating binary HHBC files took 0'00" (854117 us) wall time
all files saved in . ...
running hphp took 0'01" (1518291 us) wall time

$ hhvm -d hhvm.repo.authoritative=true -d hhvm.repo.central.path=hhvm.hhbc -m server -v Server.Type=proxygen -d hhvm.server.port=8080
```

And then loaded `localhost:8080/index.php` a bunch of times in a browser, with no problems.

**Comment by emidelgo** [comment] 2015-05-26 19:50
Hi @jwatzman . Here, all data about my environment: http://pastebin.com/6qihLwig

Twelve page refresh, and crash.

**Comment by emidelgo** [comment] 2015-05-26 19:53
Hi, Update, the bug with the last nightly doesn't appear anymore... I'm doing other tests...

**Comment by emidelgo** [comment] 2015-05-26 21:00
Hi @jwatzman, I tested the code also on 3.7 and I have no more problems. It's really strange. I executed hhvm in a VM, I paused after last my ticket response (getting the error) and I resumed that now (getting no more errors). Therefore I can't replicate the error anymore. I didn't change the php code. It's really strange...

**Comment by jwatzman** [comment] 2015-05-26 23:13
Especially since you were using the nightlies, it's possible it was a bug in master that has since been fixed. Closing this out -- feel free to reopen if you can repro again.

**Closed by jwatzman** 2015-05-26 23:13 UTC
Labels: crash, needs more info
