### ISSUE TITLE
Binary packages for Fedora 21

### ISSUE THREAD

**Issue by sebastianbergmann** [facebook/hhvm#4426] opened 2014-12-11 12:07 UTC
... are currently not offered. Would be nice if they were.

**Comment by jrobeson** [comment] 2015-01-18 23:29
the array_plus_eq_dtor test still fails on fedora 21 in hhvm 3.5.0

**Comment by wjywbs** [comment] 2015-01-19 16:37
The array_plus_eq_dtor test is false positive in interp mode because "Order of destruction is not guaranteed. Test shouldn't expect it". https://github.com/php/php-langspec/pull/99

**Comment by jwatzman** [comment] 2015-01-20 20:22
@rrh, @JoelMarcey, myself, and probably others I'm forgetting tracked down and fixed a bunch of the false positives in the OSS tests/slow failures late last week. I'm making sure those fixes get out on master and will then merge into 3.5 later, so hopefully we'll be clean there on Ubuntu 14.04 at least, interesting to see if/how Fedora differs.

**Comment by jrobeson** [comment] 2015-02-03 08:09
@jwatzman: let me know when these tests get in.

**Comment by jwatzman** [comment] 2015-02-03 17:47
They've been in. Just did a build of the current head of the 3.5 branch (f249591f2861deea06fe8ec48ae03e3c98e52825) and it passes all quick and slow tests on my 14.04 VM.

**Comment by jrobeson** [comment] 2015-02-03 21:03
@jwatzman : so what's your reading of https://github.com/facebook/hhvm/issues/4426#issuecomment-70522875 ?

**Comment by jwatzman** [comment] 2015-02-03 22:15
It passes on my 14.04 box in both jit and interp modes. I'm not sure if it's actually relying on undefined behavior or not (it's different than the linked case since that was about relative order of destruction of different objects, this is about when an object is destructed wrt control flow). @paroski do you know if we enforce when objects must be desctructed?

@jrobeson is it failing for you on Fedora? What's the output? I'm slightly surprised that the behavior would be different.

**Comment by jrobeson** [comment] 2015-02-03 22:30
it still fails in 3.5 just like in : https://github.com/facebook/hhvm/issues/4426#issuecomment-68031386 , only in fedora 21 (not EL7 or Fedora 20), and not when part of a full test run.

**Comment by jwatzman** [comment] 2015-02-03 23:28
Yeah that looks weird. Not sure how much I'll be able to help, but can you pastebin/gist/something the `.out` file you get from that test? The diff you pasted above looks weird, might have gotten munged or something.

**Comment by jrobeson** [comment] 2015-03-13 22:20
finally got a build system running fedora 21, so i can reliably reproduce this now:
```php
array(3) {
  [0]=>
  object(dtor)#1 (0) {
  }
  [1]=>
  int(5)
  [2]=>
```
  int(6)
}
done

**Comment by kminooie** [comment] 2015-06-10 00:37
considering that the packages for fedora are not being maintained, the links about fedora repositories on this page https://github.com/facebook/hhvm/wiki/Prebuilt%20Packages%20for%20HHVM should be removed. Specially since after the conversation that I had this morning in IRC, even the old files are not there anymore.

**Comment by jrobeson** [comment] 2015-06-10 02:17
I wonder if i can have access to hhvm-packaging OR if i can have more official place to put my package files like hhvm-rpm or something.

**Comment by jwatzman** [comment] 2015-06-10 16:52
@kminooie oops, thanks, I removed the Fedora 19 and 20 links, which were pointing to dl.hhvm.com, which is definitely unmaintained and ancient at this point.

@jrobeson in the short term, please make sure your repos are properly listed under "Unsupported by the HHVM team" at https://github.com/facebook/hhvm/wiki/Prebuilt%20Packages%20for%20HHVM -- I think you provide packages for at least some Fedoras, which aren't there, and would be excellent to list. I'm not sure if we'd be able to give you access to `dl.hhvm.com`, or if there's any sort of other official-ish blessing for the packages?

**Comment by jrobeson** [comment] 2015-06-10 20:06
I'd still probably be having them built on Fedora's COPR. It was more a question about a centralized place to store the packaging files themselves (spec files, patches)

**Comment by jwatzman** [comment] 2015-06-10 21:50
A `fedora` subdir under https://github.com/hhvm/packaging/tree/master/hhvm perhaps?

**Comment by jrobeson** [comment] 2015-06-10 22:07
the name should cover both fedora and el >= 7, but sure. How should access be handled?

**Comment by jwatzman** [comment] 2015-06-10 22:43
For now, I'm happy to rubberstamp any PRs you want to send. Giving contributors push access is annoying, for annoying reasons, but potentially doable; I'll look into it.

**Comment by jrobeson** [comment] 2015-06-10 23:06
@jwatzman : maybe the new github organizational features that launched today would help?  https://github.com/blog/2020-improved-organization-permissions It does require one to request access though.

**Comment by jwatzman** [comment] 2015-06-18 17:55
I think the plan for now is that @jrobeson is going to continue hosting his packages on COPR, and I've given him commit access to the packaging repo to put whatever scripts/support stuff he needs for Fedora there. The HHVM team will continue to not officially support Fedora (we just don't have the time/expertise), but I at least unofficially will recommend folks use @jrobeson's packages.

Assigning this to him -- I don't really know what else there is to do here. :)

**Comment by jwatzman** [comment] 2015-06-18 17:55
(Er, apparently I can't assign to folks who don't have push access to the repo, but you get the idea.)

**Comment by paulbiss** [comment] 2016-09-28 23:28
Closing this for now as external as there aren't any current plans to add official fedora packages.

**Closed by paulbiss** 2016-09-28 23:28 UTC
Labels: build, external
