### ISSUE TITLE
configure cmake ldap trouble

### ISSUE THREAD

**Issue by Piervit** [facebook/hhvm#5846] opened 2015-08-03 16:18 UTC
I had to add this in CMake/HPHPFindLibs.cmake in order to configure the project:

# ldap
find_package(Ldap)
if (LDAP_INCLUDE_DIR)
  include_directories(${LDAP_INCLUDE_DIR})
endif()

Then it worked well.

**Comment by Orvid** [comment] 2015-08-03 22:22
This was removed from the global find libs in favor of the extension config mechanism finding it instead. Which piece of code needed the ldap headers?

**Comment by Orvid** [comment] 2015-08-04 01:42
Is it linking correctly for you even without linking against the ldap library? [HHVMExtensionConfig.cmake:706](https://github.com/facebook/hhvm/blob/master/CMake/HHVMExtensionConfig.cmake#L706) is where this should be getting handled.

**Comment by Piervit** [comment] 2015-08-04 08:03
Hello,
Thanks for the comment.

I have to say that I am no more able to reproduce.... even after cloning fresh project. So might be a problem from myself...
In every case, the problem I had was that I got an error such as "LBER_LIBRAIRIES" defined as "NOT_FOUND".

**Comment by jwatzman** [comment] 2015-08-04 20:46
@Piervit if you can reproduce, or know what might be going on here, let us know and we can reopen. But since it looks like human error, going to close this out for now.

**Closed by jwatzman** 2015-08-04 20:46 UTC
Labels: build
