### ISSUE TITLE
repo-auth mode: incorrect class method resolution with class_alias()

### ISSUE THREAD

**Issue by catalin-manciu** [facebook/hhvm#8096] opened 2018-01-09 22:20 UTC
### HHVM Version
Current master starting from:
aeacd50432c7031143eb7f30534e0e8a8dbd8288

### Operating System and Version
Reproduced on Ubuntu 16.04

### Standalone code, or other way to reproduce the problem
A certain hierarchy of classes, in combination with having an alias for the base class, will produce an incorrect class method resolution for one of the derived classes' methods. This is what causes #8088.

Here are a PHP and a Hack snippet which will exhibit this erroneous behavior:
#### PHP
```php
<?php
    class Base  {
        public function overriddenMethod() {
            return "Base::overriddenMethod";
        }
        public function wrapper() {
            return $this->overriddenMethod();
        }
    }

    class DerivedOne extends Base {
        public function overriddenMethod() {
            return "DerivedOne::overriddenMethod";
        }
    }

    class DerivedTwo extends Base {
    }

    class_alias( 'Base', 'AliasForBase' );

    $inst = new DerivedOne();
    printf($inst->wrapper());
```
#### Hack
```hack
<?hh // strict
    class Base  {
        public function overriddenMethod() : string {
            return "Base::overriddenMethod";
        }
        public function wrapper() : string {
            return $this->overriddenMethod();
        }
    }

    class DerivedOne extends Base {
        public function overriddenMethod() : string {
            return "DerivedOne::overriddenMethod";
        }
    }

    class DerivedTwo extends Base {
    }

    class_alias( 'Base', 'AliasForBase' );
 
    $inst = new DerivedOne();
    printf($inst->wrapper());
```
Bug manifests only when running in Repo-Authoritative mode:
`hhvm --hphp --target hhbc --output-dir $REPO_FOLDER test.php`
`hhvm -v Eval.Jit=1 -vRepo.Authoritative=true -vRepo.{Central,Local}.Path="$REPO_FOLDER/hhvm.hhbc" test.php`
### Expected result
Both scripts should output `DerivedOne::overriddenMethod`
### Actual result
Both scripts output `Base::overriddenMethod`

**Comment by fredemmott** [comment] 2018-01-09 22:39
PHP example is a bug; Hack example is invalid:
 - top-level statements are banned in `<?hh // strict`
 - `class_alias()` is not defined in Hack

**Comment by octmoraru** [comment] 2018-01-09 23:09
We believe the cause for this is the fact that `Base::overriddenMethod` ends up being incorrectly marked as `AttrNoOverride` when building the HHBBC `Index`. 

This happens because:
1. In the first loop of `mark_no_override_methods`, for `class Base`, `AttrNoOverride` is not set for any of the class's methods since the class is not `AttrUnique` (line [2219](https://github.com/facebook/hhvm/blob/master/hphp/hhbbc/index.cpp#L2219))
2. Also in the first loop, for `class DerivedTwo`, method `overriddenMethod`  will set `AttrNoOverride` for its own `MethodTabEntry` and the encapsulated `php::Func`, which in this case is `Base::overriddenMethod`. At this point, the parent (`Base::overriddenMethod`) `Func` will have `AttrNoOverride` set, while its `MethodTabEntry` won't.
3. Then, in the second loop, we are unable to clear `AttrNoOverride` on the the parent `Func`. For `class DerivedOne`, we see that `overriddenMethod` actually overrides the parent method in the parent so we call `removeNoOverride()`. Because the lambda checks the flag on the parent's `MethodTabEntry` before clearing it (line [2236](https://github.com/facebook/hhvm/blob/master/hphp/hhbbc/index.cpp#L2236)), it will never be set back to `false`.

One quick fix could be removing the check at line 2236 altogether.
Another potential fix would be to remove the restriction imposed on non-`AttrUnique` classes, although this one may have implications that we don't completely understand.

As a side note, it seems that the `AttrUnique` flag can also be cleared on type aliases created with the `type` or `newtype` statements, although we weren't able to reproduce the bug using this construct; it looks like in this case only the alias (but not the aliasee) has the `AttrUnique` flag removed.

**Comment by markw65** [comment] 2018-01-17 20:07
Good analysis of the problem, but I'm pretty sure the proposed fix is wrong (or at least, doesn't cover all the possible problems that could arise in this situation); the real problem is that Base is marked non-unique (due to the class alias), but DerivedOne and DerivedTwo are not. I'll have a fix for that shortly.

**Closed** 2018-01-18 17:00 UTC
Labels: php5 incompatibility, php7 incompatibility

**Comment by octmoraru** [comment] 2018-01-18 23:42
@markw65 - thanks for fixing this, much appreciated!

**Comment by jim-saxman** [comment] 2018-01-19 01:11
@markw65 Thanks from the ARM community, too!
