### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by questionpython** [facebook/hhvm#7773] opened 2017-04-07 17:02 UTC
```
[ 99%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/calendar/cal_unix.cpp.o
[ 99%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/calendar/calendar.cpp.o
[ 99%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/calendar/dow.cpp.o
[ 99%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/calendar/easter.cpp.o
[ 99%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/calendar/french.cpp.o
[ 99%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/calendar/gregor.cpp.o
[ 99%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/calendar/jewish.cpp.o
[ 99%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/calendar/julian.cpp.o
[ 99%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/ftp/ftp.cpp.o
[ 99%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/ftp/php_ftp.cpp.o
[ 99%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/oauth/oauth.cpp.o
[100%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/oauth/provider.cpp.o
[100%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/yaml/detect.cpp.o
[100%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/yaml/emit.cpp.o
[100%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/yaml/parse.cpp.o
[100%] Building CXX object hphp/runtime/ext_zend_compat/CMakeFiles/hphp_ext_zend_compat.dir/yaml/yaml.cpp.o
[100%] Linking CXX static library libhphp_ext_zend_compat.a
[100%] Built target hphp_ext_zend_compat
[100%] Built target systemlib
Scanning dependencies of target hhvm
[100%] Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/main.cpp.o
[100%] Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/process-init.cpp.o
[100%] Linking CXX executable hhvm
Generating Repo Schema ID and Compiler ID
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McTouchRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McTouchRequest>(facebook::memcache::McTouchRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McTouchRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McSetRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McSetRequest>(facebook::memcache::McSetRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McSetRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McReplaceRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McReplaceRequest>(facebook::memcache::McReplaceRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McReplaceRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McPrependRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McPrependRequest>(facebook::memcache::McPrependRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McPrependRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McMetagetRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McMetagetRequest>(facebook::memcache::McMetagetRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McMetagetRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McLeaseSetRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McLeaseSetRequest>(facebook::memcache::McLeaseSetRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McLeaseSetRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McLeaseGetRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McLeaseGetRequest>(facebook::memcache::McLeaseGetRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McLeaseGetRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McIncrRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McIncrRequest>(facebook::memcache::McIncrRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McIncrRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McGetsRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McGetsRequest>(facebook::memcache::McGetsRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McGetsRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McGetRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McGetRequest>(facebook::memcache::McGetRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McGetRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McFlushAllRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McFlushAllRequest>(facebook::memcache::McFlushAllRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McFlushAllRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McDeleteRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McDeleteRequest>(facebook::memcache::McDeleteRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McDeleteRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McDecrRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McDecrRequest>(facebook::memcache::McDecrRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McDecrRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McCasRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McCasRequest>(facebook::memcache::McCasRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McCasRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McAppendRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McAppendRequest>(facebook::memcache::McAppendRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McAppendRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McAddRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McAddRequest>(facebook::memcache::McAddRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McAddRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McAddRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McAddRequest>(facebook::memcache::McAddRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McAddRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McAppendRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McAppendRequest>(facebook::memcache::McAppendRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McAppendRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McCasRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McCasRequest>(facebook::memcache::McCasRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McCasRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McDecrRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McDecrRequest>(facebook::memcache::McDecrRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McDecrRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McDeleteRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McDeleteRequest>(facebook::memcache::McDeleteRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McDeleteRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McFlushAllRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McFlushAllRequest>(facebook::memcache::McFlushAllRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McFlushAllRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McGetRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McGetRequest>(facebook::memcache::McGetRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McGetRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McGetsRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McGetsRequest>(facebook::memcache::McGetsRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McGetsRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McIncrRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McIncrRequest>(facebook::memcache::McIncrRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McIncrRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McLeaseGetRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McLeaseGetRequest>(facebook::memcache::McLeaseGetRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McLeaseGetRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McLeaseSetRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McLeaseSetRequest>(facebook::memcache::McLeaseSetRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McLeaseSetRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McMetagetRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McMetagetRequest>(facebook::memcache::McMetagetRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McMetagetRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McPrependRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McPrependRequest>(facebook::memcache::McPrependRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McPrependRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McReplaceRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McReplaceRequest>(facebook::memcache::McReplaceRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McReplaceRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McSetRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McSetRequest>(facebook::memcache::McSetRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McSetRequest>()'
../runtime/ext/libhphp_runtime_ext.a(ext_mcrouter.cpp.o):ext_mcrouter.cpp:function facebook::memcache::McTouchRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McTouchRequest>(facebook::memcache::McTouchRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McTouchRequest>()'
../../third-party/mcrouter/libmcrouter.a(ProxyDestination.cpp.o):ProxyDestination.cpp:function facebook::memcache::McVersionRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McVersionRequest>(facebook::memcache::McVersionRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::_FUN(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&): error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McVersionRequest>()'
../../third-party/mcrouter/libmcrouter.a(ProxyDestination.cpp.o):ProxyDestination.cpp:function facebook::memcache::McVersionRequest::reply_type facebook::memcache::AsyncMcClientImpl::sendSync<facebook::memcache::McVersionRequest>(facebook::memcache::McVersionRequest const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, facebook::memcache::ReplyStatsContext*)::{lambda(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&)#1}::operator()(facebook::memcache::ClientMcParser<facebook::memcache::AsyncMcClientImpl>&) const: error: undefined reference to 'void facebook::memcache::McClientAsciiParser::initializeReplyParser<facebook::memcache::McVersionRequest>()'
collect2: error: ld returned 1 exit status
hphp/hhvm/CMakeFiles/hhvm.dir/build.make:418: recipe for target 'hphp/hhvm/hhvm' failed
make[2]: *** [hphp/hhvm/hhvm] Error 1
CMakeFiles/Makefile2:2268: recipe for target 'hphp/hhvm/CMakeFiles/hhvm.dir/all' failed
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
how fix?

**Comment by mofarrell** [comment] 2017-04-07 19:05
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

All I can say is it appears that the mcrouter symbols can't be found by the linker.

Try running:

`rm -rf third-party && git clean -fdx && git pull && git submodule update --init --recursive && cmake . && make`

**Closed by mofarrell** 2017-04-07 19:05 UTC
Labels: build, needs more info, no isolated repro

**Comment by questionpython** [comment] 2017-04-07 20:10
$ hhvm/hphp/hhvm$ ./hhvm --version
```
HipHop VM 3.20.0-dev (rel)
Compiler: heads/master-0-gad3711465d3d25bac6b9dfad35ca46497d233250
Repo schema: b7f46a538b4b1f63c13f2f9702032197c7f8dd59
```
fixed. :+1:
