### ISSUE TITLE
Error logging when failing to load repo

### ISSUE THREAD

**Issue by syilmaz** [facebook/hhvm#5603] opened 2015-07-07 12:34 UTC
Normally, when the repo file has invalid permissions, an error is thrown with the following message:

```
Failed to load Repo::GlobalData:
  /var/www/.hhvm.hhbc: No rows in main.GlobalData_f481cde67ffa32f3e1b93991358c162bc4b67c7c. Did you forget to compile that file with this HHVM version?
```

This message is not logged when running in daemon mode. 
I've checked the following files for error messages: /var/log/messages, /var/log/syslog, /var/log/hhvm/error.log

I've encountered this error running the nightly of 7/7/2015:

HipHop VM 3.8.0-dev (rel)
Compiler: heads/master-0-g428be9348ef502e76cb344a9ff2b0b6c2c081f3a
Repo schema: f481cde67ffa32f3e1b93991358c162bc4b67c7c

**Comment by swtaarrs** [comment] 2015-07-07 12:37
I'm going to make sure those errors go in the log file as well as stderr.

**Comment by Orvid** [comment] 2016-09-30 19:39
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:39 UTC
