### ISSUE TITLE
Mac: Object of class Varien_Http_Client could not be converted to string

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#6380] opened 2015-10-16 14:39 UTC
Only get this on my Mac build of HHVM, not sure why!

Recoverable Error: Object of class Varien_Http_Client could not be converted to string  in /Users/ccarnell/Sites/xx/lib/Varien/Http/Adapter/Curl.php on line 206

Application is Magento EE 1.14.2.1

**Comment by jwatzman** [comment] 2015-10-16 18:20
Do you have a small test case, or way to repro this, so that I can look into it?

**Comment by Orvid** [comment] 2016-09-28 22:16
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-28 22:16 UTC
Labels: no isolated repro, php5 incompatibility
