### ISSUE TITLE
stream_socket_enable_crypto() not implemented for client sockets

### ISSUE THREAD

**Issue by mingtse** [facebook/hhvm#1647] opened 2014-01-27 04:15 UTC
stream's ssl and tls are not working in hhvm.

Running the openssl tests

http://gcov.php.net/viewer.php?version=PHP_5_3&func=tests&file=ext%2Fopenssl%2Ftests%2Fsni_001.phpt

None of them pass.  HHVM exits with message:

HipHop Fatal error: Undefined function: stream_socket_enable_crypto

**Comment by jmarrama** [comment] 2015-01-06 08:00
+1

**Comment by Lucky-Frost** [comment] 2015-01-08 09:14
+1

**Comment by JoelMarcey** [comment] 2015-01-08 17:31
Just a quick update -- I shook the trees a little bit this morning, and there is indeed someone internally working on this. From what I understand, some of the basic bindings are done and some more details are being worked out.

We will keep you posted.

**Comment by Zenexer** [comment] 2015-01-09 07:53
Thanks, @JoelMarcey; it's appreciated.

**Comment by thejae** [comment] 2015-01-19 10:23
+1

**Comment by daniel-zahariev** [comment] 2015-01-19 15:28
+1

**Comment by arianf** [comment] 2015-01-20 00:33
+1

**Comment by kenyiu** [comment] 2015-01-20 01:50
+1

**Comment by GreenRover** [comment] 2015-01-26 12:40
+1

**Comment by khokhlachev** [comment] 2015-01-27 16:51
+1

**Comment by JorisM** [comment] 2015-01-28 08:06
+1

**Comment by lima01** [comment] 2015-01-29 03:28
+1

**Comment by devimplode** [comment] 2015-02-04 16:57
+1

**Comment by mediablenders** [comment] 2015-02-04 21:05
+1

**Comment by jaredjones** [comment] 2015-02-05 00:02
I love how it's been over a year and there still isn't support for this. I guess Facebook doesn't utilize PHP side SSL in anything? 0_o?

**Comment by techjewel** [comment] 2015-02-06 12:47
+1 I have the same problem with SendGrid.

**Comment by hmic** [comment] 2015-02-06 14:07
+1

**Comment by thommi2k** [comment] 2015-02-06 14:11
+1

**Comment by iamtommetcalfe** [comment] 2015-02-06 14:31
+1

**Comment by rmobis** [comment] 2015-02-07 17:31
+1

**Comment by caixiaowei** [comment] 2015-02-09 06:39
+1

**Comment by PunKeel** [comment] 2015-02-23 19:52
:+1: Would love it too <3

**Comment by lukepolo** [comment] 2015-02-23 21:04
+1

**Comment by jg-development** [comment] 2015-02-25 17:29
+1

**Comment by integrii** [comment] 2015-02-26 23:36
+1 please!  Can't live without this one...

**Comment by hmic** [comment] 2015-02-27 12:47
Could we maybe get an official statement of the progess of this from one of the project guys?

**Comment by jaredjones** [comment] 2015-02-28 04:30
I think FB is waiting for a pull request, but nobody knows enough of the intricacies of HHVM to even add this missing feature.

**Comment by Apeopex** [comment] 2015-02-28 04:32
The last comment (above) from FB has stated they have someone working on it.

https://github.com/facebook/hhvm/issues/1647#issuecomment-69215713

**Comment by jrobeson** [comment] 2015-02-28 04:45
@jaredjones : i don't think it's that.  It's just not been anybody's #1 problem to solve yet.

**Comment by hmic** [comment] 2015-02-28 14:20
Lets make it a #1 problem finally!
*if* someone is working on it internally, show code! let us maybe contribute to what has been done and what still needs to be done...

Open it up!

**Comment by tomazzaman** [comment] 2015-02-28 15:15
+1, switched back to FPM because of this.

**Comment by jg-development** [comment] 2015-03-09 13:48
:( me too... switched back to php-fpm. Some libs like Zend Framework 1 with Magento Shop and PHPMailer are implementing this feature. 
Imho this is a major miss and needs to be fixed. Is anyone workling on this?

**Comment by JoelESvensson** [comment] 2015-03-25 13:06
This is the only missing feature that prevents me from using HHVM the same way I use the regular PHP engine. Has there been any progress?

**Comment by mediablenders** [comment] 2015-03-25 13:14
He Guys, while I agree this sucks, but you can run php en HHVM on the same server. Just make sure your mail script is processed by php and you should be fine for now.

Make sure you use the php-fpm unix socket and run hhvm on the regular port 9000. In nginx you could direct /mails.php to the php socket and the rest to hhvm. 

I Hope some of you are helped by this.

You could also run hhvm with a php fallback:
https://bjornjohansen.no/hhvm-with-fallback-to-php

**Comment by jg-development** [comment] 2015-03-25 13:24
Hi,
the problem is, that the most mailing in integrated in the application. This is not an option (at least for me).
The fallback has some issues, too. If you have as an example a persistent storage in your application (like mysql), it could happen that you duplicate some sql calls like update, insert etc.

Greetings Jan

**Comment by bradbernard** [comment] 2015-03-27 23:24
+1

**Comment by antonbe** [comment] 2015-04-17 17:21
+1 Please fix this!

**Comment by corientdev** [comment] 2015-04-21 10:31
+1 Fix this can't use afterlogic webmail

**Comment by corientdev** [comment] 2015-04-21 10:36
When should we expect the fix?? I mean it is really a required thing.. how can you imagine an application which can't send emails.. I am shocked.

Any work arounds guys?

**Comment by danielhirche** [comment] 2015-04-21 10:46
first of all, it's not a bug, it's a (missing) feature. *demanding* a "fix" for such a missing feature in software by people putting hard work in it to give it away for free as OSS, is, well, quite rude.
you can always use a different backend for single files and/or folders in most modern webservers like nginx, so feel free to use php-fpm if you so desperately need this function. otherwise stay calm, there's really no need to constantly keep bumping this issue.

**Comment by corientdev** [comment] 2015-04-21 10:59
@danielhirche  do you know the meaning of being rude..?? Did i told that "Hey pal i want it by the end of the day."
we are not rude here. what we are asking here is when it is gonna get fixed. may be a reminder for developer that its still pending.

And about OSS. What i believe is people make the software better by giving their IDEA for FREE it is kind of contribution and can you imagine the reliability HHVM will have after succesfully implementing this feature. Most of the PHP Mail Client will be compatible with HHVM and may be laravel will became 100% compatible.

**Comment by keiosweb** [comment] 2015-04-21 11:04
@danielhirche it seems there may be a reason to constantly keep bumping this issue:

fredemmott said: "we try to prioritize based on balancing how popular a request is vs how long it's likely to take to implement/test."

nothing strange with people showing that this issue IS popular.

**Comment by hmic** [comment] 2015-04-21 11:08
I dont think this comment was rude too.
Additionally I think the topic can not be bumped up often enough.

If there is a developer working on this, just keep us guys somewhat updated, or tell us you will not implement it at all. Just give an *official* statement of what/when to expect to happen.

As mentioned often, this is like *the* missing feature in hvm for making most apps pass 100% of their tests.

I dont think if this is of any interest, but I do personally think hhvm could be given the change for the php-7 reference implementation like the java reference implementation is done by different vendors in every release. PHP has this not in place and its the rudeness (well, lets not say this) of the php developers at zend - and obviously here too - that prevent something like that to happen after all.

**Comment by CannibalVox** [comment] 2015-04-21 14:14
I think it's weird for your first contribution on github to be a lecture about OSS etiquette.

**Comment by hmic** [comment] 2015-04-21 14:17
Could we maybe just stay on the topic and demand an implementation, finally.

:p

**Comment by antonbe** [comment] 2015-04-21 15:57
The devs prioritize based on demand. Which is why it's appropriate to keep
bumping this.

**Comment by fredemmott** [comment] 2015-04-21 16:03
It's next on the list of things that haven't been scheduled. Sorry, we've not looked into it enough yet to give any kind of time-frame.

As this is already at the top of the list, bumping doesn't help any more - it just adds to the noise.

**Comment by antonbe** [comment] 2015-04-21 16:10
So when would it be due to be scheduled, at least?

**Comment by fredemmott** [comment] 2015-04-21 16:27
We come up with a rough plan every 6 months. This isn't on our team's current plan as it was going to be worked on by an external volunteer, however we've not seen much progress there. As we've been making good progress on other areas, I expect to start working on this *much* sooner - hopefully this week or next - instead of leaving it until the next cycle. Because we weren't expecting to do this ourselves, I've not looked at it enough yet to have an idea of how that would translate to a completion time.

I'm not entirely sure what you're asking, but hope that answers it :)

**Comment by szainmehdi** [comment] 2015-04-21 17:59
@fredemmott Thanks a lot for the official update! As others have said before, I appreciate all the efforts going into Hack/HHVM. Also to echo what others have said, my adoption of Hack is hinged on the implementation of this feature. 

Thanks again! I'm looking forward to the update! :+1:

**Comment by antonbe** [comment] 2015-04-21 18:01
Fred, that answers it. Thank you very much! :)

Best Regards,

Anton Bekerman
TheIXO Consulting Group

**Comment by maclof** [comment] 2015-04-21 18:45
I think all it takes in situations like this is to hear an "official" response and then everybody's minds are put at rest (somewhat).

Thank you @fredemmott I look forward to seeing how this progresses! I'm too very eager to use it with a few Laravel sites I'm developing.

**Comment by corientdev** [comment] 2015-04-22 06:44
@fredemmott  It's even better that you are doing it by yourself :-)

@keiosweb  @hmic  @CannibalVox  @antonbe  Thanks for supporting me guys. God bless you all...

@fredemmott  Thanks to you too for looking into it. :-) God bless you...

**Comment by fredemmott** [comment] 2015-05-01 19:50
Unfortunately a couple of other things have needed a bit longer to finish off; I expect to start working on this on the 26th.

**Comment by dragonfire1119** [comment] 2015-05-01 20:01
@fredemmott Thanks for the update on this!

**Comment by integrii** [comment] 2015-05-02 19:20
@fredemmott Thank you!  This is great!

**Comment by jcherqui** [comment] 2015-05-09 11:14
+1

**Comment by giano** [comment] 2015-05-09 18:57
Thank you!



—
Inviato da Mailbox

**Comment by magenx** [comment] 2015-05-14 21:36
that fallback will never work - https://bjornjohansen.no/hhvm-with-fallback-to-php, 
lol did he ever tested it.... it is better to map incompatible requests.

**Comment by tvictorino** [comment] 2015-05-23 19:28
+1

**Comment by velegip** [comment] 2015-05-25 10:25
+1

**Comment by fredemmott** [comment] 2015-05-28 18:44
Sorry, I've had to spend a bit more time cleaning up previous projects. I should be working on this by the end of next week.

**Comment by jcherqui** [comment] 2015-06-01 13:50
@fredemmott +1

**Comment by zjhzxhz** [comment] 2015-06-02 03:41
+1

**Comment by mtinsley** [comment] 2015-06-02 16:28
+1

**Comment by Nemesis9765** [comment] 2015-06-03 15:48
@fredemmott appreciate the work you're putting into the project, I can understand peoples frustrations about it, but on the flip side I think the work you guys are doing on this project is phenomenal and can't wait to start using it on my production servers.  This issue though is what's holding me back at the moment as I to am experiencing this problem.

Thanks again and keep up the great work :+1:

**Comment by jcherqui** [comment] 2015-06-03 16:34
@Nemesis9765 It's the same situation for me. I return here every day, it's only the last problem before to use in production.

**Comment by Nemesis9765** [comment] 2015-06-03 17:00
@jcherqui toying with it a little bit, i found out you can still send mail even w/o this kind of support, you just need to configure your application to use sendmail instead of using PHP's built in functionality until its completed.  I've been able to get my dev environment working w/ sendmail using MailCatcher and make sure you turn off tls encryption.  Someone correct me if i'm wrong, but can't sendmail be configured to do the encryption for you?

**Comment by PLaRoche** [comment] 2015-06-05 16:29
Same boat here as @jcherqui look forward to having this one sorted

**Comment by alexanderbaran** [comment] 2015-06-07 08:23
Looking forward to this one! Only thing that keeps me back. Everything else seems to work. Predis works with HHVM too it seems. Now just waiting for this one.

**Comment by cie101** [comment] 2015-06-09 18:00
+1

**Comment by KarimGeiger** [comment] 2015-06-11 12:42
+1

**Comment by corientdev** [comment] 2015-06-11 13:31
@fredemmott  just to remind that you had promised us that you will start working on this by the end of next week (on 29th May). Now its nearing 3rd weekend.. any update :'-(

**Comment by antonbe** [comment] 2015-06-11 13:34
The man is busy and has already started doing some work. Give him a break.

Best Regards,

Anton Bekerman
TheIXO Consulting Group

**Comment by fredemmott** [comment] 2015-06-11 16:19
Sorry, as I said before this isn't on the roadmap, and I was hoping to fit it in around the things that were planned (issues related to/discovered during the performance lockdown, and a new XHP-related project we hope to release soon) - which unfortunately ended up taking a bunch of extra time.

The good news is that I'm almost done with that stuff, and unless something unexpected comes up, I should start on this today or tomorrow.

**Comment by corientdev** [comment] 2015-06-11 16:25
Congrats @fredemmott  && Thanks for update...

**Comment by PLaRoche** [comment] 2015-06-11 16:27
Awesome, very understandable, thanks for the update

**Comment by wojtas** [comment] 2015-06-15 13:31
@fredemmott <Shrek Puss in Boots eyes mode on> Any news? </Shrek Puss in Boots eyes mode off>

**Comment by fredemmott** [comment] 2015-06-15 16:06
Yep, working on this now.

**Comment by jaredjones** [comment] 2015-06-15 16:08
Woot! Waited a year and a half for this.

**Comment by fredemmott** [comment] 2015-06-17 21:54
Not suitable for merging in yet. Does not support disabling, or anything except the most basic usage. Still might be useful for some people.

**Comment by maclof** [comment] 2015-06-17 22:16
@fredemmott A step in the right direction though plus it's something for those who're impatient :) Many thanks for working on this!

**Comment by fredemmott** [comment] 2015-06-18 17:24
Can someone build and test my branch with a real case?

- I can't get swiftmailer's tests working, even under PHP5 - this is unrelated to TLS: Composer doesn't seem to create a working autoloader for it, so the tests don't even start
- the failing zend tests mentioned in the original comment only test creating a TLS server in PHP, which doesn't seem to be something that's relevant to most of you

**Comment by maclof** [comment] 2015-06-18 17:30
Sure I'll give this a go now and let you know how I get on, my use case is sending via Gmail SMTP with Swiftmailer.

**Comment by fredemmott** [comment] 2015-06-18 18:03
Split off server sockets to separate issue as it seems that almost everyone here only cares about client sockets. pinging @mingtse as their example was the server-only zend tests.

**Comment by maclof** [comment] 2015-06-18 20:37
Hmm, I would have tested this by now, but for some reason composer isn't working correctly with this build of hhvm. I've tested this with the pre-packaged Ubuntu 14.04 binary and it worked.

All of this was built within docker containers.

```bash
root@4dae77d36b06:/# composer create-project laravel/laravel /code
Installing laravel/laravel (v5.1.1)
  - Installing laravel/laravel (v5.1.1)
    Downloading: 100%
    Downloading: 100%
    Downloading: 100%



  [ErrorException]
  Invalid argument supplied for foreach()



create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]


root@4dae77d36b06:/# php -v
HipHop VM v2.3.0-dev (rel)
Compiler: heads/master-0-g7881fcf3e39070615d924903a7158a15dd5f1d2c
Repo schema: 8d920f1cc224012b965580383b7a1722cd0e151b
```

**Comment by fredemmott** [comment] 2015-06-18 20:45
Your 'php' is *incredibly* old: HHVM 2.3.0 is from December 2013.

**Comment by maclof** [comment] 2015-06-18 20:48
@fredemmott I know, sorry, that's why I promptly deleted my comment >_<.

I'm compiling against the correct branch now so will report back soon.

**Comment by maclof** [comment] 2015-06-18 22:48
@fredemmott This works perfectly with the Google Mail SMTP servers over TLS. I used Laravel 5.1.1 with Swiftmailer 5.4.1.

**Comment by fredemmott** [comment] 2015-06-18 23:04
:+1:

**Comment by keiosweb** [comment] 2015-06-19 05:37
:+1:

**Comment by corientdev** [comment] 2015-06-19 17:37
@fredemmott  thnx for implementation.. May i know which stable version will have this included.. :D

**Comment by paulbiss** [comment] 2015-06-19 18:06
@corientdev it hasn't been reviewed yet, but when it's accepted and landed in master it will be available in the next release. You'll see updates here when that happens.

**Comment by fredemmott** [comment] 2015-06-19 19:46
3.9 most likely; while it should hopefully be in master before 3.8 is released, the branch has already been cut.

**Comment by mediablenders** [comment] 2015-06-19 19:48
Awesome! Thanks a lot!


 
 
 


 
Tom Meulendijks

 
Technical Director

 
tom@mediablenders.com

 
+31 (0)43 851 90 02

 
+31 (0)6 1437 9205

**Comment by corientdev** [comment] 2015-06-19 19:53
Great feels like celebration :D finally

**Comment by cie101** [comment] 2015-06-19 19:54
One question guys how can use this if i'm using the install from ubuntu? I just did apt-get install hhvm is there a way to have it pull a specific branch of HHVM when you install from a repo?

**Comment by fredemmott** [comment] 2015-06-19 19:57
There are no packages for that branch; you need to either:
- wait for it to be included in a stable release (probably 3.9, expected mid-August)
- wait for ~ 24h after it's committed, then install the hhvm-nightly package instead. As this isn't a stable release, there are downsides to this.

**Comment by antonbe** [comment] 2015-06-19 21:48
Yeah, listen to Fred, you don't want to put nightly on a production server.
Wait for this to be fully tested and released as stable no matter how much
you want/need it now, I know i had to do a lot of bullshit to get around to
limitation to run hhvm alongside php5 on the same server and have only a
few key pages forward to php5 while preserving cookies/sessions. It wasn't
fun, but it's done and dealing with daily random bugs is even less fun.

**Comment by fredemmott** [comment] 2015-06-23 17:30
That branch is pretty much close to final. Not merged yet as we want to land it after another related change. ETA is ~ 1 week for master. Unsure if this will be 3.8 or 3.9.

**Comment by wojtas** [comment] 2015-06-23 17:32
Thank you for your work :-) That's a very good news.
23 cze 2015 19:30 "Fred Emmott" <notifications@github.com> napisał(a):

**Comment by corientdev** [comment] 2015-06-24 06:39
@fredemmott  Thanks for the continuous update it feels great to see you on this issue post. :+1:

**Comment by giano** [comment] 2015-06-24 07:36
Thank you for working on it. Was the only big issue we ran into running Magento on hhvm, but an insidious one...

**Comment by antonbe** [comment] 2015-06-29 02:46
Yup, people can't even place orders if you run Magento straight on the
current release of hhvm without any customization. You must disable emails
so that customers can place orders and even then, you're not sending them
any notifications and they can't use the contact form.

Pretty bad. The only real solution is to find a way to run php along hhvm
on your server... or have two separate identifical servers with the only
difference being the php server.

Then you still need to ensure that the user sessions and cookies don't
reset when they switch from hhvm to php and back or from server to server.
Can't wait for this change to hit Master and be released, as that will
simplify our stack significantly.

Thank you Facebook devs for paying attention to this issue and doing
someting about it! :D

**Comment by jg-development** [comment] 2015-06-29 05:57
Hi @antonbe 
you can use smtp in magento and it works fine with hhvm. Install an extension like smtppro.
Greetings Jan

**Comment by fredemmott** [comment] 2015-06-29 17:45
Closing as implementation is in master (hopefully in tomorrow's nightlies); we are currently expecting this in 3.8 too, though that's not guaranteed - depends on further testing. We'll delay it to 3.9 if it leads to unrelated problems.

**Closed by fredemmott** 2015-06-29 17:45 UTC
Labels: feature request, hi-pri, php5 incompatibility

**Comment by giano** [comment] 2015-06-30 07:34
Great! Actually we "glided" on this using smtppro + mandrill. Can't wait to
test on dev site.

**Comment by corientdev** [comment] 2015-07-01 07:06
Anybody please confirm if this implementation is included in latest nighty released??

**Comment by fredemmott** [comment] 2015-07-01 17:41
It's in 2015.07.01 - tested with the Trusty package.

**Comment by linkshops** [comment] 2015-07-09 06:09
Hi fredemmott, I am still having trouble with Call to undefined function stream_socket_enable_crypto() error for SMTP pro plugin for Magento on Nginx + HHVM. Any tips on how to apply the latest build (and where) to make it applied on my server?

**Comment by fredemmott** [comment] 2015-07-09 16:12
If you're not running hhvm-nightly, you don't have it yet. You can either wait for 3.8 (recommended for production), or if you don't mind installing barely-tested versions: http://hhvm.com/blog/3203/nightly-packages

**Comment by fredemmott** [comment] 2015-07-14 20:57
This is included in HHVM 3.8.0 :)

**Comment by KarimGeiger** [comment] 2015-07-14 20:59
@fredemmott You're awesome! Thanks a lot :)

**Comment by linkshops** [comment] 2015-07-15 01:18
So awesome!

2015-07-15 6:00 GMT+09:00 Karim Geiger <notifications@github.com>:

**Comment by r3wt** [comment] 2015-07-15 11:15
@fredemmott How can i enable it? I see that it freezes for like 15 seconds and times out when trying to send with gmail smtp server

![img](http://puu.sh/iZYWQ/55f64191e9.png)

**Comment by antonbe** [comment] 2015-07-16 05:26
It works! Latest Version of Magento with HHVM 3.8 and Nginx 1.9.2!

Thank you FB and Fred! I can finally stop running PHP alongside HHVM and
remove all those ugly hacks!

**Comment by tomazzaman** [comment] 2015-07-21 11:46
I tried this out and it's not working properly, I get an error:
```
Fatal error: Unexpected object type File. in /home/webmaster/www/domain.com/wp-includes/class-smtp.php on line 262
```

The function in question looks like this:
```
    public function startTLS()
    {
        if (!$this->sendCommand("STARTTLS", "STARTTLS", 220)) {
            return false;
        }
        // Begin encrypted connection
        if (!stream_socket_enable_crypto(
            $this->smtp_conn,
            true,
            STREAM_CRYPTO_METHOD_TLS_CLIENT
        ) # This is line 262
        ) {
            return false;
        }
        return true;
    }
```

Am I missing something?

**Comment by 64616E69656C** [comment] 2015-07-21 12:01
Can confirm with latest (and one older) version of PHPMailer, and HHVM 3.8.0. 
I think this is postfix/TLS related.

```
smtpd_helo_required                 = yes
smtpd_delay_reject                  = yes
smtpd_use_tls                       = yes
smtpd_tls_eecdh_grade               = strong
tls_eecdh_strong_curve              = prime256v1
tls_eecdh_ultra_curve               = secp384r1
tls_preempt_cipherlist              = yes
smtpd_tls_received_header           = yes
smtpd_tls_mandatory_ciphers         = high
smtpd_tls_ciphers                   = medium
smtpd_tls_mandatory_protocols       = !SSLv2,!SSLv3
smtpd_tls_mandatory_exclude_ciphers = aNULL,eNULL,EXPORT,DES,RC4,MD5,PSK,eECDH,EDH-DSS-DES-CBC3-SHA,EDH-RSA-DES-CDC3-SHA,KRB5-DE5,CBC3-SHA
smtpd_tls_dh1024_param_file         = /etc/ssl/dh2048.pem
```

Peer Debug Log:

```
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: connect from remote.host[1.1.1.1]
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: smtp_stream_setup: maxtime=300 enable_deadline=0
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostname: remote.host ~? 127.0.0.0/8
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostaddr: 1.1.1.1 ~? 127.0.0.0/8
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostname: remote.host ~? [::ffff:127.0.0.0]/104
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostaddr: 1.1.1.1 ~? [::ffff:127.0.0.0]/104
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostname: remote.host ~? [::1]/128
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostaddr: 1.1.1.1 ~? [::1]/128
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostname: remote.host ~? 1.1.1.0/24
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostaddr: 1.1.1.1 ~? 1.1.1.0/24
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: > remote.host[1.1.1.1]: 220 xxx ESMTP Postfix (Debian/GNU)
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: watchdog_pat: 0x7f1f04069ef0
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: < remote.host[1.1.1.1]: EHLO zzz
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_list_match: remote.host: no match
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_list_match: 1.1.1.1: no match
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: > remote.host[1.1.1.1]: 250-xxx
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: > remote.host[1.1.1.1]: 250-PIPELINING
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: > remote.host[1.1.1.1]: 250-SIZE
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: > remote.host[1.1.1.1]: 250-VRFY
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: > remote.host[1.1.1.1]: 250-ETRN
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: > remote.host[1.1.1.1]: 250-STARTTLS
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: > remote.host[1.1.1.1]: 250-ENHANCEDSTATUSCODES
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: > remote.host[1.1.1.1]: 250-8BITMIME
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: > remote.host[1.1.1.1]: 250 DSN
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: watchdog_pat: 0x7f1f04069ef0
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: < remote.host[1.1.1.1]: STARTTLS
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: > remote.host[1.1.1.1]: 220 2.0.0 Ready to start TLS
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: send attr request = seed
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: send attr size = 32
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: private/tlsmgr: wanted attribute: status
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: input attribute name: status
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: input attribute value: 0
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: private/tlsmgr: wanted attribute: seed
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: input attribute name: seed
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: input attribute value: rJyHJDgGPVCOJrmcO1S275VY2V1UM+wFm3ezVlr8JJw=
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: private/tlsmgr: wanted attribute: (list terminator)
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: input attribute name: (end)
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: SSL_accept error from remote.host[1.1.1.1]: lost connection
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostname: remote.host ~? 127.0.0.0/8
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostaddr: 1.1.1.1 ~? 127.0.0.0/8
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostname: remote.host ~? [::ffff:127.0.0.0]/104
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostaddr: 1.1.1.1 ~? [::ffff:127.0.0.0]/104
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostname: remote.host ~? [::1]/128
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostaddr: 1.1.1.1 ~? [::1]/128
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostname: remote.host ~? 1.1.1.0/24
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: match_hostaddr: 1.1.1.1 ~? 1.1.1.0/24
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: lost connection after STARTTLS from remote.host[1.1.1.1]
Jul 21 13:57:45 xxx postfix/submission/smtpd[8316]: disconnect from remote.host[1.1.1.1]
```

Not much to go on though.

**Comment by 64616E69656C** [comment] 2015-07-21 12:21
Ooooh. I just realized, PHPMailer isn't working AT ALL with HHVM 3.8, regardless of stream_socket_enable_crypto(). Before (up to 3.7.2), I never cared that much for the issue on this topic, because I was using PHPMailer on localhost and let postfix do the auth thingy with the relayhost. Latest update broke that. :-(

**Comment by Krapulat** [comment] 2015-07-21 14:57
I have the same error as @tomazzaman.

Fatal error: Unexpected object type File. in /var/www/domain.com/wp-includes/class-smtp.php on line 262

Only happen when using STARTTLS.

Any thought?

**Comment by fredemmott** [comment] 2015-07-21 15:17
Please open a new issue, ideally with < 5 line example that's just a call to stream_socket_enable_crypto() on a stream that works in PHP5 and not hhvm and doesn't depend on any framework/library. calling get_resource-type on $this->smtpConn) seems likely to be a good starting point.

**Comment by Krapulat** [comment] 2015-07-21 17:41
class-smtp.php uses library PHPMailer. So the problem is with PHPMailer?

**Comment by andrewmclagan** [comment] 2016-01-30 02:41
+1 this makes HHVM unusable for Laravel developers

**Comment by fredemmott** [comment] 2016-01-30 18:39
@andrewmclagan : this issue is fixed. If you are still having a problem with Laravel, please file a new issue with details - HHVM version, what PHP functionality is not working (i.e. which PHP functions, not which parts of laravel), and so on.

**Comment by andrewmclagan** [comment] 2016-02-01 11:18
apologies, i pulled an old version
