### ISSUE TITLE
[DEBIAN] Unable to create unix socket file

### ISSUE THREAD

**Issue by elegos** [facebook/hhvm#5087] opened 2015-03-27 18:19 UTC
Hello!

I've manually fixed the following bug: running the server with unix socket, at least on debian, will result in not being able to create the sock file.

How to reproduce:

0. start at least once the daemon with the default configuration (important, as it creates the folder which causes the bug)

1. in server.ini set `hhvm.server.file_socket = /var/run/hhvm.sock` (or even `/var/run/hhvm/hhvm.sock`)
2. always in server.ini set `hhvm.server.user = YOUR_USER_HERE` (in my case `web`)
3. in the `/etc/init.d/hhvm` script **change** the user to whatever you want (in my case from `www-data` to `web`)
4. start the daemon via `service hhvm start` (or restart)

In the error.log the daemon will warn about not being able to create the sock file, as it has no permission to do that.

Reason: in init.d's script's `check_run_dir()` function, you check for the permissions only the first time and only if the folder `/var/run/hhvm` does not exist. Simple "hack" is to not check for directory existing and always proceed with `mkdir -p` and `chown` commands.

My suggestion: remove from init.d's script the `RUN_AS_USER` and `RUN_AS_GROUP` variables (and relative commands) and let the daemon first create the files (i.e. pid, socket if needed and hhvm.hhbc file (what is that?)), change their ownership depending on the server.ini settings and **only then** execute as user. In this way the user only has to edit the files in the /etc/hhvm folder and don't mess with the service files (as expected).

Cheers :8ball:

**Comment by Orvid** [comment] 2016-09-30 21:24
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:24 UTC
