### ISSUE TITLE
Execute scripts in subdirectories

### ISSUE THREAD

**Issue by RenaudParis** [facebook/hhvm#6304] opened 2015-09-26 06:17 UTC
Hi,

HHVM seems to generate weird errors along with Composer when executing a script in a subdirectory.

**This works**

```hhvm test.php```

**This fails**

```hhvm ./bin/script.php```

It gives the error:

```Catchable fatal error: Fatal error: exception Sys_error("./bin: No such file or directory") in /home/renaud/dev/wamp/skol/lib/vendor/composer/ClassLoader.php on line 412```

The line in question is:

```
function includeFile($file)
{
    include $file; // This is the line that generates the weird error
}
```

Any ideas about this one?

**EDIT:** it looks like the path part of the executed script is added to the include path, whereas the include path is used from the lib/ directory (of my project), which is incorrect.

I tried to call this (absolute path):

```hhvm /home/renaud/dev/wamp/skol/bin/script.php```

And **it works**

**Comment by Orvid** [comment] 2016-03-23 21:32
Is this consistent with PHP?

**Comment by Orvid** [comment] 2016-09-28 22:21
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-28 22:21 UTC
Labels: needs more info
