### ISSUE TITLE
gdb segfaults when I try to debug HHVM

### ISSUE THREAD

**Issue by Daniel15** [facebook/hhvm#6499] opened 2015-11-02 00:19 UTC
Pretty self-explanatory:
```
daniel@debian:/var/www/hhvm-bugs$ gdb --quiet hhvm
Reading symbols from hhvm...Segmentation fault
```

Backtrace from `gdb`, if it helps:
```
#0  _int_malloc (av=av@entry=0x7ffff622c620 <main_arena>, bytes=bytes@entry=640) at malloc.c:3700
#1  0x00007ffff5f05a2c in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3219
#2  0x0000000000681911 in xcalloc (number=160, size=size@entry=4) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/common/common-utils.c:91
#3  0x00000000004f93ef in elf_symfile_segments (abfd=0xd60850) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/elfread.c:120
#4  0x000000000056e53f in symfile_find_segment_sections (objfile=0xd88490) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/symfile.c:3796
#5  init_objfile_sect_indices (objfile=0xd88490) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/symfile.c:345
#6  default_symfile_offsets (objfile=0xd88490, addrs=<optimized out>) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/symfile.c:765
#7  0x000000000056c2d4 in syms_from_objfile_1 (add_flags=6, addrs=0xd4e040, objfile=0xd88490) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/symfile.c:1011
#8  syms_from_objfile (add_flags=6, addrs=0xd4e040, objfile=0xd88490) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/symfile.c:1029
#9  symbol_file_add_with_addrs (abfd=abfd@entry=0xd60850, name=name@entry=0x7fffffffe8ef "hhvm", add_flags=add_flags@entry=6, addrs=addrs@entry=0x0, flags=flags@entry=0, parent=parent@entry=0x0) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/symfile.c:1126
#10 0x000000000056c824 in symbol_file_add_from_bfd (parent=0x0, flags=0, addrs=0x0, add_flags=6, name=0x7fffffffe8ef "hhvm", abfd=0xd60850) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/symfile.c:1215
#11 symbol_file_add (name=name@entry=0x7fffffffe8ef "hhvm", add_flags=6, addrs=addrs@entry=0x0, flags=flags@entry=0) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/symfile.c:1230
#12 0x000000000056c888 in symbol_file_add_main_1 (args=0x7fffffffe8ef "hhvm", from_tty=1, flags=0) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/symfile.c:1255
#13 0x0000000000592f2e in catch_command_errors_const (command=0x56c8b0 <symbol_file_add_main>, arg=arg@entry=0x7fffffffe8ef "hhvm", from_tty=1, mask=mask@entry=RETURN_MASK_ALL) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/exceptions.c:567
#14 0x0000000000595a45 in captured_main (data=data@entry=0x7fffffffe5d0) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/main.c:969
#15 0x0000000000592d8a in catch_errors (func=func@entry=0x595080 <captured_main>, func_args=func_args@entry=0x7fffffffe5d0, errstring=errstring@entry=0x740755 "", mask=mask@entry=RETURN_MASK_ALL) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/exceptions.c:524
#16 0x0000000000596084 in gdb_main (args=args@entry=0x7fffffffe5d0) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/main.c:1076
#17 0x000000000045484e in main (argc=<optimized out>, argv=<optimized out>) at /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/gdb.c:34
```

Version info:
```
daniel@debian:~$ hhvm --version
HipHop VM 3.10.1 (dbg)
Compiler: tags/HHVM-3.10.1-0-g689b4969a141620ee5a282ce0dbf72278c84d44b
Repo schema: 6c99ee1f98340f6f3ef397a332583f0e843a627d

daniel@debian:~$ gdb --version
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.

daniel@debian:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="https://bugs.debian.org/"

daniel@debian:~$ uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux
```

**Comment by wjywbs** [comment] 2015-11-03 19:00
This is likely a duplicate of https://github.com/facebook/hhvm/issues/5232.

**Comment by fredemmott** [comment] 2016-01-14 18:37
HHVM is known to trigger bugs in gdb < 7.9; building the latest gdb from source usually fixes this.

**Closed by fredemmott** 2016-01-14 18:37 UTC
