### ISSUE TITLE
OCaml version check always fails for CentOS 6.6

### ISSUE THREAD

**Issue by andrewpile** [facebook/hhvm#5392] opened 2015-05-23 01:19 UTC
It's possible this is a `cmake` issue since it seems to be using their macros, but on CentOS 6.6, OCaml 4.02.0 and 4.02.1 are both installed via `opam`:

```
[vagrant@vagrant hhvm]$ opam switch list
--     -- 3.11.2  Official 3.11.2 release
--     -- 3.12.1  Official 3.12.1 release
--     -- 4.00.0  Official 4.00.0 release
--     -- 4.00.1  Official 4.00.1 release
--     -- 4.01.0  Official 4.01.0 release
4.02.0  C 4.02.0  Official 4.02.0 release
4.02.1  I 4.02.1  Official 4.02.1 release
system  I system  System compiler (<none>)

[vagrant@vagrant hhvm]$ ocamlc -version
4.02.0
```

But during build:

```
...
-- Found ocamlc: /usr/bin/ocamlc
CMake Error at CMake/FindOCaml.cmake:13 (message):
  OCaml version is too old to build the Hack typechecker, need at least 4.01.
...
```

The offending line in `FindOCaml.cmake` is: `if ("${OCAMLC_VERSION}" VERSION_LESS "4.01")`, which may be failing because of OCaml's versioning format. Removing the check fixes it, and the build goes off without a hitch.

**Comment by jwatzman** [comment] 2015-05-23 09:49
Interesting -- in case this is a cmake bug, what version of cmake are you using?

**Comment by Orvid** [comment] 2016-09-30 21:05
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:05 UTC
Labels: build, hack
