### ISSUE TITLE
Incompatiblity between some $_SERVER vars with PHP and hhvm

### ISSUE THREAD

**Issue by nelemans1971** [facebook/hhvm#5043] opened 2015-03-19 17:25 UTC
I've been trying to convert my website to run on hhvm, but have some troubles with the content of the $_SERVER vars. I'm using apache with php and hhvm in fastcgi mode.
 
* $_SERVER['DOCUMENT_ROOT'] is missing a / at the end in hhvm when this is defined in apache conf for the DOCUMENT_ROOT.
* $_SERVER['REDIRECT_QUERY_STRING'] contains the orginal query before a redirect. php includes the query string after the redirect. (I think hhvm contains the correct info and not php+apache).
* $_SERVER['REDIRECT_URL'] contains the orginal url used in the browser. When there is a rewriterule active in apache this contains the rewritten url in php. This is the main problem for me because without this information my scripts won't work.

See below picture of result when run through hhvm and php:

![output-hhvm php](https://cloud.githubusercontent.com/assets/9059166/6736356/8f779fe0-ce64-11e4-9959-096a9facff27.png)

**Comment by Orvid** [comment] 2016-09-30 21:37
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:37 UTC
Labels: fastcgi
