### ISSUE TITLE
Failed to link against Boost Program_options=1.57.0

### ISSUE THREAD

**Issue by Majkl578** [facebook/hhvm#5675] opened 2015-07-12 21:34 UTC
Compilation went fine, but in the final stage it failed to link properly:

```
Linking CXX executable hhvm
/usr/include/boost/program_options/detail/value_semantic.hpp:167: error: undefined reference to 'boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool*, int)'
/usr/include/boost/program_options/detail/value_semantic.hpp:167: error: undefined reference to 'boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
/usr/include/boost/program_options/errors.hpp:373: error: undefined reference to 'boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
/usr/include/boost/program_options/errors.hpp:373: error: undefined reference to 'boost::program_options::error_with_option_name::error_with_option_name(std::string const&, std::string const&, std::string const&, int)'
/usr/include/boost/program_options/detail/convert.hpp:79: error: undefined reference to 'boost::program_options::to_internal(std::string const&)'
/usr/include/boost/program_options/detail/parsers.hpp:43: error: undefined reference to 'boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
/usr/include/boost/program_options/detail/value_semantic.hpp:19: error: undefined reference to 'boost::program_options::arg'
/usr/include/boost/program_options/detail/value_semantic.hpp:146: error: undefined reference to 'boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
/usr/include/boost/program_options/detail/value_semantic.hpp:150: error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
/usr/include/boost/program_options/detail/value_semantic.hpp:92: error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
/build/hhvm/hhvm/hphp/runtime/base/program-functions.cpp:1228: error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/build/hhvm/hhvm/hphp/runtime/base/program-functions.cpp:1093: error: undefined reference to 'boost::program_options::option_description::long_name() const'
/build/hhvm/hhvm/hphp/runtime/base/program-functions.cpp:1103: error: undefined reference to 'boost::program_options::option_description::format_name() const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value>: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value> >: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::error_info_injector<boost::program_options::validation_error>: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> >: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<std::string, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<std::vector<std::string, std::allocator<std::string> >, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<int, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../runtime/libhphp_runtime.a(program-functions.cpp.o):program-functions.cpp:vtable for boost::program_options::typed_value<bool, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
/build/hhvm/hhvm/hphp/compiler/compiler.cpp:204: error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/include/boost/program_options/detail/parsers.hpp:77: error: undefined reference to 'boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::string, std::string>, std::string const&>)'
/build/hhvm/hhvm/hphp/hhbbc/main.cpp:70: error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/build/hhvm/hhvm/hphp/hhbbc/main.cpp:107: error: undefined reference to 'boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/include/boost/program_options/detail/value_semantic.hpp:92: error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
/usr/include/boost/program_options/detail/value_semantic.hpp:92: error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
collect2: error: ld returned 1 exit status
hphp/hhvm/CMakeFiles/hhvm.dir/build.make:367: recipe for target 'hphp/hhvm/hhvm' failed
make[2]: *** [hphp/hhvm/hhvm] Error 1
CMakeFiles/Makefile2:1970: recipe for target 'hphp/hhvm/CMakeFiles/hhvm.dir/all' failed
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

Using libboost-program-options1.57-dev=1.57.0+dfsg-2 on Debian.

Links fine against 1.55.0.

**Comment by tengyifei** [comment] 2015-09-08 18:37
Problem still persists with boost 1.58.0

**Comment by Orvid** [comment] 2015-09-08 19:23
I link against 1.58.0 successfully under MSVC, which means it sounds like a compiler related issue. Which version of GCC are you using?

**Comment by tengyifei** [comment] 2015-09-08 19:24
GCC 5.2.0

**Comment by Orvid** [comment] 2015-09-08 20:49
I believe HHVM is only currently tested under 4.8 and 4.9, so I suspect the issue is probably because you're compiling with a newer version of GCC...

**Comment by paulbiss** [comment] 2015-09-08 20:51
Yeah, we plan to support GCC 5.2 eventually but haven't gotten there yet

**Comment by paulbiss** [comment] 2015-09-08 20:51
I'm going to close this for now

**Closed by paulbiss** 2015-09-08 20:51 UTC
Labels: build

**Comment by Orvid** [comment] 2015-09-08 22:20
Perhaps it's worth creating a tag for GCC 5+ issues?
