### ISSUE TITLE
Shape inheritance or extension

### ISSUE THREAD

**Issue by juanfernandoe** [facebook/hhvm#8504] opened 2019-05-17 15:04 UTC
Hi,

Please provide a way to extend or inherit shapes in order to avoid rewrite same fields all the time.

maybe something like this.
```php
type a = shape(
'code'=>string,
'name'=>string,
);

type b = extend_shape(a,shape(
'age'=>int
));

//the expected result here is b has fields code,name and age
```

**Comment by Wilfred** [comment] 2019-12-11 18:42
I think this is a duplicate of #7130, so let's discuss there :)

**Closed by Wilfred** 2019-12-11 18:42 UTC
