### ISSUE TITLE
stream_socket_sendto unix_socket behavior in hhvm is different with php 5.3

### ISSUE THREAD

**Issue by levixie** [facebook/hhvm#5815] opened 2015-07-29 08:17 UTC
I am using php communicate via unix_socket to my log server
but I keep getting errors like 
```
Could not write 21 bytes test.sock
```
but with php it works
example code(just wrote in here, may has bug)
```
public function write($buf)
  {
    $handle_ = @fsockopen("unix://./test.sock",
                                  -1,
                                  $errno,
                                  $errstr,
                                  0.1);
        $written = @stream_socket_sendto($handle_, $buf);
        if ($written === -1 || $written === false) {
//error all the time when handle is a unix sokcet
      }
    }
```

but this works
```
public function write($buf)
  {
    $handle_ = @fsockopen("unix://./test.sock",
                                  -1,
                                  $errno,
                                  $errstr,
                                  0.1);
        $written = @fwrite($handle_, $buf, strlen($buf));
        if ($written === -1 || $written === false) {
//error all the time when handle is a unix sokcet
      }
    }
```

**Comment by Orvid** [comment] 2016-09-30 19:27
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 19:27 UTC
Labels: php5 incompatibility
