### ISSUE TITLE
make install - starts build over again

### ISSUE THREAD

**Issue by ck-on** [facebook/hhvm#3606] opened 2014-08-28 01:43 UTC
Not sure if this is a local problem I am experiencing but if I do a `make install` instead of just copying the binary manually, it will not only run configure but also start the whole build over again.

I vaguely remember reading somewhere when this happens it is due to a cmake configuration issue.

**Comment by Orvid** [comment] 2016-04-29 19:17
I can't reproduce the issue. Closing.

**Closed by Orvid** 2016-04-29 19:17 UTC
Labels: build
