### ISSUE TITLE
$_SERVER['PHP_SELF'] is doubled

### ISSUE THREAD

**Issue by arzeth** [facebook/hhvm#5125] opened 2015-04-03 22:29 UTC
PHP 5.4 doesn't double it.
I use
```
HipHop VM 3.6.1 (rel)
Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3
```
on Debian.

/home/kaskad/x.php:
`<?php echo $_SERVER['PHP_SELF'];` says `/x.php/x.php` (instead of `/x.php`)

/home/kaskad/manager/x.php:
`<?php echo $_SERVER['PHP_SELF'];` says `/manager/x.php/manager/x.php` (instead of `/manager/x.php`)

Some of $_SERVER:
```php
  ["HTTP_HOST"]=>
  string(6) "kaskad"
  ["GATEWAY_INTERFACE"]=>
  string(7) "CGI/1.1"
  ["SERVER_NAME"]=>
  string(6) "kaskad"
  ["SERVER_PORT"]=>
  string(2) "80"
  ["SERVER_SOFTWARE"]=>
  string(11) "nginx/1.6.2"
  ["SERVER_PROTOCOL"]=>
  string(8) "HTTP/1.1"
  ["SERVER_ADMIN"]=>
  string(0) ""
  ["SERVER_SIGNATURE"]=>
  string(0) ""
  ["PATH_TRANSLATED"]=>
  string(26) "/home/kaskad/manager/x.php"
  ["REDIRECT_STATUS"]=>
  string(3) "200"
  ["CONTENT_LENGTH"]=>
  string(0) ""
  ["SCRIPT_NAME"]=>
  string(14) "/manager/x.php"
  ["DOCUMENT_URI"]=>
  string(14) "/manager/x.php"
  ["REQUEST_METHOD"]=>
  string(3) "GET"
  ["REQUEST_URI"]=>
  string(14) "/manager/x.php"
  ["CONTENT_TYPE"]=>
  string(0) ""
  ["REMOTE_PORT"]=>
  int(35952)
  ["DOCUMENT_ROOT"]=>
  string(12) "/home/kaskad"
  ["QUERY_STRING"]=>
  string(0) ""
  ["SCRIPT_FILENAME"]=>
  string(26) "/home/kaskad/manager/x.php"
  ["SCRIPT_URL"]=>
  string(14) "/manager/x.php"
  ["SCRIPT_URI"]=>
  string(27) "http://kaskad/manager/x.php"
  ["PHP_SELF"]=>
  string(28) "/manager/x.php/manager/x.php"
  ["PATH_INFO"]=>
  string(14) "/manager/x.php"
  ["HTTPS"]=>
  string(0) ""
  ["argv"]=>
  array(1) {
    [0]=>
    string(0) ""
  }
  ["argc"]=>
  int(1)
  ["THREAD_TYPE"]=>
  string(11) "Web Request"
```

My `/etc/hhvm/php.ini`:
```
; php options
session.save_handler = files
session.save_path = /var/lib/php5
;session.gc_maxlifetime = 1440
session.gc_maxlifetime = 86400


; hhvm specific 
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
```

My `/etc/hhvm/server.ini`:
```
; php options

; hhvm specific 

hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
```

**Comment by chrj** [comment] 2015-06-05 12:39
I had a similar problem. In my nginx configuration I had a:

```
fastcgi_param PATH_TRANSLATED $document_root$fastcgi_script_name;
```

Once removed, the `PHP_SELF` doubling went away. 

Here's my nginx configuration for reference:

```
server {

      [...]
 
      location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;

                fastcgi_pass php-backends;
                fastcgi_index index.php;

                include fastcgi_params;

                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

      [...]

}
upstream php-backends {
         server unix:/var/run/hhvm.sock;
         server unix:/var/run/fpm.sock backup;
}

```

HTH

**Comment by Orvid** [comment] 2016-09-30 21:19
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:19 UTC
Labels: fastcgi, webserver
