### ISSUE TITLE
Closure param type contravariance not respected when params are bound

### ISSUE THREAD

**Issue by muglug** [facebook/hhvm#8496] opened 2019-05-03 17:36 UTC
### HHVM Version

4.3.0

### Operating System and Version

MacOS High Sierra

### Standalone code, or other way to reproduce the problem

```
interface C<Te> {
  public function map<Tr>((function(Te):Tr) $action): C<Tr>;
}

interface O<T> {
  public function get() : T;
}

class A {}
class B extends A {}

function expandOptions(C<O<B>> $collection) : C<A> {
  $a = function (O<A> $optional) {
          return $optional->get();
  };
  return $collection->map($a);
}
```

### Actual result

```
Typing[4110] Invalid argument
 16 | function expandOptions(C<O<B>> $collection) : C<A> {
    |                            ^ It is incompatible with an object of type B
 17 |   $a = function (O<A> $optional) {
    |                    ^ This is an object of type A
    |                    ^ Considering that this type argument is invariant with respect to O
 20 |   return $collection->map($a);
    |                           ^^
```

### Expected result

I think this should work - at least, it doesn't feel wrong to me.

**Comment by dlreeves** [comment] 2019-05-12 23:02
The issue is that the generic `T` in interface `O` is invariant. This means there is no typing relationship between `O<A>` and `O<B>`. In order for this to type check `T` in `O` needs to be marked as covariant. The following type checks without error:

```
interface C<Te> {
  public function map<Tr>((function(Te):Tr) $action): C<Tr>;
}

interface O<+T> {
  public function get() : T;
}

class A {}
class B extends A {}

function expandOptions(C<O<B>> $collection) : C<A> {
  $a = function (O<A> $optional) {
          return $optional->get();
  };
  return $collection->map($a);
}
```

**Closed by dlreeves** 2019-05-12 23:02 UTC

**Comment by muglug** [comment] 2019-05-12 23:54
Thanks - didn't realise Hack [had covariant params](https://docs.hhvm.com/hack/generic-types-and-functions/variance)
