### ISSUE TITLE
Null coalesce operator does not work when used on multi-lines

### ISSUE THREAD

**Issue by milesj** [facebook/hhvm#5260] opened 2015-05-06 17:22 UTC
As seen here: http://3v4l.org/eYNFI

These work:

```hack
$foo = new Foo();
$foo->getBar()?->noop();

$foo = new Foo();
$foo->getBar()
    ?->noop();
```

This one doesn't:

```hack
$foo = new Foo();
$foo->getBar()?
    ->noop();
```

**Comment by SiebelsTim** [comment] 2015-05-06 17:48
I guess this is by design. 

Analogous this doesn't work either

```
$foo = new Foo();
$foo->getBar()-
        >noop();
```

**Comment by milesj** [comment] 2015-05-06 18:11
Yeah, I'm assuming `?->` is a single operator, instead of 2 operators. Perhaps match via regex? :P `\?\s*\->`

**Comment by paulbiss** [comment] 2015-05-07 03:01
Pretty sure @SiebelsTim is correct, this is the desired behavior. The token `?->` is a single operator, not two so I think allowing space may be confusing.

**Comment by milesj** [comment] 2015-05-07 04:40
Yeah but then my chains don't line up! /s

```hack
$foo = new Foo();
$foo->getBar()
        ?->noop()
        ->noop()
        ->noop()
        ->noop();
```

**Comment by paulbiss** [comment] 2015-05-07 04:45
The way that the nullsafe operator works that doesn't make any sense. If `$foo->getBar() === null` then `$foo->getBar()?->noop()` will safely evaluate to `null` but `$foo->getBar()?->noop()->noop()` will fatal when `->noop()` is invoked on null.

As a rule when you chain `->` operators if you have a nullsafe in the chain then subsequent `->`s should also use the nullsafe form.

As to the question of allowing `?` to be separated from `->` I don't have a strong feeling but my gut reaction is that since it's one operator it should be banned (`?` isn't a separate operator that modifies the null value, it's all one `?->` operator).

**Comment by milesj** [comment] 2015-05-07 06:22
I haven't ran into that issue of chained null operators. I'll have to dig into it and mess around.

**Comment by jwatzman** [comment] 2015-05-07 06:34
Ah yeah, I think this is the right behavior. (Sorry, I was the one that told you to file this bug, I must have misread your example.) We might be able to give a better error message here, but it's probably not worth the effort. @paulbiss we should prob just close this?

**Comment by milesj** [comment] 2015-05-07 06:36
Yeah it's not that big of an issue. Feel free to do whatever.

**Comment by paulbiss** [comment] 2015-05-07 06:37
Yeah, I'm going to close this out as it sounds like we're pretty happy with the current behavior. Open to hearing compelling arguments though.

**Closed by paulbiss** 2015-05-07 06:37 UTC
