### ISSUE TITLE
Assertion failure: assertion `!g_context->hasRequestEventHandlers()' failed

### ISSUE THREAD

**Issue by PKeidel** [facebook/hhvm#5321] opened 2015-05-10 18:10 UTC
While receiving emails via imap_open im getting this error:

Assertion failure: /tmp/tmp.0gBHBiCjFb/hphp/runtime/base/program-functions.cpp:2015: void HPHP::hphp_memory_cleanup(): assertion `!g_context->hasRequestEventHandlers()' failed.

Core dumped: Aborted
Stack trace in /tmp/stacktrace.18097.log

/tmp/stacktrace.18097.log:

> Host: [my hostname]
> ProcessID: 18097
> ThreadID: 7f36521507c0
> ThreadPID: 18097
> Name: /usr/bin/hhvm
> Type: Aborted
> Runtime: hhvm
> Version: tags/HHVM-3.7.0-0-gc8baf9cd3cb603e030969bfe24634d5e85549915
> DebuggerCount: 0
> 
> Assertion Failure: /tmp/tmp.0gBHBiCjFb/hphp/runtime/base/program-functions.cpp:2015: void HPHP::hphp_memory_cleanup(): assertion `!g_context->hasRequestEventHandlers()' failed.
> Arguments: cron.php
> ThreadType: CLI
> 
> 0  ?? at hhvm:0
> 1  gsignal at /lib/x86_64-linux-gnu/libc.so.6:0
> 2  abort at /lib/x86_64-linux-gnu/libc.so.6:0
> 3  HPHP::assert_fail(char const*, char const*, unsigned int, char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at hhvm:0
> 4  HPHP::execute_command_line_end(int, bool, char const*) at hhvm:0
> 5  ?? at hhvm:0
> 6  HPHP::execute_program(int, char**) at hhvm:0
> 7  main at hhvm:0
> 8  __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6:0
> 9  ?? at hhvm:0
> 
> PHP Stacktrace:
> [empty]

**Comment by Orvid** [comment] 2016-09-30 21:13
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by Orvid** 2016-09-30 21:13 UTC
Labels: crash
