### ISSUE TITLE
Page Server Stopped 

### ISSUE THREAD

**Issue by knoxcard** [facebook/hhvm#6964] opened 2016-04-06 03:23 UTC
Why is hhvm -m server crashing all the time?  It is being ran as root too by the way, so no permission problems.  This time, not even a php error triggered it, it did it all on its own.  Any ideas????!!

### HHVM Version
3.13.0

### Standalone code, or other way to reproduce the problem
hhvm -m server

### Expected result
Server should just stay on

### Actual result
BootTimer: servers started done, took 0ms wall, 0ms cpu
all servers started
BootTimer: all done, took 172ms wall, 173ms cpu total
BootTimer: ClassInfo::Load = 0ms wall, 0ms cpu
BootTimer: ExecutionContext = 0ms wall, 0ms cpu
BootTimer: ExtensionRegistry::moduleInit = 113ms wall, 113ms cpu
BootTimer: PageletServer::Restart = 0ms wall, 0ms cpu
BootTimer: Process::InitProcessStatics = 0ms wall, 0ms cpu
BootTimer: Stream::RegisterCoreWrappers = 0ms wall, 0ms cpu
BootTimer: TOTAL = 172ms wall, 173ms cpu
BootTimer: XboxServer::Restart = 0ms wall, 0ms cpu
BootTimer: apc_load = 0ms wall, 0ms cpu
BootTimer: enable_numa = 0ms wall, 0ms cpu
BootTimer: extra_process_init = 0ms wall, 0ms cpu
BootTimer: extra_process_init_concurrent_wait = 0ms wall, 0ms cpu
BootTimer: g_vmProcessInit = 29ms wall, 30ms cpu
BootTimer: loading static content = 0ms wall, 0ms cpu
BootTimer: mapping self = 23ms wall, 26ms cpu
BootTimer: onig_init = 0ms wall, 0ms cpu
BootTimer: pagein_self = 24ms wall, 26ms cpu
BootTimer: pcre_reinit = 2ms wall, 3ms cpu
BootTimer: pthread_init = 1ms wall, 0ms cpu
BootTimer: rds::requestExit = 0ms wall, 0ms cpu
BootTimer: servers started = 0ms wall, 0ms cpu
BootTimer: timezone_init = 0ms wall, 0ms cpu
BootTimer: warmup = 0ms wall, 0ms cpu
BootTimer: xenon = 0ms wall, 0ms cpu
BootTimer: xmlInitParser = 0ms wall, 0ms cpu
Page server stopped
Page server stopped
Page server stopped

**Comment by Orvid** [comment] 2016-04-06 05:23
3.13.0 is currently broken, I would suggest downgrading to 3.12.1 for now.

**Comment by knoxcard** [comment] 2016-04-06 07:14
Wow! downgrading, didn't even think of that.  I figure this is such a simple must have, how could they go wrong with it?  I am also running this under Debian, the more info the better to let the team know.  I will downgrade and post the results when done.  Thanks Orvid!

**Comment by Orvid** [comment] 2016-04-06 18:42
Closing as a duplicate of #6590.

**Closed** 2016-04-06 18:44 UTC
Labels: crash, duplicate
