### ISSUE TITLE
HHVM 3.9.1 Core dumped

### ISSUE THREAD

**Issue by JohanTan** [facebook/hhvm#6316] opened 2015-09-29 18:20 UTC
A little bit of background: we are running hhvm on production web servers, and we have around 600 MB local php files filled with static array, stored locally to each web server to serve as cache. And once in every 2-3 days we get a core dumped message in the hhvm error log. One of the most recent messages look like this:
```
PHP Stacktrace:

#0  include() called at [/var/www/public_html/sites/all/modules/custom/core/caching/PHPFileCache.php:38]
#1  FTB\core\caching\PHPFileCache->get(_page_419:detail) called at [/var/www/public_html/sites/all/modules/custom/core/caching/CompoundCache.php:30]
#2  FTB\core\caching\CompoundCache->get(_page_419:detail) called at [/var/www/public_html/sites/all/modules/custom/app_admin/template_service/PageTemplateService.php:91]
#3  FTB\app_admin\template_service\PageTemplateService->getTemplateRow() called at [/var/www/public_html/sites/all/modules/custom/app_admin/template_service/PageTemplateService.php:51]
#4  FTB\app_admin\template_service\PageTemplateService->__construct() called at [/var/www/public_html/sites/all/modules/custom/app_admin/template_service/TemplateService.php:36]
#5  FTB\app_admin\template_service\TemplateService::get() called at [/var/www/public_html/sites/all/modules/custom/core/app/AppInfo.inc:607]
#6  AppInfo->getDetailTemplate() called at [/var/www/public_html/sites/all/modules/custom/detail/AsyncRenderer.php:48]
#7  FTB\detail\AsyncRenderer->__construct(, Array) called at [/var/www/public_html/sites/all/modules/custom/background_jobs/drupal_jobs/FastCGIRenderSectionService.php:35]
#8  FastCGIRenderSectionService->perform() called at [/var/www/public_html/sites/all/modules/custom/background_jobs/fastcgi_start.php:25]
```

More detailed stacktrace is posted here: https://gist.github.com/JohanTan/c5066f4d088177e536bd.

Our JIT settings in server.ini:
```
hhvm.jit_a_cold_size = 256M
hhvm.jit_a_frozen_size = 256M
hhvm.jit_a_hot_size = 0
hhvm.jit_a_prof_size = 512M
hhvm.jit_a_size = 512M
hhvm.jit_global_data_size = 512M
```

**Comment by karpa13a** [comment] 2015-09-29 18:25
seems OOM happen

**Comment by JohanTan** [comment] 2015-09-29 18:28
Yes but we could not increase any of the jit cache size further. Anything else I can try?

**Comment by fredemmott** [comment] 2015-09-29 19:22
Can you get a C++ stack trace?

**Comment by JohanTan** [comment] 2015-09-29 20:31
@fredemmott 
Do I just set `hhvm.log.native_stack_trace = true` and wait for the next crash happen? Or I need to have `hhvm-dbg` installed?

**Comment by fredemmott** [comment] 2015-09-29 20:35
install hhvm-dbg, then if you can reproduce the problem, run hhvm in gdb - otherwise, enable core files and open it up in gdb once you have one. 'thread apply all bt' will give you the needed data.

**Comment by JohanTan** [comment] 2015-09-29 21:08
@fredemmott Wouldn't hhvm-deg be significantly more slow and is not supposed to run on production system? I can have it on our staging server and see if I can duplicate the issue. Or if there is any alternatives I am happy to try them out as well.

**Comment by fredemmott** [comment] 2015-09-29 21:11
Well, you can do it with the normal package, but it is much less likely that the data will be useful - you might be lucky though.

**Comment by Orvid** [comment] 2015-09-29 21:59
This might actually work better in repo-auth mode, so it can generate a global data piece, rather than generating code to initialize the array, as I would assume it's currently doing.

**Comment by JohanTan** [comment] 2015-09-29 22:03
@Orvid unfortunately we are based on pressflow drupal with eval() calls everywhere. Repo-auth mode will not work properly without segfaults.

**Comment by JohanTan** [comment] 2016-02-03 22:39
Here is the crash dump file we captured: https://gist.github.com/JohanTan/00fdf69e8f96fb3c2237. Hope it can help. My guess is our app is heavily relying on the central repo cache it eventually ran out. An evidence is that most of crashes of this type happens not long after our weekly production deployment.

Also it looks like there are a legacy 2GB limit on the jit memory pool settings collectively:
```
hhvm.jit_a_cold_size = 256M
hhvm.jit_a_frozen_size = 256M
hhvm.jit_a_hot_size = 0
hhvm.jit_a_prof_size = 512M
hhvm.jit_a_size = 512M
hhvm.jit_global_data_size = 512M
```

Is there an easy way to eliminate this restriction when we need more than 2GB bytecode cache?

**Comment by fredemmott** [comment] 2016-02-03 22:50
bytecode cache is for bytecode, the jit sizes are for executable machine code (and it looks like that's the limit you hit). the jit size can not be increased beyond 2GB - however, there is a still-experimental option, `hhvm.enable_reusable_tc = true` that will make it so no-longer needed jit memory can be re-used for new code. This is especially useful if you are modifying or replacing PHP code without restarting PHP.

Closing as this is an architecture issue that we are not actively planning on addressing - though, if you come across issues with hhvm.enable_reusable_tc and they still exist in more recent versions of HHVM, please file issues with details and they'll be investigated.

**Closed by fredemmott** 2016-02-03 22:50 UTC
Labels: crash, needs more info
