### ISSUE TITLE
Memory Leak HHVM (Jit=1) 3.8+ (3.7.3 is ok)

### ISSUE THREAD

**Issue by sibest** [facebook/hhvm#6502] opened 2015-11-02 02:14 UTC
I've just discovered an important memory leak with the release package of hhvm 3.8.0, it happens since 3.8.0 version, tested in Debian 8 and Ubuntu 14. It works correctly in hhvm 3.7.3. It does not work in:

3.8.0
3.8.1
3.9.0
3.9.1
3.10.0
3.10.1

The leak occurs only in JIT mode. The function is this and is part of a database manager class:

```
  public function tick($frameTime)
 	  {  
 	  	while (1)
	 	  {	 	  	
	 	  	$now = getTimer();
	 	  	if ($now - $this->grouped_query_time > DATABASE_QUERY_TIMEOUT)
	 	  	{ 
	 	  		 $this->run_grouped_queries();
	 	  		 $this->grouped_query_time = $now;
	 	  	}
	 	  	
	 	  	if ($this->query_result_id == 
	 	  	    $this->query_id)
	 	  	{
	 	  	    return;
	 	  	} 
	 	  	
	 	  	$this->arena->tick();
	 	  	$this->query_result_id++;
	 	  	if (!isset($this->queue[$this->query_result_id]))
	 	  	  continue;
	 	  	 
	 	  	$data = $this->arena->read('r', $this->query_result_id);
	
	 	  	if ($data === FALSE)
	 	  	{
	 	  	 $this->query_result_id--;
	 	  	 return;
	 	  	}
	 	  	  
	 	  	$this->arena->remove('r', $this->query_result_id);  	
	 	  	$receiver = $this->queue[$this->query_result_id];
	 	  	unset($this->queue[$this->query_result_id]);

	       // receiver[0] is an object that respons to query_result_received
               // with JIT enabled in 3.8.+ this object will never be destroyed
               // with JIT disabled or 3.7.1 this object will be destroyed
	    	$receiver[0]->query_result_received($receiver[1], new Database_ResultSet($data));
	 	  
 	    }
 	  }

class Example_Receiver {

function __destruct()
{
 echo 'Object destroyed.'."\r\n";
}

function query_result_received($category, $data)
{

}

}
```

This is the scenario:

After an object registered to the database manager receives the data, the tick function calls the receiver callback with the resulting data.

The "receiver" object is never destroyed after that, it is correctly destroyed in HHVM 3.7.1. It is also destroyed in HHVM 3.8+ with JIT turned off. But with JIT turned on the $reciever[0] destructor will never be called.

A strange thing is that if i put a simple assignment before the while (1) for example
```
  public function tick($frameTime)
 	  {  
             $a = 1;
 	while (1) ...
```

The destructor of $receiver[1] is correctly called. Unfortunately i could not reproduce this behaviour in a simple code. Also, if i remove the while(1) { the destructor is called too. I think there is a problem with deallocations in loops cycles (I also tried for (;;) and the problem persists).

The problem is not in my PHP code: with HHVM 3.7.1 works correctly both JIT enabled and disabled. With HHVM 3.8+ it works only with JIT disabled.

Please inform me if you need further information.

Thank you much

**Comment by sibest** [comment] 2015-11-02 02:47
Also,

this is not happening if i place a real condition instead of while (1)
for example while(is_numeric(1)) the leak does not occur.

The leak occurs ONLY if the loop is "while(1)" or "do.. while(1)" or "for(;;)"

**Comment by paulbiss** [comment] 2015-11-02 20:59
Do you have a shorter standalone example we can run ourselves to observe the leak?

**Comment by nilwave** [comment] 2015-11-02 21:13
I can provide you the full code, it requires a mysql database. If you want we can chat on Skype.

**Comment by nilwave** [comment] 2015-11-02 21:22
nilwave = sibest

**Comment by paulbiss** [comment] 2015-11-02 23:07
I don't know when I'll have time to play around with such a heavyweight example. The problem seems pretty isolated to the treatment of loops and arrays in the JIT. If you can spend some time reducing it down to something short enough that I can stare at easily I'd be happy to help.

If it proves too difficult to isolate a simple example of, knowing what the JIT is generating may also be helpful. If you can reproduce this bug in a debug build with the environment variables TRACE=printir:4 and HPHP_TRACE_FILE=/path/to/file.txt set and send me the trace file ([username] @fb.com) I may have some time to take a look. Thanks!

**Comment by mpu** [comment] 2016-06-28 23:10
I could reproduce it locally with a 45 lines PHP script.

**Comment by sibest** [comment] 2016-06-28 23:31
Can you share it?

**Comment by mpu** [comment] 2016-06-29 19:40
The diff D3498942 was created internally to solve that issue. It was caused by some assertions inserted unconditionally at function entries.

Here is the small example.
```
<?hh

const N = 10;

class Obj {
  function __destruct() {
    echo "object destroyed\n";
  }
}

class X {
  public array $arr;
  public int $id;

  public function f() {
    // echo "";
    for (;;) {
      echo "iterating...\n";
      if ($this->id >= N) {
        return;
      }
      $res = $this->arr[$this->id];
      unset($this->arr[$this->id]);
      $this->id++;
    }
  }

  function __construct() {
    for ($i = 0; $i < N; $i++) {
      $this->arr[] = new Obj();
    }
    $this->id = 0;
  }
}

$x = new X();
$x->f();
echo "done\n";
```

**Comment by mpu** [comment] 2016-08-03 01:23
This is fixed now, this issue can be closed.

**Closed** 2016-08-03 18:49 UTC
Labels: memory leak, no isolated repro
